Imports and dates

In [1]:
import sys
from pathlib import Path
import pandas as pd

# Add repo root to PYTHONPATH
HERE = Path().resolve()
PROJECT_ROOT = HERE.parents[0]   # notebooks → repo root
sys.path.insert(0, str(PROJECT_ROOT))


from prm_opt.run_s25 import run_s25_s1, run_s25_s2_v2_sensitivity, run_month_s25
from prm_opt.run_s26 import run_s26_s1, run_s26_s2_v2_sensitivity, run_month_s26
from prm_opt.build_s26_assumptions import build_s26_assumptions
from prm_opt.outputs import build_run_report, print_run_report, build_run_report_s1, print_run_report_s1
from prm_opt.build_jobs import build_jobs
from prm_opt.ingest_s25 import ingest_s25
from prm_opt.config import PlanningToggles

# -----------------------------
# DATE RANGES
# -----------------------------
START_S25 = "2025-04-01"
END_S25   = "2025-05-01"

START_S26 = "2026-07-01"
END_S26   = "2026-10-01"

Common toggles

In [2]:
toggles = PlanningToggles(
    sla_buffer_mins=0,
    spill_bucket_cap=10,
    standby_dep_vert_mins=10,
    standby_arr_horiz_mins=10,
    enforce_hard_sla_floor=True,
    allow_sla_floor_slack=True,
    obj_sla_floor_slack_weight=20_000_000.0,

    demand_mode="p90_stratified",
    run_p100_risk_check_with_p90=True,
    p90_quantile=0.90,
    p90_strata=("SSR Code", "Has Own Chair", "A/D"),
)

In [3]:

# 2025 (historical)
months_2025 = pd.date_range("2025-04-01", "2025-10-01", freq="MS")

# 2026 (split logic inside function)
months_2026 = pd.date_range("2026-07-01", "2026-10-01", freq="MS")

In [4]:

results_2025 = []

for m in months_2025:
    results_2025.append(run_month_s25(m, toggles))

df_2025 = pd.DataFrame(results_2025)

df_2025.to_csv("S25_monthly_outputs_v2.csv", index=False)
df_2025

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-04

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 576 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_04.csv

Running S25 2025-04

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_04.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-05

Unmatched passenger rows after merge (missing Chocks DT): 634
Unique unmatched flight keys: 386

Unmatched key reasons:
reason
no_flight_candidate               377
exact_match_should_have_joined      9
Name: count, dtype: int64

Dropped 618 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 1 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 898 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_05.csv

Running S25 2025-05

Unmatched passenger rows after merge (missing Chocks DT): 634
Unique unmatched flight keys: 386

Unmatched key reasons:
reason
no_flight_candidate               377
exact_match_should_have_joined      9
Name: count, dtype: int64

Dropped 618 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 1 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_05.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-06

Unmatched passenger rows after merge (missing Chocks DT): 656
Unique unmatched flight keys: 389

Unmatched key reasons:
reason
no_flight_candidate               335
scheduled_dt_mismatch              46
exact_match_should_have_joined      8
Name: count, dtype: int64

Dropped 636 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 731 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_06.csv

Running S25 2025-06

Unmatched passenger rows after merge (missing Chocks DT): 656
Unique unmatched flight keys: 389

Unmatched key reasons:
reason
no_flight_candidate               335
scheduled_dt_mismatch              46
exact_match_should_have_joined      8
Name: count, dtype: int64

Dropped 636 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_06.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-07

Unmatched passenger rows after merge (missing Chocks DT): 724
Unique unmatched flight keys: 458

Unmatched key reasons:
reason
no_flight_candidate               445
exact_match_should_have_joined     10
scheduled_dt_mismatch               3
Name: count, dtype: int64

Dropped 702 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 5 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 890 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_07.csv

Running S25 2025-07

Unmatched passenger rows after merge (missing Chocks DT): 724
Unique unmatched flight keys: 458

Unmatched key reasons:
reason
no_flight_candidate               445
exact_match_should_have_joined     10
scheduled_dt_mismatch               3
Name: count, dtype: int64

Dropped 702 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 5 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_07.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-08

Unmatched passenger rows after merge (missing Chocks DT): 629
Unique unmatched flight keys: 398

Unmatched key reasons:
reason
no_flight_candidate               373
scheduled_dt_mismatch              14
exact_match_should_have_joined     11
Name: count, dtype: int64

Dropped 613 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1008 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_08.csv

Running S25 2025-08

Unmatched passenger rows after merge (missing Chocks DT): 629
Unique unmatched flight keys: 398

Unmatched key reasons:
reason
no_flight_candidate               373
scheduled_dt_mismatch              14
exact_match_should_have_joined     11
Name: count, dtype: int64

Dropped 613 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_08.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-09

Unmatched passenger rows after merge (missing Chocks DT): 698
Unique unmatched flight keys: 404

Unmatched key reasons:
reason
no_flight_candidate               396
exact_match_should_have_joined      7
scheduled_dt_mismatch               1
Name: count, dtype: int64

Dropped 686 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 8 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
18323      13159410           748           LS 2025-09-30 01:35:15
18324      13159411           748           LS 2025-09-30 01:35:15
18327      13159414           748           LS 2025-09-30 01:35:15
18328      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
18323 2025-09-30 04:59:07         20 2025-09-30 01:35:15
18324 2025-09-30 05:00:53         20 2025-09-30 01:35:15
18327 2025-09-30 04:59:15         20 2025-09-30 01:35:15
18328 2025-09-30 04:59:18         20 2025-09-30 01:35:15
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 979 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_09.csv

Running S25 2025-09

Unmatched passenger rows after merge (missing Chocks DT): 698
Unique unmatched flight keys: 404

Unmatched key reasons:
reason
no_flight_candidate               396
exact_match_should_have_joined      7
scheduled_dt_mismatch               1
Name: count, dtype: int64

Dropped 686 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 8 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
18323      13159410           748           LS 2025-09-30 01:35:15
18324      13159411           748           LS 2025-09-30 01:35:15
18327      13159414           748           LS 2025-09-30 01:35:15
18328      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
18323 2025-09-30 04:59:07         20 2025-09-30 01:35:15
18324 2025-09-30 05:00:53         20 2025-09-30 01:35:15
18327 2025-09-30 04:59:15         20 2025-09-30 01:35:15
18328 2025-09-30 04:59:18         20 2025-09-30 01:35:15

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_09.csv

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S25 2025-10

Unmatched passenger rows after merge (missing Chocks DT): 729
Unique unmatched flight keys: 418

Unmatched key reasons:
reason
no_flight_candidate               390
exact_match_should_have_joined     15
scheduled_dt_mismatch              13
Name: count, dtype: int64

Dropped 705 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 6 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 900 PRM jobs via stratified percentile cap

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_10.csv

Running S25 2025-10

Unmatched passenger rows after merge (missing Chocks DT): 729
Unique unmatched flight keys: 418

Unmatched key reasons:
reason
no_flight_candidate               390
exact_match_should_have_joined     15
scheduled_dt_mismatch              13
Name: count, dtype: int64

Dropped 705 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[BUILD_JOBS] Dropping 6 jobs already impossible at release (beyond SLA + max late)
Hourly table saved (S1): S25_S1_peak_day_hourly_need_2025_10.csv

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

,month,demand_mode,demand_mode_p90,S1_PeakAmb_p90,S1_PeakMini_p90,S2_PeakAmb_p90,S2_PeakMini_p90,SLA_all_p90,SLA_arr_p90,SLA_dep_p90,...,sla_floor_slack_p100,S2_status_p100,S2_tc_p100,S2_st_p100,S1_peak_day_p100,S1_peak_day_job_count_p100,S1_hourly_table_path_p100,S2_peak_day_p100,S2_peak_day_job_count_p100,S2_hourly_table_path_p100
0,2025-04,compare_p90_vs_p100,p90_stratified,14,3,None,None,None,None,None,...,None,None,None,None,2025-04-29,504,S25_S1_peak_day_hourly_need_2025_04.csv,None,None,None
1,2025-05,compare_p90_vs_p100,p90_stratified,18,4,None,None,None,None,None,...,None,None,None,None,2025-05-27,630,S25_S1_peak_day_hourly_need_2025_05.csv,None,None,None
2,2025-06,compare_p90_vs_p100,p90_stratified,11,5,None,None,None,None,None,...,None,None,None,None,2025-06-27,636,S25_S1_peak_day_hourly_need_2025_06.csv,None,None,None
3,2025-07,compare_p90_vs_p100,p90_stratified,10,3,None,None,None,None,None,...,None,None,None,None,2025-07-07,587,S25_S1_peak_day_hourly_need_2025_07.csv,None,None,None
4,2025-08,compare_p90_vs_p100,p90_stratified,12,2,None,None,None,None,None,...,None,None,None,None,2025-08-26,577,S25_S1_peak_day_hourly_need_2025_08.csv,None,None,None
5,2025-09,compare_p90_vs_p100,p90_stratified,14,5,None,None,None,None,None,...,None,None,None,None,2025-09-17,729,S25_S1_peak_day_hourly_need_2025_09.csv,None,None,None
6,2025-10,compare_p90_vs_p100,p90_stratified,12,3,None,None,None,None,None,...,None,None,None,None,2025-10-02,654,S25_S1_peak_day_hourly_need_2025_10.csv,None,None,None

In [4]:
print(results_2025)

NameError: name 'results_2025' is not defined

In [5]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

Unmatched passenger rows after merge (missing Chocks DT): 4532
Unique unmatched flight keys: 2757

Unmatched key reasons:
reason
no_flight_candidate               1980
scheduled_dt_mismatch              714
exact_match_should_have_joined      63
Name: count, dtype: int64

Dropped 4415 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[1/5] Penetration + SSR mix…
    ✓ penetration + SSR mix built   [388.94s]
[2/5] Service times…
[BUILD_JOBS] Dropping 36 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
99965      13159410           748           LS 2025-09-30 01:35:15
99966      13159411           748           LS 2025-09-30 01:35:15
99969      13159414           748           LS 2025-09-30 01:35:15
99970      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
99965 2025-09-30 04:59:07         20 2025-09-30 01:35:15
99966 2025-09-30 05:00:53         20 2025-09-30 01:35:15
99969 2025-09-30 04:59:15         20 2025-09-30 01:35:15
99970 2025-09-30 04:59:18         20 2025-09-30 01:35:15
    ✓ service times built   [1.93s]
[2b/5] Tau mode params (S25 medians)…
    ✓ tau mode params built   [0.02s]
[3/5] Chocks offsets…
    ✓ chocks offsets built   [0.08s]
[4/5] Early/late timing…
    ✓ early/late params built   [0.07s]
[5/5] Stand inputs…
    ✓ stand inputs built   [0.08s]

In [6]:
results_2026 = []

for m in months_2026:
    results_2026.append(run_month_s26(m, assumptions, toggles))

df_2026 = pd.DataFrame(results_2026)

df_2026.to_csv("S26_monthly_outputs_v3.csv", index=False)
df_2026

[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S26 2026-07 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11663
Airlines (sample): ['U2' 'KL' 'BA' 'LH' 'FR' 'RK' 'LS' 'AF' 'LM' 'QR']
Countries (sample): ['GREAT BRITAIN' 'NETHERLANDS' 'GREECE' 'GERMANY' 'SPAIN' 'CYPRUS'
 'FRANCE' 'ITALY' 'MOROCCO' 'MALTA']

Pax describe:
count    11663.000000
mean       154.066278
std         50.485163
min          0.000000
25%        134.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2  GREAT BRITAIN       Domestic   A  145.0
1       KL    NETHERLANDS  International   A  149.0
2       U2         GREECE  International   A  195.0
3       BA  GREAT BRITAIN       Domestic   A  153.0
4       LH        GERMANY  International   A  116.0
5       FR          SPAIN  International   A  186.0
6       U2         CYPRUS  International   A  164.0
7       U2  GREAT BRITAIN       Domestic   A  130.0
8       U2         FRANCE  International   A  222.0
9       FR          ITALY  International   A  133.0
10      RK        MOROCCO  International   A  176.0
11      FR          ITALY  International   A  176.0
12      FR          MALTA  International   A  168.0
13      FR          ITALY  International   A  189.0
14      FR          SPAIN  International   A  181.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,208 / 11,663 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
229      EC        ITALY  133.0
232      EC       FRANCE  210.0
239      EC        ITALY  126.0
245      EC       FRANCE  187.0
309      RK        MALTA  187.0
336      IB        SPAIN  165.0
346      EC       FRANCE  166.0
347      DS  SWITZERLAND  180.0
349      DS  SWITZERLAND  185.0
352      IB        SPAIN  167.0
364      DS  SWITZERLAND  152.0
367      DS  SWITZERLAND  158.0
370      EC        SPAIN  109.0
371      EC       FRANCE  148.0
384      EC        SPAIN  142.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18259.205732743976
Total PRMs after rounding: 18618

Raw PRM demand distribution (prm_raw):
count    11663.000000
mean         1.565567
std          1.204368
min          0.000000
25%          0.834005
50%          1.248177
75%          1.719072
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
9548       BY                    GREECE  189.0   0.042488  8.030258
6046       BY                    GREECE  189.0   0.042488  8.030258
3360       BY                    GREECE  189.0   0.042488  8.030258
4893       BY                     SPAIN  188.0   0.042640  8.016392
8712       BY                    GREECE  188.0   0.042488  7.987770
11075      BY                     SPAIN  187.0   0.042640  7.973751
11226      BY                     SPAIN  187.0   0.042640  7.973751
7566       BY                     SPAIN  187.0   0.042640  7.973751
9708       BY                    GREECE  186.0   0.042488  7.902794
2192       BY                     SPAIN  185.0   0.042640  7.888470
6680       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
10235      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
139        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
1289       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5558       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
9548            8
6046            8
3360            8
4893            8
8712            8
11075           8
11226           8
7566            8
9708            8
2192            8
6680            8
10235           8
139             8
1289            8
5558            8
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=145.0 | Pen=0.00918 | Pax*Pen=1.331 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=149.0 | Pen=0.00831 | Pax*Pen=1.238 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=195.0 | Pen=0.01184 | Pax*Pen=2.308 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=153.0 | Pen=0.00962 | Pax*Pen=1.472 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=116.0 | Pen=0.00569 | Pax*Pen=0.660 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=186.0 | Pen=0.00966 | Pax*Pen=1.796 | PRMs=2
[DEBUG flight] Airline=U2 | Country=CYPRUS | Pax=164.0 | Pen=0.02183 | Pax*Pen=3.580 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=130.0 | Pen=0.00918 | Pax*Pen=1.193 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=222.0 | Pen=0.00839 | Pax*Pen=1.862 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=133.0 | Pen=0.00547 | Pax*Pen=0.727 | PRMs=1
[DEBUG flight] Airline=RK | Country=MOROCCO | Pax=176.0 | Pen=0.01007 | Pax*Pen=1.772 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=176.0 | Pen=0.00547 | Pax*Pen=0.962 | PRMs=1
[DEBUG flight] Airline=FR | Country=MALTA | Pax=168.0 | Pen=0.00863 | Pax*Pen=1.450 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=189.0 | Pen=0.00547 | Pax*Pen=1.033 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=181.0 | Pen=0.00966 | Pax*Pen=1.748 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 18618
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9823
WCHS     7639
WCHC     1037
OTHER     119
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1515 PRM jobs via stratified percentile cap

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-07-01 → 2026-08-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11663
Airlines (sample): ['U2' 'KL' 'BA' 'LH' 'FR' 'RK' 'LS' 'AF' 'LM' 'QR']
Countries (sample): ['GREAT BRITAIN' 'NETHERLANDS' 'GREECE' 'GERMANY' 'SPAIN' 'CYPRUS'
 'FRANCE' 'ITALY' 'MOROCCO' 'MALTA']

Pax describe:
count    11663.000000
mean       154.066278
std         50.485163
min          0.000000
25%        134.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2  GREAT BRITAIN       Domestic   A  145.0
1       KL    NETHERLANDS  International   A  149.0
2       U2         GREECE  International   A  195.0
3       BA  GREAT BRITAIN       Domestic   A  153.0
4       LH        GERMANY  International   A  116.0
5       FR          SPAIN  International   A  186.0
6       U2         CYPRUS  International   A  164.0
7       U2  GREAT BRITAIN       Domestic   A  130.0
8       U2         FRANCE  International   A  222.0
9       FR          ITALY  International   A  133.0
10      RK        MOROCCO  International   A  176.0
11      FR          ITALY  International   A  176.0
12      FR          MALTA  International   A  168.0
13      FR          ITALY  International   A  189.0
14      FR          SPAIN  International   A  181.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,208 / 11,663 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
229      EC        ITALY  133.0
232      EC       FRANCE  210.0
239      EC        ITALY  126.0
245      EC       FRANCE  187.0
309      RK        MALTA  187.0
336      IB        SPAIN  165.0
346      EC       FRANCE  166.0
347      DS  SWITZERLAND  180.0
349      DS  SWITZERLAND  185.0
352      IB        SPAIN  167.0
364      DS  SWITZERLAND  152.0
367      DS  SWITZERLAND  158.0
370      EC        SPAIN  109.0
371      EC       FRANCE  148.0
384      EC        SPAIN  142.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18259.205732743976
Total PRMs after rounding: 18618

Raw PRM demand distribution (prm_raw):
count    11663.000000
mean         1.565567
std          1.204368
min          0.000000
25%          0.834005
50%          1.248177
75%          1.719072
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
9548       BY                    GREECE  189.0   0.042488  8.030258
6046       BY                    GREECE  189.0   0.042488  8.030258
3360       BY                    GREECE  189.0   0.042488  8.030258
4893       BY                     SPAIN  188.0   0.042640  8.016392
8712       BY                    GREECE  188.0   0.042488  7.987770
11075      BY                     SPAIN  187.0   0.042640  7.973751
11226      BY                     SPAIN  187.0   0.042640  7.973751
7566       BY                     SPAIN  187.0   0.042640  7.973751
9708       BY                    GREECE  186.0   0.042488  7.902794
2192       BY                     SPAIN  185.0   0.042640  7.888470
6680       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
10235      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
139        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
1289       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5558       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
9548            8
6046            8
3360            8
4893            8
8712            8
11075           8
11226           8
7566            8
9708            8
2192            8
6680            8
10235           8
139             8
1289            8
5558            8
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=145.0 | Pen=0.00918 | Pax*Pen=1.331 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=149.0 | Pen=0.00831 | Pax*Pen=1.238 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=195.0 | Pen=0.01184 | Pax*Pen=2.308 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=153.0 | Pen=0.00962 | Pax*Pen=1.472 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=116.0 | Pen=0.00569 | Pax*Pen=0.660 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=186.0 | Pen=0.00966 | Pax*Pen=1.796 | PRMs=2
[DEBUG flight] Airline=U2 | Country=CYPRUS | Pax=164.0 | Pen=0.02183 | Pax*Pen=3.580 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=130.0 | Pen=0.00918 | Pax*Pen=1.193 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=222.0 | Pen=0.00839 | Pax*Pen=1.862 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=133.0 | Pen=0.00547 | Pax*Pen=0.727 | PRMs=1
[DEBUG flight] Airline=RK | Country=MOROCCO | Pax=176.0 | Pen=0.01007 | Pax*Pen=1.772 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=176.0 | Pen=0.00547 | Pax*Pen=0.962 | PRMs=1
[DEBUG flight] Airline=FR | Country=MALTA | Pax=168.0 | Pen=0.00863 | Pax*Pen=1.450 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=189.0 | Pen=0.00547 | Pax*Pen=1.033 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=181.0 | Pen=0.00966 | Pax*Pen=1.748 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 18618
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9823
WCHS     7639
WCHC     1037
OTHER     119
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,618   [262.45s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1515 PRM jobs via stratified percentile cap
    ✓ build_jobs done | jobs=17,101   [0.44s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.46s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 2}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
KK            D      2
dtype: int64

Bucket horizon: start=2026-07-01 23:30:00 end=2026-08-01 05:30:00 buckets=2905
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-07-23 11:45:00 | 75.0 / 210.0
  2026-07-23 12:00:00 | 75.0 / 210.0
  2026-07-21 17:45:00 | 75.0 / 210.0
  2026-07-21 18:00:00 | 75.0 / 210.0
  2026-07-24 17:30:00 | 60.0 / 210.0
  2026-07-07 12:15:00 | 60.0 / 210.0
  2026-07-07 12:30:00 | 60.0 / 210.0
  2026-07-23 12:15:00 | 60.0 / 210.0
  2026-07-23 17:45:00 | 60.0 / 210.0
  2026-07-21 17:30:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 388
  is_spin by dir:
dir
A    388
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.18216758333333333 32.594241116666666 59.95100278333334
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 8.0

Amb minutes (necessary condition):
  min required (vertical-only): 83967.7
  total available over horizon: 590250.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 25
  min mini minutes required (forced): 431.6
  total mini minutes available: 217875.0

Lift rough check:
  lift jobs: 62
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2855
Examples (first 20):
    Passenger ID                   flight_key dir                   t  \
j
12    S26_0633_0  A3_0633_2026-07-04 09:15:00   D 2026-07-04 09:15:00
13    S26_0633_0  A3_0633_2026-07-06 09:15:00   D 2026-07-06 09:15:00
14    S26_0633_0  A3_0633_2026-07-08 09:45:00   D 2026-07-08 09:45:00
15    S26_0633_0  A3_0633_2026-07-11 09:15:00   D 2026-07-11 09:15:00
17    S26_0633_0  A3_0633_2026-07-15 10:00:00   D 2026-07-15 09:45:00
18    S26_0633_0  A3_0633_2026-07-18 09:15:00   D 2026-07-18 09:15:00
20    S26_0633_0  A3_0633_2026-07-22 09:30:00   D 2026-07-22 09:15:00
21    S26_0633_0  A3_0633_2026-07-25 10:00:00   D 2026-07-25 10:00:00
22    S26_0633_0  A3_0633_2026-07-27 09:30:00   D 2026-07-27 09:15:00
78    S26_0083_0  AA_0083_2026-07-03 11:15:00   D 2026-07-03 11:15:00
79    S26_0083_1  AA_0083_2026-07-03 11:15:00   D 2026-07-03 11:15:00
80    S26_0083_1  AA_0083_2026-07-04 11:30:00   D 2026-07-04 11:15:00
81    S26_0083_0  AA_0083_2026-07-04 11:30:00   D 2026-07-04 11:15:00
98    S26_0083_1  AA_0083_2026-07-13 11:30:00   D 2026-07-13 11:30:00
99    S26_0083_0  AA_0083_2026-07-13 11:30:00   D 2026-07-13 11:30:00
102   S26_0083_1  AA_0083_2026-07-15 10:30:00   D 2026-07-15 10:30:00
103   S26_0083_0  AA_0083_2026-07-15 10:30:00   D 2026-07-15 10:30:00
105   S26_0083_1  AA_0083_2026-07-17 11:00:00   D 2026-07-17 11:00:00
106   S26_0083_0  AA_0083_2026-07-17 11:00:00   D 2026-07-17 11:00:00
111   S26_0083_0  AA_0083_2026-07-20 10:45:00   D 2026-07-20 10:45:00

               hard_deadline_time      sla_start_time Stand Airline Code
j
12  2026-07-04 09:25:00.000000000 2026-07-04 09:25:00   16A           A3
13  2026-07-06 09:25:00.000000000 2026-07-06 09:25:00   16A           A3
14  2026-07-08 09:45:55.586828994 2026-07-08 09:25:00     3           A3
15  2026-07-11 09:25:00.000000000 2026-07-11 09:25:00     3           A3
17  2026-07-15 09:56:51.425334084 2026-07-15 09:25:00    17           A3
18  2026-07-18 09:25:00.000000000 2026-07-18 09:25:00   15A           A3
20  2026-07-22 09:25:05.672673660 2026-07-22 09:25:00    25           A3
21  2026-07-25 10:02:51.714818028 2026-07-25 09:25:00    22           A3
22  2026-07-27 09:27:04.220000946 2026-07-27 09:25:00    1A           A3
78  2026-07-03 11:23:04.310105850 2026-07-03 10:30:00    4A           AA
79  2026-07-03 11:23:04.310105850 2026-07-03 10:30:00    4A           AA
80  2026-07-04 11:25:52.911308478 2026-07-04 10:30:00    4A           AA
81  2026-07-04 11:25:52.911308478 2026-07-04 10:30:00    4A           AA
98  2026-07-13 11:39:30.274666722 2026-07-13 10:30:00    4A           AA

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-07 | Cutoff: 2026-07-01
Scenario 1:
  PeakAmb=14 | PeakMini=2
Scenario 2:
  PeakAmb=13 | PeakMini=5
SLA:
  All=0.9290 | Arr=0.9368 | Dep=0.9210
SLA diagnostics:
  allowed_breaches=343 | actual_breaches=1215 | sla_percent=92.90% | sla_floor_slack=872.00
  WARNING: hard SLA floor relaxed by slack on 872.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_07.csv
================================================


Running S26 2026-07 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11663
Airlines (sample): ['U2' 'KL' 'BA' 'LH' 'FR' 'RK' 'LS' 'AF' 'LM' 'QR']
Countries (sample): ['GREAT BRITAIN' 'NETHERLANDS' 'GREECE' 'GERMANY' 'SPAIN' 'CYPRUS'
 'FRANCE' 'ITALY' 'MOROCCO' 'MALTA']

Pax describe:
count    11663.000000
mean       154.066878
std         50.485311
min          0.000000
25%        134.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2  GREAT BRITAIN       Domestic   A  145.0
1       KL    NETHERLANDS  International   A  149.0
2       U2         GREECE  International   A  195.0
3       BA  GREAT BRITAIN       Domestic   A  153.0
4       LH        GERMANY  International   A  116.0
5       FR          SPAIN  International   A  186.0
6       U2         CYPRUS  International   A  164.0
7       U2  GREAT BRITAIN       Domestic   A  130.0
8       U2         FRANCE  International   A  222.0
9       FR          ITALY  International   A  133.0
10      RK        MOROCCO  International   A  176.0
11      FR          ITALY  International   A  176.0
12      FR          MALTA  International   A  168.0
13      FR          ITALY  International   A  189.0
14      FR          SPAIN  International   A  181.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,208 / 11,663 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
229      EC        ITALY  133.0
232      EC       FRANCE  210.0
239      EC        ITALY  126.0
245      EC       FRANCE  187.0
309      RK        MALTA  187.0
336      IB        SPAIN  165.0
346      EC       FRANCE  166.0
347      DS  SWITZERLAND  180.0
349      DS  SWITZERLAND  185.0
352      IB        SPAIN  167.0
364      DS  SWITZERLAND  152.0
367      DS  SWITZERLAND  158.0
370      EC        SPAIN  109.0
371      EC       FRANCE  148.0
384      EC        SPAIN  142.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18259.244005815694
Total PRMs after rounding: 18618

Raw PRM demand distribution (prm_raw):
count    11663.000000
mean         1.565570
std          1.204366
min          0.000000
25%          0.834005
50%          1.248177
75%          1.719072
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
9548       BY                    GREECE  189.0   0.042488  8.030258
6046       BY                    GREECE  189.0   0.042488  8.030258
3360       BY                    GREECE  189.0   0.042488  8.030258
4893       BY                     SPAIN  188.0   0.042640  8.016392
8712       BY                    GREECE  188.0   0.042488  7.987770
11075      BY                     SPAIN  187.0   0.042640  7.973751
11226      BY                     SPAIN  187.0   0.042640  7.973751
7566       BY                     SPAIN  187.0   0.042640  7.973751
9708       BY                    GREECE  186.0   0.042488  7.902794
2192       BY                     SPAIN  185.0   0.042640  7.888470
6680       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
10235      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
139        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
1289       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5558       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
9548            8
6046            8
3360            8
4893            8
8712            8
11075           8
11226           8
7566            8
9708            8
2192            8
6680            8
10235           8
139             8
1289            8
5558            8
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=145.0 | Pen=0.00918 | Pax*Pen=1.331 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=149.0 | Pen=0.00831 | Pax*Pen=1.238 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=195.0 | Pen=0.01184 | Pax*Pen=2.308 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=153.0 | Pen=0.00962 | Pax*Pen=1.472 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=116.0 | Pen=0.00569 | Pax*Pen=0.660 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=186.0 | Pen=0.00966 | Pax*Pen=1.796 | PRMs=2
[DEBUG flight] Airline=U2 | Country=CYPRUS | Pax=164.0 | Pen=0.02183 | Pax*Pen=3.580 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=130.0 | Pen=0.00918 | Pax*Pen=1.193 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=222.0 | Pen=0.00839 | Pax*Pen=1.862 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=133.0 | Pen=0.00547 | Pax*Pen=0.727 | PRMs=1
[DEBUG flight] Airline=RK | Country=MOROCCO | Pax=176.0 | Pen=0.01007 | Pax*Pen=1.772 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=176.0 | Pen=0.00547 | Pax*Pen=0.962 | PRMs=1
[DEBUG flight] Airline=FR | Country=MALTA | Pax=168.0 | Pen=0.00863 | Pax*Pen=1.450 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=189.0 | Pen=0.00547 | Pax*Pen=1.033 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=181.0 | Pen=0.00966 | Pax*Pen=1.748 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 18618
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9823
WCHS     7639
WCHC     1037
OTHER     119
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-07-01 → 2026-08-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11663
Airlines (sample): ['AF' 'FR' 'KL' 'BA' 'U2' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['FRANCE' 'POLAND' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'ITALY'
 'PORTUGAL' 'SPAIN' 'GREECE' 'GERMANY']

Pax describe:
count    11663.000000
mean       154.066878
std         50.485311
min          0.000000
25%        134.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D  124.0
1       FR         POLAND  International   D  196.0
2       FR         LATVIA  International   D  179.0
3       KL    NETHERLANDS  International   D  143.0
4       BA  GREAT BRITAIN       Domestic   D  164.0
5       U2          ITALY  International   D  174.0
6       U2       PORTUGAL  International   D  170.0
7       U2          ITALY  International   D  153.0
8       FR          SPAIN  International   D  167.0
9       LS         GREECE  International   D  199.0
10      U2         FRANCE  International   D  231.0
11      LH        GERMANY  International   D  161.0
12      FR          ITALY  International   D  180.0
13      LM  GREAT BRITAIN       Domestic   D   44.0
14      LS          SPAIN  International   D  203.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,208 / 11,663 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
119      EC        ITALY  126.0
121      EC       FRANCE  187.0
155      RK        MALTA  187.0
175      IB        SPAIN  167.0
183      DS  SWITZERLAND  152.0
184      DS  SWITZERLAND  158.0
186      EC       FRANCE  148.0
193      EC        SPAIN  142.0
199      EC        SPAIN  125.0
243      AP       FRANCE  179.0
244      EC       FRANCE  164.0
254      EC        SPAIN  154.0
321      EC        ITALY  130.0
331      LG   LUXEMBOURG  127.0
385      DS  SWITZERLAND  157.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18259.244005815694
Total PRMs after rounding: 18618

Raw PRM demand distribution (prm_raw):
count    11663.000000
mean         1.565570
std          1.204366
min          0.000000
25%          0.834005
50%          1.248177
75%          1.719072
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
4619       BY                    GREECE  189.0   0.042488  8.030258
9548       BY                    GREECE  189.0   0.042488  8.030258
7927       BY                    GREECE  189.0   0.042488  8.030258
6755       BY                     SPAIN  188.0   0.042640  8.016392
5229       BY                    GREECE  188.0   0.042488  7.987770
11226      BY                     SPAIN  187.0   0.042640  7.973751
5171       BY                     SPAIN  187.0   0.042640  7.973751
11075      BY                     SPAIN  187.0   0.042640  7.973751
9708       BY                    GREECE  186.0   0.042488  7.902794
6174       BY                     SPAIN  185.0   0.042640  7.888470
8756       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5807       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5288       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
10235      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5025       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
4619            8
9548            8
7927            8
6755            8
5229            8
11226           8
5171            8
11075           8
9708            8
6174            8
8756            8
5807            8
5288            8
10235           8
5025            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=124.0 | Pen=0.00755 | Pax*Pen=0.936 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=196.0 | Pen=0.00313 | Pax*Pen=0.614 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=179.0 | Pen=0.00414 | Pax*Pen=0.741 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=143.0 | Pen=0.00831 | Pax*Pen=1.188 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=164.0 | Pen=0.00962 | Pax*Pen=1.577 | PRMs=2
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=174.0 | Pen=0.00872 | Pax*Pen=1.517 | PRMs=2
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=170.0 | Pen=0.00785 | Pax*Pen=1.334 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=153.0 | Pen=0.00872 | Pax*Pen=1.334 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=167.0 | Pen=0.00966 | Pax*Pen=1.613 | PRMs=2
[DEBUG flight] Airline=LS | Country=GREECE | Pax=199.0 | Pen=0.01748 | Pax*Pen=3.478 | PRMs=3
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=231.0 | Pen=0.00839 | Pax*Pen=1.937 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=161.0 | Pen=0.00569 | Pax*Pen=0.916 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=180.0 | Pen=0.00547 | Pax*Pen=0.984 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=44.0 | Pen=0.01980 | Pax*Pen=0.871 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=203.0 | Pen=0.02578 | Pax*Pen=5.233 | PRMs=5

[DEBUG ingest_s26]
Total PRM jobs (rows): 18618
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9825
WCHS     7671
WCHC     1011
OTHER     111
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,618   [333.79s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,616   [0.37s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.57s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 2}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
KK            D      2
dtype: int64

Bucket horizon: start=2026-07-01 23:30:00 end=2026-08-01 05:30:00 buckets=2905
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-07-09 08:45:00 | 75.0 / 210.0
  2026-07-09 08:15:00 | 60.0 / 210.0
  2026-07-09 08:30:00 | 60.0 / 210.0
  2026-07-09 09:00:00 | 60.0 / 210.0
  2026-07-30 19:15:00 | 60.0 / 210.0
  2026-07-14 16:00:00 | 60.0 / 210.0
  2026-07-05 20:00:00 | 60.0 / 210.0
  2026-07-14 13:00:00 | 45.0 / 210.0
  2026-07-04 14:45:00 | 45.0 / 210.0
  2026-07-21 15:30:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 401
  is_spin by dir:
dir
A    401
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.014512683333333333 31.906655366666666 59.95100278333334
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 85048.6
  total available over horizon: 590250.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 16
  min mini minutes required (forced): 279.6
  total mini minutes available: 217875.0

Lift rough check:
  lift jobs: 51
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3120
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_1887_0  AF_1887_2026-07-09 06:00:00   D 2026-07-09 05:45:00
8    S26_3321_0  U2_3321_2026-07-09 05:45:00   D 2026-07-09 05:45:00
9    S26_3311_0  U2_3311_2026-07-09 06:15:00   D 2026-07-09 06:00:00
10   S26_6698_0  FR_6698_2026-07-09 06:15:00   D 2026-07-09 06:15:00
11   S26_6698_1  FR_6698_2026-07-09 06:15:00   D 2026-07-09 06:15:00
19   S26_0321_0  LM_0321_2026-07-09 06:30:00   D 2026-07-09 06:30:00
26   S26_0307_0  U2_0307_2026-07-09 06:45:00   D 2026-07-09 06:30:00
27   S26_8750_0  FR_8750_2026-07-09 06:45:00   D 2026-07-09 06:45:00
34   S26_0353_0  LM_0353_2026-07-09 07:00:00   D 2026-07-09 06:45:00
38   S26_8711_0  BA_8711_2026-07-09 07:00:00   D 2026-07-09 07:00:00
41   S26_3241_0  U2_3241_2026-07-09 07:30:00   D 2026-07-09 07:15:00
42   S26_3301_0  U2_3301_2026-07-09 07:00:00   D 2026-07-09 07:00:00
44   S26_3331_0  U2_3331_2026-07-09 07:45:00   D 2026-07-09 07:30:00
45   S26_3331_1  U2_3331_2026-07-09 07:45:00   D 2026-07-09 07:30:00
46   S26_0775_0  LS_0775_2026-07-09 07:00:00   D 2026-07-09 07:00:00
47   S26_0775_1  LS_0775_2026-07-09 07:00:00   D 2026-07-09 07:00:00
48   S26_0775_2  LS_0775_2026-07-09 07:00:00   D 2026-07-09 07:00:00
49   S26_0775_3  LS_0775_2026-07-09 07:00:00   D 2026-07-09 07:00:00
50   S26_0775_4  LS_0775_2026-07-09 07:00:00   D 2026-07-09 07:00:00
59   S26_0597_0  RK_0597_2026-07-09 07:15:00   D 2026-07-09 07:15:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-07-09 05:59:14.174584266 2026-07-09 05:40:00    31           AF
8  2026-07-09 05:55:00.000000000 2026-07-09 05:55:00    25           U2
9  2026-07-09 06:13:08.533175352 2026-07-09 06:00:00    29           U2
10 2026-07-09 06:18:52.955173068 2026-07-09 06:00:00    11           FR
11 2026-07-09 06:18:52.955173068 2026-07-09 06:00:00    11           FR
19 2026-07-09 06:32:11.583290682 2026-07-09 06:15:00     7           LM
26 2026-07-09 06:42:02.223107940 2026-07-09 06:30:00    22           U2
27 2026-07-09 06:54:01.967220600 2026-07-09 06:35:00    10           FR
34 2026-07-09 06:55:36.476689446 2026-07-09 06:50:00   311           LM
38 2026-07-09 07:02:11.664489876 2026-07-09 07:00:00     9           BA
41 2026-07-09 07:26:38.901191406 2026-07-09 07:00:00    11           U2
42 2026-07-09 07:03:24.520095252 2026-07-09 07:00:00   15B           U2
44 2026-07-09 07:40:04.053367740 2026-07-09 07:05:00    25           U2

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-07 | Cutoff: 2026-07-01
Scenario 1:
  PeakAmb=14 | PeakMini=2
Scenario 2:
  PeakAmb=12 | PeakMini=5
SLA:
  All=0.9357 | Arr=0.9441 | Dep=0.9273
SLA diagnostics:
  allowed_breaches=373 | actual_breaches=1197 | sla_percent=93.57% | sla_floor_slack=824.00
  WARNING: hard SLA floor relaxed by slack on 824.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_07.csv
================================================


[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S26 2026-08 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11885
Airlines (sample): ['RK' 'FR' 'EI' 'U2' 'LM' 'LS' 'AF' 'AY' 'SK' 'KL']
Countries (sample): ['GREAT BRITAIN' 'CZECH REPUBLIC' 'ITALY' 'IRISH REPUBLIC' 'CYPRUS'
 'TURKEY' 'FRANCE' 'SPAIN' 'FINLAND' 'DENMARK']

Pax describe:
count    11885.000000
mean       153.296592
std         52.511228
min          0.000000
25%        131.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       RK   GREAT BRITAIN       Domestic   D  166.0
1       FR  CZECH REPUBLIC  International   D  182.0
2       FR           ITALY  International   D  187.0
3       EI  IRISH REPUBLIC            CTA   D   66.0
4       U2   GREAT BRITAIN       Domestic   D  137.0
5       FR           ITALY  International   D  178.0
6       EI  IRISH REPUBLIC            CTA   D   65.0
7       EI  IRISH REPUBLIC            CTA   D   64.0
8       U2          CYPRUS  International   D  158.0
9       U2   GREAT BRITAIN       Domestic   D  167.0
10      U2          TURKEY  International   D  181.0
11      LM   GREAT BRITAIN       Domestic   D   40.0
12      LS          TURKEY  International   D  232.0
13      AF          FRANCE  International   D   87.0
14      EI  IRISH REPUBLIC            CTA   D   68.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,370 / 11,885 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
75       EC      GERMANY  156.0
91       EC        ITALY  142.0
220      EC        ITALY  111.0
255      EC       FRANCE  132.0
265      EC  NETHERLANDS  170.0
282      EC        SPAIN   91.0
284      EC        ITALY  139.0
324      DS  SWITZERLAND  153.0
355      EC        SPAIN   90.0
388      EC        ITALY  112.0
391      RK      ROMANIA  159.0
409      LG   LUXEMBOURG  120.0
412      DS  SWITZERLAND  167.0
417      EC       FRANCE  154.0
445      EC        SPAIN  118.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18472.40687061708
Total PRMs after rounding: 18888

Raw PRM demand distribution (prm_raw):
count    11885.000000
mean         1.554262
std          1.255458
min          0.000000
25%          0.815614
50%          1.233208
75%          1.707065
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
4984       QR       QATAR  311.0   0.026728  8.312373           8
2020       QR       QATAR  311.0   0.026728  8.312373           8
689        QR       QATAR  311.0   0.026728  8.312373           8
4043       QR       QATAR  311.0   0.026728  8.312373           8
39         QR       QATAR  311.0   0.026728  8.312373           8
92         QR       QATAR  311.0   0.026728  8.312373           8
3936       QR       QATAR  311.0   0.026728  8.312373           8
10771      QR       QATAR  311.0   0.026728  8.312373           8
3845       QR       QATAR  311.0   0.026728  8.312373           8
5072       QR       QATAR  311.0   0.026728  8.312373           8
562        QR       QATAR  311.0   0.026728  8.312373           8
873        QR       QATAR  311.0   0.026728  8.312373           8
1827       QR       QATAR  311.0   0.026728  8.312373           8
3734       QR       QATAR  311.0   0.026728  8.312373           8
11766      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=166.0 | Pen=0.00637 | Pax*Pen=1.058 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=182.0 | Pen=0.00359 | Pax*Pen=0.653 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=187.0 | Pen=0.00547 | Pax*Pen=1.022 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=66.0 | Pen=0.01035 | Pax*Pen=0.683 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=137.0 | Pen=0.00918 | Pax*Pen=1.257 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=178.0 | Pen=0.00547 | Pax*Pen=0.973 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=65.0 | Pen=0.01035 | Pax*Pen=0.673 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=64.0 | Pen=0.01035 | Pax*Pen=0.662 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CYPRUS | Pax=158.0 | Pen=0.02183 | Pax*Pen=3.449 | PRMs=3
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=167.0 | Pen=0.00918 | Pax*Pen=1.533 | PRMs=2
[DEBUG flight] Airline=U2 | Country=TURKEY | Pax=181.0 | Pen=0.01858 | Pax*Pen=3.363 | PRMs=3
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=40.0 | Pen=0.01980 | Pax*Pen=0.792 | PRMs=1
[DEBUG flight] Airline=LS | Country=TURKEY | Pax=232.0 | Pen=0.02622 | Pax*Pen=6.084 | PRMs=6
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=87.0 | Pen=0.00755 | Pax*Pen=0.657 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=68.0 | Pen=0.01035 | Pax*Pen=0.704 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18888
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10006
WCHS      7683
WCHC      1076
OTHER      123
Name: count, dtype: int64
[BUILD_JOBS] Dropping 4 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1546 PRM jobs via stratified percentile cap

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-08-01 → 2026-09-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11885
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SLOVAKIA' 'NETHERLANDS' 'SPAIN' 'GREAT BRITAIN' 'POLAND'
 'SWITZERLAND' 'GERMANY' 'CROATIA' 'ITALY']

Pax describe:
count    11885.000000
mean       153.296592
std         52.511228
min          0.000000
25%        131.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   90.0
1       U2         FRANCE  International   D  208.0
2       FR       SLOVAKIA  International   D  186.0
3       KL    NETHERLANDS  International   D  139.0
4       FR          SPAIN  International   D  197.0
5       BA  GREAT BRITAIN       Domestic   D  143.0
6       U2  GREAT BRITAIN       Domestic   D  126.0
7       U2          SPAIN  International   D  169.0
8       FR         POLAND  International   D  186.0
9       LS          SPAIN  International   D  229.0
10      U2    SWITZERLAND  International   D  164.0
11      LH        GERMANY  International   D  166.0
12      U2        CROATIA  International   D  177.0
13      FR          ITALY  International   D  175.0
14      FR        ROMANIA  International   D  196.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,370 / 11,885 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
20       RK        MALTA  181.0
36       EC  NETHERLANDS  156.0
101      EC      GERMANY  151.0
103      U2     SLOVENIA  171.0
116      EC        ITALY  144.0
121      BA        ITALY   76.0
156      EC        SPAIN  127.0
157      DS  SWITZERLAND  175.0
160      EC        SPAIN  129.0
228      EC        ITALY  149.0
231      IB        SPAIN  159.0
262      EC      GERMANY  156.0
275      EC       FRANCE  107.0
292      EC        ITALY  142.0
319      EC       FRANCE  149.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18472.40687061708
Total PRMs after rounding: 18888

Raw PRM demand distribution (prm_raw):
count    11885.000000
mean         1.554262
std          1.255458
min          0.000000
25%          0.815614
50%          1.233208
75%          1.707065
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
35         QR       QATAR  311.0   0.026728  8.312373           8
5474       QR       QATAR  311.0   0.026728  8.312373           8
873        QR       QATAR  311.0   0.026728  8.312373           8
11766      QR       QATAR  311.0   0.026728  8.312373           8
2309       QR       QATAR  311.0   0.026728  8.312373           8
4505       QR       QATAR  311.0   0.026728  8.312373           8
2399       QR       QATAR  311.0   0.026728  8.312373           8
2507       QR       QATAR  311.0   0.026728  8.312373           8
10771      QR       QATAR  311.0   0.026728  8.312373           8
2597       QR       QATAR  311.0   0.026728  8.312373           8
974        QR       QATAR  311.0   0.026728  8.312373           8
2705       QR       QATAR  311.0   0.026728  8.312373           8
5558       QR       QATAR  311.0   0.026728  8.312373           8
689        QR       QATAR  311.0   0.026728  8.312373           8
2794       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=90.0 | Pen=0.00755 | Pax*Pen=0.679 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=208.0 | Pen=0.00839 | Pax*Pen=1.745 | PRMs=2
[DEBUG flight] Airline=FR | Country=SLOVAKIA | Pax=186.0 | Pen=0.00226 | Pax*Pen=0.421 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=139.0 | Pen=0.00831 | Pax*Pen=1.155 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00962 | Pax*Pen=1.375 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=126.0 | Pen=0.00918 | Pax*Pen=1.156 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=169.0 | Pen=0.01381 | Pax*Pen=2.334 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=186.0 | Pen=0.00313 | Pax*Pen=0.582 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=229.0 | Pen=0.02578 | Pax*Pen=5.904 | PRMs=6
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=164.0 | Pen=0.00694 | Pax*Pen=1.139 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=166.0 | Pen=0.00569 | Pax*Pen=0.945 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=177.0 | Pen=0.00421 | Pax*Pen=0.746 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=175.0 | Pen=0.00547 | Pax*Pen=0.957 | PRMs=1
[DEBUG flight] Airline=FR | Country=ROMANIA | Pax=196.0 | Pen=0.00422 | Pax*Pen=0.828 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18888
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10020
WCHS      7663
WCHC      1093
OTHER      112
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,888   [87.48s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 4 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1543 PRM jobs via stratified percentile cap
    ✓ build_jobs done | jobs=17,341   [0.51s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.50s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-07-31 23:15:00 end=2026-09-01 05:45:00 buckets=3003
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-08-23 21:00:00 | 75.0 / 210.0
  2026-08-28 18:15:00 | 75.0 / 210.0
  2026-08-28 18:30:00 | 75.0 / 210.0
  2026-08-23 20:15:00 | 60.0 / 210.0
  2026-08-23 20:45:00 | 60.0 / 210.0
  2026-08-12 19:45:00 | 60.0 / 210.0
  2026-08-01 12:45:00 | 60.0 / 210.0
  2026-08-28 15:15:00 | 60.0 / 210.0
  2026-08-28 15:30:00 | 60.0 / 210.0
  2026-08-28 18:00:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 395
  is_spin by dir:
dir
A    395
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.041245899999999995 31.871224283333333 59.97451768333334
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 82688.0
  total available over horizon: 610470.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 18
  min mini minutes required (forced): 312.1
  total mini minutes available: 225225.0

Lift rough check:
  lift jobs: 78
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2906
Examples (first 20):
    Passenger ID                   flight_key dir                   t  \
j
14    S26_0633_0  A3_0633_2026-08-01 09:45:00   D 2026-08-01 09:45:00
17    S26_0633_0  A3_0633_2026-08-08 09:30:00   D 2026-08-08 09:15:00
19    S26_0633_0  A3_0633_2026-08-12 09:45:00   D 2026-08-12 09:45:00
20    S26_0633_0  A3_0633_2026-08-15 09:15:00   D 2026-08-15 09:15:00
21    S26_0633_0  A3_0633_2026-08-17 09:30:00   D 2026-08-17 09:30:00
23    S26_0633_0  A3_0633_2026-08-22 09:45:00   D 2026-08-22 09:30:00
27    S26_0633_0  A3_0633_2026-08-31 09:30:00   D 2026-08-31 09:30:00
80    S26_0083_0  AA_0083_2026-08-01 10:45:00   D 2026-08-01 10:45:00
81    S26_0083_1  AA_0083_2026-08-01 10:45:00   D 2026-08-01 10:45:00
84    S26_0083_0  AA_0083_2026-08-03 10:45:00   D 2026-08-03 10:45:00
85    S26_0083_1  AA_0083_2026-08-03 10:45:00   D 2026-08-03 10:45:00
88    S26_0083_0  AA_0083_2026-08-05 11:45:00   D 2026-08-05 11:30:00
89    S26_0083_1  AA_0083_2026-08-05 11:45:00   D 2026-08-05 11:30:00
90    S26_0083_0  AA_0083_2026-08-06 12:00:00   D 2026-08-06 11:45:00
91    S26_0083_1  AA_0083_2026-08-06 12:00:00   D 2026-08-06 11:45:00
94    S26_0083_0  AA_0083_2026-08-08 10:45:00   D 2026-08-08 10:45:00
95    S26_0083_1  AA_0083_2026-08-08 10:45:00   D 2026-08-08 10:45:00
100   S26_0083_1  AA_0083_2026-08-11 10:45:00   D 2026-08-11 10:30:00
101   S26_0083_0  AA_0083_2026-08-11 10:45:00   D 2026-08-11 10:30:00
102   S26_0083_0  AA_0083_2026-08-12 11:15:00   D 2026-08-12 11:00:00

               hard_deadline_time      sla_start_time Stand Airline Code
j
14  2026-08-01 09:46:36.200633400 2026-08-01 09:25:00    1B           A3
17  2026-08-08 09:28:51.272611752 2026-08-08 09:25:00     1           A3
19  2026-08-12 09:50:09.619731210 2026-08-12 09:25:00    27           A3
20  2026-08-15 09:25:00.000000000 2026-08-15 09:25:00    14           A3
21  2026-08-17 09:32:36.976575486 2026-08-17 09:25:00     3           A3
23  2026-08-22 09:40:36.871692774 2026-08-22 09:25:00     3           A3
27  2026-08-31 09:30:23.786951208 2026-08-31 09:25:00     3           A3
80  2026-08-01 10:53:36.135304170 2026-08-01 10:30:00    4A           AA
81  2026-08-01 10:53:36.135304170 2026-08-01 10:30:00    4A           AA
84  2026-08-03 10:54:41.048185434 2026-08-03 10:30:00   102           AA
85  2026-08-03 10:54:41.048185434 2026-08-03 10:30:00   102           AA
88  2026-08-05 11:41:16.042016987 2026-08-05 10:30:00    4A           AA
89  2026-08-05 11:41:16.042016987 2026-08-05 10:30:00    4A           AA
90  2026-08-06 11:57:21.416736246 2026-08-06 10:30:00    4A           AA
91  2026-08-06 11:57:21.416736246 2026-08-06 10:30:00    4A           AA
94  2026-08-08 10:50:15.565484111 2026-08-08 10:30:00    4A           AA
95  2026-08-08 10:50:15.565484111 2026-08-08 10:30:00    4A           AA

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-08 | Cutoff: 2026-07-02
Scenario 1:
  PeakAmb=11 | PeakMini=2
Scenario 2:
  PeakAmb=12 | PeakMini=5
SLA:
  All=0.9304 | Arr=0.9419 | Dep=0.9190
SLA diagnostics:
  allowed_breaches=347 | actual_breaches=1207 | sla_percent=93.04% | sla_floor_slack=860.00
  WARNING: hard SLA floor relaxed by slack on 860.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_08.csv
================================================


Running S26 2026-08 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11885
Airlines (sample): ['LS' 'U2' 'LH' 'FR' 'RK' 'LM' 'AC' 'DL' 'BA' 'EI']
Countries (sample): ['SPAIN' 'SWITZERLAND' 'GERMANY' 'ITALY' 'GREAT BRITAIN' 'FRANCE'
 'PORTUGAL' 'POLAND' 'IRISH REPUBLIC' 'CZECH REPUBLIC']

Pax describe:
count    11885.000000
mean       153.296592
std         52.511228
min          0.000000
25%        131.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       LS           SPAIN  International   D  229.0
1       U2     SWITZERLAND  International   D  164.0
2       LH         GERMANY  International   D  166.0
3       FR           ITALY  International   D  175.0
4       RK   GREAT BRITAIN       Domestic   D  161.0
5       U2          FRANCE  International   D  166.0
6       LS        PORTUGAL  International   D  170.0
7       FR          POLAND  International   D  193.0
8       U2   GREAT BRITAIN       Domestic   D  171.0
9       FR  IRISH REPUBLIC            CTA   D  171.0
10      LM   GREAT BRITAIN       Domestic   D   27.0
11      FR          FRANCE  International   D  181.0
12      LM   GREAT BRITAIN       Domestic   D   53.0
13      RK   GREAT BRITAIN       Domestic   D  166.0
14      FR           SPAIN  International   D  194.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,370 / 11,885 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
116      EC      GERMANY  156.0
133      EC        ITALY  142.0
271      EC        ITALY  111.0
308      EC       FRANCE  132.0
318      EC  NETHERLANDS  170.0
335      EC        SPAIN   91.0
337      EC        ITALY  139.0
377      DS  SWITZERLAND  153.0
408      EC        SPAIN   90.0
441      EC        ITALY  112.0
444      RK      ROMANIA  159.0
460      LG   LUXEMBOURG  120.0
463      DS  SWITZERLAND  167.0
468      EC       FRANCE  154.0
491      EC        SPAIN  118.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18472.40687061708
Total PRMs after rounding: 18888

Raw PRM demand distribution (prm_raw):
count    11885.000000
mean         1.554262
std          1.255458
min          0.000000
25%          0.815614
50%          1.233208
75%          1.707065
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
2965      QR       QATAR  311.0   0.026728  8.312373           8
4218      QR       QATAR  311.0   0.026728  8.312373           8
1625      QR       QATAR  311.0   0.026728  8.312373           8
7220      QR       QATAR  311.0   0.026728  8.312373           8
2597      QR       QATAR  311.0   0.026728  8.312373           8
4133      QR       QATAR  311.0   0.026728  8.312373           8
77        QR       QATAR  311.0   0.026728  8.312373           8
7067      QR       QATAR  311.0   0.026728  8.312373           8
4698      QR       QATAR  311.0   0.026728  8.312373           8
3936      QR       QATAR  311.0   0.026728  8.312373           8
1367      QR       QATAR  311.0   0.026728  8.312373           8
4306      QR       QATAR  311.0   0.026728  8.312373           8
4043      QR       QATAR  311.0   0.026728  8.312373           8
1456      QR       QATAR  311.0   0.026728  8.312373           8
1541      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=229.0 | Pen=0.02578 | Pax*Pen=5.904 | PRMs=6
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=164.0 | Pen=0.00694 | Pax*Pen=1.139 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=166.0 | Pen=0.00569 | Pax*Pen=0.945 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=175.0 | Pen=0.00547 | Pax*Pen=0.957 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=161.0 | Pen=0.00637 | Pax*Pen=1.026 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=166.0 | Pen=0.00839 | Pax*Pen=1.392 | PRMs=1
[DEBUG flight] Airline=LS | Country=PORTUGAL | Pax=170.0 | Pen=0.01789 | Pax*Pen=3.041 | PRMs=3
[DEBUG flight] Airline=FR | Country=POLAND | Pax=193.0 | Pen=0.00313 | Pax*Pen=0.604 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=171.0 | Pen=0.00918 | Pax*Pen=1.569 | PRMs=2
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=171.0 | Pen=0.00652 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=27.0 | Pen=0.01980 | Pax*Pen=0.535 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=181.0 | Pen=0.00686 | Pax*Pen=1.242 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=53.0 | Pen=0.01980 | Pax*Pen=1.049 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=166.0 | Pen=0.00637 | Pax*Pen=1.058 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=194.0 | Pen=0.00966 | Pax*Pen=1.873 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 18888
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10038
WCHS      7683
WCHC      1042
OTHER      125
Name: count, dtype: int64
[BUILD_JOBS] Dropping 4 jobs already impossible at release (beyond SLA + max late)

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-08-01 → 2026-09-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11885
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SLOVAKIA' 'NETHERLANDS' 'SPAIN' 'GREAT BRITAIN' 'POLAND'
 'SWITZERLAND' 'GERMANY' 'CROATIA' 'ITALY']

Pax describe:
count    11885.000000
mean       153.296592
std         52.511228
min          0.000000
25%        131.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   90.0
1       U2         FRANCE  International   D  208.0
2       FR       SLOVAKIA  International   D  186.0
3       KL    NETHERLANDS  International   D  139.0
4       FR          SPAIN  International   D  197.0
5       BA  GREAT BRITAIN       Domestic   D  143.0
6       U2  GREAT BRITAIN       Domestic   D  126.0
7       U2          SPAIN  International   D  169.0
8       FR         POLAND  International   D  186.0
9       LS          SPAIN  International   D  229.0
10      U2    SWITZERLAND  International   D  164.0
11      LH        GERMANY  International   D  166.0
12      U2        CROATIA  International   D  177.0
13      FR          ITALY  International   D  175.0
14      FR        ROMANIA  International   D  196.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,370 / 11,885 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
20       RK        MALTA  181.0
36       EC  NETHERLANDS  156.0
101      EC      GERMANY  151.0
103      U2     SLOVENIA  171.0
116      EC        ITALY  144.0
121      BA        ITALY   76.0
156      EC        SPAIN  127.0
157      DS  SWITZERLAND  175.0
160      EC        SPAIN  129.0
228      EC        ITALY  149.0
231      IB        SPAIN  159.0
262      EC      GERMANY  156.0
275      EC       FRANCE  107.0
292      EC        ITALY  142.0
319      EC       FRANCE  149.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18472.40687061708
Total PRMs after rounding: 18888

Raw PRM demand distribution (prm_raw):
count    11885.000000
mean         1.554262
std          1.255458
min          0.000000
25%          0.815614
50%          1.233208
75%          1.707065
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
35         QR       QATAR  311.0   0.026728  8.312373           8
5474       QR       QATAR  311.0   0.026728  8.312373           8
873        QR       QATAR  311.0   0.026728  8.312373           8
11766      QR       QATAR  311.0   0.026728  8.312373           8
2309       QR       QATAR  311.0   0.026728  8.312373           8
4505       QR       QATAR  311.0   0.026728  8.312373           8
2399       QR       QATAR  311.0   0.026728  8.312373           8
2507       QR       QATAR  311.0   0.026728  8.312373           8
10771      QR       QATAR  311.0   0.026728  8.312373           8
2597       QR       QATAR  311.0   0.026728  8.312373           8
974        QR       QATAR  311.0   0.026728  8.312373           8
2705       QR       QATAR  311.0   0.026728  8.312373           8
5558       QR       QATAR  311.0   0.026728  8.312373           8
689        QR       QATAR  311.0   0.026728  8.312373           8
2794       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=90.0 | Pen=0.00755 | Pax*Pen=0.679 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=208.0 | Pen=0.00839 | Pax*Pen=1.745 | PRMs=2
[DEBUG flight] Airline=FR | Country=SLOVAKIA | Pax=186.0 | Pen=0.00226 | Pax*Pen=0.421 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=139.0 | Pen=0.00831 | Pax*Pen=1.155 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00962 | Pax*Pen=1.375 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=126.0 | Pen=0.00918 | Pax*Pen=1.156 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=169.0 | Pen=0.01381 | Pax*Pen=2.334 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=186.0 | Pen=0.00313 | Pax*Pen=0.582 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=229.0 | Pen=0.02578 | Pax*Pen=5.904 | PRMs=6
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=164.0 | Pen=0.00694 | Pax*Pen=1.139 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=166.0 | Pen=0.00569 | Pax*Pen=0.945 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=177.0 | Pen=0.00421 | Pax*Pen=0.746 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=175.0 | Pen=0.00547 | Pax*Pen=0.957 | PRMs=1
[DEBUG flight] Airline=FR | Country=ROMANIA | Pax=196.0 | Pen=0.00422 | Pax*Pen=0.828 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18888
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10020
WCHS      7663
WCHC      1093
OTHER      112
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,888   [86.05s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 4 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,884   [0.35s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.57s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-07-31 23:15:00 end=2026-09-01 05:45:00 buckets=3003
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-08-23 21:00:00 | 75.0 / 210.0
  2026-08-28 18:15:00 | 75.0 / 210.0
  2026-08-28 18:30:00 | 75.0 / 210.0
  2026-08-23 20:15:00 | 60.0 / 210.0
  2026-08-23 20:45:00 | 60.0 / 210.0
  2026-08-12 19:45:00 | 60.0 / 210.0
  2026-08-01 12:45:00 | 60.0 / 210.0
  2026-08-28 15:15:00 | 60.0 / 210.0
  2026-08-28 15:30:00 | 60.0 / 210.0
  2026-08-28 18:00:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 406
  is_spin by dir:
dir
A    406
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.041245899999999995 31.84397045833333 59.97451768333334
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 84928.3
  total available over horizon: 610470.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 18
  min mini minutes required (forced): 312.1
  total mini minutes available: 225225.0

Lift rough check:
  lift jobs: 78
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3108
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
1    S26_3249_0  U2_3249_2026-08-01 06:15:00   D 2026-08-01 06:00:00
2    S26_3249_1  U2_3249_2026-08-01 06:15:00   D 2026-08-01 06:00:00
4    S26_6266_0  FR_6266_2026-08-01 06:15:00   D 2026-08-01 06:15:00
5    S26_6266_1  FR_6266_2026-08-01 06:15:00   D 2026-08-01 06:15:00
11   S26_0775_0  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
12   S26_0775_1  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
13   S26_0775_2  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
14   S26_0775_3  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
15   S26_0775_4  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
16   S26_0775_5  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
19   S26_3319_0  U2_3319_2026-08-01 07:00:00   D 2026-08-01 07:00:00
20   S26_3264_0  FR_3264_2026-08-01 07:15:00   D 2026-08-01 07:00:00
44   S26_5608_0  FR_5608_2026-08-01 07:00:00   D 2026-08-01 06:45:00
45   S26_5608_1  FR_5608_2026-08-01 07:00:00   D 2026-08-01 06:45:00
59   S26_0032_0  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00
60   S26_0032_1  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00
61   S26_0032_2  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00
62   S26_0032_3  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00
63   S26_0032_4  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00
64   S26_0032_5  QR_0032_2026-08-01 08:00:00   D 2026-08-01 08:00:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
1  2026-08-01 06:14:33.639457470 2026-08-01 05:40:00    20           U2
2  2026-08-01 06:14:33.639457470 2026-08-01 05:40:00    20           U2
4  2026-08-01 06:18:33.619277772 2026-08-01 05:55:00   100           FR
5  2026-08-01 06:18:33.619277772 2026-08-01 05:55:00   100           FR
11 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
12 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
13 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
14 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
15 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
16 2026-08-01 06:14:25.860809208 2026-08-01 06:00:00    14           LS
19 2026-08-01 07:05:41.954360046 2026-08-01 06:15:00    24           U2
20 2026-08-01 07:10:01.128383616 2026-08-01 06:15:00    24           FR
44 2026-08-01 06:55:36.379105548 2026-08-01 06:55:00   15A           FR
45 2026-08-01 06:55:36.379105548 2026-08-01 06:55:00   15A           FR
59 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR
60 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR
61 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR
62 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR
63 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR
64 2026-08-01 08:07:01.421835396 2026-08-01 07:55:00    18           QR

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 10
  tight vertical jobs: 871
  saturated (avail=0) buckets: 0

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-08 | Cutoff: 2026-07-02
Scenario 1:
  PeakAmb=12 | PeakMini=2
Scenario 2:
  PeakAmb=11 | PeakMini=5
SLA:
  All=0.9340 | Arr=0.9439 | Dep=0.9242
SLA diagnostics:
  allowed_breaches=378 | actual_breaches=1247 | sla_percent=93.40% | sla_floor_slack=869.00
  WARNING: hard SLA floor relaxed by slack on 869.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_08.csv
================================================


[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S26 2026-09 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11433
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'LH' 'LS' 'LM' 'BA' 'QR' 'D8']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'CROATIA' 'SPAIN'
 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC' 'POLAND']

Pax describe:
count    11433.000000
mean       146.368845
std         54.771466
min          0.000000
25%        120.000000
50%        157.000000
75%        179.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  100.0
1       U2           ITALY  International   D  159.0
2       FR           ITALY  International   D  172.0
3       KL     NETHERLANDS  International   D  107.0
4       U2   GREAT BRITAIN       Domestic   D  165.0
5       U2   GREAT BRITAIN       Domestic   D  162.0
6       U2   GREAT BRITAIN       Domestic   D  146.0
7       U2         CROATIA  International   D  154.0
8       FR           SPAIN  International   D  188.0
9       LH         GERMANY  International   D  108.0
10      U2         TUNISIA  International   D  139.0
11      FR  IRISH REPUBLIC            CTA   D  120.0
12      LS           SPAIN  International   D  213.0
13      FR          POLAND  International   D  158.0
14      FR         BELGIUM  International   D   43.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,995 / 11,433 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
34       EC  NETHERLANDS  160.0
68       EC        ITALY  121.0
104      EC        SPAIN   81.0
136      U2     SLOVENIA  138.0
216      DS  SWITZERLAND  146.0
223      EC        ITALY  137.0
227      EC        SPAIN  156.0
269      EC  NETHERLANDS  162.0
330      DS  SWITZERLAND  116.0
367      IB        SPAIN  143.0
451      RK      ROMANIA  143.0
483      EC        ITALY  122.0
492      EC       FRANCE  182.0
518      RK        MALTA  176.0
540      IB        SPAIN  163.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17697.46475610584
Total PRMs after rounding: 17973

Raw PRM demand distribution (prm_raw):
count    11433.000000
mean         1.547928
std          1.302005
min          0.000000
25%          0.763414
50%          1.190974
75%          1.710000
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
497       QR       QATAR  311.0   0.026728  8.312373           8
5958      QR       QATAR  311.0   0.026728  8.312373           8
972       QR       QATAR  311.0   0.026728  8.312373           8
5031      QR       QATAR  311.0   0.026728  8.312373           8
4677      QR       QATAR  311.0   0.026728  8.312373           8
2388      QR       QATAR  311.0   0.026728  8.312373           8
5891      QR       QATAR  311.0   0.026728  8.312373           8
6953      QR       QATAR  311.0   0.026728  8.312373           8
5721      QR       QATAR  311.0   0.026728  8.312373           8
3151      QR       QATAR  311.0   0.026728  8.312373           8
1830      QR       QATAR  311.0   0.026728  8.312373           8
4943      QR       QATAR  311.0   0.026728  8.312373           8
890       QR       QATAR  311.0   0.026728  8.312373           8
5228      QR       QATAR  311.0   0.026728  8.312373           8
2299      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=100.0 | Pen=0.00755 | Pax*Pen=0.755 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=159.0 | Pen=0.00872 | Pax*Pen=1.386 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=172.0 | Pen=0.00547 | Pax*Pen=0.940 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=107.0 | Pen=0.00831 | Pax*Pen=0.889 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=165.0 | Pen=0.00918 | Pax*Pen=1.514 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=146.0 | Pen=0.00918 | Pax*Pen=1.340 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=154.0 | Pen=0.00421 | Pax*Pen=0.649 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=188.0 | Pen=0.00966 | Pax*Pen=1.815 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=139.0 | Pen=0.02346 | Pax*Pen=3.261 | PRMs=3
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=120.0 | Pen=0.00652 | Pax*Pen=0.783 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=213.0 | Pen=0.02578 | Pax*Pen=5.491 | PRMs=5
[DEBUG flight] Airline=FR | Country=POLAND | Pax=158.0 | Pen=0.00313 | Pax*Pen=0.495 | PRMs=0
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=43.0 | Pen=0.00380 | Pax*Pen=0.163 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 17973
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9519
WCHS     7376
WCHC      986
OTHER      92
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1638 PRM jobs via stratified percentile cap

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-09-01 → 2026-10-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11433
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'LH' 'LS' 'LM' 'BA' 'QR' 'D8']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'CROATIA' 'SPAIN'
 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC' 'POLAND']

Pax describe:
count    11433.000000
mean       146.368845
std         54.771466
min          0.000000
25%        120.000000
50%        157.000000
75%        179.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  100.0
1       U2           ITALY  International   D  159.0
2       FR           ITALY  International   D  172.0
3       KL     NETHERLANDS  International   D  107.0
4       U2   GREAT BRITAIN       Domestic   D  165.0
5       U2   GREAT BRITAIN       Domestic   D  162.0
6       U2   GREAT BRITAIN       Domestic   D  146.0
7       U2         CROATIA  International   D  154.0
8       FR           SPAIN  International   D  188.0
9       LH         GERMANY  International   D  108.0
10      U2         TUNISIA  International   D  139.0
11      FR  IRISH REPUBLIC            CTA   D  120.0
12      LS           SPAIN  International   D  213.0
13      FR          POLAND  International   D  158.0
14      FR         BELGIUM  International   D   43.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,995 / 11,433 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
34       EC  NETHERLANDS  160.0
68       EC        ITALY  121.0
104      EC        SPAIN   81.0
136      U2     SLOVENIA  138.0
214      DS  SWITZERLAND  146.0
221      EC        ITALY  137.0
225      EC        SPAIN  156.0
267      EC  NETHERLANDS  162.0
328      DS  SWITZERLAND  116.0
365      IB        SPAIN  143.0
451      RK      ROMANIA  143.0
483      EC        ITALY  122.0
492      EC       FRANCE  182.0
518      RK        MALTA  176.0
540      IB        SPAIN  163.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17697.46475610584
Total PRMs after rounding: 17973

Raw PRM demand distribution (prm_raw):
count    11433.000000
mean         1.547928
std          1.302005
min          0.000000
25%          0.763414
50%          1.190974
75%          1.710000
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
972        QR       QATAR  311.0   0.026728  8.312373           8
4943       QR       QATAR  311.0   0.026728  8.312373           8
4782       QR       QATAR  311.0   0.026728  8.312373           8
4584       QR       QATAR  311.0   0.026728  8.312373           8
4389       QR       QATAR  311.0   0.026728  8.312373           8
11017      QR       QATAR  311.0   0.026728  8.312373           8
2388       QR       QATAR  311.0   0.026728  8.312373           8
3066       QR       QATAR  311.0   0.026728  8.312373           8
3151       QR       QATAR  311.0   0.026728  8.312373           8
1061       QR       QATAR  311.0   0.026728  8.312373           8
3711       QR       QATAR  311.0   0.026728  8.312373           8
5031       QR       QATAR  311.0   0.026728  8.312373           8
2217       QR       QATAR  311.0   0.026728  8.312373           8
3538       QR       QATAR  311.0   0.026728  8.312373           8
6692       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=100.0 | Pen=0.00755 | Pax*Pen=0.755 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=159.0 | Pen=0.00872 | Pax*Pen=1.386 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=172.0 | Pen=0.00547 | Pax*Pen=0.940 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=107.0 | Pen=0.00831 | Pax*Pen=0.889 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=165.0 | Pen=0.00918 | Pax*Pen=1.514 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=146.0 | Pen=0.00918 | Pax*Pen=1.340 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=154.0 | Pen=0.00421 | Pax*Pen=0.649 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=188.0 | Pen=0.00966 | Pax*Pen=1.815 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=139.0 | Pen=0.02346 | Pax*Pen=3.261 | PRMs=3
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=120.0 | Pen=0.00652 | Pax*Pen=0.783 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=213.0 | Pen=0.02578 | Pax*Pen=5.491 | PRMs=5
[DEBUG flight] Airline=FR | Country=POLAND | Pax=158.0 | Pen=0.00313 | Pax*Pen=0.495 | PRMs=0
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=43.0 | Pen=0.00380 | Pax*Pen=0.163 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 17973
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9568
WCHS     7308
WCHC     1004
OTHER      93
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=17,973   [328.07s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 4 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1610 PRM jobs via stratified percentile cap
    ✓ build_jobs done | jobs=16,359   [0.48s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.48s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-08-31 23:45:00 end=2026-10-01 05:45:00 buckets=2905
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-09-18 13:45:00 | 75.0 / 210.0
  2026-09-18 14:00:00 | 60.0 / 210.0
  2026-09-10 09:30:00 | 60.0 / 210.0
  2026-09-19 14:30:00 | 60.0 / 210.0
  2026-09-09 09:15:00 | 60.0 / 210.0
  2026-09-17 15:45:00 | 45.0 / 210.0
  2026-09-17 16:00:00 | 45.0 / 210.0
  2026-09-17 16:15:00 | 45.0 / 210.0
  2026-09-17 16:30:00 | 45.0 / 210.0
  2026-09-15 18:00:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 332
  is_spin by dir:
dir
A    332
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.024663833333333333 32.5546438 59.854376450000004
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 77628.1
  total available over horizon: 593670.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 22
  min mini minutes required (forced): 382.0
  total mini minutes available: 217875.0

Lift rough check:
  lift jobs: 55
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2857
Examples (first 20):
    Passenger ID                   flight_key dir                   t  \
j
13    S26_0633_0  A3_0633_2026-09-02 09:15:00   D 2026-09-02 09:15:00
14    S26_0633_0  A3_0633_2026-09-05 10:00:00   D 2026-09-05 09:45:00
15    S26_0633_0  A3_0633_2026-09-07 09:30:00   D 2026-09-07 09:15:00
18    S26_0633_1  A3_0633_2026-09-14 09:45:00   D 2026-09-14 09:45:00
19    S26_0633_0  A3_0633_2026-09-14 09:45:00   D 2026-09-14 09:45:00
20    S26_0633_0  A3_0633_2026-09-16 10:00:00   D 2026-09-16 10:00:00
21    S26_0633_0  A3_0633_2026-09-19 09:30:00   D 2026-09-19 09:15:00
22    S26_0633_0  A3_0633_2026-09-21 09:30:00   D 2026-09-21 09:30:00
23    S26_0633_0  A3_0633_2026-09-23 09:30:00   D 2026-09-23 09:15:00
24    S26_0633_0  A3_0633_2026-09-26 09:15:00   D 2026-09-26 09:15:00
25    S26_0633_0  A3_0633_2026-09-28 09:45:00   D 2026-09-28 09:45:00
26    S26_0633_0  A3_0633_2026-09-30 09:45:00   D 2026-09-30 09:45:00
86    S26_0083_0  AA_0083_2026-09-01 11:30:00   D 2026-09-01 11:30:00
87    S26_0083_1  AA_0083_2026-09-01 11:30:00   D 2026-09-01 11:30:00
90    S26_0083_0  AA_0083_2026-09-03 10:30:00   D 2026-09-03 10:30:00
91    S26_0083_1  AA_0083_2026-09-03 10:30:00   D 2026-09-03 10:30:00
92    S26_0083_0  AA_0083_2026-09-04 11:15:00   D 2026-09-04 11:00:00
93    S26_0083_1  AA_0083_2026-09-04 11:15:00   D 2026-09-04 11:00:00
100   S26_0083_0  AA_0083_2026-09-08 11:00:00   D 2026-09-08 11:00:00
101   S26_0083_1  AA_0083_2026-09-08 11:00:00   D 2026-09-08 11:00:00

               hard_deadline_time      sla_start_time Stand Airline Code
j
13  2026-09-02 09:25:00.000000000 2026-09-02 09:25:00   15B           A3
14  2026-09-05 09:55:53.506215336 2026-09-05 09:25:00     3           A3
15  2026-09-07 09:29:03.978724572 2026-09-07 09:25:00     9           A3
18  2026-09-14 09:48:07.649805648 2026-09-14 09:25:00   15B           A3
19  2026-09-14 09:48:07.649805648 2026-09-14 09:25:00   15B           A3
20  2026-09-16 10:00:15.077495297 2026-09-16 09:25:00    1A           A3
21  2026-09-19 09:28:53.394850626 2026-09-19 09:25:00     3           A3
22  2026-09-21 09:35:35.735178186 2026-09-21 09:25:00   16B           A3
23  2026-09-23 09:26:05.934687072 2026-09-23 09:25:00     1           A3
24  2026-09-26 09:25:00.000000000 2026-09-26 09:25:00     1           A3
25  2026-09-28 09:49:59.769555084 2026-09-28 09:25:00   16B           A3
26  2026-09-30 09:50:05.023350714 2026-09-30 09:25:00   16B           A3
86  2026-09-01 11:32:18.202673244 2026-09-01 10:30:00    4A           AA
87  2026-09-01 11:32:18.202673244 2026-09-01 10:30:00    4A           AA
90  2026-09-03 10:36:18.660704262 2026-09-03 10:30:00    4A           AA
91  2026-09-03 10:36:18.660704262 2026-09-03 10:30:00    4A           AA
92  2026-09-04 11:11:48.955411974 2026-09-04 10:30:00   102           AA
93  2026-09-04 11:11:48.955411974 2026-09-04 10:30:00   102           AA
100 2026-09-08 11:02:24.638193648 2026-09-08 10:30:00    4A           AA
101 2026-09-08 11:02:24.638193648 2026-09-08 10:30:00    4A           AA

Lift tight-window check:

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-09 | Cutoff: 2026-07-02
Scenario 1:
  PeakAmb=11 | PeakMini=2
Scenario 2:
  PeakAmb=11 | PeakMini=5
SLA:
  All=0.9328 | Arr=0.9459 | Dep=0.9197
SLA diagnostics:
  allowed_breaches=328 | actual_breaches=1100 | sla_percent=93.28% | sla_floor_slack=772.00
  WARNING: hard SLA floor relaxed by slack on 772.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_09.csv
================================================


Running S26 2026-09 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11433
Airlines (sample): ['U2' 'FR' 'RK' 'LS' 'D8' 'AC' 'EI' 'OS' 'HU' 'DY']
Countries (sample): ['TUNISIA' 'POLAND' 'GREECE' 'GREAT BRITAIN' 'ITALY' 'DENMARK' 'CANADA'
 'IRISH REPUBLIC' 'SPAIN' 'AUSTRIA']

Pax describe:
count    11433.000000
mean       146.368845
std         54.771466
min          0.000000
25%        120.000000
50%        157.000000
75%        179.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       U2         TUNISIA  International   D  139.0
1       FR          POLAND  International   D  158.0
2       U2          GREECE  International   D  218.0
3       RK   GREAT BRITAIN       Domestic   D   94.0
4       LS           ITALY  International   D  172.0
5       D8         DENMARK  International   D  108.0
6       AC          CANADA  International   D  155.0
7       EI  IRISH REPUBLIC            CTA   D   33.0
8       FR           ITALY  International   D  162.0
9       RK           SPAIN  International   D  146.0
10      OS         AUSTRIA  International   D  180.0
11      HU           CHINA  International   D  241.0
12      DY          NORWAY  International   D  160.0
13      U2           SPAIN  International   D  158.0
14      RK           SPAIN  International   D  171.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,995 / 11,433 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
99       EC        ITALY  137.0
142      EC  NETHERLANDS  162.0
252      EC        ITALY  122.0
258      EC       FRANCE  182.0
295      IB        SPAIN  163.0
301      DS  SWITZERLAND   95.0
307      EC       FRANCE  153.0
311      EC        SPAIN  149.0
319      EC        SPAIN  160.0
364      EC       FRANCE  163.0
374      RK        MALTA  176.0
389      DS  SWITZERLAND  116.0
400      IB        SPAIN  143.0
414      EC        SPAIN  156.0
419      DS  SWITZERLAND  146.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17697.464756105845
Total PRMs after rounding: 17973

Raw PRM demand distribution (prm_raw):
count    11433.000000
mean         1.547928
std          1.302005
min          0.000000
25%          0.763414
50%          1.190974
75%          1.710000
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
11412      QR       QATAR  311.0   0.026728  8.312373           8
2217       QR       QATAR  311.0   0.026728  8.312373           8
972        QR       QATAR  311.0   0.026728  8.312373           8
2299       QR       QATAR  311.0   0.026728  8.312373           8
2135       QR       QATAR  311.0   0.026728  8.312373           8
1830       QR       QATAR  311.0   0.026728  8.312373           8
4474       QR       QATAR  311.0   0.026728  8.312373           8
4389       QR       QATAR  311.0   0.026728  8.312373           8
3538       QR       QATAR  311.0   0.026728  8.312373           8
3066       QR       QATAR  311.0   0.026728  8.312373           8
3455       QR       QATAR  311.0   0.026728  8.312373           8
803        QR       QATAR  311.0   0.026728  8.312373           8
3151       QR       QATAR  311.0   0.026728  8.312373           8
11017      QR       QATAR  311.0   0.026728  8.312373           8
890        QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=139.0 | Pen=0.02346 | Pax*Pen=3.261 | PRMs=3
[DEBUG flight] Airline=FR | Country=POLAND | Pax=158.0 | Pen=0.00313 | Pax*Pen=0.495 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=218.0 | Pen=0.01184 | Pax*Pen=2.581 | PRMs=3
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=94.0 | Pen=0.00637 | Pax*Pen=0.599 | PRMs=1
[DEBUG flight] Airline=LS | Country=ITALY | Pax=172.0 | Pen=0.01426 | Pax*Pen=2.453 | PRMs=2
[DEBUG flight] Airline=D8 | Country=DENMARK | Pax=108.0 | Pen=0.00531 | Pax*Pen=0.574 | PRMs=1
[DEBUG flight] Airline=AC | Country=CANADA | Pax=155.0 | Pen=0.01580 | Pax*Pen=2.450 | PRMs=2
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=33.0 | Pen=0.01035 | Pax*Pen=0.341 | PRMs=0
[DEBUG flight] Airline=FR | Country=ITALY | Pax=162.0 | Pen=0.00547 | Pax*Pen=0.886 | PRMs=1
[DEBUG flight] Airline=RK | Country=SPAIN | Pax=146.0 | Pen=0.00822 | Pax*Pen=1.200 | PRMs=1
[DEBUG flight] Airline=OS | Country=AUSTRIA | Pax=180.0 | Pen=0.00476 | Pax*Pen=0.857 | PRMs=1
[DEBUG flight] Airline=HU | Country=CHINA | Pax=241.0 | Pen=0.00399 | Pax*Pen=0.961 | PRMs=1
[DEBUG flight] Airline=DY | Country=NORWAY | Pax=160.0 | Pen=0.00440 | Pax*Pen=0.704 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=158.0 | Pen=0.01381 | Pax*Pen=2.182 | PRMs=2
[DEBUG flight] Airline=RK | Country=SPAIN | Pax=171.0 | Pen=0.00822 | Pax*Pen=1.406 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 17973
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9468
WCHS     7419
WCHC      983
OTHER     103
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-09-01 → 2026-10-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11433
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    11433.000000
mean       146.368845
std         54.771466
min          0.000000
25%        120.000000
50%        157.000000
75%        179.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D  100.0
1       U2          ITALY  International   D  159.0
2       FR         FRANCE  International   D  114.0
3       FR          ITALY  International   D  172.0
4       KL    NETHERLANDS  International   D  107.0
5       BA  GREAT BRITAIN       Domestic   D  116.0
6       U2  GREAT BRITAIN       Domestic   D  165.0
7       U2  GREAT BRITAIN       Domestic   D  128.0
8       U2  GREAT BRITAIN       Domestic   D  162.0
9       FR          SPAIN  International   D  197.0
10      RK        ROMANIA  International   D  143.0
11      U2  GREAT BRITAIN       Domestic   D  146.0
12      U2        CROATIA  International   D  154.0
13      FR          SPAIN  International   D  188.0
14      LH        GERMANY  International   D  108.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,995 / 11,433 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  143.0
53       EC  NETHERLANDS  160.0
106      EC        ITALY  121.0
158      EC        SPAIN   81.0
203      U2     SLOVENIA  138.0
291      DS  SWITZERLAND  146.0
299      EC        ITALY  137.0
303      EC        SPAIN  156.0
354      IB        SPAIN  143.0
358      EC  NETHERLANDS  162.0
422      DS  SWITZERLAND  116.0
483      EC        ITALY  122.0
492      EC       FRANCE  182.0
518      RK        MALTA  176.0
540      IB        SPAIN  163.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17697.464756105845
Total PRMs after rounding: 17973

Raw PRM demand distribution (prm_raw):
count    11433.000000
mean         1.547928
std          1.302005
min          0.000000
25%          0.763414
50%          1.190974
75%          1.710000
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
11412      QR       QATAR  311.0   0.026728  8.312373           8
4389       QR       QATAR  311.0   0.026728  8.312373           8
5935       QR       QATAR  311.0   0.026728  8.312373           8
11017      QR       QATAR  311.0   0.026728  8.312373           8
4782       QR       QATAR  311.0   0.026728  8.312373           8
4943       QR       QATAR  311.0   0.026728  8.312373           8
3066       QR       QATAR  311.0   0.026728  8.312373           8
4584       QR       QATAR  311.0   0.026728  8.312373           8
972        QR       QATAR  311.0   0.026728  8.312373           8
2388       QR       QATAR  311.0   0.026728  8.312373           8
2299       QR       QATAR  311.0   0.026728  8.312373           8
413        QR       QATAR  311.0   0.026728  8.312373           8
5722       QR       QATAR  311.0   0.026728  8.312373           8
4677       QR       QATAR  311.0   0.026728  8.312373           8
6010       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=100.0 | Pen=0.00755 | Pax*Pen=0.755 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=159.0 | Pen=0.00872 | Pax*Pen=1.386 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=114.0 | Pen=0.00686 | Pax*Pen=0.782 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=172.0 | Pen=0.00547 | Pax*Pen=0.940 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=107.0 | Pen=0.00831 | Pax*Pen=0.889 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=116.0 | Pen=0.00962 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=165.0 | Pen=0.00918 | Pax*Pen=1.514 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=128.0 | Pen=0.00918 | Pax*Pen=1.175 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=143.0 | Pen=0.01000 | Pax*Pen=1.430 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=146.0 | Pen=0.00918 | Pax*Pen=1.340 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=154.0 | Pen=0.00421 | Pax*Pen=0.649 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=188.0 | Pen=0.00966 | Pax*Pen=1.815 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 17973
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9492
WCHS     7403
WCHC      982
OTHER      96
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=17,973   [352.37s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=17,971   [0.37s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.51s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-08-31 23:45:00 end=2026-10-01 05:45:00 buckets=2905
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-09-18 13:45:00 | 75.0 / 210.0
  2026-09-18 14:00:00 | 60.0 / 210.0
  2026-09-02 12:00:00 | 60.0 / 210.0
  2026-09-02 12:15:00 | 60.0 / 210.0
  2026-09-15 10:00:00 | 60.0 / 210.0
  2026-09-12 15:30:00 | 60.0 / 210.0
  2026-09-19 17:30:00 | 60.0 / 210.0
  2026-09-19 17:45:00 | 60.0 / 210.0
  2026-09-19 18:00:00 | 60.0 / 210.0
  2026-09-19 17:15:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 323
  is_spin by dir:
dir
A    323
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.024663833333333333 34.253943299999996 59.95789643333333
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 82154.0
  total available over horizon: 593850.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 14
  min mini minutes required (forced): 242.2
  total mini minutes available: 217875.0

Lift rough check:
  lift jobs: 56
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3141
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_1887_0  AF_1887_2026-09-01 05:30:00   D 2026-09-01 05:30:00
5    S26_1465_0  BA_1465_2026-09-01 06:15:00   D 2026-09-01 06:00:00
8    S26_0331_0  U2_0331_2026-09-01 06:15:00   D 2026-09-01 06:15:00
14   S26_3319_0  U2_3319_2026-09-01 06:00:00   D 2026-09-01 06:00:00
25   S26_0597_0  RK_0597_2026-09-01 06:15:00   D 2026-09-01 06:15:00
26   S26_0717_0  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
27   S26_0717_1  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
28   S26_0717_2  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
29   S26_0717_3  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
30   S26_0717_4  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
36   S26_8711_0  BA_8711_2026-09-01 07:30:00   D 2026-09-01 07:30:00
53   S26_0789_0  LS_0789_2026-09-01 08:00:00   D 2026-09-01 07:45:00
54   S26_0789_1  LS_0789_2026-09-01 08:00:00   D 2026-09-01 07:45:00
55   S26_0789_2  LS_0789_2026-09-01 08:00:00   D 2026-09-01 07:45:00
56   S26_0789_3  LS_0789_2026-09-01 08:00:00   D 2026-09-01 07:45:00
64   S26_6698_0  FR_6698_2026-09-01 09:00:00   D 2026-09-01 09:00:00
65   S26_6698_1  FR_6698_2026-09-01 09:00:00   D 2026-09-01 09:00:00
67   S26_3251_0  EI_3251_2026-09-01 09:00:00   D 2026-09-01 08:45:00
74   S26_0035_0  DL_0035_2026-09-01 09:45:00   D 2026-09-01 09:45:00
75   S26_0035_1  DL_0035_2026-09-01 09:45:00   D 2026-09-01 09:45:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-09-01 05:40:00.000000000 2026-09-01 05:40:00    31           AF
5  2026-09-01 06:13:35.844926052 2026-09-01 05:50:00     9           BA
8  2026-09-01 06:24:21.931764930 2026-09-01 06:00:00    28           U2
14 2026-09-01 06:10:00.000000000 2026-09-01 06:10:00    24           U2
25 2026-09-01 06:23:40.664311854 2026-09-01 06:20:00    24           RK
26 2026-09-01 06:39:03.108887622 2026-09-01 06:30:00     2           LS
27 2026-09-01 06:39:03.108887622 2026-09-01 06:30:00     2           LS
28 2026-09-01 06:39:03.108887622 2026-09-01 06:30:00     2           LS
29 2026-09-01 06:39:03.108887622 2026-09-01 06:30:00     2           LS
30 2026-09-01 06:39:03.108887622 2026-09-01 06:30:00     2           LS
36 2026-09-01 07:31:16.800664182 2026-09-01 07:00:00   105           BA
53 2026-09-01 07:55:29.591774442 2026-09-01 07:50:00    14           LS
54 2026-09-01 07:55:29.591774442 2026-09-01 07:50:00    14           LS
55 2026-09-01 07:55:29.591774442 2026-09-01 07:50:00    14           LS
56 2026-09-01 07:55:29.591774442 2026-09-01 07:50:00    14           LS
64 2026-09-01 09:02:29.220675078 2026-09-01 08:20:00    1B           FR
65 2026-09-01 09:02:29.220675078 2026-09-01 08:20:00    1B           FR
67 2026-09-01 08:56:05.637504396 2026-09-01 08:35:00    22           EI
74 2026-09-01 09:49:57.088102368 2026-09-01 09:00:00     2           DL
75 2026-09-01 09:49:57.088102368 2026-09-01 09:00:00     2           DL

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 10
  tight vertical jobs: 869
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 655
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.


C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-09 | Cutoff: 2026-07-02
Scenario 1:
  PeakAmb=12 | PeakMini=2
Scenario 2:
  PeakAmb=13 | PeakMini=5
SLA:
  All=0.9299 | Arr=0.9451 | Dep=0.9148
SLA diagnostics:
  allowed_breaches=360 | actual_breaches=1260 | sla_percent=92.99% | sla_floor_slack=900.00
  WARNING: hard SLA floor relaxed by slack on 900.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_09.csv
================================================


[MONTH COMPARE] Running both p90_stratified and p100 for risk check

Running S26 2026-10 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11488
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'SPAIN' 'GREECE' 'GERMANY' 'POLAND']

Pax describe:
count    11488.000000
mean       149.139711
std         54.680100
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  155.0
1       AF         FRANCE  International   D   99.0
2       FR         LATVIA  International   D  184.0
3       KL    NETHERLANDS  International   D  122.0
4       BA  GREAT BRITAIN       Domestic   D  116.0
5       U2       PORTUGAL  International   D  158.0
6       U2          ITALY  International   D  138.0
7       FR          SPAIN  International   D  156.0
8       LS         GREECE  International   D  186.0
9       U2  GREAT BRITAIN       Domestic   D  104.0
10      U2  GREAT BRITAIN       Domestic   D   62.0
11      U2         FRANCE  International   D  191.0
12      LH        GERMANY  International   D  143.0
13      FR          ITALY  International   D  180.0
14      LM  GREAT BRITAIN       Domestic   D    0.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,760 / 11,488 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
73       EC       FRANCE  174.0
82       EC       FRANCE  174.0
117      EC       FRANCE  147.0
164      EC       FRANCE  229.0
169      EC        ITALY  138.0
175      LG   LUXEMBOURG  124.0
212      DS  SWITZERLAND  131.0
214      EC  NETHERLANDS  185.0
246      RK        MALTA  189.0
312      U2     SLOVENIA  162.0
324      EC        ITALY  152.0
352      EC        SPAIN  149.0
395      DS  SWITZERLAND  107.0
415      IB        SPAIN  171.0
473      EC        ITALY  161.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17753.051020857973
Total PRMs after rounding: 18026

Raw PRM demand distribution (prm_raw):
count    11488.000000
mean         1.545356
std          1.276697
min          0.000000
25%          0.765501
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
8952      QR       QATAR  311.0   0.026728  8.312373           8
394       QR       QATAR  311.0   0.026728  8.312373           8
2978      QR       QATAR  311.0   0.026728  8.312373           8
4485      QR       QATAR  311.0   0.026728  8.312373           8
4019      QR       QATAR  311.0   0.026728  8.312373           8
5429      QR       QATAR  311.0   0.026728  8.312373           8
4106      QR       QATAR  311.0   0.026728  8.312373           8
2006      QR       QATAR  311.0   0.026728  8.312373           8
3083      QR       QATAR  311.0   0.026728  8.312373           8
883       QR       QATAR  311.0   0.026728  8.312373           8
5253      QR       QATAR  311.0   0.026728  8.312373           8
4304      QR       QATAR  311.0   0.026728  8.312373           8
5325      QR       QATAR  311.0   0.026728  8.312373           8
1453      QR       QATAR  311.0   0.026728  8.312373           8
1368      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=155.0 | Pen=0.00872 | Pax*Pen=1.351 | PRMs=1
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=99.0 | Pen=0.00755 | Pax*Pen=0.747 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=184.0 | Pen=0.00414 | Pax*Pen=0.761 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=122.0 | Pen=0.00831 | Pax*Pen=1.013 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=116.0 | Pen=0.00962 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=158.0 | Pen=0.00785 | Pax*Pen=1.240 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=138.0 | Pen=0.00872 | Pax*Pen=1.203 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=156.0 | Pen=0.00966 | Pax*Pen=1.506 | PRMs=2
[DEBUG flight] Airline=LS | Country=GREECE | Pax=186.0 | Pen=0.01748 | Pax*Pen=3.251 | PRMs=3
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=104.0 | Pen=0.00918 | Pax*Pen=0.954 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=62.0 | Pen=0.00918 | Pax*Pen=0.569 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=191.0 | Pen=0.00839 | Pax*Pen=1.602 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=143.0 | Pen=0.00569 | Pax*Pen=0.814 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=180.0 | Pen=0.00547 | Pax*Pen=0.984 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=0.0 | Pen=0.01980 | Pax*Pen=0.000 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 18026
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9503
WCHS     7352
WCHC     1027
OTHER     144
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1537 PRM jobs via stratified percentile cap

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-10-01 → 2026-11-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11488
Airlines (sample): ['FR' 'U2' 'LS' 'AF' 'KL' 'BA' 'LH' 'QR' 'LM' 'HU']
Countries (sample): ['ITALY' 'SPAIN' 'TURKEY' 'PORTUGAL' 'POLAND' 'MOROCCO' 'GREECE' 'CYPRUS'
 'FRANCE' 'NETHERLANDS']

Pax describe:
count    11488.000000
mean       149.139711
std         54.680100
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline CountryName         Sector dir    Pax
0       FR       ITALY  International   A  185.0
1       FR       SPAIN  International   A  184.0
2       U2      TURKEY  International   A  157.0
3       LS       ITALY  International   A  135.0
4       LS      TURKEY  International   A  204.0
5       FR    PORTUGAL  International   A  142.0
6       FR      POLAND  International   A  137.0
7       FR       SPAIN  International   A  166.0
8       FR       ITALY  International   A  174.0
9       U2       SPAIN  International   A  154.0
10      U2     MOROCCO  International   A  159.0
11      U2      GREECE  International   A  168.0
12      LS       SPAIN  International   A  147.0
13      LS       SPAIN  International   A  129.0
14      LS      CYPRUS  International   A  168.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,760 / 11,488 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
65       EC        ITALY  160.0
73       DS  SWITZERLAND  103.0
78       EC        ITALY  156.0
89       DS  SWITZERLAND   95.0
206      EC        ITALY  121.0
212      EC        ITALY  102.0
217      EC       FRANCE  160.0
234      EC       FRANCE  174.0
283      RK        MALTA  172.0
311      IB        SPAIN  161.0
322      DS  SWITZERLAND  142.0
328      IB        SPAIN  151.0
336      EC       FRANCE  160.0
338      DS  SWITZERLAND   74.0
344      EC        SPAIN  134.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17753.051020857973
Total PRMs after rounding: 18026

Raw PRM demand distribution (prm_raw):
count    11488.000000
mean         1.545356
std          1.276697
min          0.000000
25%          0.765501
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
3504       QR       QATAR  311.0   0.026728  8.312373           8
6155       QR       QATAR  311.0   0.026728  8.312373           8
9114       QR       QATAR  311.0   0.026728  8.312373           8
11343      QR       QATAR  311.0   0.026728  8.312373           8
68         QR       QATAR  311.0   0.026728  8.312373           8
645        QR       QATAR  311.0   0.026728  8.312373           8
8959       QR       QATAR  311.0   0.026728  8.312373           8
1752       QR       QATAR  311.0   0.026728  8.312373           8
6312       QR       QATAR  311.0   0.026728  8.312373           8
9257       QR       QATAR  311.0   0.026728  8.312373           8
4793       QR       QATAR  311.0   0.026728  8.312373           8
8804       QR       QATAR  311.0   0.026728  8.312373           8
3295       QR       QATAR  311.0   0.026728  8.312373           8
5947       QR       QATAR  311.0   0.026728  8.312373           8
10634      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=FR | Country=ITALY | Pax=185.0 | Pen=0.00547 | Pax*Pen=1.012 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=184.0 | Pen=0.00966 | Pax*Pen=1.777 | PRMs=2
[DEBUG flight] Airline=U2 | Country=TURKEY | Pax=157.0 | Pen=0.01858 | Pax*Pen=2.917 | PRMs=3
[DEBUG flight] Airline=LS | Country=ITALY | Pax=135.0 | Pen=0.01426 | Pax*Pen=1.925 | PRMs=2
[DEBUG flight] Airline=LS | Country=TURKEY | Pax=204.0 | Pen=0.02622 | Pax*Pen=5.350 | PRMs=5
[DEBUG flight] Airline=FR | Country=PORTUGAL | Pax=142.0 | Pen=0.00756 | Pax*Pen=1.074 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=137.0 | Pen=0.00313 | Pax*Pen=0.429 | PRMs=0
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=166.0 | Pen=0.00966 | Pax*Pen=1.603 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=174.0 | Pen=0.00547 | Pax*Pen=0.951 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=154.0 | Pen=0.01381 | Pax*Pen=2.127 | PRMs=2
[DEBUG flight] Airline=U2 | Country=MOROCCO | Pax=159.0 | Pen=0.01193 | Pax*Pen=1.897 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=168.0 | Pen=0.01184 | Pax*Pen=1.989 | PRMs=2
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=147.0 | Pen=0.02578 | Pax*Pen=3.790 | PRMs=4
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=129.0 | Pen=0.02578 | Pax*Pen=3.326 | PRMs=3
[DEBUG flight] Airline=LS | Country=CYPRUS | Pax=168.0 | Pen=0.02263 | Pax*Pen=3.802 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 18026
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9500
WCHS     7428
WCHC      968
OTHER     130
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,026   [325.35s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 1 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1523 PRM jobs via stratified percentile cap
    ✓ build_jobs done | jobs=16,502   [0.51s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.46s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 89}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
EA            D      68
              A      21
dtype: int64

Bucket horizon: start=2026-10-01 00:30:00 end=2026-11-01 05:45:00 buckets=2998
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-10-26 15:15:00 | 75.0 / 210.0
  2026-10-26 15:00:00 | 60.0 / 210.0
  2026-10-08 12:30:00 | 60.0 / 210.0
  2026-10-11 09:45:00 | 60.0 / 210.0
  2026-10-16 19:00:00 | 60.0 / 210.0
  2026-10-18 17:45:00 | 60.0 / 210.0
  2026-10-18 18:00:00 | 60.0 / 210.0
  2026-10-09 19:15:00 | 60.0 / 210.0
  2026-10-12 20:15:00 | 60.0 / 210.0
  2026-10-12 19:45:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 328
  is_spin by dir:
dir
A    328
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.2777425333333333 30.38032196666667 59.78170106666666
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 79597.9
  total available over horizon: 612660.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 20
  min mini minutes required (forced): 347.9
  total mini minutes available: 224850.0

Lift rough check:
  lift jobs: 60
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2820
Examples (first 20):
    Passenger ID                   flight_key dir                   t  \
j
14    S26_0633_0  A3_0633_2026-10-03 09:15:00   D 2026-10-03 09:15:00
15    S26_0633_0  A3_0633_2026-10-05 10:00:00   D 2026-10-05 09:45:00
17    S26_0633_0  A3_0633_2026-10-10 09:15:00   D 2026-10-10 09:15:00
19    S26_0633_0  A3_0633_2026-10-14 09:30:00   D 2026-10-14 09:30:00
21    S26_0633_0  A3_0633_2026-10-19 09:15:00   D 2026-10-19 09:15:00
25    S26_0633_0  A3_0633_2026-10-27 12:15:00   D 2026-10-27 12:00:00
81    S26_0083_0  AA_0083_2026-10-05 11:15:00   D 2026-10-05 11:15:00
82    S26_0083_1  AA_0083_2026-10-05 11:15:00   D 2026-10-05 11:15:00
84    S26_0083_0  AA_0083_2026-10-07 10:45:00   D 2026-10-07 10:45:00
85    S26_0083_1  AA_0083_2026-10-07 10:45:00   D 2026-10-07 10:45:00
86    S26_0083_0  AA_0083_2026-10-08 12:00:00   D 2026-10-08 12:00:00
97    S26_0083_1  AA_0083_2026-10-14 11:15:00   D 2026-10-14 11:15:00
98    S26_0083_0  AA_0083_2026-10-14 11:15:00   D 2026-10-14 11:15:00
101   S26_0083_0  AA_0083_2026-10-16 11:15:00   D 2026-10-16 11:15:00
102   S26_0083_1  AA_0083_2026-10-16 11:15:00   D 2026-10-16 11:15:00
105   S26_0083_0  AA_0083_2026-10-18 11:45:00   D 2026-10-18 11:30:00
106   S26_0083_1  AA_0083_2026-10-18 11:45:00   D 2026-10-18 11:30:00
112   S26_0083_0  AA_0083_2026-10-22 10:45:00   D 2026-10-22 10:45:00
192   S26_0279_0  AA_0279_2026-10-01 13:15:00   D 2026-10-01 13:00:00
193   S26_0279_1  AA_0279_2026-10-01 13:15:00   D 2026-10-01 13:00:00

               hard_deadline_time      sla_start_time Stand Airline Code
j
14  2026-10-03 09:25:00.000000000 2026-10-03 09:25:00    25           A3
15  2026-10-05 09:55:53.039527830 2026-10-05 09:25:00     9           A3
17  2026-10-10 09:25:00.000000000 2026-10-10 09:25:00    17           A3
19  2026-10-14 09:38:54.921999342 2026-10-14 09:25:00   15A           A3
21  2026-10-19 09:25:00.000000000 2026-10-19 09:25:00    25           A3
25  2026-10-27 12:14:19.082658648 2026-10-27 11:55:00     3           A3
81  2026-10-05 11:19:53.269321812 2026-10-05 10:30:00    4A           AA
82  2026-10-05 11:19:53.269321812 2026-10-05 10:30:00    4A           AA
84  2026-10-07 10:51:17.308439538 2026-10-07 10:30:00    4A           AA
85  2026-10-07 10:51:17.308439538 2026-10-07 10:30:00    4A           AA
86  2026-10-08 12:02:55.532730120 2026-10-08 10:30:00    4A           AA
97  2026-10-14 11:23:42.954082782 2026-10-14 10:30:00    4A           AA
98  2026-10-14 11:23:42.954082782 2026-10-14 10:30:00    4A           AA
101 2026-10-16 11:22:12.003338406 2026-10-16 10:30:00    4A           AA
102 2026-10-16 11:22:12.003338406 2026-10-16 10:30:00    4A           AA
105 2026-10-18 11:42:05.791852584 2026-10-18 10:30:00    23           AA
106 2026-10-18 11:42:05.791852584 2026-10-18 10:30:00    23           AA

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-10 | Cutoff: 2026-07-02
Scenario 1:
  PeakAmb=10 | PeakMini=2
Scenario 2:
  PeakAmb=12 | PeakMini=5
SLA:
  All=0.9327 | Arr=0.9408 | Dep=0.9247
SLA diagnostics:
  allowed_breaches=331 | actual_breaches=1110 | sla_percent=93.27% | sla_floor_slack=779.00
  WARNING: hard SLA floor relaxed by slack on 779.00 jobs
Hourly table saved (S2): S26_S2_peak_day_hourly_need_2026_10.csv
================================================


Running S26 2026-10 | cutoff=2026-07-02
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11488
Airlines (sample): ['BA' 'LH' 'U2' 'FR' 'KL' 'AC' 'DY' 'EI' 'PC' 'EC']
Countries (sample): ['GREAT BRITAIN' 'GERMANY' 'POLAND' 'NETHERLANDS' 'CANADA' 'NORWAY'
 'IRISH REPUBLIC' 'TURKEY' 'FRANCE' 'DENMARK']

Pax describe:
count    11488.000000
mean       149.139711
std         54.680100
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       BA   GREAT BRITAIN       Domestic   D  171.0
1       LH         GERMANY  International   D  148.0
2       U2   GREAT BRITAIN       Domestic   D  175.0
3       FR          POLAND  International   D  185.0
4       KL     NETHERLANDS  International   D  186.0
5       BA   GREAT BRITAIN       Domestic   D  101.0
6       AC          CANADA  International   D  270.0
7       DY          NORWAY  International   D  178.0
8       EI  IRISH REPUBLIC            CTA   D   67.0
9       PC          TURKEY  International   D  239.0
10      EC          FRANCE  International   D  229.0
11      BA   GREAT BRITAIN       Domestic   D  170.0
12      D8         DENMARK  International   D  133.0
13      BA   GREAT BRITAIN       Domestic   D   75.0
14      FR         GERMANY  International   D  185.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,760 / 11,488 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
10       EC       FRANCE  229.0
19       EC        ITALY  138.0
82       DS  SWITZERLAND  131.0
84       EC  NETHERLANDS  185.0
124      RK        MALTA  189.0
130      EC        ITALY  120.0
181      EC        ITALY  138.0
200      U2     SLOVENIA  162.0
213      EC        ITALY  152.0
236      EC       FRANCE  147.0
253      EC        SPAIN  149.0
303      DS  SWITZERLAND  107.0
325      IB        SPAIN  171.0
388      EC        ITALY  161.0
430      EC        SPAIN  143.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17753.051020857973
Total PRMs after rounding: 18026

Raw PRM demand distribution (prm_raw):
count    11488.000000
mean         1.545356
std          1.276697
min          0.000000
25%          0.765501
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
37        QR       QATAR  311.0   0.026728  8.312373           8
625       QR       QATAR  311.0   0.026728  8.312373           8
2779      QR       QATAR  311.0   0.026728  8.312373           8
2692      QR       QATAR  311.0   0.026728  8.312373           8
8952      QR       QATAR  311.0   0.026728  8.312373           8
883       QR       QATAR  311.0   0.026728  8.312373           8
2591      QR       QATAR  311.0   0.026728  8.312373           8
6206      QR       QATAR  311.0   0.026728  8.312373           8
7326      QR       QATAR  311.0   0.026728  8.312373           8
2887      QR       QATAR  311.0   0.026728  8.312373           8
5678      QR       QATAR  311.0   0.026728  8.312373           8
5610      QR       QATAR  311.0   0.026728  8.312373           8
392       QR       QATAR  311.0   0.026728  8.312373           8
1076      QR       QATAR  311.0   0.026728  8.312373           8
4798      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=171.0 | Pen=0.00962 | Pax*Pen=1.645 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=148.0 | Pen=0.00569 | Pax*Pen=0.842 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=175.0 | Pen=0.00918 | Pax*Pen=1.606 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=185.0 | Pen=0.00313 | Pax*Pen=0.579 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=186.0 | Pen=0.00831 | Pax*Pen=1.545 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=101.0 | Pen=0.00962 | Pax*Pen=0.971 | PRMs=1
[DEBUG flight] Airline=AC | Country=CANADA | Pax=270.0 | Pen=0.01580 | Pax*Pen=4.267 | PRMs=4
[DEBUG flight] Airline=DY | Country=NORWAY | Pax=178.0 | Pen=0.00440 | Pax*Pen=0.783 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=67.0 | Pen=0.01035 | Pax*Pen=0.693 | PRMs=1
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=239.0 | Pen=0.00852 | Pax*Pen=2.036 | PRMs=2
[DEBUG flight] Airline=EC | Country=FRANCE | Pax=229.0 | Pen=0.01000 | Pax*Pen=2.290 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=170.0 | Pen=0.00962 | Pax*Pen=1.635 | PRMs=2
[DEBUG flight] Airline=D8 | Country=DENMARK | Pax=133.0 | Pen=0.00531 | Pax*Pen=0.707 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=75.0 | Pen=0.00962 | Pax*Pen=0.721 | PRMs=1
[DEBUG flight] Airline=FR | Country=GERMANY | Pax=185.0 | Pen=0.00282 | Pax*Pen=0.521 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18026
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9521
WCHS     7322
WCHC     1044
OTHER     139
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-10-01 → 2026-11-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11488
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'SPAIN' 'GREECE' 'GERMANY' 'POLAND']

Pax describe:
count    11488.000000
mean       149.139711
std         54.680100
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  155.0
1       AF         FRANCE  International   D   99.0
2       FR         LATVIA  International   D  184.0
3       KL    NETHERLANDS  International   D  122.0
4       BA  GREAT BRITAIN       Domestic   D  116.0
5       U2       PORTUGAL  International   D  158.0
6       U2          ITALY  International   D  138.0
7       FR          SPAIN  International   D  156.0
8       LS         GREECE  International   D  186.0
9       U2  GREAT BRITAIN       Domestic   D  104.0
10      U2  GREAT BRITAIN       Domestic   D   62.0
11      U2         FRANCE  International   D  191.0
12      LH        GERMANY  International   D  143.0
13      FR          ITALY  International   D  180.0
14      LM  GREAT BRITAIN       Domestic   D    0.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,760 / 11,488 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
44       EC        ITALY  156.0
49       DS  SWITZERLAND   95.0
112      EC        ITALY  102.0
121      EC       FRANCE  174.0
148      RK        MALTA  172.0
169      IB        SPAIN  151.0
177      DS  SWITZERLAND   74.0
182      EC       FRANCE  174.0
186      EC        SPAIN  156.0
194      EC        SPAIN  139.0
241      EC       FRANCE  147.0
254      EC        ITALY  138.0
263      EC        ITALY  120.0
301      EC       FRANCE  229.0
310      EC        ITALY  138.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17753.051020857973
Total PRMs after rounding: 18026

Raw PRM demand distribution (prm_raw):
count    11488.000000
mean         1.545356
std          1.276697
min          0.000000
25%          0.765501
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
1653      QR       QATAR  311.0   0.026728  8.312373           8
5325      QR       QATAR  311.0   0.026728  8.312373           8
1453      QR       QATAR  311.0   0.026728  8.312373           8
883       QR       QATAR  311.0   0.026728  8.312373           8
5429      QR       QATAR  311.0   0.026728  8.312373           8
126       QR       QATAR  311.0   0.026728  8.312373           8
2006      QR       QATAR  311.0   0.026728  8.312373           8
5678      QR       QATAR  311.0   0.026728  8.312373           8
4565      QR       QATAR  311.0   0.026728  8.312373           8
1919      QR       QATAR  311.0   0.026728  8.312373           8
1757      QR       QATAR  311.0   0.026728  8.312373           8
1368      QR       QATAR  311.0   0.026728  8.312373           8
7431      QR       QATAR  311.0   0.026728  8.312373           8
4793      QR       QATAR  311.0   0.026728  8.312373           8
2208      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=155.0 | Pen=0.00872 | Pax*Pen=1.351 | PRMs=1
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=99.0 | Pen=0.00755 | Pax*Pen=0.747 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=184.0 | Pen=0.00414 | Pax*Pen=0.761 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=122.0 | Pen=0.00831 | Pax*Pen=1.013 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=116.0 | Pen=0.00962 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=158.0 | Pen=0.00785 | Pax*Pen=1.240 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=138.0 | Pen=0.00872 | Pax*Pen=1.203 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=156.0 | Pen=0.00966 | Pax*Pen=1.506 | PRMs=2
[DEBUG flight] Airline=LS | Country=GREECE | Pax=186.0 | Pen=0.01748 | Pax*Pen=3.251 | PRMs=3
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=104.0 | Pen=0.00918 | Pax*Pen=0.954 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=62.0 | Pen=0.00918 | Pax*Pen=0.569 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=191.0 | Pen=0.00839 | Pax*Pen=1.602 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=143.0 | Pen=0.00569 | Pax*Pen=0.814 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=180.0 | Pen=0.00547 | Pax*Pen=0.984 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=0.0 | Pen=0.01980 | Pax*Pen=0.000 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 18026
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9522
WCHS     7314
WCHC     1040
OTHER     150
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,026   [415.47s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=18,026   [0.38s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.51s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 89}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
EA            D      68
              A      21
dtype: int64

Bucket horizon: start=2026-09-30 23:30:00 end=2026-11-01 05:45:00 buckets=3002
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-10-26 10:15:00 | 90.0 / 210.0
  2026-10-26 10:30:00 | 90.0 / 210.0
  2026-10-11 17:15:00 | 75.0 / 210.0
  2026-10-11 17:30:00 | 75.0 / 210.0
  2026-10-26 10:45:00 | 75.0 / 210.0
  2026-10-26 11:00:00 | 75.0 / 210.0
  2026-10-11 17:45:00 | 75.0 / 210.0
  2026-10-25 18:45:00 | 60.0 / 210.0
  2026-10-25 19:00:00 | 60.0 / 210.0
  2026-10-25 19:15:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 381
  is_spin by dir:
dir
A    381
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.028185850000000002 31.893238483333334 59.7242609
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 83690.4
  total available over horizon: 611820.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 22
  min mini minutes required (forced): 380.4
  total mini minutes available: 225150.0

Lift rough check:
  lift jobs: 64
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3174
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_3273_0  U2_3273_2026-10-01 05:45:00   D 2026-10-01 05:30:00
1    S26_1887_0  AF_1887_2026-10-01 06:00:00   D 2026-10-01 06:00:00
4    S26_1467_0  BA_1467_2026-10-01 05:45:00   D 2026-10-01 05:45:00
16   S26_0965_0  LH_0965_2026-10-01 06:15:00   D 2026-10-01 06:00:00
17   S26_5589_0  FR_5589_2026-10-01 06:30:00   D 2026-10-01 06:15:00
25   S26_8750_0  FR_8750_2026-10-01 06:45:00   D 2026-10-01 06:30:00
26   S26_5579_0  FR_5579_2026-10-01 06:30:00   D 2026-10-01 06:30:00
27   S26_5579_1  FR_5579_2026-10-01 06:30:00   D 2026-10-01 06:30:00
31   S26_4524_0  FR_4524_2026-10-01 07:15:00   D 2026-10-01 07:15:00
55   S26_0783_0  LS_0783_2026-10-01 07:30:00   D 2026-10-01 07:30:00
56   S26_2969_0  RK_2969_2026-10-01 07:30:00   D 2026-10-01 07:30:00
59   S26_0032_0  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
60   S26_0032_1  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
61   S26_0032_2  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
62   S26_0032_3  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
63   S26_0032_4  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
64   S26_0032_5  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
65   S26_0032_6  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
66   S26_0032_7  QR_0032_2026-10-01 08:00:00   D 2026-10-01 08:00:00
67   S26_3264_0  FR_3264_2026-10-01 08:45:00   D 2026-10-01 08:30:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-10-01 05:43:54.378357306 2026-10-01 05:35:00    25           U2
1  2026-10-01 06:00:32.317101402 2026-10-01 05:40:00    19           AF
4  2026-10-01 05:52:31.836483498 2026-10-01 05:50:00    22           BA
16 2026-10-01 06:13:36.832744272 2026-10-01 06:10:00     2           LH
17 2026-10-01 06:27:00.726346062 2026-10-01 06:15:00    24           FR
25 2026-10-01 06:42:58.890538338 2026-10-01 06:35:00    10           FR
26 2026-10-01 06:40:00.000000000 2026-10-01 06:40:00    24           FR
27 2026-10-01 06:40:00.000000000 2026-10-01 06:40:00    24           FR
31 2026-10-01 07:20:31.147781262 2026-10-01 06:50:00    20           FR
55 2026-10-01 07:34:33.171005352 2026-10-01 07:30:00   100           LS
56 2026-10-01 07:35:00.000000000 2026-10-01 07:35:00   15B           RK
59 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
60 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
61 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
62 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
63 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
64 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
65 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
66 2026-10-01 08:04:33.213282239 2026-10-01 07:55:00    18           QR
67 2026-10-01 08:44:42.115365246 2026-10-01 08:15:00    24           FR

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

,month,cutoff_used,demand_mode,demand_mode_p90,S1_PeakAmb_p90,S1_PeakMini_p90,S2_PeakAmb_p90,S2_PeakMini_p90,SLA_all_p90,SLA_arr_p90,...,sla_floor_slack_p100,S2_status_p100,S2_tc_p100,S2_st_p100,S1_peak_day_p100,S1_peak_day_job_count_p100,S1_hourly_table_path_p100,S2_peak_day_p100,S2_peak_day_job_count_p100,S2_hourly_table_path_p100
0,2026-07,2026-07-01,compare_p90_vs_p100,p90_stratified,14,2,13,5,0.928952,0.936846,...,824.0,maxtimelimit,maxtimelimit,aborted,2026-07-12,685,S26_S1_peak_day_hourly_need_2026_07.csv,2026-07-12,676,S26_S2_peak_day_hourly_need_2026_07.csv
1,2026-08,2026-07-02,compare_p90_vs_p100,p90_stratified,11,2,12,5,0.930396,0.941914,...,869.0,maxtimelimit,maxtimelimit,aborted,2026-08-09,665,S26_S1_peak_day_hourly_need_2026_08.csv,2026-08-09,666,S26_S2_peak_day_hourly_need_2026_08.csv
2,2026-09,2026-07-02,compare_p90_vs_p100,p90_stratified,11,2,11,5,0.932759,0.945853,...,900.0,maxtimelimit,maxtimelimit,aborted,2026-09-27,662,S26_S1_peak_day_hourly_need_2026_09.csv,2026-09-27,663,S26_S2_peak_day_hourly_need_2026_09.csv
3,2026-10,2026-07-02,compare_p90_vs_p100,p90_stratified,10,2,12,5,0.932735,0.940763,...,840.0,maxtimelimit,maxtimelimit,aborted,2026-10-18,683,S26_S1_peak_day_hourly_need_2026_10.csv,2026-10-18,677,S26_S2_peak_day_hourly_need_2026_10.csv

In [ ]:
import pandas as pd

# show everything (no truncation)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)
pd.set_option("display.max_colwidth", None)

display(df_2026)

,month,cutoff_used,demand_mode,demand_mode_p90,S1_PeakAmb_p90,S1_PeakMini_p90,S2_PeakAmb_p90,S2_PeakMini_p90,SLA_all_p90,SLA_arr_p90,SLA_dep_p90,allowed_breaches_p90,actual_breaches_p90,sla_percent_p90,sla_floor_slack_p90,S2_status_p90,S2_tc_p90,S2_st_p90,S1_peak_day_p90,S1_peak_day_job_count_p90,S1_hourly_table_path_p90,S2_peak_day_p90,S2_peak_day_job_count_p90,S2_hourly_table_path_p90,demand_mode_p100,S1_PeakAmb_p100,S1_PeakMini_p100,S2_PeakAmb_p100,S2_PeakMini_p100,SLA_all_p100,SLA_arr_p100,SLA_dep_p100,allowed_breaches_p100,actual_breaches_p100,sla_percent_p100,sla_floor_slack_p100,S2_status_p100,S2_tc_p100,S2_st_p100,S1_peak_day_p100,S1_peak_day_job_count_p100,S1_hourly_table_path_p100,S2_peak_day_p100,S2_peak_day_job_count_p100,S2_hourly_table_path_p100
0,2026-07,2026-07-01,compare_p90_vs_p100,p90_stratified,14,2,13,5,0.928952,0.936846,0.920969,343,1215,92.895152,872.0,maxtimelimit,maxtimelimit,aborted,2026-07-12,626,S26_S1_peak_day_hourly_need_2026_07.csv,2026-07-12,626,S26_S2_peak_day_hourly_need_2026_07.csv,p100,14,2,12,5,0.935700,0.944063,0.927294,373,1197,93.570047,824.0,maxtimelimit,maxtimelimit,aborted,2026-07-12,685,S26_S1_peak_day_hourly_need_2026_07.csv,2026-07-12,676,S26_S2_peak_day_hourly_need_2026_07.csv
1,2026-08,2026-07-02,compare_p90_vs_p100,p90_stratified,11,2,12,5,0.930396,0.941914,0.919043,347,1207,93.039617,860.0,maxtimelimit,maxtimelimit,aborted,2026-08-09,614,S26_S1_peak_day_hourly_need_2026_08.csv,2026-08-09,612,S26_S2_peak_day_hourly_need_2026_08.csv,p100,12,2,11,5,0.933965,0.943870,0.924171,378,1247,93.396526,869.0,maxtimelimit,maxtimelimit,aborted,2026-08-09,665,S26_S1_peak_day_hourly_need_2026_08.csv,2026-08-09,666,S26_S2_peak_day_hourly_need_2026_08.csv
2,2026-09,2026-07-02,compare_p90_vs_p100,p90_stratified,11,2,11,5,0.932759,0.945853,0.919717,328,1100,93.275873,772.0,maxtimelimit,maxtimelimit,aborted,2026-09-27,602,S26_S1_peak_day_hourly_need_2026_09.csv,2026-09-13,610,S26_S2_peak_day_hourly_need_2026_09.csv,p100,12,2,13,5,0.929887,0.945089,0.914771,360,1260,92.988704,900.0,maxtimelimit,maxtimelimit,aborted,2026-09-27,662,S26_S1_peak_day_hourly_need_2026_09.csv,2026-09-27,663,S26_S2_peak_day_hourly_need_2026_09.csv
3,2026-10,2026-07-02,compare_p90_vs_p100,p90_stratified,10,2,12,5,0.932735,0.940763,0.924700,331,1110,93.273543,779.0,maxtimelimit,maxtimelimit,aborted,2026-10-18,623,S26_S1_peak_day_hourly_need_2026_10.csv,2026-10-18,621,S26_S2_peak_day_hourly_need_2026_10.csv,p100,10,2,13,5,0.933374,0.942762,0.924055,361,1201,93.337402,840.0,maxtimelimit,maxtimelimit,aborted,2026-10-18,683,S26_S1_peak_day_hourly_need_2026_10.csv,2026-10-18,677,S26_S2_peak_day_hourly_need_2026_10.csv

In [9]:
print(df_2026.columns)

Index(['month', 'cutoff_used', 'demand_mode', 'demand_mode_p90',
       'S1_PeakAmb_p90', 'S1_PeakMini_p90', 'S2_PeakAmb_p90',
       'S2_PeakMini_p90', 'SLA_all_p90', 'SLA_arr_p90', 'SLA_dep_p90',
       'allowed_breaches_p90', 'actual_breaches_p90', 'sla_percent_p90',
       'sla_floor_slack_p90', 'S2_status_p90', 'S2_tc_p90', 'S2_st_p90',
       'S1_peak_day_p90', 'S1_peak_day_job_count_p90',
       'S1_hourly_table_path_p90', 'S2_peak_day_p90',
       'S2_peak_day_job_count_p90', 'S2_hourly_table_path_p90',
       'demand_mode_p100', 'S1_PeakAmb_p100', 'S1_PeakMini_p100',
       'S2_PeakAmb_p100', 'S2_PeakMini_p100', 'SLA_all_p100', 'SLA_arr_p100',
       'SLA_dep_p100', 'allowed_breaches_p100', 'actual_breaches_p100',
       'sla_percent_p100', 'sla_floor_slack_p100', 'S2_status_p100',
       'S2_tc_p100', 'S2_st_p100', 'S1_peak_day_p100',
       'S1_peak_day_job_count_p100', 'S1_hourly_table_path_p100',
       'S2_peak_day_p100', 'S2_peak_day_job_count_p100',
       'S2_hourly_table_path_p100'],
      dtype='object')

In [ ]:
month_start = "2026-10-01"
month_end = "2026-11-01"

if "out_s26_s2" in globals() and out_s26_s2.get("runs"):
    r = out_s26_s2["runs"][0]
else:
    tmp = run_s26_s2_v2_sensitivity(
        start=month_start,
        end=month_end,
        **assumptions["inputs"],
        vertical_cycle_grid=[10],
        solver_name="highs",
        toggles=toggles,
        time_limit_sec=600,
        threads=8,
        mip_rel_gap=0.20,
    )
    r = tmp["runs"][0]

report = build_run_report(r, day_from="s", hour_method="max")
print_run_report(report, show_hours=48)

hourly = report["peak_day_report"]["hourly"].copy()
display(hourly)

hourly.to_csv("S26_peak_day_hourly_need.csv")
print("Saved:", "S26_peak_day_hourly_need.csv")

Run S25 Scenario 1 (baseline)

In [ ]:

out_s1 = run_s25_s1(START_S25, END_S25, toggles=toggles)

report_s1 = build_run_report_s1(out_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s1)

# # 15-min peak day detail:
# report_s1["peak_day_report"]["bucket_level"].to_csv("S1_peak_day_15min.csv")
# report_s1["peak_day_report"]["hourly"].to_csv("S1_peak_day_hourly.csv")

Run S25 Scenario 2 (optimised)

In [ ]:

sens = run_s25_s2_v2_sensitivity(
    start=START_S25,
    end=END_S25,
    vertical_cycle_grid=[10],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)

# Build a comparison table

for r in sens["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY: {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r)

    # attach assumption for printing (not rebuilding anything)
    report["assumptions"] = {
        "vertical_cycle_mins": r["vertical_cycle_mins"]
    }

    print_run_report(report)

Run S26 Scenario 1

In [ ]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

In [ ]:
out_s26_s1 = run_s26_s1(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    toggles=toggles,
)


report_s26_s1 = build_run_report_s1(out_s26_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s26_s1)


# report_s26_s1["peak_day_report"]["bucket_level"].to_csv("S26_S1_peak_day_15min.csv")
# report_s26_s1["peak_day_report"]["hourly"].to_csv("S26_S1_peak_day_hourly.csv"

Run S26 scenario 2

In [ ]:



out_s26_s2 = run_s26_s2_v2_sensitivity(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    vertical_cycle_grid=[15],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)



for r in out_s26_s2["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY (S26): {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r, day_from="s", hour_method="max")
    report["assumptions"] = {"vertical_cycle_mins": r["vertical_cycle_mins"]}
    print_run_report(report)