Imports and dates

In [1]:
import sys
from pathlib import Path
import pandas as pd

# Add repo root to PYTHONPATH
HERE = Path().resolve()
PROJECT_ROOT = HERE.parents[0]   # notebooks → repo root
sys.path.insert(0, str(PROJECT_ROOT))


from prm_opt.run_s25 import run_s25_s1, run_s25_s2_v2_sensitivity, run_month_s25
from prm_opt.run_s26 import run_s26_s1, run_s26_s2_v2_sensitivity, run_month_s26
from prm_opt.build_s26_assumptions import build_s26_assumptions
from prm_opt.outputs import build_run_report, print_run_report, build_run_report_s1, print_run_report_s1
from prm_opt.build_jobs import build_jobs
from prm_opt.ingest_s25 import ingest_s25
from prm_opt.config import PlanningToggles

# -----------------------------
# DATE RANGES
# -----------------------------
START_S25 = "2025-04-01"
END_S25   = "2025-05-01"

START_S26 = "2026-07-01"
END_S26   = "2026-10-01"

Common toggles

In [ ]:
toggles = PlanningToggles(
    sla_buffer_mins=0,
    spill_bucket_cap=10,
    standby_dep_vert_mins=10,
    standby_arr_horiz_mins=10,
    enforce_hard_sla_floor=True,
    allow_sla_floor_slack=True,
    obj_sla_floor_slack_weight=20_000_000.0,

    demand_mode="p90_stratified",
    run_p100_risk_check_with_p90=True,
    p90_quantile=0.90,
    p90_strata=("SSR Code", "Has Own Chair", "A/D"),
)

In [3]:

# 2025 (historical)
months_2025 = pd.date_range("2025-04-01", "2025-10-01", freq="MS")

# 2026 (split logic inside function)
months_2026 = pd.date_range("2026-07-01", "2026-10-01", freq="MS")

In [4]:

results_2025 = []

for m in months_2025:
    results_2025.append(run_month_s25(m, toggles))

df_2025 = pd.DataFrame(results_2025)

df_2025.to_csv("S25_monthly_outputs_v2.csv", index=False)
df_2025

Running S25 2025-04

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-05

Unmatched passenger rows after merge (missing Chocks DT): 634
Unique unmatched flight keys: 386

Unmatched key reasons:
reason
no_flight_candidate               377
exact_match_should_have_joined      9
Name: count, dtype: int64

Dropped 618 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 1 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-06

Unmatched passenger rows after merge (missing Chocks DT): 656
Unique unmatched flight keys: 389

Unmatched key reasons:
reason
no_flight_candidate               335
scheduled_dt_mismatch              46
exact_match_should_have_joined      8
Name: count, dtype: int64

Dropped 636 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-07

Unmatched passenger rows after merge (missing Chocks DT): 724
Unique unmatched flight keys: 458

Unmatched key reasons:
reason
no_flight_candidate               445
exact_match_should_have_joined     10
scheduled_dt_mismatch               3
Name: count, dtype: int64

Dropped 702 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 5 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-08

Unmatched passenger rows after merge (missing Chocks DT): 629
Unique unmatched flight keys: 398

Unmatched key reasons:
reason
no_flight_candidate               373
scheduled_dt_mismatch              14
exact_match_should_have_joined     11
Name: count, dtype: int64

Dropped 613 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 7 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-09

Unmatched passenger rows after merge (missing Chocks DT): 698
Unique unmatched flight keys: 404

Unmatched key reasons:
reason
no_flight_candidate               396
exact_match_should_have_joined      7
scheduled_dt_mismatch               1
Name: count, dtype: int64

Dropped 686 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 8 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
18323      13159410           748           LS 2025-09-30 01:35:15
18324      13159411           748           LS 2025-09-30 01:35:15
18327      13159414           748           LS 2025-09-30 01:35:15
18328      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
18323 2025-09-30 04:59:07         20 2025-09-30 01:35:15
18324 2025-09-30 05:00:53         20 2025-09-30 01:35:15
18327 2025-09-30 04:59:15         20 2025-09-30 01:35:15
18328 2025-09-30 04:59:18         20 2025-09-30 01:35:15

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Running S25 2025-10

Unmatched passenger rows after merge (missing Chocks DT): 729
Unique unmatched flight keys: 418

Unmatched key reasons:
reason
no_flight_candidate               390
exact_match_should_have_joined     15
scheduled_dt_mismatch              13
Name: count, dtype: int64

Dropped 705 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[BUILD_JOBS] Dropping 6 jobs already impossible at release (beyond SLA + max late)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

,month,S1_PeakAmb,S1_PeakMini,S2_PeakAmb,S2_PeakMini,SLA_all,SLA_arr,SLA_dep,allowed_breaches,actual_breaches,sla_percent,sla_floor_slack,S2_status,S2_tc,S2_st
0,2025-04,14,4,None,None,None,None,None,None,None,None,None,None,None,None
1,2025-05,19,5,None,None,None,None,None,None,None,None,None,None,None,None
2,2025-06,12,7,None,None,None,None,None,None,None,None,None,None,None,None
3,2025-07,14,5,None,None,None,None,None,None,None,None,None,None,None,None
4,2025-08,13,5,None,None,None,None,None,None,None,None,None,None,None,None
5,2025-09,15,6,None,None,None,None,None,None,None,None,None,None,None,None
6,2025-10,22,5,None,None,None,None,None,None,None,None,None,None,None,None

In [4]:
print(results_2025)

NameError: name 'results_2025' is not defined

In [5]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

Unmatched passenger rows after merge (missing Chocks DT): 4532
Unique unmatched flight keys: 2757

Unmatched key reasons:
reason
no_flight_candidate               1980
scheduled_dt_mismatch              714
exact_match_should_have_joined      63
Name: count, dtype: int64

Dropped 4415 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[1/5] Penetration + SSR mix…
    ✓ penetration + SSR mix built   [396.92s]
[2/5] Service times…
[BUILD_JOBS] Dropping 36 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
99965      13159410           748           LS 2025-09-30 01:35:15
99966      13159411           748           LS 2025-09-30 01:35:15
99969      13159414           748           LS 2025-09-30 01:35:15
99970      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
99965 2025-09-30 04:59:07         20 2025-09-30 01:35:15
99966 2025-09-30 05:00:53         20 2025-09-30 01:35:15
99969 2025-09-30 04:59:15         20 2025-09-30 01:35:15
99970 2025-09-30 04:59:18         20 2025-09-30 01:35:15
    ✓ service times built   [4.51s]
[2b/5] Tau mode params (S25 medians)…
    ✓ tau mode params built   [0.04s]
[3/5] Chocks offsets…
    ✓ chocks offsets built   [0.12s]
[4/5] Early/late timing…
    ✓ early/late params built   [0.12s]
[5/5] Stand inputs…
    ✓ stand inputs built   [0.15s]

In [6]:

results_2026 = []

for m in months_2026:
    results_2026.append(run_month_s26(m, assumptions, toggles))

df_2026 = pd.DataFrame(results_2026)

df_2026.to_csv("S26_monthly_outputs_v3.csv", index=False)
df_2026

Running S26 2026-07 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11669
Airlines (sample): ['FR' 'LS' 'LM' 'BA' 'U2' 'RK' 'QR' 'AY' 'EI' 'DS']
Countries (sample): ['SPAIN' 'ITALY' 'PORTUGAL' 'GREAT BRITAIN' 'IRISH REPUBLIC' 'CROATIA'
 'SWEDEN' 'QATAR' 'FINLAND' 'AUSTRIA']

Pax describe:
count    11669.000000
mean       154.047819
std         50.440214
min          0.000000
25%        133.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       FR           SPAIN  International   D  173.0
1       LS           ITALY  International   D  172.0
2       LS        PORTUGAL  International   D  158.0
3       LM   GREAT BRITAIN       Domestic   D   36.0
4       BA   GREAT BRITAIN       Domestic   D   57.0
5       U2   GREAT BRITAIN       Domestic   D  167.0
6       LM   GREAT BRITAIN       Domestic   D   13.0
7       RK   GREAT BRITAIN       Domestic   D  183.0
8       U2   GREAT BRITAIN       Domestic   D  139.0
9       FR           SPAIN  International   D  185.0
10      RK   GREAT BRITAIN       Domestic   D  158.0
11      FR  IRISH REPUBLIC            CTA   D  167.0
12      LS         CROATIA  International   D  176.0
13      BA   GREAT BRITAIN       Domestic   D   60.0
14      FR          SWEDEN  International   D  131.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,214 / 11,669 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
25       DS  SWITZERLAND  174.0
85       EC      GERMANY  157.0
92       EC        ITALY  144.0
146      EC        SPAIN  150.0
147      IB        SPAIN  144.0
151      EC  NETHERLANDS  162.0
286      EC        ITALY  126.0
288      EC       FRANCE  187.0
322      RK        MALTA  187.0
342      IB        SPAIN  167.0
350      DS  SWITZERLAND  152.0
351      DS  SWITZERLAND  158.0
353      EC       FRANCE  148.0
360      EC        SPAIN  142.0
366      EC        SPAIN  125.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18266.14913075279
Total PRMs after rounding: 18622

Raw PRM demand distribution (prm_raw):
count    11669.000000
mean         1.565357
std          1.203595
min          0.000000
25%          0.832628
50%          1.248017
75%          1.718781
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
4789       BY                    GREECE  189.0   0.042488  8.030258
8207       BY                    GREECE  189.0   0.042488  8.030258
9914       BY                    GREECE  189.0   0.042488  8.030258
7014       BY                     SPAIN  188.0   0.042640  8.016392
5408       BY                    GREECE  188.0   0.042488  7.987770
11599      BY                     SPAIN  187.0   0.042640  7.973751
5343       BY                     SPAIN  187.0   0.042640  7.973751
11448      BY                     SPAIN  187.0   0.042640  7.973751
10081      BY                    GREECE  186.0   0.042488  7.902794
6410       BY                     SPAIN  185.0   0.042640  7.888470
10608      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5344       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5453       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
9090       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5786       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
4789            8
8207            8
9914            8
7014            8
5408            8
11599           8
5343            8
11448           8
10081           8
6410            8
10608           8
5344            8
5453            8
9090            8
5786            8
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=173.0 | Pen=0.00966 | Pax*Pen=1.671 | PRMs=2
[DEBUG flight] Airline=LS | Country=ITALY | Pax=172.0 | Pen=0.01426 | Pax*Pen=2.453 | PRMs=2
[DEBUG flight] Airline=LS | Country=PORTUGAL | Pax=158.0 | Pen=0.01789 | Pax*Pen=2.826 | PRMs=3
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=36.0 | Pen=0.01980 | Pax*Pen=0.713 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=57.0 | Pen=0.00962 | Pax*Pen=0.548 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=167.0 | Pen=0.00918 | Pax*Pen=1.533 | PRMs=2
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=13.0 | Pen=0.01980 | Pax*Pen=0.257 | PRMs=0
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=183.0 | Pen=0.00637 | Pax*Pen=1.167 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=139.0 | Pen=0.00918 | Pax*Pen=1.276 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=185.0 | Pen=0.00966 | Pax*Pen=1.786 | PRMs=2
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=158.0 | Pen=0.00637 | Pax*Pen=1.007 | PRMs=1
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=167.0 | Pen=0.00652 | Pax*Pen=1.090 | PRMs=1
[DEBUG flight] Airline=LS | Country=CROATIA | Pax=176.0 | Pen=0.00916 | Pax*Pen=1.611 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=60.0 | Pen=0.00962 | Pax*Pen=0.577 | PRMs=1
[DEBUG flight] Airline=FR | Country=SWEDEN | Pax=131.0 | Pen=0.00533 | Pax*Pen=0.698 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18622
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9845
WCHS     7665
WCHC      999
OTHER     113
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-07-01 → 2026-08-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11669
Airlines (sample): ['AF' 'FR' 'KL' 'BA' 'U2' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SPAIN' 'NETHERLANDS' 'GREAT BRITAIN' 'CZECH REPUBLIC' 'BELGIUM'
 'MALTA' 'ICELAND' 'GERMANY' 'ALBANIA']

Pax describe:
count    11669.000000
mean       154.047819
std         50.440214
min          0.000000
25%        133.000000
50%        167.000000
75%        185.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  111.0
1       FR           SPAIN  International   D  182.0
2       KL     NETHERLANDS  International   D  157.0
3       BA   GREAT BRITAIN       Domestic   D  127.0
4       U2   GREAT BRITAIN       Domestic   D  132.0
5       U2          FRANCE  International   D  154.0
6       U2  CZECH REPUBLIC  International   D  224.0
7       FR         BELGIUM  International   D  163.0
8       LS           MALTA  International   D  162.0
9       U2           SPAIN  International   D  154.0
10      U2         ICELAND  International   D  165.0
11      LH         GERMANY  International   D  172.0
12      LS           SPAIN  International   D  230.0
13      LS           SPAIN  International   D  177.0
14      BA   GREAT BRITAIN       Domestic   D   49.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,214 / 11,669 (96.1%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
2       DS  SWITZERLAND           78
7       EC        SPAIN           78
5       EC        ITALY           75
3       EC       FRANCE           56
6       EC  NETHERLANDS           34
4       EC      GERMANY           32
8       IB        SPAIN           26
13      RK        MALTA           18
10      LG   LUXEMBOURG           18
15      U2     SLOVENIA           16
1       BA        ITALY            8
14      RK      ROMANIA            8
0       AP       FRANCE            2
9       KK      AUSTRIA            2
12    None      AUSTRIA            2

Example missing keys:
    Airline  CountryName    Pax
19       U2     SLOVENIA  147.0
47       DS  SWITZERLAND  174.0
107      EC      GERMANY  157.0
114      EC        ITALY  144.0
168      EC        SPAIN  150.0
169      IB        SPAIN  144.0
173      EC  NETHERLANDS  162.0
308      EC        ITALY  126.0
310      EC       FRANCE  187.0
344      RK        MALTA  187.0
364      IB        SPAIN  167.0
372      DS  SWITZERLAND  152.0
373      DS  SWITZERLAND  158.0
375      EC       FRANCE  148.0
382      EC        SPAIN  142.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18266.14913075279
Total PRMs after rounding: 18622

Raw PRM demand distribution (prm_raw):
count    11669.000000
mean         1.565357
std          1.203595
min          0.000000
25%          0.832628
50%          1.248017
75%          1.718781
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
4804       BY                    GREECE  189.0   0.042488  8.030258
8204       BY                    GREECE  189.0   0.042488  8.030258
9914       BY                    GREECE  189.0   0.042488  8.030258
7002       BY                     SPAIN  188.0   0.042640  8.016392
5435       BY                    GREECE  188.0   0.042488  7.987770
5390       BY                     SPAIN  187.0   0.042640  7.973751
11448      BY                     SPAIN  187.0   0.042640  7.973751
11599      BY                     SPAIN  187.0   0.042640  7.973751
10081      BY                    GREECE  186.0   0.042488  7.902794
6409       BY                     SPAIN  185.0   0.042640  7.888470
6021       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
10608      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
9068       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5658       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5790       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
4804            8
8204            8
9914            8
7002            8
5435            8
5390            8
11448           8
11599           8
10081           8
6409            8
6021            8
10608           8
9068            8
5658            8
5790            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=111.0 | Pen=0.00755 | Pax*Pen=0.838 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=182.0 | Pen=0.00966 | Pax*Pen=1.757 | PRMs=2
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=157.0 | Pen=0.00831 | Pax*Pen=1.304 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=127.0 | Pen=0.00962 | Pax*Pen=1.221 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=132.0 | Pen=0.00918 | Pax*Pen=1.211 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=154.0 | Pen=0.00839 | Pax*Pen=1.292 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CZECH REPUBLIC | Pax=224.0 | Pen=0.00446 | Pax*Pen=0.998 | PRMs=1
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=163.0 | Pen=0.00380 | Pax*Pen=0.619 | PRMs=1
[DEBUG flight] Airline=LS | Country=MALTA | Pax=162.0 | Pen=0.01755 | Pax*Pen=2.843 | PRMs=3
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=154.0 | Pen=0.01381 | Pax*Pen=2.127 | PRMs=2
[DEBUG flight] Airline=U2 | Country=ICELAND | Pax=165.0 | Pen=0.00577 | Pax*Pen=0.952 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=172.0 | Pen=0.00569 | Pax*Pen=0.979 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=230.0 | Pen=0.02578 | Pax*Pen=5.930 | PRMs=6
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=177.0 | Pen=0.02578 | Pax*Pen=4.563 | PRMs=5
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=49.0 | Pen=0.00962 | Pax*Pen=0.471 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 18622
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9910
WCHS     7606
WCHC     1002
OTHER     104
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,622   [379.21s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,620   [0.54s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [1.02s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 2}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
KK            D      2
dtype: int64

Bucket horizon: start=2026-07-02 00:15:00 end=2026-08-01 05:45:00 buckets=2903
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-07-31 13:30:00 | 60.0 / 210.0
  2026-07-31 13:45:00 | 60.0 / 210.0
  2026-07-22 17:00:00 | 60.0 / 210.0
  2026-07-28 20:15:00 | 60.0 / 210.0
  2026-07-21 17:15:00 | 60.0 / 210.0
  2026-07-22 19:15:00 | 45.0 / 210.0
  2026-07-10 13:45:00 | 45.0 / 210.0
  2026-07-07 14:45:00 | 45.0 / 210.0
  2026-07-05 15:15:00 | 45.0 / 210.0
  2026-07-19 15:15:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 385
  is_spin by dir:
dir
A    385
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.10850686666666666 32.67715376666667 59.58119546666667
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 8.0

Amb minutes (necessary condition):
  min required (vertical-only): 84490.0
  total available over horizon: 591390.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 20
  min mini minutes required (forced): 346.3
  total mini minutes available: 217725.0

Lift rough check:
  lift jobs: 66
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3170
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
5    S26_0807_0  U2_0807_2026-07-08 06:00:00   D 2026-07-08 06:00:00
8    S26_7322_0  FR_7322_2026-07-08 06:00:00   D 2026-07-08 06:00:00
12   S26_3205_0  U2_3205_2026-07-08 06:00:00   D 2026-07-08 06:00:00
13   S26_3205_1  U2_3205_2026-07-08 06:00:00   D 2026-07-08 06:00:00
14   S26_3315_0  U2_3315_2026-07-08 06:00:00   D 2026-07-08 06:00:00
28   S26_2969_0  FR_2969_2026-07-08 06:30:00   D 2026-07-08 06:30:00
29   S26_2969_1  FR_2969_2026-07-08 06:30:00   D 2026-07-08 06:30:00
31   S26_0759_0  LS_0759_2026-07-08 07:15:00   D 2026-07-08 07:15:00
32   S26_0759_1  LS_0759_2026-07-08 07:15:00   D 2026-07-08 07:15:00
33   S26_0759_2  LS_0759_2026-07-08 07:15:00   D 2026-07-08 07:15:00
34   S26_0759_3  LS_0759_2026-07-08 07:15:00   D 2026-07-08 07:15:00
35   S26_0759_4  LS_0759_2026-07-08 07:15:00   D 2026-07-08 07:15:00
36   S26_3217_0  U2_3217_2026-07-08 06:45:00   D 2026-07-08 06:45:00
41   S26_0703_0  LS_0703_2026-07-08 07:15:00   D 2026-07-08 07:00:00
42   S26_0703_1  LS_0703_2026-07-08 07:15:00   D 2026-07-08 07:00:00
55   S26_0809_0  FR_0809_2026-07-08 08:00:00   D 2026-07-08 08:00:00
56   S26_0791_0  LS_0791_2026-07-08 07:45:00   D 2026-07-08 07:45:00
57   S26_0791_1  LS_0791_2026-07-08 07:45:00   D 2026-07-08 07:45:00
58   S26_8713_0  BA_8713_2026-07-08 08:15:00   D 2026-07-08 08:00:00
59   S26_5657_0  FR_5657_2026-07-08 07:30:00   D 2026-07-08 07:30:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
5  2026-07-08 06:05:36.594198408 2026-07-08 06:00:00   15A           U2
8  2026-07-08 06:00:52.083252594 2026-07-08 06:00:00    22           FR
12 2026-07-08 06:10:00.000000000 2026-07-08 06:10:00    20           U2
13 2026-07-08 06:10:00.000000000 2026-07-08 06:10:00    20           U2
14 2026-07-08 06:10:00.000000000 2026-07-08 06:10:00    1B           U2
28 2026-07-08 06:37:45.715994982 2026-07-08 06:20:00    1A           FR
29 2026-07-08 06:37:45.715994982 2026-07-08 06:20:00    1A           FR
31 2026-07-08 07:22:51.387990312 2026-07-08 06:30:00     3           LS
32 2026-07-08 07:22:51.387990312 2026-07-08 06:30:00     3           LS
33 2026-07-08 07:22:51.387990312 2026-07-08 06:30:00     3           LS
34 2026-07-08 07:22:51.387990312 2026-07-08 06:30:00     3           LS
35 2026-07-08 07:22:51.387990312 2026-07-08 06:30:00     3           LS
36 2026-07-08 06:51:33.411523104 2026-07-08 06:35:00    24           U2
41 2026-07-08 07:12:49.153306206 2026-07-08 06:45:00   310           LS
42 2026-07-08 07:12:49.153306206 2026-07-08 06:45:00   310           LS
55 2026-07-08 08:07:24.732688620 2026-07-08 07:20:00    17           FR
56 2026-07-08 07:45:20.619475038 2026-07-08 07:20:00    14           LS
57 2026-07-08 07:45:20.619475038 2026-07-08 07:20:00    14           LS
58 2026-07-08 08:10:17.111692398 2026-07-08 07:25:00     4           BA

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-07 | Cutoff: 2026-07-01
Scenario 1:
  PeakAmb=14 | PeakMini=2
Scenario 2:
  PeakAmb=12 | PeakMini=5
SLA:
  All=0.9327 | Arr=0.9454 | Dep=0.9200
SLA diagnostics:
  allowed_breaches=373 | actual_breaches=1253 | sla_percent=93.27% | sla_floor_slack=880.00
  WARNING: hard SLA floor relaxed by slack on 880.00 jobs
================================================


Running S26 2026-08 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11943
Airlines (sample): ['U2' 'FR' 'DY' 'EI' 'LM' 'LS' 'AF' 'RK' 'BA' 'TK']
Countries (sample): ['FRANCE' 'ITALY' 'CZECH REPUBLIC' 'NORWAY' 'IRISH REPUBLIC'
 'GREAT BRITAIN' 'CYPRUS' 'GREECE' 'TURKEY' 'SPAIN']

Pax describe:
count    11943.000000
mean       152.867286
std         52.729101
min          0.000000
25%        130.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       U2          FRANCE  International   D  166.0
1       FR           ITALY  International   D  183.0
2       FR  CZECH REPUBLIC  International   D  182.0
3       FR           ITALY  International   D  187.0
4       DY          NORWAY  International   D  184.0
5       EI  IRISH REPUBLIC            CTA   D   66.0
6       U2   GREAT BRITAIN       Domestic   D  137.0
7       FR           ITALY  International   D  178.0
8       EI  IRISH REPUBLIC            CTA   D   65.0
9       EI  IRISH REPUBLIC            CTA   D   64.0
10      U2          CYPRUS  International   D  158.0
11      U2   GREAT BRITAIN       Domestic   D  167.0
12      LM   GREAT BRITAIN       Domestic   D   72.0
13      U2          GREECE  International   D  170.0
14      LM   GREAT BRITAIN       Domestic   D   40.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,428 / 11,943 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
31       EC        SPAIN  129.0
71       IB        SPAIN  159.0
95       EC      GERMANY  156.0
111      EC        ITALY  142.0
247      EC        ITALY  111.0
282      EC       FRANCE  132.0
293      EC  NETHERLANDS  170.0
310      EC        SPAIN   91.0
312      EC        ITALY  139.0
351      DS  SWITZERLAND  153.0
383      EC        SPAIN   90.0
416      EC        ITALY  112.0
420      RK      ROMANIA  159.0
437      LG   LUXEMBOURG  120.0
439      DS  SWITZERLAND  167.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18514.574476470356
Total PRMs after rounding: 18943

Raw PRM demand distribution (prm_raw):
count    11943.000000
mean         1.550245
std          1.253615
min          0.000000
25%          0.807886
50%          1.233208
75%          1.702331
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
59         QR       QATAR  311.0   0.026728  8.312373           8
2418       QR       QATAR  311.0   0.026728  8.312373           8
5592       QR       QATAR  311.0   0.026728  8.312373           8
1468       QR       QATAR  311.0   0.026728  8.312373           8
4247       QR       QATAR  311.0   0.026728  8.312373           8
2987       QR       QATAR  311.0   0.026728  8.312373           8
5508       QR       QATAR  311.0   0.026728  8.312373           8
1638       QR       QATAR  311.0   0.026728  8.312373           8
1069       QR       QATAR  311.0   0.026728  8.312373           8
9867       QR       QATAR  311.0   0.026728  8.312373           8
10825      QR       QATAR  311.0   0.026728  8.312373           8
5681       QR       QATAR  311.0   0.026728  8.312373           8
4536       QR       QATAR  311.0   0.026728  8.312373           8
2327       QR       QATAR  311.0   0.026728  8.312373           8
1271       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=166.0 | Pen=0.00839 | Pax*Pen=1.392 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=183.0 | Pen=0.00547 | Pax*Pen=1.001 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=182.0 | Pen=0.00359 | Pax*Pen=0.653 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=187.0 | Pen=0.00547 | Pax*Pen=1.022 | PRMs=1
[DEBUG flight] Airline=DY | Country=NORWAY | Pax=184.0 | Pen=0.00440 | Pax*Pen=0.809 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=66.0 | Pen=0.01035 | Pax*Pen=0.683 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=137.0 | Pen=0.00918 | Pax*Pen=1.257 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=178.0 | Pen=0.00547 | Pax*Pen=0.973 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=65.0 | Pen=0.01035 | Pax*Pen=0.673 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=64.0 | Pen=0.01035 | Pax*Pen=0.662 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CYPRUS | Pax=158.0 | Pen=0.02183 | Pax*Pen=3.449 | PRMs=3
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=167.0 | Pen=0.00918 | Pax*Pen=1.533 | PRMs=2
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=72.0 | Pen=0.01980 | Pax*Pen=1.426 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=170.0 | Pen=0.01184 | Pax*Pen=2.012 | PRMs=2
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=40.0 | Pen=0.01980 | Pax*Pen=0.792 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18943
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10052
WCHS      7700
WCHC      1059
OTHER      132
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-08-01 → 2026-09-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11943
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SLOVAKIA' 'NETHERLANDS' 'SPAIN' 'GREAT BRITAIN' 'POLAND'
 'SWITZERLAND' 'GERMANY' 'CROATIA' 'ITALY']

Pax describe:
count    11943.000000
mean       152.867286
std         52.729101
min          0.000000
25%        130.000000
50%        164.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   90.0
1       U2         FRANCE  International   D  208.0
2       FR       SLOVAKIA  International   D  186.0
3       KL    NETHERLANDS  International   D  139.0
4       FR          SPAIN  International   D  197.0
5       BA  GREAT BRITAIN       Domestic   D  143.0
6       U2  GREAT BRITAIN       Domestic   D  126.0
7       U2          SPAIN  International   D  169.0
8       FR         POLAND  International   D  186.0
9       LS          SPAIN  International   D  229.0
10      U2    SWITZERLAND  International   D  164.0
11      LH        GERMANY  International   D  166.0
12      U2        CROATIA  International   D  177.0
13      FR          ITALY  International   D  175.0
14      FR        ROMANIA  International   D  196.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,428 / 11,943 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
20       RK        MALTA  181.0
36       EC  NETHERLANDS  156.0
101      EC      GERMANY  151.0
103      U2     SLOVENIA  171.0
116      EC        ITALY  144.0
121      BA        ITALY   76.0
156      EC        SPAIN  127.0
157      DS  SWITZERLAND  175.0
160      EC        SPAIN  129.0
229      EC        ITALY  149.0
232      IB        SPAIN  159.0
263      EC      GERMANY  156.0
276      EC       FRANCE  107.0
293      EC        ITALY  142.0
320      EC       FRANCE  149.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18514.574476470356
Total PRMs after rounding: 18943

Raw PRM demand distribution (prm_raw):
count    11943.000000
mean         1.550245
std          1.253615
min          0.000000
25%          0.807886
50%          1.233208
75%          1.702331
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
692        QR       QATAR  311.0   0.026728  8.312373           8
5508       QR       QATAR  311.0   0.026728  8.312373           8
5106       QR       QATAR  311.0   0.026728  8.312373           8
35         QR       QATAR  311.0   0.026728  8.312373           8
879        QR       QATAR  311.0   0.026728  8.312373           8
5681       QR       QATAR  311.0   0.026728  8.312373           8
2526       QR       QATAR  311.0   0.026728  8.312373           8
4536       QR       QATAR  311.0   0.026728  8.312373           8
7259       QR       QATAR  311.0   0.026728  8.312373           8
11825      QR       QATAR  311.0   0.026728  8.312373           8
4336       QR       QATAR  311.0   0.026728  8.312373           8
10411      QR       QATAR  311.0   0.026728  8.312373           8
4730       QR       QATAR  311.0   0.026728  8.312373           8
124        QR       QATAR  311.0   0.026728  8.312373           8
9867       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=90.0 | Pen=0.00755 | Pax*Pen=0.679 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=208.0 | Pen=0.00839 | Pax*Pen=1.745 | PRMs=2
[DEBUG flight] Airline=FR | Country=SLOVAKIA | Pax=186.0 | Pen=0.00226 | Pax*Pen=0.421 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=139.0 | Pen=0.00831 | Pax*Pen=1.155 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00962 | Pax*Pen=1.375 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=126.0 | Pen=0.00918 | Pax*Pen=1.156 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=169.0 | Pen=0.01381 | Pax*Pen=2.334 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=186.0 | Pen=0.00313 | Pax*Pen=0.582 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=229.0 | Pen=0.02578 | Pax*Pen=5.904 | PRMs=6
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=164.0 | Pen=0.00694 | Pax*Pen=1.139 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=166.0 | Pen=0.00569 | Pax*Pen=0.945 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=177.0 | Pen=0.00421 | Pax*Pen=0.746 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=175.0 | Pen=0.00547 | Pax*Pen=0.957 | PRMs=1
[DEBUG flight] Airline=FR | Country=ROMANIA | Pax=196.0 | Pen=0.00422 | Pax*Pen=0.828 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18943
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10042
WCHS      7709
WCHC      1066
OTHER      126
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,943   [107.77s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,941   [0.39s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.59s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-07-31 23:45:00 end=2026-09-01 05:15:00 buckets=2999
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-08-07 15:15:00 | 60.0 / 210.0
  2026-08-07 15:30:00 | 60.0 / 210.0
  2026-08-06 19:45:00 | 60.0 / 210.0
  2026-08-21 18:45:00 | 60.0 / 210.0
  2026-08-21 19:15:00 | 60.0 / 210.0
  2026-08-02 13:45:00 | 60.0 / 210.0
  2026-08-02 14:00:00 | 60.0 / 210.0
  2026-08-07 18:30:00 | 60.0 / 210.0
  2026-08-28 08:15:00 | 45.0 / 210.0
  2026-08-06 20:00:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 396
  is_spin by dir:
dir
A    396
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.5922877666666667 34.62952145833333 59.95600291666666
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 7.0

Amb minutes (necessary condition):
  min required (vertical-only): 86048.2
  total available over horizon: 611190.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 27
  min mini minutes required (forced): 462.4
  total mini minutes available: 224925.0

Lift rough check:
  lift jobs: 81
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3173
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
4    S26_6266_0  FR_6266_2026-08-01 06:00:00   D 2026-08-01 06:00:00
5    S26_6266_1  FR_6266_2026-08-01 06:00:00   D 2026-08-01 06:00:00
6    S26_1467_0  BA_1467_2026-08-01 06:30:00   D 2026-08-01 06:30:00
11   S26_0775_0  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
12   S26_0775_1  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
13   S26_0775_2  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
14   S26_0775_3  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
15   S26_0775_4  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
16   S26_0775_5  LS_0775_2026-08-01 06:15:00   D 2026-08-01 06:00:00
19   S26_3319_0  U2_3319_2026-08-01 06:15:00   D 2026-08-01 06:15:00
22   S26_0597_0  RK_0597_2026-08-01 07:30:00   D 2026-08-01 07:15:00
41   S26_2337_0  BA_2337_2026-08-01 07:30:00   D 2026-08-01 07:30:00
42   S26_2337_1  BA_2337_2026-08-01 07:30:00   D 2026-08-01 07:30:00
46   S26_0307_0  U2_0307_2026-08-01 07:00:00   D 2026-08-01 07:00:00
47   S26_0307_1  U2_0307_2026-08-01 07:00:00   D 2026-08-01 07:00:00
54   S26_0703_0  LS_0703_2026-08-01 07:45:00   D 2026-08-01 07:45:00
55   S26_0703_1  LS_0703_2026-08-01 07:45:00   D 2026-08-01 07:45:00
56   S26_0703_2  LS_0703_2026-08-01 07:45:00   D 2026-08-01 07:45:00
57   S26_1465_0  BA_1465_2026-08-01 07:30:00   D 2026-08-01 07:30:00
58   S26_0321_0  LM_0321_2026-08-01 07:45:00   D 2026-08-01 07:45:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
4  2026-08-01 06:04:58.853742108 2026-08-01 05:55:00   100           FR
5  2026-08-01 06:04:58.853742108 2026-08-01 05:55:00   100           FR
6  2026-08-01 06:38:01.697936472 2026-08-01 06:00:00     9           BA
11 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
12 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
13 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
14 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
15 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
16 2026-08-01 06:13:02.609858514 2026-08-01 06:00:00    14           LS
19 2026-08-01 06:18:59.491685358 2026-08-01 06:15:00    24           U2
22 2026-08-01 07:29:10.141666416 2026-08-01 06:15:00    1B           RK
41 2026-08-01 07:37:47.749828458 2026-08-01 06:50:00     8           BA
42 2026-08-01 07:37:47.749828458 2026-08-01 06:50:00     8           BA
46 2026-08-01 07:04:47.903267142 2026-08-01 07:00:00    22           U2
47 2026-08-01 07:04:47.903267142 2026-08-01 07:00:00    22           U2
54 2026-08-01 07:49:55.205414916 2026-08-01 07:35:00   104           LS
55 2026-08-01 07:49:55.205414916 2026-08-01 07:35:00   104           LS
56 2026-08-01 07:49:55.205414916 2026-08-01 07:35:00   104           LS
57 2026-08-01 07:40:00.000000000 2026-08-01 07:40:00     6           BA
58 2026-08-01 07:55:00.000000000 2026-08-01 07:55:00     4           LM

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 10
  tight vertical jobs: 889
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 687
  infeasible buckets (req > avail): 0

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-08 | Cutoff: 2026-07-01
Scenario 1:
  PeakAmb=11 | PeakMini=3
Scenario 2:
  PeakAmb=13 | PeakMini=5
SLA:
  All=0.9366 | Arr=0.9463 | Dep=0.9270
SLA diagnostics:
  allowed_breaches=379 | actual_breaches=1201 | sla_percent=93.66% | sla_floor_slack=822.00
  WARNING: hard SLA floor relaxed by slack on 822.00 jobs
================================================


Running S26 2026-09 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11441
Airlines (sample): ['FR' 'RK' 'EI' 'AA' 'HU' 'U2' 'PC' 'DL' 'BA' 'LM']
Countries (sample): ['MALTA' 'ITALY' 'SPAIN' 'IRISH REPUBLIC' 'UNITED STATES OF AMERICA'
 'CHINA' 'GREAT BRITAIN' 'TURKEY' 'GREECE' 'GERMANY']

Pax describe:
count    11441.000000
mean       146.972555
std         54.283725
min          0.000000
25%        120.000000
50%        157.000000
75%        180.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline               CountryName         Sector dir    Pax
0       FR                     MALTA  International   D  172.0
1       FR                     ITALY  International   D  189.0
2       RK                     SPAIN  International   D  146.0
3       EI            IRISH REPUBLIC            CTA   D   48.0
4       AA  UNITED STATES OF AMERICA  International   D  279.0
5       HU                     CHINA  International   D  241.0
6       EI            IRISH REPUBLIC            CTA   D   50.0
7       U2             GREAT BRITAIN       Domestic   D  151.0
8       PC                    TURKEY  International   D  168.0
9       RK             GREAT BRITAIN       Domestic   D  173.0
10      DL  UNITED STATES OF AMERICA  International   D  216.0
11      U2                     SPAIN  International   D  158.0
12      RK                     SPAIN  International   D  171.0
13      FR                     SPAIN  International   D  177.0
14      EI            IRISH REPUBLIC            CTA   D   55.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,003 / 11,441 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
106      EC        ITALY  137.0
110      EC        SPAIN  156.0
159      EC  NETHERLANDS  162.0
261      EC        ITALY  122.0
302      IB        SPAIN  163.0
308      DS  SWITZERLAND   95.0
314      EC       FRANCE  153.0
318      EC        SPAIN  149.0
368      EC       FRANCE  163.0
388      EC        ITALY  214.0
424      EC        ITALY  164.0
431      EC        SPAIN  160.0
436      RK        MALTA  176.0
445      EC       FRANCE  182.0
457      DS  SWITZERLAND  116.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17761.39330909508
Total PRMs after rounding: 18037

Raw PRM demand distribution (prm_raw):
count    11441.000000
mean         1.552434
std          1.298933
min          0.000000
25%          0.769415
50%          1.194166
75%          1.716516
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
11404      QR       QATAR  311.0   0.026728  8.312373           8
5252       QR       QATAR  311.0   0.026728  8.312373           8
3079       QR       QATAR  311.0   0.026728  8.312373           8
3166       QR       QATAR  311.0   0.026728  8.312373           8
5054       QR       QATAR  311.0   0.026728  8.312373           8
2143       QR       QATAR  311.0   0.026728  8.312373           8
4700       QR       QATAR  311.0   0.026728  8.312373           8
4805       QR       QATAR  311.0   0.026728  8.312373           8
2225       QR       QATAR  311.0   0.026728  8.312373           8
6556       QR       QATAR  311.0   0.026728  8.312373           8
2396       QR       QATAR  311.0   0.026728  8.312373           8
6006       QR       QATAR  311.0   0.026728  8.312373           8
4885       QR       QATAR  311.0   0.026728  8.312373           8
5782       QR       QATAR  311.0   0.026728  8.312373           8
4966       QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=FR | Country=MALTA | Pax=172.0 | Pen=0.00863 | Pax*Pen=1.484 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=189.0 | Pen=0.00547 | Pax*Pen=1.033 | PRMs=1
[DEBUG flight] Airline=RK | Country=SPAIN | Pax=146.0 | Pen=0.00822 | Pax*Pen=1.200 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=48.0 | Pen=0.01035 | Pax*Pen=0.497 | PRMs=0
[DEBUG flight] Airline=AA | Country=UNITED STATES OF AMERICA | Pax=279.0 | Pen=0.01552 | Pax*Pen=4.330 | PRMs=4
[DEBUG flight] Airline=HU | Country=CHINA | Pax=241.0 | Pen=0.00399 | Pax*Pen=0.961 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=50.0 | Pen=0.01035 | Pax*Pen=0.517 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=151.0 | Pen=0.00918 | Pax*Pen=1.386 | PRMs=1
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=168.0 | Pen=0.00852 | Pax*Pen=1.431 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=173.0 | Pen=0.00637 | Pax*Pen=1.103 | PRMs=1
[DEBUG flight] Airline=DL | Country=UNITED STATES OF AMERICA | Pax=216.0 | Pen=0.01410 | Pax*Pen=3.045 | PRMs=3
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=158.0 | Pen=0.01381 | Pax*Pen=2.182 | PRMs=2
[DEBUG flight] Airline=RK | Country=SPAIN | Pax=171.0 | Pen=0.00822 | Pax*Pen=1.406 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=177.0 | Pen=0.00966 | Pax*Pen=1.709 | PRMs=2
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=55.0 | Pen=0.01035 | Pax*Pen=0.569 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18037
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9590
WCHS     7372
WCHC      975
OTHER     100
Name: count, dtype: int64
[BUILD_JOBS] Dropping 6 jobs already impossible at release (beyond SLA + max late)

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-09-01 → 2026-10-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11441
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    11441.000000
mean       146.972555
std         54.283725
min          0.000000
25%        120.000000
50%        157.000000
75%        180.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D  100.0
1       U2          ITALY  International   D  159.0
2       FR         FRANCE  International   D  114.0
3       FR          ITALY  International   D  172.0
4       KL    NETHERLANDS  International   D  107.0
5       BA  GREAT BRITAIN       Domestic   D  116.0
6       U2  GREAT BRITAIN       Domestic   D  165.0
7       U2  GREAT BRITAIN       Domestic   D  128.0
8       U2  GREAT BRITAIN       Domestic   D  162.0
9       FR          SPAIN  International   D  197.0
10      RK        ROMANIA  International   D  143.0
11      U2  GREAT BRITAIN       Domestic   D  146.0
12      U2        CROATIA  International   D  154.0
13      FR          SPAIN  International   D  188.0
14      LH        GERMANY  International   D  108.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,003 / 11,441 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  143.0
53       EC  NETHERLANDS  160.0
106      EC        ITALY  121.0
158      EC        SPAIN   81.0
203      U2     SLOVENIA  138.0
291      DS  SWITZERLAND  146.0
299      EC        ITALY  137.0
303      EC        SPAIN  156.0
353      IB        SPAIN  143.0
357      EC  NETHERLANDS  162.0
415      EC        ITALY  203.0
423      DS  SWITZERLAND  116.0
484      EC        ITALY  122.0
493      EC       FRANCE  182.0
519      RK        MALTA  176.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17761.393309095085
Total PRMs after rounding: 18037

Raw PRM demand distribution (prm_raw):
count    11441.000000
mean         1.552434
std          1.298933
min          0.000000
25%          0.769415
50%          1.194166
75%          1.716516
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
11404      QR       QATAR  311.0   0.026728  8.312373           8
1835       QR       QATAR  311.0   0.026728  8.312373           8
498        QR       QATAR  311.0   0.026728  8.312373           8
2396       QR       QATAR  311.0   0.026728  8.312373           8
2307       QR       QATAR  311.0   0.026728  8.312373           8
3473       QR       QATAR  311.0   0.026728  8.312373           8
3166       QR       QATAR  311.0   0.026728  8.312373           8
3079       QR       QATAR  311.0   0.026728  8.312373           8
8651       QR       QATAR  311.0   0.026728  8.312373           8
2225       QR       QATAR  311.0   0.026728  8.312373           8
3639       QR       QATAR  311.0   0.026728  8.312373           8
3729       QR       QATAR  311.0   0.026728  8.312373           8
4966       QR       QATAR  311.0   0.026728  8.312373           8
4885       QR       QATAR  311.0   0.026728  8.312373           8
974        QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=100.0 | Pen=0.00755 | Pax*Pen=0.755 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=159.0 | Pen=0.00872 | Pax*Pen=1.386 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=114.0 | Pen=0.00686 | Pax*Pen=0.782 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=172.0 | Pen=0.00547 | Pax*Pen=0.940 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=107.0 | Pen=0.00831 | Pax*Pen=0.889 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=116.0 | Pen=0.00962 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=165.0 | Pen=0.00918 | Pax*Pen=1.514 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=128.0 | Pen=0.00918 | Pax*Pen=1.175 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=143.0 | Pen=0.01000 | Pax*Pen=1.430 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=146.0 | Pen=0.00918 | Pax*Pen=1.340 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=154.0 | Pen=0.00421 | Pax*Pen=0.649 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=188.0 | Pen=0.00966 | Pax*Pen=1.815 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18037
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9567
WCHS     7360
WCHC      990
OTHER     120
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,037   [86.89s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 6 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,031   [0.36s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.51s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-08-31 23:15:00 end=2026-10-01 05:30:00 buckets=2906
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-09-29 14:30:00 | 75.0 / 210.0
  2026-09-29 14:45:00 | 75.0 / 210.0
  2026-09-29 15:00:00 | 75.0 / 210.0
  2026-09-18 19:00:00 | 60.0 / 210.0
  2026-09-14 13:00:00 | 60.0 / 210.0
  2026-09-14 13:15:00 | 60.0 / 210.0
  2026-09-20 18:00:00 | 60.0 / 210.0
  2026-09-13 13:15:00 | 60.0 / 210.0
  2026-09-13 13:30:00 | 60.0 / 210.0
  2026-09-25 15:30:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 325
  is_spin by dir:
dir
A    325
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 1.0109914333333334 32.27862326666666 59.867434583333335
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 6.0

Amb minutes (necessary condition):
  min required (vertical-only): 79475.0
  total available over horizon: 593580.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 22
  min mini minutes required (forced): 378.8
  total mini minutes available: 217950.0

Lift rough check:
  lift jobs: 68
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3156
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
3    S26_1652_0  FR_1652_2026-09-01 06:30:00   D 2026-09-01 06:15:00
4    S26_0922_0  KL_0922_2026-09-01 06:00:00   D 2026-09-01 05:45:00
21   S26_0815_0  FR_0815_2026-09-01 06:30:00   D 2026-09-01 06:30:00
34   S26_1467_0  BA_1467_2026-09-01 07:15:00   D 2026-09-01 07:15:00
35   S26_1467_1  BA_1467_2026-09-01 07:15:00   D 2026-09-01 07:15:00
40   S26_0391_0  LM_0391_2026-09-01 07:15:00   D 2026-09-01 07:15:00
41   S26_0775_0  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
42   S26_0775_1  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
43   S26_0775_2  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
44   S26_0775_3  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
45   S26_0775_4  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
46   S26_0775_5  LS_0775_2026-09-01 07:15:00   D 2026-09-01 07:15:00
57   S26_0032_0  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
58   S26_0032_1  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
59   S26_0032_2  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
60   S26_0032_3  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
61   S26_0032_4  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
62   S26_0032_5  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
63   S26_0032_6  QR_0032_2026-09-01 07:45:00   D 2026-09-01 07:45:00
74   S26_0035_0  DL_0035_2026-09-01 09:45:00   D 2026-09-01 09:45:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
3  2026-09-01 06:26:16.464625890 2026-09-01 05:45:00    1B           FR
4  2026-09-01 05:55:09.186417894 2026-09-01 05:45:00    10           KL
21 2026-09-01 06:31:29.949408468 2026-09-01 06:15:00    1A           FR
34 2026-09-01 07:21:10.235577864 2026-09-01 07:00:00     6           BA
35 2026-09-01 07:21:10.235577864 2026-09-01 07:00:00     6           BA
40 2026-09-01 07:22:58.727795364 2026-09-01 07:00:00     6           LM
41 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
42 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
43 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
44 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
45 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
46 2026-09-01 07:22:24.447503178 2026-09-01 07:10:00     2           LS
57 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
58 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
59 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
60 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
61 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
62 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
63 2026-09-01 07:55:00.000000000 2026-09-01 07:55:00    18           QR
74 2026-09-01 09:47:08.310763842 2026-09-01 09:00:00     2           DL

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 10
  tight vertical jobs: 878
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

================ MONTH SUMMARY =================
Month: 2026-09 | Cutoff: 2026-07-01
Scenario 1:
  PeakAmb=14 | PeakMini=2
Scenario 2:
  PeakAmb=12 | PeakMini=5
SLA:
  All=0.9366 | Arr=0.9486 | Dep=0.9247
SLA diagnostics:
  allowed_breaches=361 | actual_breaches=1143 | sla_percent=93.66% | sla_floor_slack=782.00
  WARNING: hard SLA floor relaxed by slack on 782.00 jobs
================================================


Running S26 2026-10 | cutoff=2026-07-01
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11490
Airlines (sample): ['AF' 'LH' 'U2' 'FR' 'KL' 'BA' 'AA' 'DY' 'EI' 'PC']
Countries (sample): ['FRANCE' 'GERMANY' 'GREAT BRITAIN' 'POLAND' 'NETHERLANDS'
 'UNITED STATES OF AMERICA' 'NORWAY' 'IRISH REPUBLIC' 'TURKEY' 'DENMARK']

Pax describe:
count    11490.000000
mean       149.146649
std         54.677870
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline               CountryName         Sector dir    Pax
0       AF                    FRANCE  International   D  138.0
1       LH                   GERMANY  International   D  148.0
2       U2             GREAT BRITAIN       Domestic   D  175.0
3       FR                    POLAND  International   D  185.0
4       KL               NETHERLANDS  International   D  186.0
5       BA             GREAT BRITAIN       Domestic   D  101.0
6       AA  UNITED STATES OF AMERICA  International   D  285.0
7       DY                    NORWAY  International   D  178.0
8       EI            IRISH REPUBLIC            CTA   D   67.0
9       PC                    TURKEY  International   D  239.0
10      EC                    FRANCE  International   D  229.0
11      BA             GREAT BRITAIN       Domestic   D  180.0
12      D8                   DENMARK  International   D  133.0
13      BA             GREAT BRITAIN       Domestic   D  171.0
14      FR                   GERMANY  International   D  185.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,762 / 11,490 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
10       EC       FRANCE  229.0
19       EC        ITALY  138.0
82       DS  SWITZERLAND  131.0
84       EC  NETHERLANDS  185.0
124      RK        MALTA  189.0
213      EC        ITALY  152.0
217      EC        ITALY  120.0
237      EC        ITALY  138.0
253      EC        SPAIN  149.0
285      EC       FRANCE  147.0
303      DS  SWITZERLAND  107.0
340      LG   LUXEMBOURG  124.0
388      EC        ITALY  161.0
430      EC        SPAIN  143.0
435      EC       FRANCE  180.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17762.963860704513
Total PRMs after rounding: 18036

Raw PRM demand distribution (prm_raw):
count    11490.000000
mean         1.545950
std          1.277379
min          0.000000
25%          0.765722
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
883       QR       QATAR  311.0   0.026728  8.312373           8
37        QR       QATAR  311.0   0.026728  8.312373           8
1368      QR       QATAR  311.0   0.026728  8.312373           8
2208      QR       QATAR  311.0   0.026728  8.312373           8
2006      QR       QATAR  311.0   0.026728  8.312373           8
1653      QR       QATAR  311.0   0.026728  8.312373           8
1453      QR       QATAR  311.0   0.026728  8.312373           8
1919      QR       QATAR  311.0   0.026728  8.312373           8
1757      QR       QATAR  311.0   0.026728  8.312373           8
1836      QR       QATAR  311.0   0.026728  8.312373           8
3083      QR       QATAR  311.0   0.026728  8.312373           8
2978      QR       QATAR  311.0   0.026728  8.312373           8
3246      QR       QATAR  311.0   0.026728  8.312373           8
2588      QR       QATAR  311.0   0.026728  8.312373           8
2692      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=138.0 | Pen=0.00755 | Pax*Pen=1.042 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=148.0 | Pen=0.00569 | Pax*Pen=0.842 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=175.0 | Pen=0.00918 | Pax*Pen=1.606 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=185.0 | Pen=0.00313 | Pax*Pen=0.579 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=186.0 | Pen=0.00831 | Pax*Pen=1.545 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=101.0 | Pen=0.00962 | Pax*Pen=0.971 | PRMs=1
[DEBUG flight] Airline=AA | Country=UNITED STATES OF AMERICA | Pax=285.0 | Pen=0.01552 | Pax*Pen=4.423 | PRMs=4
[DEBUG flight] Airline=DY | Country=NORWAY | Pax=178.0 | Pen=0.00440 | Pax*Pen=0.783 | PRMs=1
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=67.0 | Pen=0.01035 | Pax*Pen=0.693 | PRMs=1
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=239.0 | Pen=0.00852 | Pax*Pen=2.036 | PRMs=2
[DEBUG flight] Airline=EC | Country=FRANCE | Pax=229.0 | Pen=0.01000 | Pax*Pen=2.290 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=180.0 | Pen=0.00962 | Pax*Pen=1.731 | PRMs=2
[DEBUG flight] Airline=D8 | Country=DENMARK | Pax=133.0 | Pen=0.00531 | Pax*Pen=0.707 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=171.0 | Pen=0.00962 | Pax*Pen=1.645 | PRMs=2
[DEBUG flight] Airline=FR | Country=GERMANY | Pax=185.0 | Pen=0.00282 | Pax*Pen=0.521 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18036
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9440
WCHS     7448
WCHC      997
OTHER     151
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-10-01 → 2026-11-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11490
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LM' 'RK' 'QR' 'AY']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'GREECE' 'SPAIN' 'POLAND' 'MOROCCO']

Pax describe:
count    11490.000000
mean       149.146649
std         54.677870
min          0.000000
25%        123.000000
50%        163.000000
75%        183.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  155.0
1       AF         FRANCE  International   D   99.0
2       FR         LATVIA  International   D  184.0
3       KL    NETHERLANDS  International   D  122.0
4       BA  GREAT BRITAIN       Domestic   D  116.0
5       U2       PORTUGAL  International   D  158.0
6       U2          ITALY  International   D  138.0
7       LS         GREECE  International   D  186.0
8       U2  GREAT BRITAIN       Domestic   D  104.0
9       U2         FRANCE  International   D  191.0
10      FR          ITALY  International   D  180.0
11      LM  GREAT BRITAIN       Domestic   D    0.0
12      LS          SPAIN  International   D  219.0
13      BA  GREAT BRITAIN       Domestic   D   62.0
14      FR         FRANCE  International   D   90.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 10,762 / 11,490 (93.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
5       EA  IRISH REPUBLIC          112
8       EC           ITALY          112
1       CJ   GREAT BRITAIN           88
6       EC          FRANCE           82
10      EC           SPAIN           72
9       EC     NETHERLANDS           62
4       EA   GREAT BRITAIN           54
3       DS     SWITZERLAND           54
12      LG      LUXEMBOURG           18
15      RK           MALTA           16
18      U2        SLOVENIA           14
11      IB           SPAIN           14
0       BA           ITALY            8
16      RK         ROMANIA            8
7       EC         GERMANY            4

Example missing keys:
    Airline  CountryName    Pax
38       EC        ITALY  156.0
43       DS  SWITZERLAND   95.0
100      EC        ITALY  102.0
121      EC       FRANCE  174.0
148      RK        MALTA  172.0
169      IB        SPAIN  151.0
177      DS  SWITZERLAND   74.0
182      EC       FRANCE  174.0
186      EC        SPAIN  156.0
194      EC        SPAIN  139.0
241      EC       FRANCE  147.0
254      EC        ITALY  138.0
263      EC        ITALY  120.0
301      EC       FRANCE  229.0
310      EC        ITALY  138.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17762.963860704513
Total PRMs after rounding: 18036

Raw PRM demand distribution (prm_raw):
count    11490.000000
mean         1.545950
std          1.277379
min          0.000000
25%          0.765722
50%          1.211466
75%          1.709124
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
3162      QR       QATAR  311.0   0.026728  8.312373           8
3535      QR       QATAR  311.0   0.026728  8.312373           8
8952      QR       QATAR  311.0   0.026728  8.312373           8
3246      QR       QATAR  311.0   0.026728  8.312373           8
3083      QR       QATAR  311.0   0.026728  8.312373           8
1368      QR       QATAR  311.0   0.026728  8.312373           8
1453      QR       QATAR  311.0   0.026728  8.312373           8
683       QR       QATAR  311.0   0.026728  8.312373           8
2978      QR       QATAR  311.0   0.026728  8.312373           8
1076      QR       QATAR  311.0   0.026728  8.312373           8
3333      QR       QATAR  311.0   0.026728  8.312373           8
2208      QR       QATAR  311.0   0.026728  8.312373           8
4485      QR       QATAR  311.0   0.026728  8.312373           8
328       QR       QATAR  311.0   0.026728  8.312373           8
5429      QR       QATAR  311.0   0.026728  8.312373           8
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=155.0 | Pen=0.00872 | Pax*Pen=1.351 | PRMs=1
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=99.0 | Pen=0.00755 | Pax*Pen=0.747 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=184.0 | Pen=0.00414 | Pax*Pen=0.761 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=122.0 | Pen=0.00831 | Pax*Pen=1.013 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=116.0 | Pen=0.00962 | Pax*Pen=1.116 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=158.0 | Pen=0.00785 | Pax*Pen=1.240 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=138.0 | Pen=0.00872 | Pax*Pen=1.203 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=186.0 | Pen=0.01748 | Pax*Pen=3.251 | PRMs=3
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=104.0 | Pen=0.00918 | Pax*Pen=0.954 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=191.0 | Pen=0.00839 | Pax*Pen=1.602 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=180.0 | Pen=0.00547 | Pax*Pen=0.984 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=0.0 | Pen=0.01980 | Pax*Pen=0.000 | PRMs=0
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=219.0 | Pen=0.02578 | Pax*Pen=5.646 | PRMs=6
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=62.0 | Pen=0.00962 | Pax*Pen=0.596 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=90.0 | Pen=0.00686 | Pax*Pen=0.618 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18036
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9491
WCHS     7402
WCHC     1002
OTHER     141
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,036   [300.39s]
[2/4] build_jobs…
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
    ✓ build_jobs done | jobs=18,034   [0.37s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.51s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 89}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
EA            D      68
              A      21
dtype: int64

Bucket horizon: start=2026-10-01 00:00:00 end=2026-11-01 05:45:00 buckets=3000
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-10-09 15:00:00 | 60.0 / 210.0
  2026-10-08 09:15:00 | 60.0 / 210.0
  2026-10-09 19:00:00 | 60.0 / 210.0
  2026-10-30 09:30:00 | 60.0 / 210.0
  2026-10-12 08:15:00 | 60.0 / 210.0
  2026-10-12 08:30:00 | 60.0 / 210.0
  2026-10-09 18:45:00 | 60.0 / 210.0
  2026-10-05 20:30:00 | 60.0 / 210.0
  2026-10-05 21:00:00 | 60.0 / 210.0
  2026-10-10 14:30:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 391
  is_spin by dir:
dir
A    391
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.17416258333333332 30.90926585 59.94731263333333
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 6.0

Amb minutes (necessary condition):
  min required (vertical-only): 83194.6
  total available over horizon: 610980.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 23
  min mini minutes required (forced): 397.5
  total mini minutes available: 225000.0

Lift rough check:
  lift jobs: 63
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3094
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_3273_0  U2_3273_2026-10-01 05:45:00   D 2026-10-01 05:30:00
5    S26_3321_0  U2_3321_2026-10-01 06:00:00   D 2026-10-01 05:45:00
10   S26_0301_0  U2_0301_2026-10-01 06:00:00   D 2026-10-01 06:00:00
11   S26_3245_0  U2_3245_2026-10-01 06:15:00   D 2026-10-01 06:15:00
12   S26_3245_1  U2_3245_2026-10-01 06:15:00   D 2026-10-01 06:15:00
21   S26_8750_0  FR_8750_2026-10-01 07:00:00   D 2026-10-01 06:45:00
24   S26_0769_0  LS_0769_2026-10-01 06:45:00   D 2026-10-01 06:45:00
25   S26_0769_1  LS_0769_2026-10-01 06:45:00   D 2026-10-01 06:45:00
26   S26_0769_2  LS_0769_2026-10-01 06:45:00   D 2026-10-01 06:45:00
28   S26_0353_0  LM_0353_2026-10-01 06:45:00   D 2026-10-01 06:45:00
44   S26_0597_0  RK_0597_2026-10-01 07:30:00   D 2026-10-01 07:30:00
56   S26_3264_0  FR_3264_2026-10-01 08:30:00   D 2026-10-01 08:30:00
57   S26_3651_0  EI_3651_2026-10-01 09:30:00   D 2026-10-01 09:15:00
58   S26_3834_0  EC_3834_2026-10-01 09:00:00   D 2026-10-01 09:00:00
59   S26_3834_1  EC_3834_2026-10-01 09:00:00   D 2026-10-01 09:00:00
61   S26_1437_0  BA_1437_2026-10-01 09:00:00   D 2026-10-01 09:00:00
62   S26_1437_1  BA_1437_2026-10-01 09:00:00   D 2026-10-01 09:00:00
66   S26_0214_0  U2_0214_2026-10-01 09:15:00   D 2026-10-01 09:00:00
78   S26_5091_0  FR_5091_2026-10-01 10:00:00   D 2026-10-01 10:00:00
79   S26_5091_1  FR_5091_2026-10-01 10:00:00   D 2026-10-01 10:00:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-10-01 05:43:45.517337850 2026-10-01 05:35:00    25           U2
5  2026-10-01 05:55:45.831412092 2026-10-01 05:55:00     8           U2
10 2026-10-01 06:08:02.537020548 2026-10-01 06:05:00   15B           U2
11 2026-10-01 06:19:00.359190198 2026-10-01 06:10:00    20           U2
12 2026-10-01 06:19:00.359190198 2026-10-01 06:10:00    20           U2
21 2026-10-01 06:56:57.249499710 2026-10-01 06:35:00   16B           FR
24 2026-10-01 06:53:47.427718758 2026-10-01 06:45:00   15A           LS
25 2026-10-01 06:53:47.427718758 2026-10-01 06:45:00   15A           LS
26 2026-10-01 06:53:47.427718758 2026-10-01 06:45:00   15A           LS
28 2026-10-01 06:50:00.000000000 2026-10-01 06:50:00     7           LM
44 2026-10-01 07:30:23.469160092 2026-10-01 07:25:00    24           RK
56 2026-10-01 08:31:11.118795150 2026-10-01 08:15:00   15A           FR
57 2026-10-01 09:28:06.541559814 2026-10-01 08:25:00    20           EI
58 2026-10-01 09:08:18.070829520 2026-10-01 08:25:00   15A           EC
59 2026-10-01 09:08:18.070829520 2026-10-01 08:25:00   15A           EC
61 2026-10-01 09:02:03.064392456 2026-10-01 08:35:00     6           BA
62 2026-10-01 09:02:03.064392456 2026-10-01 08:35:00     6           BA
66 2026-10-01 09:13:50.380405290 2026-10-01 08:55:00   311           U2
78 2026-10-01 10:05:56.714255808 2026-10-01 09:40:00   15A           FR
79 2026-10-01 10:05:56.714255808 2026-10-01 09:40:00   15A           FR


C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:1007: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:787: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

,month,cutoff_used,S1_PeakAmb,S1_PeakMini,S2_PeakAmb,S2_PeakMini,SLA_all,SLA_arr,SLA_dep,allowed_breaches,actual_breaches,sla_percent,sla_floor_slack,S2_status,S2_tc,S2_st
0,2026-07,2026-07-01,14,2,12,5,0.932707,0.945361,0.919987,373,1253,93.270677,880.0,maxtimelimit,maxtimelimit,aborted
1,2026-08,2026-07-01,11,3,13,5,0.936593,0.946250,0.927049,379,1201,93.659258,822.0,maxtimelimit,maxtimelimit,aborted
2,2026-09,2026-07-01,14,2,12,5,0.936609,0.948581,0.924718,361,1143,93.660917,782.0,maxtimelimit,maxtimelimit,aborted
3,2026-10,2026-07-01,11,2,12,5,0.930797,0.937264,0.924370,361,1248,93.079738,887.0,maxtimelimit,maxtimelimit,aborted

In [8]:
if "report" in globals() and "peak_day_report" in report and "hourly" in report["peak_day_report"]:
    hourly = report["peak_day_report"]["hourly"]
    display(hourly)
else:
    print("Hourly table not in memory yet. Run the report cell first (no model rerun needed if r/report already exist).")

Hourly table not in memory yet. Run the report cell first (no model rerun needed if r/report already exist).

In [7]:
print(results_2026)

[{'month': '2026-07', 'cutoff_used': '2026-06-30', 'S1_PeakAmb': 11, 'S1_PeakMini': 3, 'S2_PeakAmb': 12, 'S2_PeakMini': 7, 'SLA_all': np.float64(0.9322421408157964), 'SLA_arr': np.float64(0.9413045732655813), 'SLA_dep': np.float64(0.9231410122891064), 'allowed_breaches': 385, 'actual_breaches': 1304, 'sla_percent': 93.22421408157963, 'sla_floor_slack': 919.0, 'S2_status': 'maxtimelimit', 'S2_tc': 'maxtimelimit', 'S2_st': 'aborted'}, {'month': '2026-08', 'cutoff_used': '2026-06-30', 'S1_PeakAmb': 11, 'S1_PeakMini': 2, 'S2_PeakAmb': 11, 'S2_PeakMini': 7, 'SLA_all': np.float64(0.9360101036678419), 'SLA_arr': np.float64(0.9438154692625119), 'SLA_dep': np.float64(0.928287269681742), 'allowed_breaches': 381, 'actual_breaches': 1216, 'sla_percent': 93.60101036678418, 'sla_floor_slack': 835.0, 'S2_status': 'maxtimelimit', 'S2_tc': 'maxtimelimit', 'S2_st': 'aborted'}, {'month': '2026-09', 'cutoff_used': '2026-06-30', 'S1_PeakAmb': 12, 'S1_PeakMini': 2, 'S2_PeakAmb': None, 'S2_PeakMini': None, 'SLA_all': None, 'SLA_arr': None, 'SLA_dep': None, 'allowed_breaches': None, 'actual_breaches': None, 'sla_percent': None, 'sla_floor_slack': None, 'S2_status': 'maxtimelimit', 'S2_tc': 'maxtimelimit', 'S2_st': 'aborted'}]

In [ ]:
month_start = "2026-10-01"
month_end = "2026-11-01"

if "out_s26_s2" in globals() and out_s26_s2.get("runs"):
    r = out_s26_s2["runs"][0]
else:
    tmp = run_s26_s2_v2_sensitivity(
        start=month_start,
        end=month_end,
        **assumptions["inputs"],
        vertical_cycle_grid=[10],
        solver_name="highs",
        toggles=toggles,
        time_limit_sec=600,
        threads=8,
        mip_rel_gap=0.20,
    )
    r = tmp["runs"][0]

report = build_run_report(r, day_from="s", hour_method="max")
print_run_report(report, show_hours=48)

hourly = report["peak_day_report"]["hourly"].copy()
display(hourly)

hourly.to_csv("S26_peak_day_hourly_need.csv")
print("Saved:", "S26_peak_day_hourly_need.csv")

Run S25 Scenario 1 (baseline)

In [ ]:

out_s1 = run_s25_s1(START_S25, END_S25, toggles=toggles)

report_s1 = build_run_report_s1(out_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s1)

# # 15-min peak day detail:
# report_s1["peak_day_report"]["bucket_level"].to_csv("S1_peak_day_15min.csv")
# report_s1["peak_day_report"]["hourly"].to_csv("S1_peak_day_hourly.csv")

Run S25 Scenario 2 (optimised)

In [ ]:

sens = run_s25_s2_v2_sensitivity(
    start=START_S25,
    end=END_S25,
    vertical_cycle_grid=[10],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)

# Build a comparison table

for r in sens["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY: {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r)

    # attach assumption for printing (not rebuilding anything)
    report["assumptions"] = {
        "vertical_cycle_mins": r["vertical_cycle_mins"]
    }

    print_run_report(report)

Run S26 Scenario 1

In [ ]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

In [ ]:
out_s26_s1 = run_s26_s1(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    toggles=toggles,
)


report_s26_s1 = build_run_report_s1(out_s26_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s26_s1)


# report_s26_s1["peak_day_report"]["bucket_level"].to_csv("S26_S1_peak_day_15min.csv")
# report_s26_s1["peak_day_report"]["hourly"].to_csv("S26_S1_peak_day_hourly.csv"

Run S26 scenario 2

In [ ]:



out_s26_s2 = run_s26_s2_v2_sensitivity(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    vertical_cycle_grid=[15],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)



for r in out_s26_s2["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY (S26): {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r, day_from="s", hour_method="max")
    report["assumptions"] = {"vertical_cycle_mins": r["vertical_cycle_mins"]}
    print_run_report(report)