Imports and dates

In [1]:
import sys
from pathlib import Path
import pandas as pd

# Add repo root to PYTHONPATH
HERE = Path().resolve()
PROJECT_ROOT = HERE.parents[0]   # notebooks → repo root
sys.path.insert(0, str(PROJECT_ROOT))


from prm_opt.run_s25 import run_s25_s1, run_s25_s2_v2_sensitivity, run_month_s25
from prm_opt.run_s26 import run_s26_s1, run_s26_s2_v2_sensitivity, run_month_s26
from prm_opt.build_s26_assumptions import build_s26_assumptions
from prm_opt.outputs import build_run_report, print_run_report, build_run_report_s1, print_run_report_s1
from prm_opt.build_jobs import build_jobs
from prm_opt.ingest_s25 import ingest_s25
from prm_opt.config import PlanningToggles

# -----------------------------
# DATE RANGES
# -----------------------------
START_S25 = "2025-04-01"
END_S25   = "2025-05-01"

START_S26 = "2026-05-19"
END_S26   = "2026-06-01"

Common toggles

In [2]:

toggles = PlanningToggles(
    sla_buffer_mins=0,
    spill_bucket_cap=12,
    standby_dep_vert_mins=10,
    standby_arr_horiz_mins=10,
)

In [ ]:

# 2025 (historical)
months_2025 = pd.date_range("2025-04-01", "2025-05-01", freq="MS")

# 2026 (split logic inside function)
months_2026 = pd.date_range("2026-04-01", "2026-05-01", freq="MS")

In [ ]:

results_2025 = []

for m in months_2025:
    results_2025.append(run_month_s25(m, toggles))

df_2025 = pd.DataFrame(results_2025)

df_2025.to_csv("S25_monthly_outputs_v2.csv", index=False)
df_2025

Running S25 2025-04

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-04-01 → 2025-05-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=12,701   [28.28s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=12,701   [0.37s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.45s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 7}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
FR            D      6
RK            D      1
dtype: int64

Bucket horizon: start=2025-04-01 00:00:00 end=2025-05-01 04:30:00 buckets=2899
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-04-15 12:00:00 | 45.0 / 210.0
  2025-04-15 12:15:00 | 45.0 / 210.0
  2025-04-15 12:30:00 | 45.0 / 210.0
  2025-04-17 14:45:00 | 30.0 / 210.0
  2025-04-29 14:30:00 | 30.0 / 210.0
  2025-04-29 14:45:00 | 30.0 / 210.0
  2025-04-29 15:00:00 | 30.0 / 210.0
  2025-04-29 15:15:00 | 30.0 / 210.0
  2025-04-21 12:00:00 | 30.0 / 210.0
  2025-04-21 12:15:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 107
  is_spin by dir:
dir
A    107
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 33.0 49.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 53080.5
  total available over horizon: 603990.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 19
  min mini minutes required (forced): 304.6
  total mini minutes available: 87100455.0

Lift rough check:
  lift jobs: 45
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 179
Examples (first 20):
      Passenger ID                   flight_key dir                   t  \
j
5         10684489   LS_775_2025-04-01 07:00:00   D 2025-04-01 07:00:00
46        10691644  U2_3241_2025-04-01 09:45:00   D 2025-04-01 09:30:00
139       10695011  FR_6656_2025-04-01 15:15:00   D 2025-04-01 15:15:00
314       10707532   U2_214_2025-04-03 08:45:00   D 2025-04-03 08:45:00
347       10709017   U2_341_2025-04-03 13:30:00   D 2025-04-03 13:30:00
401       10710804   U2_313_2025-04-03 20:00:00   D 2025-04-03 20:00:00
557       10719433   LS_745_2025-04-05 16:00:00   D 2025-04-05 16:00:00
787       10734061  U2_3203_2025-04-06 14:15:00   D 2025-04-06 14:15:00
800       10734529  U2_3243_2025-04-06 16:15:00   D 2025-04-06 16:15:00
815       10735509   U2_335_2025-04-06 19:15:00   D 2025-04-06 19:15:00
846       10735976   FR_479_2025-04-06 16:45:00   D 2025-04-06 16:45:00
886       10740779   U2_315_2025-04-07 10:00:00   D 2025-04-07 10:00:00
940       10742588  U2_3201_2025-04-07 15:15:00   D 2025-04-07 15:15:00
978       10743954   RK_179_2025-04-07 15:15:00   D 2025-04-07 15:15:00
982       10744091   U2_335_2025-04-07 20:30:00   D 2025-04-07 20:30:00
983       10744093   U2_335_2025-04-07 20:45:00   D 2025-04-07 20:30:00
1196      10758563   LS_717_2025-04-10 06:00:00   D 2025-04-10 06:00:00
1203      10758916   LS_775_2025-04-10 07:00:00   D 2025-04-10 07:00:00
1204      10758917   LS_775_2025-04-10 07:00:00   D 2025-04-10 07:00:00
1267      10760524  U2_3223_2025-04-09 17:15:00   D 2025-04-09 17:15:00

      hard_deadline_time      sla_start_time Stand Airline Code
j
5    2025-04-01 07:10:00 2025-04-01 07:10:00    10           LS
46   2025-04-01 09:40:08 2025-04-01 09:40:00    24           U2
139  2025-04-01 15:20:00 2025-04-01 15:20:00   15B           FR
314  2025-04-03 08:50:00 2025-04-03 08:50:00     8           U2
347  2025-04-03 13:35:00 2025-04-03 13:35:00     3           U2
401  2025-04-03 20:00:48 2025-04-03 19:10:00    22           U2
557  2025-04-05 16:10:00 2025-04-05 16:10:00    10           LS
787  2025-04-06 14:25:00 2025-04-06 14:25:00    22           U2
800  2025-04-06 16:20:00 2025-04-06 16:20:00    22           U2
815  2025-04-06 19:20:13 2025-04-06 19:15:00   15B           U2
846  2025-04-06 16:50:00 2025-04-06 16:50:00   15B           FR
886  2025-04-07 10:10:00 2025-04-07 10:10:00    20           U2
940  2025-04-07 15:25:00 2025-04-07 15:25:00    24           U2
978  2025-04-07 15:17:38 2025-04-07 15:05:00   16A           RK
982  2025-04-07 20:39:27 2025-04-07 19:30:00    10           U2
983  2025-04-07 20:42:27 2025-04-07 19:30:00    10           U2
1196 2025-04-10 06:05:00 2025-04-10 06:05:00    10           LS
1203 2025-04-10 07:10:00 2025-04-10 07:10:00   102           LS
1204 2025-04-10 07:10:00 2025-04-10 07:10:00   102           LS
1267 2025-04-09 17:17:56 2025-04-09 16:15:00    11           U2

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 0

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 29
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 49
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 2

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.24s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,899   [0.02s]
    ✓ sets built | J=12,701 | F=7,608   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.20s]
    ✓ JB set built | JB=153,497   [0.92s]
    ✓ FB set built | FB=85,174   [0.34s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=38,103 | JB=153,497 | A=153,497 | U=460,491 | k=1,618,306 | V=85,174 | Z=85,174 | W=85,174   [8.73s]
    ✓ objective created   [26.46s]
    ✓ constraints: U linearisation (JB x M)   [13.26s]
    ✓ constraints: passenger timing + SLA   [1.10s]
    ✓ constraints: eligibility   [0.26s]
    ✓ constraints: vertical visit   [74.03s]
    ✓ constraints: standby indicators   [19.21s]
    ✓ constraints: per-flight capacity (seat/wc)   [48.88s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [12.33s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [163.85s]
    ✓ constraints: staff   [19.00s]
    ✓ constraints: LiftCap   [0.13s]
    ✓ build_pyomo_model complete | total=389.74s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 3293487 rows; 2888013 cols; 20249118 nonzeros; 2888013 integer variables (1261010 binary)
Coefficient ranges:
  Matrix  [1e-01, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
2389417 rows, 2440050 cols, 14909877 nonzeros 12s
1966466 rows, 2168832 cols, 12280104 nonzeros 88s
Presolve reductions: rows 1966466(-1327021); columns 2168832(-719181); nonzeros 12280104(-7969014)

Solving MIP model with:
   1966466 rows
   2168832 cols (2157882 binary, 10950 integer, 0 implied int., 0 continuous, 0 domain fixed)
   12280104 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            496833746.7443     Large        0      0      0         0   255.9s
         0       0         0   0.00%   348000968       496833746.7443    29.96%        0      0      0         0   265.5s
         0       0         0   0.00%   350189419.4449  496833746.7443    29.52%        0      0      5    242123   333.2s
         0       0         0   0.00%   350193082.3255  496833746.7443    29.52%    15759   7767      5    265188   498.2s
         0       0         0   0.00%   350193082.3255  496833746.7443    29.52%    25320  15455      5    265188   617.6s

Solving report
  Status            Time limit reached
  Primal bound      496833746.744
  Dual bound        350193082.325
  Gap               29.52% (tolerance: 20%)
  P-D integral      104.211061203
  Solution status   feasible
                    496833746.744 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            617.62
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0
  LP iterations     265188
                    0 (strong br.)
                    23065 (separation)
                    0 (heuristics)
WARNING: Loading a SolverResults object with an 'aborted' status, but
containing a solution

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-05

Unmatched passenger rows after merge (missing Chocks DT): 634
Unique unmatched flight keys: 386

Unmatched key reasons:
reason
no_flight_candidate               377
exact_match_should_have_joined      9
Name: count, dtype: int64

Dropped 618 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
4592      11148662          1460           BA 2025-05-02 00:01:00

          Job Start Time  sla_limit           Chocks DT
4592 2025-05-02 23:51:37         20 2025-05-02 00:01:00

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-05-01 → 2025-06-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 634
Unique unmatched flight keys: 386

Unmatched key reasons:
reason
no_flight_candidate               377
exact_match_should_have_joined      9
Name: count, dtype: int64

Dropped 618 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=17,399   [21.45s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
4592      11148662          1460           BA 2025-05-02 00:01:00

          Job Start Time  sla_limit           Chocks DT
4592 2025-05-02 23:51:37         20 2025-05-02 00:01:00
    ✓ build_jobs done | jobs=17,398   [0.27s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.36s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 16}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
FR            A      5
EI            D      3
U2            D      2
UA            D      2
B6            D      1
BA            D      1
PC            D      1
KL            D      1
dtype: int64

Bucket horizon: start=2025-05-01 00:30:00 end=2025-06-01 04:45:00 buckets=2994
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-05-08 14:30:00 | 45.0 / 210.0
  2025-05-08 14:45:00 | 45.0 / 210.0
  2025-05-31 18:45:00 | 45.0 / 210.0
  2025-05-31 19:00:00 | 45.0 / 210.0
  2025-05-08 14:15:00 | 30.0 / 210.0
  2025-05-08 15:00:00 | 30.0 / 210.0
  2025-05-28 12:30:00 | 30.0 / 210.0
  2025-05-28 12:45:00 | 30.0 / 210.0
  2025-05-15 18:00:00 | 30.0 / 210.0
  2025-05-15 18:15:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 107
  is_spin by dir:
dir
A    107
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 36.0 49.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 75039.9
  total available over horizon: 624120.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 16
  min mini minutes required (forced): 334.5
  total mini minutes available: 89954730.0

Lift rough check:
  lift jobs: 68
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 280
Examples (first 20):
      Passenger ID                   flight_key dir                   t  \
j
68        10967013   LS_711_2025-05-01 15:15:00   D 2025-05-01 15:15:00
73        10967056   LS_727_2025-05-01 16:00:00   D 2025-05-01 16:00:00
222       10976166   FR_813_2025-05-01 14:45:00   D 2025-05-01 14:45:00
247       10976886  RK_5091_2025-05-01 16:30:00   D 2025-05-01 16:30:00
398       10986166   LS_711_2025-05-03 14:45:00   D 2025-05-03 14:45:00
400       10986169   LS_711_2025-05-03 14:45:00   D 2025-05-03 14:45:00
401       10986173   LS_711_2025-05-03 14:45:00   D 2025-05-03 14:45:00
402       10986174   LS_711_2025-05-03 14:45:00   D 2025-05-03 14:45:00
404       10986249  FR_3740_2025-05-02 15:00:00   D 2025-05-02 15:00:00
455       10987979  FR_1652_2025-05-02 19:00:00   D 2025-05-02 19:00:00
565       10994389  U2_3225_2025-05-03 16:45:00   D 2025-05-03 16:45:00
639       10997433  U2_3329_2025-05-03 16:45:00   D 2025-05-03 16:45:00
798       11008152  FR_3646_2025-05-04 20:30:00   D 2025-05-04 20:15:00
962       11016458   RK_179_2025-05-05 15:15:00   D 2025-05-05 15:00:00
997       11017737  FR_1051_2025-05-05 17:45:00   D 2025-05-05 17:45:00
1088      11025589   U2_319_2025-05-02 20:00:00   D 2025-05-02 19:45:00
1116      11026637   FR_813_2025-05-06 11:00:00   D 2025-05-06 11:00:00
1695      11054771  U2_3291_2025-05-06 11:30:00   D 2025-05-06 11:15:00
1732      11058741   LS_717_2025-05-10 06:15:00   D 2025-05-10 06:15:00
1753      11059208   LS_723_2025-05-10 07:15:00   D 2025-05-10 07:15:00

      hard_deadline_time      sla_start_time Stand Airline Code
j
68   2025-05-01 15:25:00 2025-05-01 15:25:00   15A           LS
73   2025-05-01 16:04:31 2025-05-01 15:35:00     3           LS
222  2025-05-01 14:47:56 2025-05-01 14:25:00   16B           FR
247  2025-05-01 16:36:42 2025-05-01 16:25:00   15B           RK
398  2025-05-03 14:53:18 2025-05-03 14:50:00     2           LS
400  2025-05-03 14:50:00 2025-05-03 14:50:00     2           LS
401  2025-05-03 14:50:00 2025-05-03 14:50:00     2           LS
402  2025-05-03 14:53:23 2025-05-03 14:50:00     2           LS
404  2025-05-02 15:05:00 2025-05-02 15:05:00    20           FR
455  2025-05-02 19:10:00 2025-05-02 19:10:00    10           FR
565  2025-05-03 16:55:00 2025-05-03 16:55:00    20           U2
639  2025-05-03 16:55:00 2025-05-03 16:55:00    1B           U2
798  2025-05-04 20:27:02 2025-05-04 20:10:00   15A           FR
962  2025-05-05 15:13:25 2025-05-05 15:05:00   15B           RK
997  2025-05-05 17:50:00 2025-05-05 17:50:00   15A           FR
1088 2025-05-02 19:58:13 2025-05-02 19:55:00   15B           U2
1116 2025-05-06 11:05:00 2025-05-06 11:05:00   15A           FR
1695 2025-05-06 11:25:13 2025-05-06 10:45:00    22           U2
1732 2025-05-10 06:25:00 2025-05-10 06:25:00   104           LS
1753 2025-05-10 07:20:00 2025-05-10 07:20:00   100           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 60
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 59
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 3

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.18s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,994   [0.01s]
    ✓ sets built | J=17,398 | F=9,585   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [0.96s]
    ✓ JB set built | JB=207,905   [0.65s]
    ✓ FB set built | FB=104,662   [0.16s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=52,194 | JB=207,905 | A=207,905 | U=623,715 | k=1,988,578 | V=104,662 | Z=104,662 | W=104,662   [3.91s]
    ✓ objective created   [18.82s]
    ✓ constraints: U linearisation (JB x M)   [22.04s]
    ✓ constraints: passenger timing + SLA   [1.74s]
    ✓ constraints: eligibility   [0.36s]
    ✓ constraints: vertical visit   [55.39s]
    ✓ constraints: standby indicators   [11.74s]
    ✓ constraints: per-flight capacity (seat/wc)   [31.38s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [11.56s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [156.96s]
    ✓ constraints: staff   [16.83s]
    ✓ constraints: LiftCap   [0.14s]
    ✓ build_pyomo_model complete | total=332.65s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4256695 rows; 3631406 cols; 25369108 nonzeros; 3631406 integer variables (1633846 binary)
Coefficient ranges:
  Matrix  [2e-01, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
3178128 rows, 3133250 cols, 19161467 nonzeros 15s
2650641 rows, 2805217 cols, 15859187 nonzeros 109s
Presolve reductions: rows 2650641(-1606054); columns 2805217(-826189); nonzeros 15859187(-9509921)

Solving MIP model with:
   2650641 rows
   2805217 cols (2792093 binary, 13124 integer, 0 implied int., 0 continuous, 0 domain fixed)
   15859187 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            793416698.9863     Large        0      0      0         0   403.1s
         0       0         0   0.00%   616001384       793416698.9863    22.36%        0      0      0         0   417.1s
         0       0         0   0.00%   618925326.3242  793416698.9863    21.99%        0      0      6    324651   548.6s
         0       0         0   0.00%   618925326.3242  793416698.9863    21.99%    21095   7233      6    324651  1028.4s

Solving report
  Status            Time limit reached
  Primal bound      793416698.986
  Dual bound        618925326.324
  Gap               21.99% (tolerance: 20%)
  P-D integral      134.917361617
  Solution status   feasible
                    793416698.986 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            1028.43
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0
  LP iterations     324651
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
WARNING: Loading a SolverResults object with an 'aborted' status, but
containing a solution

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-06

Unmatched passenger rows after merge (missing Chocks DT): 656
Unique unmatched flight keys: 389

Unmatched key reasons:
reason
no_flight_candidate               335
scheduled_dt_mismatch              46
exact_match_should_have_joined      8
Name: count, dtype: int64

Dropped 636 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
     Passenger ID Flight Number Airline Code      sla_start_time  \
794      11390224          6619           RK 2025-06-04 15:15:00

         Job Start Time  sla_limit Chocks DT
794 2025-06-05 11:08:52         20       NaT

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-06-01 → 2025-07-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 656
Unique unmatched flight keys: 389

Unmatched key reasons:
reason
no_flight_candidate               335
scheduled_dt_mismatch              46
exact_match_should_have_joined      8
Name: count, dtype: int64

Dropped 636 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=16,856   [23.18s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
     Passenger ID Flight Number Airline Code      sla_start_time  \
794      11390224          6619           RK 2025-06-04 15:15:00

         Job Start Time  sla_limit Chocks DT
794 2025-06-05 11:08:52         20       NaT
    ✓ build_jobs done | jobs=16,855   [0.30s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.52s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 19}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
DL            D      5
U2            A      5
UA            D      5
XQ            D      2
EI            D      1
LM            D      1
dtype: int64

Bucket horizon: start=2025-06-01 00:15:00 end=2025-07-01 04:45:00 buckets=2899
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-06-11 15:00:00 | 60.0 / 210.0
  2025-06-19 15:00:00 | 45.0 / 210.0
  2025-06-19 15:15:00 | 45.0 / 210.0
  2025-06-19 15:30:00 | 45.0 / 210.0
  2025-06-02 14:30:00 | 45.0 / 210.0
  2025-06-11 14:15:00 | 45.0 / 210.0
  2025-06-11 14:45:00 | 45.0 / 210.0
  2025-06-11 15:15:00 | 45.0 / 210.0
  2025-06-11 15:30:00 | 45.0 / 210.0
  2025-06-05 14:45:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 121
  is_spin by dir:
dir
A    121
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 31.0 48.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 68800.8
  total available over horizon: 603210.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 21
  min mini minutes required (forced): 397.1
  total mini minutes available: 87100455.0

Lift rough check:
  lift jobs: 82
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 381
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
144      11346474   U2_311_2025-06-01 13:45:00   D 2025-06-01 13:45:00
145      11346476   U2_311_2025-06-01 13:45:00   D 2025-06-01 13:45:00
173      11348603   U2_218_2025-06-01 18:00:00   D 2025-06-01 18:00:00
183      11348904  FR_5679_2025-06-01 13:45:00   D 2025-06-01 13:30:00
190      11349359   U2_814_2025-06-01 19:45:00   D 2025-06-01 19:45:00
228      11350335   U2_220_2025-06-02 00:15:00   D 2025-06-02 00:15:00
229      11350337   U2_220_2025-06-02 00:15:00   D 2025-06-02 00:15:00
237      11350486   LS_729_2025-06-02 17:15:00   D 2025-06-02 17:00:00
249      11350988   LS_765_2025-06-02 19:15:00   D 2025-06-02 19:15:00
250      11350989   LS_765_2025-06-02 18:15:00   D 2025-06-02 18:15:00
251      11350990   LS_765_2025-06-02 18:15:00   D 2025-06-02 18:15:00
252      11350991   LS_765_2025-06-02 18:15:00   D 2025-06-02 18:00:00
253      11350992   LS_765_2025-06-02 19:15:00   D 2025-06-02 19:15:00
254      11350993   LS_765_2025-06-02 18:15:00   D 2025-06-02 18:15:00
256      11350995   LS_765_2025-06-02 18:30:00   D 2025-06-02 18:30:00
257      11350998   LS_765_2025-06-02 18:15:00   D 2025-06-02 18:15:00
330      11359333   LS_775_2025-06-03 07:00:00   D 2025-06-03 07:00:00
393      11362906  FR_2969_2025-06-02 15:00:00   D 2025-06-02 14:45:00
413      11363818   LS_739_2025-06-03 15:30:00   D 2025-06-03 15:30:00
430      11364015   LS_781_2025-06-03 16:00:00   D 2025-06-03 16:00:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
144 2025-06-01 13:52:15 2025-06-01 13:45:00   16B           U2
145 2025-06-01 13:52:12 2025-06-01 13:45:00   16B           U2
173 2025-06-01 18:04:56 2025-06-01 17:50:00    17           U2
183 2025-06-01 13:40:56 2025-06-01 13:35:00     2           FR
190 2025-06-01 19:47:28 2025-06-01 19:45:00     7           U2
228 2025-06-02 00:24:31 2025-06-01 22:45:00    17           U2
229 2025-06-02 00:23:44 2025-06-01 22:45:00    17           U2
237 2025-06-02 17:12:12 2025-06-02 16:45:00   15B           LS
249 2025-06-02 19:22:45 2025-06-02 17:20:00    25           LS
250 2025-06-02 18:17:39 2025-06-02 17:20:00    25           LS
251 2025-06-02 18:17:43 2025-06-02 17:20:00    25           LS
252 2025-06-02 18:11:26 2025-06-02 17:20:00    25           LS
253 2025-06-02 19:15:17 2025-06-02 17:20:00    25           LS
254 2025-06-02 18:17:34 2025-06-02 17:20:00    25           LS
256 2025-06-02 18:30:50 2025-06-02 17:20:00    25           LS
257 2025-06-02 18:17:13 2025-06-02 17:20:00    25           LS
330 2025-06-03 07:10:00 2025-06-03 07:10:00    11           LS
393 2025-06-02 14:55:46 2025-06-02 14:05:00   16B           FR
413 2025-06-03 15:35:00 2025-06-03 15:35:00   16B           LS
430 2025-06-03 16:02:37 2025-06-03 16:00:00   102           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 80
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 72
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 2

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.26s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,899   [0.02s]
    ✓ sets built | J=16,855 | F=9,511   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.67s]
    ✓ JB set built | JB=203,356   [1.10s]
    ✓ FB set built | FB=105,029   [0.16s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=50,565 | JB=203,356 | A=203,356 | U=610,068 | k=1,995,551 | V=105,029 | Z=105,029 | W=105,029   [5.32s]
    ✓ objective created   [15.81s]
    ✓ constraints: U linearisation (JB x M)   [38.57s]
    ✓ constraints: passenger timing + SLA   [0.70s]
    ✓ constraints: eligibility   [0.22s]
    ✓ constraints: vertical visit   [54.34s]
    ✓ constraints: standby indicators   [10.63s]
    ✓ constraints: per-flight capacity (seat/wc)   [28.28s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [10.30s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [147.21s]
    ✓ constraints: staff   [16.50s]
    ✓ constraints: LiftCap   [0.16s]
    ✓ build_pyomo_model complete | total=330.99s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4206925 rows; 3620295 cols; 25540506 nonzeros; 3620295 integer variables (1616047 binary)
Coefficient ranges:
  Matrix  [2e-02, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
3128916 rows, 3127880 cols, 19372802 nonzeros 22s
2603110 rows, 2797339 cols, 16068698 nonzeros 114s
Presolve reductions: rows 2603110(-1603815); columns 2797339(-822956); nonzeros 16068698(-9471808)

Solving MIP model with:
   2603110 rows
   2797339 cols (2784987 binary, 12352 integer, 0 implied int., 0 continuous, 0 domain fixed)
   16068698 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            955371412.7717     Large        0      0      0         0   423.4s
         0       0         0   0.00%   765001338       955371412.7717    19.93%        0      0      0         0   438.1s
         1       0         1 100.00%   767844576.5446  955371412.7717    19.63%        0      0      0    314954   553.0s

Solving report
  Status            Optimal
  Primal bound      955371412.772
  Dual bound        767844576.545
  Gap               19.63% (tolerance: 20%)
  P-D integral      22.892121968
  Solution status   feasible
                    955371412.772 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            553.03
  Max sub-MIP depth 0
  Nodes             1
  Repair LPs        0
  LP iterations     314954
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-07

Unmatched passenger rows after merge (missing Chocks DT): 724
Unique unmatched flight keys: 458

Unmatched key reasons:
reason
no_flight_candidate               445
exact_match_should_have_joined     10
scheduled_dt_mismatch               3
Name: count, dtype: int64

Dropped 702 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
6637      12013252           312           U2 2025-07-21 19:16:42

          Job Start Time  sla_limit           Chocks DT
6637 2025-07-22 00:58:27         20 2025-07-21 19:16:42

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-07-01 → 2025-08-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 724
Unique unmatched flight keys: 458

Unmatched key reasons:
reason
no_flight_candidate               445
exact_match_should_have_joined     10
scheduled_dt_mismatch               3
Name: count, dtype: int64

Dropped 702 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=16,288   [23.57s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
6637      12013252           312           U2 2025-07-21 19:16:42

          Job Start Time  sla_limit           Chocks DT
6637 2025-07-22 00:58:27         20 2025-07-21 19:16:42
    ✓ build_jobs done | jobs=16,287   [0.25s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.33s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 22}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
U2            D      8
EI            D      6
WS            D      3
LM            D      3
B6            D      1
WK            D      1
dtype: int64

Bucket horizon: start=2025-06-30 23:45:00 end=2025-08-01 05:15:00 buckets=2999
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-07-08 13:30:00 | 45.0 / 210.0
  2025-07-08 13:45:00 | 45.0 / 210.0
  2025-07-04 16:30:00 | 45.0 / 210.0
  2025-07-04 16:45:00 | 45.0 / 210.0
  2025-07-04 17:00:00 | 45.0 / 210.0
  2025-07-05 16:30:00 | 45.0 / 210.0
  2025-07-27 16:30:00 | 45.0 / 210.0
  2025-07-27 16:45:00 | 45.0 / 210.0
  2025-07-07 17:30:00 | 45.0 / 210.0
  2025-07-07 17:45:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 138
  is_spin by dir:
dir
A    138
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 35.0 47.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 61317.6
  total available over horizon: 623730.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 15
  min mini minutes required (forced): 259.3
  total mini minutes available: 90104955.0

Lift rough check:
  lift jobs: 84
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 382
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
30       11739464   LS_739_2025-07-01 15:30:00   D 2025-07-01 15:30:00
83       11748766   LS_769_2025-07-02 07:30:00   D 2025-07-02 07:15:00
84       11748767   LS_769_2025-07-02 07:30:00   D 2025-07-02 07:30:00
134      11752186  FR_5679_2025-07-01 12:30:00   D 2025-07-01 12:30:00
149      11753287   LS_709_2025-07-02 14:30:00   D 2025-07-02 14:30:00
150      11753289   LS_709_2025-07-02 14:30:00   D 2025-07-02 14:15:00
152      11753294   LS_709_2025-07-02 14:15:00   D 2025-07-02 14:15:00
166      11753700  FR_6695_2025-07-01 16:30:00   D 2025-07-01 16:15:00
167      11753701  FR_6695_2025-07-01 16:30:00   D 2025-07-01 16:15:00
169      11753773   LS_747_2025-07-02 16:30:00   D 2025-07-02 16:15:00
173      11753842   LS_745_2025-07-02 15:45:00   D 2025-07-02 15:45:00
181      11754872  FR_1064_2025-07-01 18:00:00   D 2025-07-01 18:00:00
347      11767131   LS_711_2025-07-03 15:30:00   D 2025-07-03 15:15:00
357      11767293   RK_861_2025-07-02 16:45:00   D 2025-07-02 16:45:00
358      11767294   RK_861_2025-07-02 16:45:00   D 2025-07-02 16:45:00
359      11767295   RK_861_2025-07-02 16:45:00   D 2025-07-02 16:45:00
368      11767353   LS_713_2025-07-03 15:45:00   D 2025-07-03 15:45:00
438      11776296   U2_341_2025-07-03 14:15:00   D 2025-07-03 14:00:00
455      11776499  U2_3203_2025-07-03 14:00:00   D 2025-07-03 14:00:00
456      11776502  U2_3203_2025-07-03 14:00:00   D 2025-07-03 14:00:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
30  2025-07-01 15:35:00 2025-07-01 15:35:00    11           LS
83  2025-07-02 07:29:26 2025-07-02 06:45:00    24           LS
84  2025-07-02 07:36:50 2025-07-02 06:45:00    24           LS
134 2025-07-01 12:40:00 2025-07-01 12:40:00   16A           FR
149 2025-07-02 14:35:55 2025-07-02 14:25:00     2           LS
150 2025-07-02 14:28:56 2025-07-02 14:25:00     2           LS
152 2025-07-02 14:25:00 2025-07-02 14:25:00     2           LS
166 2025-07-01 16:29:29 2025-07-01 15:25:00    1B           FR
167 2025-07-01 16:29:32 2025-07-01 15:25:00    1B           FR
169 2025-07-02 16:26:24 2025-07-02 15:30:00    10           LS
173 2025-07-02 15:45:20 2025-07-02 15:40:00   15B           LS
181 2025-07-01 18:09:16 2025-07-01 17:50:00    1B           FR
347 2025-07-03 15:26:39 2025-07-03 15:25:00     1           LS
357 2025-07-02 16:54:31 2025-07-02 16:05:00   15A           RK
358 2025-07-02 16:54:35 2025-07-02 16:05:00   15A           RK
359 2025-07-02 16:51:28 2025-07-02 16:05:00   15A           RK
368 2025-07-03 15:55:00 2025-07-03 15:55:00     3           LS
438 2025-07-03 14:14:15 2025-07-03 13:35:00     1           U2
455 2025-07-03 14:01:19 2025-07-03 13:55:00    1B           U2
456 2025-07-03 14:01:24 2025-07-03 13:55:00    1B           U2

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 0

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 79
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 68
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 3

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.18s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,999   [0.02s]
    ✓ sets built | J=16,287 | F=9,532   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [0.92s]
    ✓ JB set built | JB=199,477   [0.73s]
    ✓ FB set built | FB=107,378   [0.17s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=48,861 | JB=199,477 | A=199,477 | U=598,431 | k=2,040,182 | V=107,378 | Z=107,378 | W=107,378   [4.18s]
    ✓ objective created   [16.29s]
    ✓ constraints: U linearisation (JB x M)   [53.48s]
    ✓ constraints: passenger timing + SLA   [0.64s]
    ✓ constraints: eligibility   [0.18s]
    ✓ constraints: vertical visit   [55.01s]
    ✓ constraints: standby indicators   [12.93s]
    ✓ constraints: per-flight capacity (seat/wc)   [28.81s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [11.36s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [154.13s]
    ✓ constraints: staff   [16.62s]
    ✓ constraints: LiftCap   [0.17s]
    ✓ build_pyomo_model complete | total=355.64s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4202066 rows; 3663881 cols; 25703831 nonzeros; 3663881 integer variables (1614702 binary)
Coefficient ranges:
  Matrix  [3e-02, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
3080077 rows, 3142134 cols, 19257075 nonzeros 15s
2548493 rows, 2801993 cols, 16005855 nonzeros 109s
Presolve reductions: rows 2548493(-1653573); columns 2801993(-861888); nonzeros 16005855(-9697976)

Solving MIP model with:
   2548493 rows
   2801993 cols (2790197 binary, 11796 integer, 0 implied int., 0 continuous, 0 domain fixed)
   16005855 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            825214485.3881     Large        0      0      0         0   412.0s
         0       0         0   0.00%   603001366       825214485.3881    26.93%        0      0      0         0   425.3s
         0       0         0   0.00%   605797547.8685  825214485.3881    26.59%        0      0     15    307618   539.2s
         0       0         0   0.00%   605797547.8685  825214485.3881    26.59%    20583  10178     15    307618   751.4s

Solving report
  Status            Time limit reached
  Primal bound      825214485.388
  Dual bound        605797547.868
  Gap               26.59% (tolerance: 20%)
  P-D integral      87.0773190001
  Solution status   feasible
                    825214485.388 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            751.41
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0
  LP iterations     307618
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
WARNING: Loading a SolverResults object with an 'aborted' status, but
containing a solution

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-08

Unmatched passenger rows after merge (missing Chocks DT): 629
Unique unmatched flight keys: 398

Unmatched key reasons:
reason
no_flight_candidate               373
scheduled_dt_mismatch              14
exact_match_should_have_joined     11
Name: count, dtype: int64

Dropped 613 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
6066      12405117          3252           EI 2025-08-06 11:12:05

          Job Start Time  sla_limit           Chocks DT
6066 2025-08-06 22:05:14         20 2025-08-06 11:12:05

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-08-01 → 2025-09-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 629
Unique unmatched flight keys: 398

Unmatched key reasons:
reason
no_flight_candidate               373
scheduled_dt_mismatch              14
exact_match_should_have_joined     11
Name: count, dtype: int64

Dropped 613 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=15,866   [23.00s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 1 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
6066      12405117          3252           EI 2025-08-06 11:12:05

          Job Start Time  sla_limit           Chocks DT
6066 2025-08-06 22:05:14         20 2025-08-06 11:12:05
    ✓ build_jobs done | jobs=15,865   [0.25s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.39s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 16}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
LH            D      4
UA            D      4
AA            D      2
EI            D      2
DL            D      2
D8            D      1
WS            D      1
dtype: int64

Bucket horizon: start=2025-07-31 23:45:00 end=2025-09-01 05:00:00 buckets=2998
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-08-03 15:15:00 | 45.0 / 210.0
  2025-08-22 17:00:00 | 45.0 / 210.0
  2025-08-05 14:15:00 | 45.0 / 210.0
  2025-08-01 16:00:00 | 45.0 / 210.0
  2025-08-01 16:15:00 | 45.0 / 210.0
  2025-08-01 16:30:00 | 45.0 / 210.0
  2025-08-01 16:45:00 | 45.0 / 210.0
  2025-08-25 14:45:00 | 30.0 / 210.0
  2025-08-25 15:00:00 | 30.0 / 210.0
  2025-08-25 15:15:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 141
  is_spin by dir:
dir
A    141
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 33.0 47.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 57743.8
  total available over horizon: 623640.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 19
  min mini minutes required (forced): 241.0
  total mini minutes available: 90074910.0

Lift rough check:
  lift jobs: 93
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 349
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
14       12145028   LS_715_2025-08-01 15:45:00   D 2025-08-01 15:30:00
15       12145029   LS_715_2025-08-01 15:45:00   D 2025-08-01 15:30:00
16       12145030   LS_757_2025-08-01 15:15:00   D 2025-08-01 15:15:00
112      12154674  U2_3303_2025-08-01 15:30:00   D 2025-08-01 15:30:00
137      12155724  U2_3313_2025-08-01 18:00:00   D 2025-08-01 18:00:00
186      12157702   FR_813_2025-08-01 16:45:00   D 2025-08-01 16:45:00
188      12157824  FR_5579_2025-08-01 17:30:00   D 2025-08-01 17:30:00
189      12157825  FR_5579_2025-08-01 17:30:00   D 2025-08-01 17:30:00
240      12165431   U2_319_2025-08-02 13:15:00   D 2025-08-02 13:00:00
280      12167502  U2_3225_2025-08-02 17:00:00   D 2025-08-02 17:00:00
411      12178539  U2_3311_2025-08-03 14:45:00   D 2025-08-03 14:45:00
457      12181136   LS_747_2025-08-04 14:45:00   D 2025-08-04 14:45:00
459      12181426   LS_709_2025-08-04 16:15:00   D 2025-08-04 16:00:00
465      12181508   LS_727_2025-08-04 17:00:00   D 2025-08-04 16:45:00
477      12182106   LS_729_2025-08-04 17:30:00   D 2025-08-04 17:15:00
518      12187591  U2_3271_2025-08-04 07:00:00   D 2025-08-04 07:00:00
596      12192005   U2_319_2025-08-04 17:00:00   D 2025-08-04 16:45:00
598      12192009   U2_319_2025-08-04 17:00:00   D 2025-08-04 17:00:00
622      12193317  FR_7322_2025-08-04 13:00:00   D 2025-08-04 12:45:00
630      12193937  FR_1677_2025-08-04 14:15:00   D 2025-08-04 14:15:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
14  2025-08-01 15:44:11 2025-08-01 15:20:00     6           LS
15  2025-08-01 15:44:04 2025-08-01 15:20:00     6           LS
16  2025-08-01 15:20:00 2025-08-01 15:20:00     2           LS
112 2025-08-01 15:40:00 2025-08-01 15:40:00    25           U2
137 2025-08-01 18:01:15 2025-08-01 17:50:00     4           U2
186 2025-08-01 16:50:00 2025-08-01 16:50:00    1B           FR
188 2025-08-01 17:39:22 2025-08-01 17:05:00   15A           FR
189 2025-08-01 17:32:24 2025-08-01 17:05:00   15A           FR
240 2025-08-02 13:11:26 2025-08-02 12:50:00    20           U2
280 2025-08-02 17:02:22 2025-08-02 16:55:00   16A           U2
411 2025-08-03 14:50:25 2025-08-03 14:40:00    22           U2
457 2025-08-04 14:48:39 2025-08-04 14:30:00     4           LS
459 2025-08-04 16:11:30 2025-08-04 15:20:00     1           LS
465 2025-08-04 16:55:17 2025-08-04 15:25:00     2           LS
477 2025-08-04 17:29:51 2025-08-04 16:45:00   16A           LS
518 2025-08-04 07:05:00 2025-08-04 07:05:00     8           U2
596 2025-08-04 16:59:31 2025-08-04 15:35:00   16B           U2
598 2025-08-04 17:00:00 2025-08-04 15:35:00   16B           U2
622 2025-08-04 12:56:04 2025-08-04 12:50:00    20           FR
630 2025-08-04 14:20:53 2025-08-04 13:55:00    22           FR

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 99
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 101
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 4

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.24s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,998   [0.02s]
    ✓ sets built | J=15,865 | F=10,091   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.19s]
    ✓ JB set built | JB=186,857   [0.71s]
    ✓ FB set built | FB=111,240   [0.17s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=47,595 | JB=186,857 | A=186,857 | U=560,571 | k=2,113,560 | V=111,240 | Z=111,240 | W=111,240   [4.35s]
    ✓ objective created   [18.15s]
    ✓ constraints: U linearisation (JB x M)   [51.06s]
    ✓ constraints: passenger timing + SLA   [0.78s]
    ✓ constraints: eligibility   [0.24s]
    ✓ constraints: vertical visit   [67.28s]
    ✓ constraints: standby indicators   [9.30s]
    ✓ constraints: per-flight capacity (seat/wc)   [34.75s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [12.42s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [180.52s]
    ✓ constraints: staff   [23.87s]
    ✓ constraints: LiftCap   [0.23s]
    ✓ build_pyomo_model complete | total=405.04s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4126506 rows; 3712122 cols; 25705490 nonzeros; 3712122 integer variables (1589568 binary)
Coefficient ranges:
  Matrix  [5e-02, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
2953749 rows, 3164407 cols, 18948657 nonzeros 15s
2415340 rows, 2806268 cols, 15801956 nonzeros 104s
Presolve reductions: rows 2415340(-1711166); columns 2806268(-905854); nonzeros 15801956(-9903534)

Solving MIP model with:
   2415340 rows
   2806268 cols (2794922 binary, 11346 integer, 0 implied int., 0 continuous, 0 domain fixed)
   15801956 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            1177310607.79      Large        0      0      0         0   351.9s
         0       0         0   0.00%   945001342       1177310607.79     19.73%        0      0      0         0   364.2s
         1       0         1 100.00%   947815576.4567  1177310607.79     19.49%        0      0      0    305980   451.2s

Solving report
  Status            Optimal
  Primal bound      1177310607.79
  Dual bound        947815576.457
  Gap               19.49% (tolerance: 20%)
  P-D integral      17.1628363949
  Solution status   feasible
                    1177310607.79 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            451.18
  Max sub-MIP depth 0
  Nodes             1
  Repair LPs        0
  LP iterations     305980
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-09

Unmatched passenger rows after merge (missing Chocks DT): 698
Unique unmatched flight keys: 404

Unmatched key reasons:
reason
no_flight_candidate               396
exact_match_should_have_joined      7
scheduled_dt_mismatch               1
Name: count, dtype: int64

Dropped 686 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
18323      13159410           748           LS 2025-09-30 01:35:15
18324      13159411           748           LS 2025-09-30 01:35:15
18327      13159414           748           LS 2025-09-30 01:35:15
18328      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
18323 2025-09-30 04:59:07         20 2025-09-30 01:35:15
18324 2025-09-30 05:00:53         20 2025-09-30 01:35:15
18327 2025-09-30 04:59:15         20 2025-09-30 01:35:15
18328 2025-09-30 04:59:18         20 2025-09-30 01:35:15

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-09-01 → 2025-10-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 698
Unique unmatched flight keys: 404

Unmatched key reasons:
reason
no_flight_candidate               396
exact_match_should_have_joined      7
scheduled_dt_mismatch               1
Name: count, dtype: int64

Dropped 686 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=18,882   [21.29s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
18323      13159410           748           LS 2025-09-30 01:35:15
18324      13159411           748           LS 2025-09-30 01:35:15
18327      13159414           748           LS 2025-09-30 01:35:15
18328      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
18323 2025-09-30 04:59:07         20 2025-09-30 01:35:15
18324 2025-09-30 05:00:53         20 2025-09-30 01:35:15
18327 2025-09-30 04:59:15         20 2025-09-30 01:35:15
18328 2025-09-30 04:59:18         20 2025-09-30 01:35:15
    ✓ build_jobs done | jobs=18,878   [0.29s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.37s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 12}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
LS            D      4
B6            D      2
UA            D      2
U2            D      2
EI            D      1
FR            D      1
dtype: int64

Bucket horizon: start=2025-09-01 00:15:00 end=2025-10-01 05:00:00 buckets=2900
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-09-27 12:15:00 | 60.0 / 210.0
  2025-09-27 12:30:00 | 60.0 / 210.0
  2025-09-12 17:00:00 | 45.0 / 210.0
  2025-09-12 17:15:00 | 45.0 / 210.0
  2025-09-09 12:45:00 | 45.0 / 210.0
  2025-09-30 12:45:00 | 45.0 / 210.0
  2025-09-27 12:00:00 | 45.0 / 210.0
  2025-09-16 16:15:00 | 45.0 / 210.0
  2025-09-16 16:30:00 | 45.0 / 210.0
  2025-09-16 16:45:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 160
  is_spin by dir:
dir
A    160
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 29.0 50.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 65017.8
  total available over horizon: 602640.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 14
  min mini minutes required (forced): 211.7
  total mini minutes available: 87130500.0

Lift rough check:
  lift jobs: 56
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 507
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
33       12545224   LS_747_2025-09-01 15:15:00   D 2025-09-01 15:00:00
34       12545225   LS_747_2025-09-01 14:45:00   D 2025-09-01 14:30:00
37       12545261   LS_727_2025-09-01 15:15:00   D 2025-09-01 15:15:00
38       12545262   LS_727_2025-09-01 15:15:00   D 2025-09-01 15:15:00
39       12545263   LS_727_2025-09-01 15:15:00   D 2025-09-01 15:15:00
119      12553471   U2_305_2025-09-01 14:00:00   D 2025-09-01 14:00:00
120      12553473   U2_305_2025-09-01 14:00:00   D 2025-09-01 14:00:00
124      12553712   LS_723_2025-09-02 07:45:00   D 2025-09-02 07:45:00
130      12554029  U2_3261_2025-09-01 14:15:00   D 2025-09-01 14:00:00
131      12554031  U2_3261_2025-09-01 14:15:00   D 2025-09-01 14:00:00
151      12554303  U2_3303_2025-09-01 14:45:00   D 2025-09-01 14:45:00
162      12554946  U2_3201_2025-09-01 15:30:00   D 2025-09-01 15:15:00
199      12556276  U2_3245_2025-09-01 18:45:00   D 2025-09-01 18:30:00
218      12557298   U2_319_2025-09-01 19:30:00   D 2025-09-01 19:30:00
233      12557583   FR_189_2025-09-01 14:45:00   D 2025-09-01 14:45:00
248      12558080   LS_739_2025-09-02 15:30:00   D 2025-09-02 15:30:00
249      12558081   LS_739_2025-09-02 15:30:00   D 2025-09-02 15:30:00
412      12570440  U2_3273_2025-09-02 16:30:00   D 2025-09-02 16:30:00
436      12571536  FR_7409_2025-09-02 14:00:00   D 2025-09-02 13:45:00
464      12572258  BY_1266_2025-09-02 15:15:00   D 2025-09-02 15:00:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
33  2025-09-01 15:13:07 2025-09-01 14:30:00     2           LS
34  2025-09-01 14:40:34 2025-09-01 14:30:00     2           LS
37  2025-09-01 15:25:00 2025-09-01 15:25:00     4           LS
38  2025-09-01 15:25:00 2025-09-01 15:25:00     4           LS
39  2025-09-01 15:25:00 2025-09-01 15:25:00     4           LS
119 2025-09-01 14:03:05 2025-09-01 13:00:00     6           U2
120 2025-09-01 14:03:10 2025-09-01 13:00:00     6           U2
124 2025-09-02 07:55:00 2025-09-02 07:55:00   102           LS
130 2025-09-01 14:10:40 2025-09-01 13:55:00   15A           U2
131 2025-09-01 14:11:28 2025-09-01 13:55:00   15A           U2
151 2025-09-01 14:45:43 2025-09-01 14:40:00    10           U2
162 2025-09-01 15:29:24 2025-09-01 15:25:00    24           U2
199 2025-09-01 18:42:22 2025-09-01 17:55:00    1B           U2
218 2025-09-01 19:33:29 2025-09-01 19:25:00   15B           U2
233 2025-09-01 14:50:00 2025-09-01 14:50:00   16A           FR
248 2025-09-02 15:38:11 2025-09-02 15:35:00    10           LS
249 2025-09-02 15:38:07 2025-09-02 15:35:00    10           LS
412 2025-09-02 16:40:00 2025-09-02 16:40:00    17           U2
436 2025-09-02 13:57:24 2025-09-02 13:55:00   16A           FR
464 2025-09-02 15:10:13 2025-09-02 15:10:00   15A           BY

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 0

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 121
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 103
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 3

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.21s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,900   [0.02s]
    ✓ sets built | J=18,878 | F=10,990   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.03s]
    ✓ JB set built | JB=217,509   [0.79s]
    ✓ FB set built | FB=117,651   [0.19s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=56,634 | JB=217,509 | A=217,509 | U=652,527 | k=2,235,369 | V=117,651 | Z=117,651 | W=117,651   [3.87s]
    ✓ objective created   [17.01s]
    ✓ constraints: U linearisation (JB x M)   [22.63s]
    ✓ constraints: passenger timing + SLA   [2.78s]
    ✓ constraints: eligibility   [0.19s]
    ✓ constraints: vertical visit   [63.19s]
    ✓ constraints: standby indicators   [9.09s]
    ✓ constraints: per-flight capacity (seat/wc)   [30.03s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [10.88s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [140.31s]
    ✓ constraints: staff   [18.20s]
    ✓ constraints: LiftCap   [0.14s]
    ✓ build_pyomo_model complete | total=320.36s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4588170 rows; 4013174 cols; 27693008 nonzeros; 4013174 integer variables (1769105 binary)
Coefficient ranges:
  Matrix  [6e-02, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
3373367 rows, 3461922 cols, 20768305 nonzeros 16s
2790861 rows, 3084997 cols, 17531910 nonzeros 120s
Presolve reductions: rows 2790861(-1797309); columns 3084997(-928177); nonzeros 17531910(-10161098)

Solving MIP model with:
   2790861 rows
   3084997 cols (3072463 binary, 12534 integer, 0 implied int., 0 continuous, 0 domain fixed)
   17531910 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            1589020434.105     Large        0      0      0         0   418.0s
         0       0         0   0.00%   1403001528      1589020434.105    11.71%        0      0      0         0   432.2s
         1       0         1 100.00%   1406109261.208  1589020434.105    11.51%        0      0      0    353376   535.3s

Solving report
  Status            Optimal
  Primal bound      1589020434.11
  Dual bound        1406109261.21
  Gap               11.51% (tolerance: 20%)
  P-D integral      12.0628688939
  Solution status   feasible
                    1589020434.11 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            535.29
  Max sub-MIP depth 0
  Nodes             1
  Repair LPs        0
  LP iterations     353376
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S25 2025-10

Unmatched passenger rows after merge (missing Chocks DT): 729
Unique unmatched flight keys: 418

Unmatched key reasons:
reason
no_flight_candidate               390
exact_match_should_have_joined     15
scheduled_dt_mismatch              13
Name: count, dtype: int64

Dropped 705 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

[BUILD_JOBS] Dropping 2 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
9978      13357994           770           LS 2025-10-13 15:06:01
9979      13357995           770           LS 2025-10-13 15:06:01

          Job Start Time  sla_limit           Chocks DT
9978 2025-10-13 18:49:24         20 2025-10-13 15:06:01
9979 2025-10-13 18:49:15         20 2025-10-13 15:06:01

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-10-01 → 2025-11-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 729
Unique unmatched flight keys: 418

Unmatched key reasons:
reason
no_flight_candidate               390
exact_match_should_have_joined     15
scheduled_dt_mismatch              13
Name: count, dtype: int64

Dropped 705 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=17,255   [35.63s]
[2/4] build_jobs…

[BUILD_JOBS] Dropping 2 arrival jobs with expired SLA window (max_late_mins=180).
      Passenger ID Flight Number Airline Code      sla_start_time  \
9978      13357994           770           LS 2025-10-13 15:06:01
9979      13357995           770           LS 2025-10-13 15:06:01

          Job Start Time  sla_limit           Chocks DT
9978 2025-10-13 18:49:24         20 2025-10-13 15:06:01
9979 2025-10-13 18:49:15         20 2025-10-13 15:06:01
    ✓ build_jobs done | jobs=17,253   [0.28s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.35s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 24}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
LM            D      7
FR            A      3
EI            D      2
WS            D      2
BA            D      1
AF            D      1
EW            D      1
EI            A      1
D8            D      1
FI            D      1
LH            D      1
              A      1
LM            A      1
U2            D      1
dtype: int64

Bucket horizon: start=2025-10-01 00:00:00 end=2025-11-01 05:00:00 buckets=2997
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-10-03 13:45:00 | 60.0 / 210.0
  2025-10-03 14:00:00 | 60.0 / 210.0
  2025-10-03 14:15:00 | 45.0 / 210.0
  2025-10-27 13:00:00 | 45.0 / 210.0
  2025-10-06 15:00:00 | 30.0 / 210.0
  2025-10-06 15:15:00 | 30.0 / 210.0
  2025-10-06 15:30:00 | 30.0 / 210.0
  2025-10-04 12:15:00 | 30.0 / 210.0
  2025-10-04 12:30:00 | 30.0 / 210.0
  2025-10-04 12:45:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 128
  is_spin by dir:
dir
A    128
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 35.0 48.0 59.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 64310.1
  total available over horizon: 623610.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 8
  min mini minutes required (forced): 108.3
  total mini minutes available: 90044865.0

Lift rough check:
  lift jobs: 73
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 448
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
4        12976740  LS_3921_2025-10-01 06:15:00   D 2025-10-01 06:00:00
11       12977318   LS_769_2025-10-01 07:30:00   D 2025-10-01 07:15:00
36       12982211   LS_797_2025-10-01 14:30:00   D 2025-10-01 14:15:00
37       12982212   LS_797_2025-10-01 14:45:00   D 2025-10-01 14:30:00
57       12982870   LS_747_2025-10-01 16:00:00   D 2025-10-01 15:45:00
58       12982871   LS_747_2025-10-01 15:45:00   D 2025-10-01 15:45:00
59       12982872   LS_747_2025-10-01 16:00:00   D 2025-10-01 15:45:00
60       12982873   LS_747_2025-10-01 16:15:00   D 2025-10-01 16:15:00
61       12982951   LS_745_2025-10-01 17:15:00   D 2025-10-01 17:00:00
62       12982953   LS_815_2025-10-01 15:30:00   D 2025-10-01 15:30:00
135      12994181  U2_3285_2025-10-01 14:30:00   D 2025-10-01 14:30:00
136      12994182  U2_3285_2025-10-01 14:30:00   D 2025-10-01 14:30:00
137      12994185  U2_3285_2025-10-01 14:30:00   D 2025-10-01 14:30:00
141      12994279  FR_6656_2025-10-01 08:45:00   D 2025-10-01 08:45:00
169      12995372  FR_8750_2025-10-01 10:45:00   D 2025-10-01 10:45:00
171      12995374  FR_8750_2025-10-01 10:45:00   D 2025-10-01 10:45:00
172      12995375  FR_8750_2025-10-01 10:45:00   D 2025-10-01 10:45:00
233      12998137   LS_785_2025-10-02 15:45:00   D 2025-10-02 15:30:00
235      12998139   LS_785_2025-10-02 15:45:00   D 2025-10-02 15:30:00
259      12998719   LS_773_2025-10-02 17:00:00   D 2025-10-02 17:00:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
4   2025-10-01 06:13:12 2025-10-01 06:05:00   309           LS
11  2025-10-01 07:29:00 2025-10-01 06:45:00     3           LS
36  2025-10-01 14:27:09 2025-10-01 14:15:00    10           LS
37  2025-10-01 14:40:20 2025-10-01 14:15:00    10           LS
57  2025-10-01 15:59:40 2025-10-01 15:30:00    1A           LS
58  2025-10-01 15:45:11 2025-10-01 15:30:00    1A           LS
59  2025-10-01 15:59:25 2025-10-01 15:30:00    1A           LS
60  2025-10-01 16:17:03 2025-10-01 15:30:00    1A           LS
61  2025-10-01 17:10:47 2025-10-01 15:40:00     4           LS
62  2025-10-01 15:35:00 2025-10-01 15:35:00     2           LS
135 2025-10-01 14:35:10 2025-10-01 13:50:00    22           U2
136 2025-10-01 14:32:15 2025-10-01 13:50:00    22           U2
137 2025-10-01 14:35:07 2025-10-01 13:50:00    22           U2
141 2025-10-01 08:50:00 2025-10-01 08:50:00    25           FR
169 2025-10-01 10:55:00 2025-10-01 10:55:00   104           FR
171 2025-10-01 10:55:00 2025-10-01 10:55:00   104           FR
172 2025-10-01 10:55:00 2025-10-01 10:55:00   104           FR
233 2025-10-02 15:43:49 2025-10-02 15:35:00     4           LS
235 2025-10-02 15:43:46 2025-10-02 15:35:00     4           LS
259 2025-10-02 17:05:32 2025-10-02 16:45:00     1           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 95
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 92
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 3

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.21s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,997   [0.03s]
    ✓ sets built | J=17,253 | F=9,907   [0.02s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.03s]
    ✓ JB set built | JB=204,746   [0.62s]
    ✓ FB set built | FB=109,243   [0.24s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=51,759 | JB=204,746 | A=204,746 | U=614,238 | k=2,075,617 | V=109,243 | Z=109,243 | W=109,243   [4.23s]
    ✓ objective created   [15.99s]
    ✓ constraints: U linearisation (JB x M)   [47.45s]
    ✓ constraints: passenger timing + SLA   [0.86s]
    ✓ constraints: eligibility   [0.19s]
    ✓ constraints: vertical visit   [56.81s]
    ✓ constraints: standby indicators   [8.89s]
    ✓ constraints: per-flight capacity (seat/wc)   [28.46s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [10.35s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [129.11s]
    ✓ constraints: staff   [16.91s]
    ✓ constraints: LiftCap   [0.16s]
    ✓ build_pyomo_model complete | total=321.36s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 4298170 rows; 3737305 cols; 25589544 nonzeros; 3737305 integer variables (1652697 binary)
Coefficient ranges:
  Matrix  [1e-01, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
3168270 rows, 3204848 cols, 19038691 nonzeros 18s
2624428 rows, 2856943 cols, 16091921 nonzeros 128s
Presolve reductions: rows 2624428(-1673742); columns 2856943(-880362); nonzeros 16091921(-9497623)

Solving MIP model with:
   2624428 rows
   2856943 cols (2844609 binary, 12334 integer, 0 implied int., 0 continuous, 0 domain fixed)
   16091921 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            1382544805.479     Large        0      0      0         0   439.8s
         0       0         0   0.00%   1180001342      1382544805.479    14.65%        0      0      0         0   454.2s
         1       0         1 100.00%   1182848704.637  1382544805.479    14.44%        0      0      0    322306   570.7s

Solving report
  Status            Optimal
  Primal bound      1382544805.48
  Dual bound        1182848704.64
  Gap               14.44% (tolerance: 20%)
  P-D integral      17.0565921638
  Solution status   feasible
                    1382544805.48 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            570.68
  Max sub-MIP depth 0
  Nodes             1
  Repair LPs        0
  LP iterations     322306
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

,month,S1_PeakAmb,S1_PeakMini,S2_PeakAmb,S2_PeakMini,SLA_all,SLA_arr,SLA_dep
0,2025-04,8,3,11,9,0.961735,0.940090,0.993754
1,2025-05,9,3,13,9,0.955225,0.929172,0.994521
2,2025-06,9,4,11,12,0.944171,0.920103,0.983448
3,2025-07,11,5,13,10,0.950206,0.931188,0.983079
4,2025-08,10,3,13,7,0.926694,0.884189,0.986766
5,2025-09,12,4,12,11,0.916675,0.864074,0.987002
6,2025-10,11,4,13,11,0.920709,0.879058,0.986010

In [4]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

Unmatched passenger rows after merge (missing Chocks DT): 4532
Unique unmatched flight keys: 2757

Unmatched key reasons:
reason
no_flight_candidate               1980
scheduled_dt_mismatch              714
exact_match_should_have_joined      63
Name: count, dtype: int64

Dropped 4415 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[1/5] Penetration + SSR mix…
    ✓ penetration + SSR mix built   [119.07s]
[2/5] Service times…

[BUILD_JOBS] Dropping 10 arrival jobs with expired SLA window (max_late_mins=180).
        Passenger ID Flight Number Airline Code      sla_start_time  \
17310       11148662          1460           BA 2025-05-02 00:01:00
27820       11390224          6619           RK 2025-06-04 15:15:00
53617       12013252           312           U2 2025-07-21 19:16:42
69339       12405117          3252           EI 2025-08-06 11:12:05
99965       13159410           748           LS 2025-09-30 01:35:15
99966       13159411           748           LS 2025-09-30 01:35:15
99969       13159414           748           LS 2025-09-30 01:35:15
99970       13159415           748           LS 2025-09-30 01:35:15
108003      13357994           770           LS 2025-10-13 15:06:01
108004      13357995           770           LS 2025-10-13 15:06:01

            Job Start Time  sla_limit           Chocks DT
17310  2025-05-02 23:51:37         20 2025-05-02 00:01:00
27820  2025-06-05 11:08:52         20                 NaT
53617  2025-07-22 00:58:27         20 2025-07-21 19:16:42
69339  2025-08-06 22:05:14         20 2025-08-06 11:12:05
99965  2025-09-30 04:59:07         20 2025-09-30 01:35:15
99966  2025-09-30 05:00:53         20 2025-09-30 01:35:15
99969  2025-09-30 04:59:15         20 2025-09-30 01:35:15
99970  2025-09-30 04:59:18         20 2025-09-30 01:35:15
108003 2025-10-13 18:49:24         20 2025-10-13 15:06:01
108004 2025-10-13 18:49:15         20 2025-10-13 15:06:01
    ✓ service times built   [1.57s]
[2b/5] Tau mode params (S25 medians)…
    ✓ tau mode params built   [0.02s]
[3/5] Chocks offsets…
    ✓ chocks offsets built   [0.05s]
[4/5] Early/late timing…
    ✓ early/late params built   [0.05s]
[5/5] Stand inputs…
    ✓ stand inputs built   [0.06s]

In [ ]:

results_2026 = []

for m in months_2026:
    results_2026.append(run_month_s26(m, assumptions, toggles))

df_2026 = pd.DataFrame(results_2026)

df_2026.to_csv("S26_monthly_outputs_v2.csv", index=False)
df_2026

Running S26 2026-04 | cutoff=2026-05-19
→ HISTORICAL ONLY

Unmatched passenger rows after merge (missing Chocks DT): 749
Unique unmatched flight keys: 437

Unmatched key reasons:
reason
no_flight_candidate               427
exact_match_should_have_joined     10
Name: count, dtype: int64

Dropped 727 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2026-04-01 → 2026-05-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 749
Unique unmatched flight keys: 437

Unmatched key reasons:
reason
no_flight_candidate               427
exact_match_should_have_joined     10
Name: count, dtype: int64

Dropped 727 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
    ✓ ingest_s25 done | rows=14,226   [22.65s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=14,226   [0.21s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.32s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 22}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
U2            A      7
              D      5
UA            D      4
AF            D      2
LS            D      2
LM            A      1
KL            D      1
dtype: int64

Bucket horizon: start=2026-04-01 00:15:00 end=2026-05-01 04:45:00 buckets=2899
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-04-07 14:15:00 | 45.0 / 210.0
  2026-04-07 14:30:00 | 45.0 / 210.0
  2026-04-07 14:45:00 | 45.0 / 210.0
  2026-04-07 15:00:00 | 45.0 / 210.0
  2026-04-28 14:45:00 | 45.0 / 210.0
  2026-04-28 15:00:00 | 45.0 / 210.0
  2026-04-27 14:15:00 | 30.0 / 210.0
  2026-04-27 14:30:00 | 30.0 / 210.0
  2026-04-27 14:45:00 | 30.0 / 210.0
  2026-04-27 15:00:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 81
  is_spin by dir:
dir
A    81
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 34.0 48.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 4.0

Amb minutes (necessary condition):
  min required (vertical-only): 45853.9
  total available over horizon: 605370.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 10
  min mini minutes required (forced): 116.6
  total mini minutes available: 87100455.0

Lift rough check:
  lift jobs: 55
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 191
Examples (first 20):
     Passenger ID                   flight_key dir                   t  \
j
117      14880815  RK_1274_2026-04-01 11:00:00   D 2026-04-01 11:00:00
181      14882977   U2_220_2026-04-01 22:15:00   D 2026-04-01 22:15:00
230      14890194  U2_3233_2026-04-02 19:00:00   D 2026-04-02 19:00:00
231      14890195  U2_3233_2026-04-02 17:45:00   D 2026-04-02 17:45:00
232      14890196  U2_3233_2026-04-02 18:00:00   D 2026-04-02 18:00:00
284      14892368   LS_757_2026-04-03 16:00:00   D 2026-04-03 16:00:00
302      14893364   RK_179_2026-04-02 18:15:00   D 2026-04-02 18:15:00
346      14899670   U2_602_2026-04-03 12:15:00   D 2026-04-03 12:15:00
374      14900559  U2_3227_2026-04-03 14:15:00   D 2026-04-03 14:15:00
403      14901628   U2_305_2026-04-03 17:15:00   D 2026-04-03 17:15:00
406      14901844  U2_3245_2026-04-03 18:45:00   D 2026-04-03 18:45:00
412      14902290   LS_727_2026-04-04 14:45:00   D 2026-04-04 14:45:00
522      14910526   FR_890_2026-04-04 10:30:00   D 2026-04-04 10:30:00
527      14910994  U2_3201_2026-04-04 16:00:00   D 2026-04-04 16:00:00
554      14912077   LS_739_2026-04-05 15:00:00   D 2026-04-05 15:00:00
555      14912078   LS_739_2026-04-05 15:00:00   D 2026-04-05 15:00:00
563      14912358   U2_329_2026-04-04 20:30:00   D 2026-04-04 20:30:00
598      14917630  U2_3331_2026-04-05 07:00:00   D 2026-04-05 07:00:00
643      14920756  U2_3321_2026-04-05 14:45:00   D 2026-04-05 14:45:00
648      14920988  U2_3243_2026-04-05 16:00:00   D 2026-04-05 15:45:00

     hard_deadline_time      sla_start_time Stand Airline Code
j
117 2026-04-01 11:05:00 2026-04-01 11:05:00    25           RK
181 2026-04-01 22:15:24 2026-04-01 21:45:00    22           U2
230 2026-04-02 19:01:47 2026-04-02 14:30:00    20           U2
231 2026-04-02 17:54:56 2026-04-02 14:30:00    20           U2
232 2026-04-02 18:01:23 2026-04-02 14:30:00    20           U2
284 2026-04-03 16:09:09 2026-04-03 15:20:00     4           LS
302 2026-04-02 18:25:00 2026-04-02 18:25:00    25           RK
346 2026-04-03 12:20:00 2026-04-03 12:20:00    22           U2
374 2026-04-03 14:25:00 2026-04-03 14:25:00     3           U2
403 2026-04-03 17:25:00 2026-04-03 17:25:00   15B           U2
406 2026-04-03 18:49:18 2026-04-03 18:00:00    20           U2
412 2026-04-04 14:55:00 2026-04-04 14:55:00     2           LS
522 2026-04-04 10:35:00 2026-04-04 10:35:00    1A           FR
527 2026-04-04 16:04:41 2026-04-04 15:45:00    11           U2
554 2026-04-05 15:09:16 2026-04-05 14:40:00     3           LS
555 2026-04-05 15:07:51 2026-04-05 14:40:00     3           LS
563 2026-04-04 20:32:08 2026-04-04 19:55:00    10           U2
598 2026-04-05 07:10:00 2026-04-05 07:10:00    22           U2
643 2026-04-05 14:50:18 2026-04-05 14:50:00   16B           U2
648 2026-04-05 15:55:30 2026-04-05 15:55:00    25           U2

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 0

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 31
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 28
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 2

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.16s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,899   [0.01s]
    ✓ sets built | J=14,226 | F=8,736   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [0.88s]
    ✓ JB set built | JB=170,777   [0.67s]
    ✓ FB set built | FB=98,411   [0.14s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=42,678 | JB=170,777 | A=170,777 | U=512,331 | k=1,869,809 | V=98,411 | Z=98,411 | W=98,411   [5.51s]
    ✓ objective created   [13.70s]
    ✓ constraints: U linearisation (JB x M)   [8.99s]
    ✓ constraints: passenger timing + SLA   [0.62s]
    ✓ constraints: eligibility   [0.15s]
    ✓ constraints: vertical visit   [47.05s]
    ✓ constraints: standby indicators   [7.36s]
    ✓ constraints: per-flight capacity (seat/wc)   [28.25s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [10.00s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [99.63s]
    ✓ constraints: staff   [16.36s]
    ✓ constraints: LiftCap   [0.12s]
    ✓ build_pyomo_model complete | total=239.45s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 3717652 rows; 3307395 cols; 22495622 nonzeros; 3307395 integer variables (1428889 binary)
Coefficient ranges:
  Matrix  [2e-01, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
2678348 rows, 2804368 cols, 16399325 nonzeros 15s
2195969 rows, 2486909 cols, 13803486 nonzeros 93s
Presolve reductions: rows 2195969(-1521683); columns 2486909(-820486); nonzeros 13803486(-8692136)

Solving MIP model with:
   2195969 rows
   2486909 cols (2475781 binary, 11128 integer, 0 implied int., 0 continuous, 0 domain fixed)
   13803486 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            814510390.758      Large        0      0      0         0   268.4s
         0       0         0   0.00%   637001007       814510390.758     21.79%        0      0      0         0   278.5s
         0       0         0   0.00%   639370014.0419  814510390.758     21.50%        0      0      4    266923   357.6s
         0       0         0   0.00%   639372900.5858  814510390.758     21.50%    16872   6837      4    281681   458.5s
         0       0         0   0.00%   639372900.5858  814510390.758     21.50%    23916  15285      4    281681   608.7s

Solving report
  Status            Time limit reached
  Primal bound      814510390.758
  Dual bound        639372900.586
  Gap               21.5% (tolerance: 20%)
  P-D integral      71.2197947049
  Solution status   feasible
                    814510390.758 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            608.70
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0
  LP iterations     281681
                    0 (strong br.)
                    14758 (separation)
                    0 (heuristics)
WARNING: Loading a SolverResults object with an 'aborted' status, but
containing a solution

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-05 | cutoff=2026-05-19
→ SPLIT MONTH

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 4482
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    4482.000000
mean      146.339134
std        49.781878
min         0.000000
25%       123.000000
50%       159.000000
75%       179.000000
max       397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D  118.0
1       U2          ITALY  International   D  115.0
2       FR         FRANCE  International   D  178.0
3       FR          ITALY  International   D  164.0
4       KL    NETHERLANDS  International   D  106.0
5       BA  GREAT BRITAIN       Domestic   D   87.0
6       U2  GREAT BRITAIN       Domestic   D  147.0
7       U2  GREAT BRITAIN       Domestic   D  150.0
8       U2  GREAT BRITAIN       Domestic   D  155.0
9       FR          SPAIN  International   D  197.0
10      RK        ROMANIA  International   D  139.0
11      U2  GREAT BRITAIN       Domestic   D  122.0
12      U2        CROATIA  International   D  160.0
13      LH        GERMANY  International   D  130.0
14      U2        TUNISIA  International   D  173.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 4,315 / 4,482 (96.3%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY           40
6       EC           SPAIN           28
2       DS     SWITZERLAND           26
5       EC     NETHERLANDS           22
3       EC          FRANCE           20
7       IB           SPAIN            8
8       RK           MALTA            8
10      U2        SLOVENIA            8
0       BA           ITALY            4
9       RK         ROMANIA            2
1      CAT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  139.0
54       EC  NETHERLANDS  130.0
105      EC        ITALY  115.0
154      EC        SPAIN  121.0
194      U2     SLOVENIA  151.0
285      DS  SWITZERLAND  146.0
294      EC        ITALY  121.0
297      EC        SPAIN  112.0
348      EC  NETHERLANDS  150.0
410      DS  SWITZERLAND  176.0
474      EC        ITALY  128.0
481      EC       FRANCE  235.0
488      EC  NETHERLANDS  141.0
492      EC        ITALY  135.0
509      RK        MALTA  165.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 6720.229895635033
Total PRMs after rounding: 6849

Raw PRM demand distribution (prm_raw):
count    4482.000000
mean        1.499382
std         1.163239
min         0.000000
25%         0.775296
50%         1.205970
75%         1.663703
max         8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline               CountryName    Pax  _pen_used  _prm_raw  _prm_round
1397      BY                    GREECE  189.0   0.042488  8.030258           8
3365      BY                    GREECE  186.0   0.042488  7.902794           8
3521      BY                    GREECE  186.0   0.042488  7.902794           8
2477      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
679       BY                    GREECE  183.0   0.042488  7.775329           8
1268      BY                     SPAIN  182.0   0.042640  7.760549           8
4006      VS  UNITED STATES OF AMERICA  387.0   0.019717  7.630303           8
2956      VS  UNITED STATES OF AMERICA  380.0   0.019717  7.492287           7
1835      LS                  BULGARIA  189.0   0.039265  7.421135           7
3156      LS                  BULGARIA  189.0   0.039265  7.421135           7
498       LS                  BULGARIA  189.0   0.039265  7.421135           7
118       BY                     SPAIN  170.0   0.042640  7.248865           7
3850      VS  UNITED STATES OF AMERICA  366.0   0.019717  7.216255           7
3268      LS                  BULGARIA  180.0   0.039265  7.067747           7
861       VS  UNITED STATES OF AMERICA  358.0   0.019717  7.058523           7
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=118.0 | Pen=0.00755 | Pax*Pen=0.891 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=115.0 | Pen=0.00872 | Pax*Pen=1.002 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=178.0 | Pen=0.00686 | Pax*Pen=1.222 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=164.0 | Pen=0.00547 | Pax*Pen=0.897 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=106.0 | Pen=0.00831 | Pax*Pen=0.881 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=87.0 | Pen=0.00962 | Pax*Pen=0.837 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=147.0 | Pen=0.00918 | Pax*Pen=1.349 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=150.0 | Pen=0.00918 | Pax*Pen=1.377 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=155.0 | Pen=0.00918 | Pax*Pen=1.423 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=139.0 | Pen=0.01000 | Pax*Pen=1.390 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=122.0 | Pen=0.00918 | Pax*Pen=1.120 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=160.0 | Pen=0.00421 | Pax*Pen=0.674 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=130.0 | Pen=0.00569 | Pax*Pen=0.740 | PRMs=1
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=173.0 | Pen=0.02346 | Pax*Pen=4.058 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 6849
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     3595
WCHS     2820
WCHC      393
OTHER      41
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-05-19 → 2026-06-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 4482
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    4482.000000
mean      146.339134
std        49.781878
min         0.000000
25%       123.000000
50%       159.000000
75%       179.000000
max       397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D  118.0
1       U2          ITALY  International   D  115.0
2       FR         FRANCE  International   D  178.0
3       FR          ITALY  International   D  164.0
4       KL    NETHERLANDS  International   D  106.0
5       BA  GREAT BRITAIN       Domestic   D   87.0
6       U2  GREAT BRITAIN       Domestic   D  147.0
7       U2  GREAT BRITAIN       Domestic   D  150.0
8       U2  GREAT BRITAIN       Domestic   D  155.0
9       FR          SPAIN  International   D  197.0
10      RK        ROMANIA  International   D  139.0
11      U2  GREAT BRITAIN       Domestic   D  122.0
12      U2        CROATIA  International   D  160.0
13      LH        GERMANY  International   D  130.0
14      U2        TUNISIA  International   D  173.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 4,315 / 4,482 (96.3%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY           40
6       EC           SPAIN           28
2       DS     SWITZERLAND           26
5       EC     NETHERLANDS           22
3       EC          FRANCE           20
7       IB           SPAIN            8
8       RK           MALTA            8
10      U2        SLOVENIA            8
0       BA           ITALY            4
9       RK         ROMANIA            2
1      CAT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  139.0
54       EC  NETHERLANDS  130.0
105      EC        ITALY  115.0
154      EC        SPAIN  121.0
194      U2     SLOVENIA  151.0
285      DS  SWITZERLAND  146.0
294      EC        ITALY  121.0
297      EC        SPAIN  112.0
348      EC  NETHERLANDS  150.0
410      DS  SWITZERLAND  176.0
474      EC        ITALY  128.0
481      EC       FRANCE  235.0
488      EC  NETHERLANDS  141.0
492      EC        ITALY  135.0
509      RK        MALTA  165.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 6720.229895635033
Total PRMs after rounding: 6849

Raw PRM demand distribution (prm_raw):
count    4482.000000
mean        1.499382
std         1.163239
min         0.000000
25%         0.775296
50%         1.205970
75%         1.663703
max         8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline               CountryName    Pax  _pen_used  _prm_raw  _prm_round
1260      BY                    GREECE  189.0   0.042488  8.030258           8
3521      BY                    GREECE  186.0   0.042488  7.902794           8
3365      BY                    GREECE  186.0   0.042488  7.902794           8
2477      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
679       BY                    GREECE  183.0   0.042488  7.775329           8
1289      BY                     SPAIN  182.0   0.042640  7.760549           8
4006      VS  UNITED STATES OF AMERICA  387.0   0.019717  7.630303           8
2956      VS  UNITED STATES OF AMERICA  380.0   0.019717  7.492287           7
3156      LS                  BULGARIA  189.0   0.039265  7.421135           7
1850      LS                  BULGARIA  189.0   0.039265  7.421135           7
498       LS                  BULGARIA  189.0   0.039265  7.421135           7
118       BY                     SPAIN  170.0   0.042640  7.248865           7
3850      VS  UNITED STATES OF AMERICA  366.0   0.019717  7.216255           7
3268      LS                  BULGARIA  180.0   0.039265  7.067747           7
861       VS  UNITED STATES OF AMERICA  358.0   0.019717  7.058523           7
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=118.0 | Pen=0.00755 | Pax*Pen=0.891 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=115.0 | Pen=0.00872 | Pax*Pen=1.002 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=178.0 | Pen=0.00686 | Pax*Pen=1.222 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=164.0 | Pen=0.00547 | Pax*Pen=0.897 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=106.0 | Pen=0.00831 | Pax*Pen=0.881 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=87.0 | Pen=0.00962 | Pax*Pen=0.837 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=147.0 | Pen=0.00918 | Pax*Pen=1.349 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=150.0 | Pen=0.00918 | Pax*Pen=1.377 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=155.0 | Pen=0.00918 | Pax*Pen=1.423 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=197.0 | Pen=0.00966 | Pax*Pen=1.902 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=139.0 | Pen=0.01000 | Pax*Pen=1.390 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=122.0 | Pen=0.00918 | Pax*Pen=1.120 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=160.0 | Pen=0.00421 | Pax*Pen=0.674 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=130.0 | Pen=0.00569 | Pax*Pen=0.740 | PRMs=1
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=173.0 | Pen=0.02346 | Pax*Pen=4.058 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 6849
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     3580
WCHS     2854
WCHC      377
OTHER      38
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=6,849   [20.53s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=6,849   [0.14s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.15s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-05-19 23:45:00 end=2026-06-01 05:30:00 buckets=1176
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-05-22 08:30:00 | 45.0 / 210.0
  2026-05-28 11:00:00 | 45.0 / 210.0
  2026-05-22 18:15:00 | 45.0 / 210.0
  2026-05-30 20:15:00 | 45.0 / 210.0
  2026-05-30 20:30:00 | 45.0 / 210.0
  2026-05-21 16:45:00 | 45.0 / 210.0
  2026-05-21 17:00:00 | 45.0 / 210.0
  2026-05-28 09:15:00 | 30.0 / 210.0
  2026-05-25 19:45:00 | 30.0 / 210.0
  2026-05-25 20:00:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 114
  is_spin by dir:
dir
A    114
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.09635113333333334 31.974178716666668 59.239630166666664
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 2.0

Amb minutes (necessary condition):
  min required (vertical-only): 27937.4
  total available over horizon: 240840.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 6
  min mini minutes required (forced): 104.0
  total mini minutes available: 35332920.0

Lift rough check:
  lift jobs: 33
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 1048
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_1887_0  AF_1887_2026-05-26 05:45:00   D 2026-05-26 05:45:00
4    S26_0922_0  KL_0922_2026-05-26 06:15:00   D 2026-05-26 06:15:00
6    S26_0301_0  U2_0301_2026-05-26 06:30:00   D 2026-05-26 06:30:00
11   S26_5614_0  RK_5614_2026-05-26 06:00:00   D 2026-05-26 06:00:00
12   S26_0307_0  U2_0307_2026-05-26 06:45:00   D 2026-05-26 06:45:00
14   S26_0965_0  LH_0965_2026-05-26 06:30:00   D 2026-05-26 06:15:00
39   S26_0321_0  LM_0321_2026-05-26 07:00:00   D 2026-05-26 07:00:00
43   S26_0353_0  LM_0353_2026-05-26 08:00:00   D 2026-05-26 07:45:00
47   S26_3225_0  U2_3225_2026-05-26 07:15:00   D 2026-05-26 07:15:00
48   S26_3225_1  U2_3225_2026-05-26 07:15:00   D 2026-05-26 07:15:00
57   S26_3301_0  U2_3301_2026-05-26 07:15:00   D 2026-05-26 07:15:00
58   S26_0723_0  LS_0723_2026-05-26 07:15:00   D 2026-05-26 07:15:00
59   S26_0723_1  LS_0723_2026-05-26 07:15:00   D 2026-05-26 07:15:00
60   S26_8713_0  BA_8713_2026-05-26 07:30:00   D 2026-05-26 07:15:00
61   S26_0323_0  U2_0323_2026-05-26 07:30:00   D 2026-05-26 07:30:00
70   S26_0032_0  QR_0032_2026-05-26 08:15:00   D 2026-05-26 08:15:00
71   S26_0032_1  QR_0032_2026-05-26 08:15:00   D 2026-05-26 08:15:00
72   S26_0032_2  QR_0032_2026-05-26 08:15:00   D 2026-05-26 08:15:00
73   S26_0032_3  QR_0032_2026-05-26 08:15:00   D 2026-05-26 08:15:00
74   S26_0032_4  QR_0032_2026-05-26 08:15:00   D 2026-05-26 08:15:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-05-26 05:48:44.748838902 2026-05-26 05:40:00    31           AF
4  2026-05-26 06:23:15.814725132 2026-05-26 05:45:00    10           KL
6  2026-05-26 06:31:40.368227964 2026-05-26 06:00:00    25           U2
11 2026-05-26 06:04:37.801628730 2026-05-26 06:00:00     2           RK
12 2026-05-26 06:51:52.823585700 2026-05-26 06:05:00     7           U2
14 2026-05-26 06:26:22.215355854 2026-05-26 06:10:00     4           LH
39 2026-05-26 07:07:39.999049098 2026-05-26 06:40:00     8           LM
43 2026-05-26 07:55:34.512067848 2026-05-26 06:50:00    26           LM
47 2026-05-26 07:19:52.200558024 2026-05-26 07:00:00   15B           U2
48 2026-05-26 07:19:52.200558024 2026-05-26 07:00:00   15B           U2
57 2026-05-26 07:20:00.000000000 2026-05-26 07:20:00    1B           U2
58 2026-05-26 07:24:40.017943158 2026-05-26 07:20:00   100           LS
59 2026-05-26 07:24:40.017943158 2026-05-26 07:20:00   100           LS
60 2026-05-26 07:27:31.481325948 2026-05-26 07:25:00    28           BA
61 2026-05-26 07:39:43.222593390 2026-05-26 07:35:00    22           U2
70 2026-05-26 08:22:54.817103952 2026-05-26 07:55:00    18           QR
71 2026-05-26 08:22:54.817103952 2026-05-26 07:55:00    18           QR
72 2026-05-26 08:22:54.817103952 2026-05-26 07:55:00    18           QR
73 2026-05-26 08:22:54.817103952 2026-05-26 07:55:00    18           QR
74 2026-05-26 08:22:54.817103952 2026-05-26 07:55:00    18           QR

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 290
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 229
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 6

✅ Tight-window checks complete.

✅ Pre-solver debug complete.

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-06 | cutoff=2026-05-19
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11660
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'LS' 'LH' 'RK' 'BA' 'LM' 'TO']
Countries (sample): ['FRANCE' 'GREAT BRITAIN' 'SPAIN' 'NETHERLANDS' 'GREECE' 'CZECH REPUBLIC'
 'MALTA' 'GERMANY' 'ITALY' 'TURKEY']

Pax describe:
count    11660.000000
mean       144.569897
std         49.305639
min          0.000000
25%        121.000000
50%        156.000000
75%        176.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  131.0
1       U2   GREAT BRITAIN       Domestic   D  149.0
2       FR           SPAIN  International   D  191.0
3       KL     NETHERLANDS  International   D  152.0
4       FR          FRANCE  International   D  147.0
5       U2   GREAT BRITAIN       Domestic   D  162.0
6       LS          GREECE  International   D  187.0
7       U2  CZECH REPUBLIC  International   D  186.0
8       FR           MALTA  International   D  183.0
9       LH         GERMANY  International   D  119.0
10      RK   GREAT BRITAIN       Domestic   D  152.0
11      U2           ITALY  International   D  169.0
12      FR           ITALY  International   D  134.0
13      LS          TURKEY  International   D  163.0
14      BA   GREAT BRITAIN       Domestic   D  134.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,228 / 11,660 (96.3%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
6       EC        ITALY          106
8       EC        SPAIN           70
2       DS  SWITZERLAND           66
4       EC       FRANCE           58
7       EC  NETHERLANDS           40
9       IB        SPAIN           24
12      U2     SLOVENIA           16
10      RK        MALTA           16
5       EC      GERMANY           14
11      RK      ROMANIA           10
0       BA        ITALY            8
3       E4   MONTENEGRO            2
1       BQ       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
44       EC       FRANCE  186.0
82       EC  NETHERLANDS  156.0
105      DS  SWITZERLAND  134.0
120      EC        ITALY  140.0
139      EC        ITALY  207.0
175      EC  NETHERLANDS  154.0
184      DS  SWITZERLAND  177.0
191      EC       FRANCE  154.0
196      EC        SPAIN   73.0
210      RK      ROMANIA  136.0
256      EC  NETHERLANDS  153.0
309      EC        ITALY  133.0
362      EC        SPAIN   94.0
378      EC       FRANCE  147.0
405      U2     SLOVENIA  148.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17243.34798793989
Total PRMs after rounding: 17562

Raw PRM demand distribution (prm_raw):
count    11660.000000
mean         1.478846
std          1.124536
min          0.000000
25%          0.773729
50%          1.194058
75%          1.660000
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
9342       BY                    GREECE  189.0   0.042488  8.030258
11446      BY                    GREECE  189.0   0.042488  8.030258
10505      BY                    GREECE  189.0   0.042488  8.030258
10549      BY                    GREECE  189.0   0.042488  8.030258
8282       BY                     SPAIN  188.0   0.042640  8.016392
907        BY                    GREECE  186.0   0.042488  7.902794
5173       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
3806       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
4982       BY                    GREECE  184.0   0.042488  7.817818
3618       BY                    GREECE  184.0   0.042488  7.817818
9144       BY                     SPAIN  182.0   0.042640  7.760549
11626      BY                     SPAIN  181.0   0.042640  7.717909
2260       BY                    GREECE  181.0   0.042488  7.690353
6050       BY                     SPAIN  180.0   0.042640  7.675269
6854       BY                     SPAIN  178.0   0.042640  7.589988

       _prm_round
9342            8
11446           8
10505           8
10549           8
8282            8
907             8
5173            8
3806            8
4982            8
3618            8
9144            8
11626           8
2260            8
6050            8
6854            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=131.0 | Pen=0.00755 | Pax*Pen=0.989 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=149.0 | Pen=0.00918 | Pax*Pen=1.367 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=191.0 | Pen=0.00966 | Pax*Pen=1.844 | PRMs=2
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=152.0 | Pen=0.00831 | Pax*Pen=1.263 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=147.0 | Pen=0.00686 | Pax*Pen=1.009 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=187.0 | Pen=0.01748 | Pax*Pen=3.269 | PRMs=3
[DEBUG flight] Airline=U2 | Country=CZECH REPUBLIC | Pax=186.0 | Pen=0.00446 | Pax*Pen=0.829 | PRMs=1
[DEBUG flight] Airline=FR | Country=MALTA | Pax=183.0 | Pen=0.00863 | Pax*Pen=1.579 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=119.0 | Pen=0.00569 | Pax*Pen=0.677 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=152.0 | Pen=0.00637 | Pax*Pen=0.969 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=169.0 | Pen=0.00872 | Pax*Pen=1.473 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=134.0 | Pen=0.00547 | Pax*Pen=0.733 | PRMs=1
[DEBUG flight] Airline=LS | Country=TURKEY | Pax=163.0 | Pen=0.02622 | Pax*Pen=4.275 | PRMs=4
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=134.0 | Pen=0.00962 | Pax*Pen=1.289 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 17562
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9317
WCHS     7140
WCHC     1002
OTHER     103
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-06-01 → 2026-07-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11660
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'LS' 'LH' 'RK' 'BA' 'LM' 'TO']
Countries (sample): ['FRANCE' 'GREAT BRITAIN' 'SPAIN' 'NETHERLANDS' 'GREECE' 'CZECH REPUBLIC'
 'MALTA' 'GERMANY' 'ITALY' 'TURKEY']

Pax describe:
count    11660.000000
mean       144.569897
std         49.305639
min          0.000000
25%        121.000000
50%        156.000000
75%        176.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  131.0
1       U2   GREAT BRITAIN       Domestic   D  149.0
2       FR           SPAIN  International   D  191.0
3       KL     NETHERLANDS  International   D  152.0
4       FR          FRANCE  International   D  147.0
5       U2   GREAT BRITAIN       Domestic   D  162.0
6       LS          GREECE  International   D  187.0
7       U2  CZECH REPUBLIC  International   D  186.0
8       FR           MALTA  International   D  183.0
9       LH         GERMANY  International   D  119.0
10      RK   GREAT BRITAIN       Domestic   D  152.0
11      U2           ITALY  International   D  169.0
12      FR           ITALY  International   D  134.0
13      LS          TURKEY  International   D  163.0
14      BA   GREAT BRITAIN       Domestic   D  134.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,228 / 11,660 (96.3%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
6       EC        ITALY          106
8       EC        SPAIN           70
2       DS  SWITZERLAND           66
4       EC       FRANCE           58
7       EC  NETHERLANDS           40
9       IB        SPAIN           24
12      U2     SLOVENIA           16
10      RK        MALTA           16
5       EC      GERMANY           14
11      RK      ROMANIA           10
0       BA        ITALY            8
3       E4   MONTENEGRO            2
1       BQ       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
47       EC       FRANCE  186.0
86       EC  NETHERLANDS  156.0
105      DS  SWITZERLAND  134.0
120      EC        ITALY  140.0
139      EC        ITALY  207.0
175      EC  NETHERLANDS  154.0
184      DS  SWITZERLAND  177.0
191      EC       FRANCE  154.0
196      EC        SPAIN   73.0
210      RK      ROMANIA  136.0
256      EC  NETHERLANDS  153.0
309      EC        ITALY  133.0
362      EC        SPAIN   94.0
378      EC       FRANCE  147.0
405      U2     SLOVENIA  148.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17243.34798793989
Total PRMs after rounding: 17562

Raw PRM demand distribution (prm_raw):
count    11660.000000
mean         1.478846
std          1.124536
min          0.000000
25%          0.773729
50%          1.194058
75%          1.660000
max          8.030258
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
10549      BY                    GREECE  189.0   0.042488  8.030258
10505      BY                    GREECE  189.0   0.042488  8.030258
11446      BY                    GREECE  189.0   0.042488  8.030258
9342       BY                    GREECE  189.0   0.042488  8.030258
8282       BY                     SPAIN  188.0   0.042640  8.016392
907        BY                    GREECE  186.0   0.042488  7.902794
3806       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5173       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
4982       BY                    GREECE  184.0   0.042488  7.817818
3618       BY                    GREECE  184.0   0.042488  7.817818
9144       BY                     SPAIN  182.0   0.042640  7.760549
11626      BY                     SPAIN  181.0   0.042640  7.717909
2260       BY                    GREECE  181.0   0.042488  7.690353
6066       BY                     SPAIN  180.0   0.042640  7.675269
6854       BY                     SPAIN  178.0   0.042640  7.589988

       _prm_round
10549           8
10505           8
11446           8
9342            8
8282            8
907             8
3806            8
5173            8
4982            8
3618            8
9144            8
11626           8
2260            8
6066            8
6854            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=131.0 | Pen=0.00755 | Pax*Pen=0.989 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=149.0 | Pen=0.00918 | Pax*Pen=1.367 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=191.0 | Pen=0.00966 | Pax*Pen=1.844 | PRMs=2
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=152.0 | Pen=0.00831 | Pax*Pen=1.263 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=147.0 | Pen=0.00686 | Pax*Pen=1.009 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=162.0 | Pen=0.00918 | Pax*Pen=1.487 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=187.0 | Pen=0.01748 | Pax*Pen=3.269 | PRMs=3
[DEBUG flight] Airline=U2 | Country=CZECH REPUBLIC | Pax=186.0 | Pen=0.00446 | Pax*Pen=0.829 | PRMs=1
[DEBUG flight] Airline=FR | Country=MALTA | Pax=183.0 | Pen=0.00863 | Pax*Pen=1.579 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=119.0 | Pen=0.00569 | Pax*Pen=0.677 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=152.0 | Pen=0.00637 | Pax*Pen=0.969 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=169.0 | Pen=0.00872 | Pax*Pen=1.473 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=134.0 | Pen=0.00547 | Pax*Pen=0.733 | PRMs=1
[DEBUG flight] Airline=LS | Country=TURKEY | Pax=163.0 | Pen=0.02622 | Pax*Pen=4.275 | PRMs=4
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=134.0 | Pen=0.00962 | Pax*Pen=1.289 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 17562
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9342
WCHS     7103
WCHC     1010
OTHER     107
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=17,562   [182.75s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=17,562   [0.28s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.39s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 2}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
E4            D      2
dtype: int64

Bucket horizon: start=2026-05-31 23:30:00 end=2026-07-01 05:45:00 buckets=2906
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-06-25 08:15:00 | 60.0 / 210.0
  2026-06-25 08:30:00 | 60.0 / 210.0
  2026-06-02 12:00:00 | 60.0 / 210.0
  2026-06-02 12:15:00 | 60.0 / 210.0
  2026-06-26 08:30:00 | 60.0 / 210.0
  2026-06-03 10:30:00 | 60.0 / 210.0
  2026-06-03 10:45:00 | 60.0 / 210.0
  2026-06-24 16:15:00 | 60.0 / 210.0
  2026-06-09 14:15:00 | 60.0 / 210.0
  2026-06-09 14:30:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 298
  is_spin by dir:
dir
A    298
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.025107116666666665 31.16924905 59.89746453333333
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 6.0

Amb minutes (necessary condition):
  min required (vertical-only): 71566.2
  total available over horizon: 594840.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 14
  min mini minutes required (forced): 240.6
  total mini minutes available: 87310770.0

Lift rough check:
  lift jobs: 64
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2960
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
1    S26_0807_0  U2_0807_2026-06-01 05:30:00   D 2026-06-01 05:30:00
6    S26_0307_0  U2_0307_2026-06-01 06:00:00   D 2026-06-01 06:00:00
7    S26_0731_0  LS_0731_2026-06-01 06:15:00   D 2026-06-01 06:00:00
8    S26_0731_1  LS_0731_2026-06-01 06:15:00   D 2026-06-01 06:00:00
9    S26_0731_2  LS_0731_2026-06-01 06:15:00   D 2026-06-01 06:00:00
13   S26_0965_0  LH_0965_2026-06-01 06:30:00   D 2026-06-01 06:30:00
17   S26_0711_0  LS_0711_2026-06-01 06:30:00   D 2026-06-01 06:30:00
18   S26_0711_1  LS_0711_2026-06-01 06:30:00   D 2026-06-01 06:30:00
19   S26_0711_2  LS_0711_2026-06-01 06:30:00   D 2026-06-01 06:30:00
20   S26_0711_3  LS_0711_2026-06-01 06:30:00   D 2026-06-01 06:30:00
21   S26_1465_0  BA_1465_2026-06-01 06:15:00   D 2026-06-01 06:15:00
23   S26_3313_0  U2_3313_2026-06-01 06:15:00   D 2026-06-01 06:15:00
27   S26_9286_0  FR_9286_2026-06-01 06:30:00   D 2026-06-01 06:30:00
45   S26_1467_0  BA_1467_2026-06-01 07:45:00   D 2026-06-01 07:45:00
46   S26_0301_0  U2_0301_2026-06-01 07:00:00   D 2026-06-01 07:00:00
47   S26_0301_1  U2_0301_2026-06-01 07:00:00   D 2026-06-01 07:00:00
49   S26_3271_0  U2_3271_2026-06-01 07:00:00   D 2026-06-01 07:00:00
50   S26_3271_1  U2_3271_2026-06-01 07:00:00   D 2026-06-01 07:00:00
54   S26_8713_0  BA_8713_2026-06-01 07:30:00   D 2026-06-01 07:30:00
55   S26_3915_0  LS_3915_2026-06-01 07:45:00   D 2026-06-01 07:30:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
1  2026-06-01 05:40:00.000000000 2026-06-01 05:40:00    20           U2
6  2026-06-01 06:09:39.548728812 2026-06-01 06:00:00     8           U2
7  2026-06-01 06:11:18.712027224 2026-06-01 06:00:00     2           LS
8  2026-06-01 06:11:18.712027224 2026-06-01 06:00:00     2           LS
9  2026-06-01 06:11:18.712027224 2026-06-01 06:00:00     2           LS
13 2026-06-01 06:36:23.316250920 2026-06-01 06:10:00   16A           LH
17 2026-06-01 06:30:28.240304394 2026-06-01 06:15:00     3           LS
18 2026-06-01 06:30:28.240304394 2026-06-01 06:15:00     3           LS
19 2026-06-01 06:30:28.240304394 2026-06-01 06:15:00     3           LS
20 2026-06-01 06:30:28.240304394 2026-06-01 06:15:00     3           LS
21 2026-06-01 06:20:00.000000000 2026-06-01 06:20:00     6           BA
23 2026-06-01 06:20:00.000000000 2026-06-01 06:20:00    22           U2
27 2026-06-01 06:30:27.035965932 2026-06-01 06:25:00    1B           FR
45 2026-06-01 07:51:33.477653850 2026-06-01 07:00:00   105           BA
46 2026-06-01 07:00:17.481698106 2026-06-01 07:00:00   15B           U2
47 2026-06-01 07:00:17.481698106 2026-06-01 07:00:00   15B           U2
49 2026-06-01 07:08:57.229783284 2026-06-01 07:05:00    25           U2
50 2026-06-01 07:08:57.229783284 2026-06-01 07:05:00    25           U2
54 2026-06-01 07:30:05.262860640 2026-06-01 07:25:00     6           BA
55 2026-06-01 07:43:03.768207684 2026-06-01 07:30:00    11           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 748

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-07 | cutoff=2026-05-19
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 12151
Airlines (sample): ['AF' 'FR' 'KL' 'BA' 'U2' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SPAIN' 'NETHERLANDS' 'GREAT BRITAIN' 'CZECH REPUBLIC' 'BELGIUM'
 'MALTA' 'ICELAND' 'GERMANY' 'ALBANIA']

Pax describe:
count    12151.000000
mean       150.089458
std         50.608571
min          0.000000
25%        129.500000
50%        162.000000
75%        182.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  121.0
1       FR           SPAIN  International   D  170.0
2       KL     NETHERLANDS  International   D  118.0
3       BA   GREAT BRITAIN       Domestic   D  108.0
4       U2   GREAT BRITAIN       Domestic   D  143.0
5       U2          FRANCE  International   D  161.0
6       U2  CZECH REPUBLIC  International   D  235.0
7       FR         BELGIUM  International   D  131.0
8       LS           MALTA  International   D  132.0
9       U2           SPAIN  International   D  215.0
10      U2         ICELAND  International   D  173.0
11      LH         GERMANY  International   D  108.0
12      LS           SPAIN  International   D  224.0
13      LS           SPAIN  International   D  170.0
14      BA   GREAT BRITAIN       Domestic   D   90.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,686 / 12,151 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
2       DS     SWITZERLAND           80
7       EC           SPAIN           80
5       EC           ITALY           78
3       EC          FRANCE           56
6       EC     NETHERLANDS           36
4       EC         GERMANY           34
8       IB           SPAIN           28
13      U2        SLOVENIA           18
11      RK           MALTA           18
9       LG      LUXEMBOURG           18
12      RK         ROMANIA            8
1       BA           ITALY            8
0       AP          FRANCE            2
10      LM  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
19       U2     SLOVENIA  156.0
49       DS  SWITZERLAND  153.0
111      EC      GERMANY  105.0
119      EC        ITALY  119.0
172      EC        SPAIN  110.0
173      IB        SPAIN  152.0
177      EC  NETHERLANDS  157.0
314      EC        ITALY  124.0
316      EC       FRANCE  156.0
350      RK        MALTA  161.0
371      IB        SPAIN  178.0
379      DS  SWITZERLAND  149.0
380      DS  SWITZERLAND  158.0
382      EC       FRANCE  186.0
389      EC        SPAIN  176.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18464.33664561013
Total PRMs after rounding: 18944

Raw PRM demand distribution (prm_raw):
count    12151.000000
mean         1.519573
std          1.156425
min          0.000000
25%          0.809145
50%          1.230000
75%          1.697888
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
5898       QR                     QATAR  311.0   0.026728  8.312373
4546       QR                     QATAR  309.0   0.026728  8.258917
5321       QR                     QATAR  306.0   0.026728  8.178734
2602       QR                     QATAR  303.0   0.026728  8.098550
5699       QR                     QATAR  302.0   0.026728  8.071822
9294       BY                    GREECE  189.0   0.042488  8.030258
9309       BY                    GREECE  189.0   0.042488  8.030258
6212       BY                    GREECE  189.0   0.042488  8.030258
7344       BY                    GREECE  189.0   0.042488  8.030258
10626      BY                    GREECE  189.0   0.042488  8.030258
3967       QR                     QATAR  300.0   0.026728  8.018366
9068       BY                     SPAIN  184.0   0.042640  7.845830
3190       QR                     QATAR  293.0   0.026728  7.831271
7823       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
2096       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
5898            8
4546            8
5321            8
2602            8
5699            8
9294            8
9309            8
6212            8
7344            8
10626           8
3967            8
9068            8
3190            8
7823            8
2096            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=121.0 | Pen=0.00755 | Pax*Pen=0.914 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=170.0 | Pen=0.00966 | Pax*Pen=1.642 | PRMs=2
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=118.0 | Pen=0.00831 | Pax*Pen=0.980 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=108.0 | Pen=0.00962 | Pax*Pen=1.039 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00918 | Pax*Pen=1.312 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=161.0 | Pen=0.00839 | Pax*Pen=1.350 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CZECH REPUBLIC | Pax=235.0 | Pen=0.00446 | Pax*Pen=1.047 | PRMs=1
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=131.0 | Pen=0.00380 | Pax*Pen=0.497 | PRMs=0
[DEBUG flight] Airline=LS | Country=MALTA | Pax=132.0 | Pen=0.01755 | Pax*Pen=2.316 | PRMs=2
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=215.0 | Pen=0.01381 | Pax*Pen=2.970 | PRMs=3
[DEBUG flight] Airline=U2 | Country=ICELAND | Pax=173.0 | Pen=0.00577 | Pax*Pen=0.998 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=224.0 | Pen=0.02578 | Pax*Pen=5.775 | PRMs=6
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=170.0 | Pen=0.02578 | Pax*Pen=4.383 | PRMs=4
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=90.0 | Pen=0.00962 | Pax*Pen=0.866 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18944
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9986
WCHS     7835
WCHC     1008
OTHER     115
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-07-01 → 2026-08-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 12151
Airlines (sample): ['AF' 'FR' 'KL' 'BA' 'U2' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SPAIN' 'NETHERLANDS' 'GREAT BRITAIN' 'CZECH REPUBLIC' 'BELGIUM'
 'MALTA' 'ICELAND' 'GERMANY' 'ALBANIA']

Pax describe:
count    12151.000000
mean       150.089458
std         50.608571
min          0.000000
25%        129.500000
50%        162.000000
75%        182.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       AF          FRANCE  International   D  121.0
1       FR           SPAIN  International   D  170.0
2       KL     NETHERLANDS  International   D  118.0
3       BA   GREAT BRITAIN       Domestic   D  108.0
4       U2   GREAT BRITAIN       Domestic   D  143.0
5       U2          FRANCE  International   D  161.0
6       U2  CZECH REPUBLIC  International   D  235.0
7       FR         BELGIUM  International   D  131.0
8       LS           MALTA  International   D  132.0
9       U2           SPAIN  International   D  215.0
10      U2         ICELAND  International   D  173.0
11      LH         GERMANY  International   D  108.0
12      LS           SPAIN  International   D  224.0
13      LS           SPAIN  International   D  170.0
14      BA   GREAT BRITAIN       Domestic   D   90.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,686 / 12,151 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
2       DS     SWITZERLAND           80
7       EC           SPAIN           80
5       EC           ITALY           78
3       EC          FRANCE           56
6       EC     NETHERLANDS           36
4       EC         GERMANY           34
8       IB           SPAIN           28
13      U2        SLOVENIA           18
11      RK           MALTA           18
9       LG      LUXEMBOURG           18
12      RK         ROMANIA            8
1       BA           ITALY            8
0       AP          FRANCE            2
10      LM  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
19       U2     SLOVENIA  156.0
49       DS  SWITZERLAND  153.0
111      EC      GERMANY  105.0
119      EC        ITALY  119.0
172      EC        SPAIN  110.0
173      IB        SPAIN  152.0
177      EC  NETHERLANDS  157.0
314      EC        ITALY  124.0
316      EC       FRANCE  156.0
350      RK        MALTA  161.0
371      IB        SPAIN  178.0
379      DS  SWITZERLAND  149.0
380      DS  SWITZERLAND  158.0
382      EC       FRANCE  186.0
389      EC        SPAIN  176.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 18464.33664561013
Total PRMs after rounding: 18944

Raw PRM demand distribution (prm_raw):
count    12151.000000
mean         1.519573
std          1.156425
min          0.000000
25%          0.809145
50%          1.230000
75%          1.697888
max          8.312373
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
5898       QR                     QATAR  311.0   0.026728  8.312373
4546       QR                     QATAR  309.0   0.026728  8.258917
5321       QR                     QATAR  306.0   0.026728  8.178734
2602       QR                     QATAR  303.0   0.026728  8.098550
5699       QR                     QATAR  302.0   0.026728  8.071822
9294       BY                    GREECE  189.0   0.042488  8.030258
9309       BY                    GREECE  189.0   0.042488  8.030258
6216       BY                    GREECE  189.0   0.042488  8.030258
7344       BY                    GREECE  189.0   0.042488  8.030258
10626      BY                    GREECE  189.0   0.042488  8.030258
3967       QR                     QATAR  300.0   0.026728  8.018366
9068       BY                     SPAIN  184.0   0.042640  7.845830
3190       QR                     QATAR  293.0   0.026728  7.831271
7823       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
2096       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
5898            8
4546            8
5321            8
2602            8
5699            8
9294            8
9309            8
6216            8
7344            8
10626           8
3967            8
9068            8
3190            8
7823            8
2096            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=121.0 | Pen=0.00755 | Pax*Pen=0.914 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=170.0 | Pen=0.00966 | Pax*Pen=1.642 | PRMs=2
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=118.0 | Pen=0.00831 | Pax*Pen=0.980 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=108.0 | Pen=0.00962 | Pax*Pen=1.039 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00918 | Pax*Pen=1.312 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=161.0 | Pen=0.00839 | Pax*Pen=1.350 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CZECH REPUBLIC | Pax=235.0 | Pen=0.00446 | Pax*Pen=1.047 | PRMs=1
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=131.0 | Pen=0.00380 | Pax*Pen=0.497 | PRMs=0
[DEBUG flight] Airline=LS | Country=MALTA | Pax=132.0 | Pen=0.01755 | Pax*Pen=2.316 | PRMs=2
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=215.0 | Pen=0.01381 | Pax*Pen=2.970 | PRMs=3
[DEBUG flight] Airline=U2 | Country=ICELAND | Pax=173.0 | Pen=0.00577 | Pax*Pen=0.998 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=108.0 | Pen=0.00569 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=224.0 | Pen=0.02578 | Pax*Pen=5.775 | PRMs=6
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=170.0 | Pen=0.02578 | Pax*Pen=4.383 | PRMs=4
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=90.0 | Pen=0.00962 | Pax*Pen=0.866 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18944
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9959
WCHS     7844
WCHC     1032
OTHER     109
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,944   [203.93s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=18,944   [0.37s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.59s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-06-30 23:45:00 end=2026-08-01 06:30:00 buckets=3004
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-07-16 19:45:00 | 75.0 / 210.0
  2026-07-22 14:00:00 | 60.0 / 210.0
  2026-07-16 08:45:00 | 60.0 / 210.0
  2026-07-16 09:00:00 | 60.0 / 210.0
  2026-07-02 08:30:00 | 60.0 / 210.0
  2026-07-20 09:00:00 | 60.0 / 210.0
  2026-07-12 11:30:00 | 60.0 / 210.0
  2026-07-20 17:30:00 | 60.0 / 210.0
  2026-07-20 17:45:00 | 60.0 / 210.0
  2026-07-16 19:30:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 355
  is_spin by dir:
dir
A    355
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.0223085 31.848520399999998 59.983390916666664
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 80195.9
  total available over horizon: 613020.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 23
  min mini minutes required (forced): 399.1
  total mini minutes available: 90255180.0

Lift rough check:
  lift jobs: 68
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3153
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
4    S26_1467_0  BA_1467_2026-07-01 06:15:00   D 2026-07-01 06:15:00
5    S26_0807_0  U2_0807_2026-07-01 06:30:00   D 2026-07-01 06:30:00
6    S26_3249_0  U2_3249_2026-07-01 06:15:00   D 2026-07-01 06:15:00
14   S26_0965_0  LH_0965_2026-07-01 06:30:00   D 2026-07-01 06:15:00
21   S26_0799_0  LS_0799_2026-07-01 06:30:00   D 2026-07-01 06:15:00
22   S26_0799_1  LS_0799_2026-07-01 06:30:00   D 2026-07-01 06:15:00
23   S26_0799_2  LS_0799_2026-07-01 06:30:00   D 2026-07-01 06:15:00
24   S26_0799_3  LS_0799_2026-07-01 06:30:00   D 2026-07-01 06:15:00
29   S26_8294_0  RK_8294_2026-07-01 06:30:00   D 2026-07-01 06:30:00
35   S26_3217_0  U2_3217_2026-07-01 06:30:00   D 2026-07-01 06:30:00
36   S26_3217_1  U2_3217_2026-07-01 06:30:00   D 2026-07-01 06:30:00
37   S26_1465_0  BA_1465_2026-07-01 06:45:00   D 2026-07-01 06:45:00
47   S26_8711_0  BA_8711_2026-07-01 08:00:00   D 2026-07-01 08:00:00
48   S26_0301_0  U2_0301_2026-07-01 07:30:00   D 2026-07-01 07:30:00
49   S26_0301_1  U2_0301_2026-07-01 07:30:00   D 2026-07-01 07:30:00
52   S26_5683_0  FR_5683_2026-07-01 07:30:00   D 2026-07-01 07:30:00
53   S26_0809_0  FR_0809_2026-07-01 07:15:00   D 2026-07-01 07:15:00
68   S26_5091_0  FR_5091_2026-07-01 09:00:00   D 2026-07-01 09:00:00
69   S26_5091_1  FR_5091_2026-07-01 09:00:00   D 2026-07-01 09:00:00
73   S26_1054_0  FR_1054_2026-07-01 09:00:00   D 2026-07-01 09:00:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
4  2026-07-01 06:21:05.763657606 2026-07-01 05:55:00     8           BA
5  2026-07-01 06:39:54.463994322 2026-07-01 06:00:00   15A           U2
6  2026-07-01 06:21:44.201830200 2026-07-01 06:00:00     8           U2
14 2026-07-01 06:25:36.103712568 2026-07-01 06:10:00     4           LH
21 2026-07-01 06:27:13.737929328 2026-07-01 06:15:00     3           LS
22 2026-07-01 06:27:13.737929328 2026-07-01 06:15:00     3           LS
23 2026-07-01 06:27:13.737929328 2026-07-01 06:15:00     3           LS
24 2026-07-01 06:27:13.737929328 2026-07-01 06:15:00     3           LS
29 2026-07-01 06:38:34.660664172 2026-07-01 06:20:00    11           RK
35 2026-07-01 06:35:00.000000000 2026-07-01 06:35:00    24           U2
36 2026-07-01 06:35:00.000000000 2026-07-01 06:35:00    24           U2
37 2026-07-01 06:49:23.468004114 2026-07-01 06:40:00     9           BA
47 2026-07-01 08:00:40.102441500 2026-07-01 07:00:00   105           BA
48 2026-07-01 07:30:58.907524410 2026-07-01 07:00:00   15B           U2
49 2026-07-01 07:30:58.907524410 2026-07-01 07:00:00   15B           U2
52 2026-07-01 07:36:48.710957844 2026-07-01 07:15:00   15B           FR
53 2026-07-01 07:24:16.582127544 2026-07-01 07:20:00    1A           FR
68 2026-07-01 09:01:54.140644350 2026-07-01 08:45:00   16A           FR
69 2026-07-01 09:01:54.140644350 2026-07-01 08:45:00   16A           FR
73 2026-07-01 09:01:34.087978511 2026-07-01 08:55:00   15A           FR

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-08 | cutoff=2026-05-19
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11976
Airlines (sample): ['U2' 'FR' 'KL' 'BA' 'LS' 'LH' 'RK' 'LM' 'AF' 'QR']
Countries (sample): ['FRANCE' 'SLOVAKIA' 'NETHERLANDS' 'SPAIN' 'GREAT BRITAIN' 'POLAND'
 'SWITZERLAND' 'GERMANY' 'CROATIA' 'ITALY']

Pax describe:
count    11976.000000
mean       149.251670
std         50.587497
min          0.000000
25%        128.000000
50%        160.000000
75%        180.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2         FRANCE  International   D  231.0
1       FR       SLOVAKIA  International   D  179.0
2       KL    NETHERLANDS  International   D  141.0
3       FR          SPAIN  International   D  187.0
4       BA  GREAT BRITAIN       Domestic   D  143.0
5       U2  GREAT BRITAIN       Domestic   D  130.0
6       U2          SPAIN  International   D  173.0
7       FR         POLAND  International   D  174.0
8       LS          SPAIN  International   D  213.0
9       U2    SWITZERLAND  International   D  134.0
10      LH        GERMANY  International   D  105.0
11      U2        CROATIA  International   D  173.0
12      FR          ITALY  International   D  158.0
13      FR        ROMANIA  International   D  197.0
14      RK  GREAT BRITAIN       Domestic   D  160.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,461 / 11,976 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
19       RK        MALTA  169.0
35       EC  NETHERLANDS  147.0
102      EC      GERMANY  148.0
104      U2     SLOVENIA  169.0
117      EC        ITALY  145.0
122      BA        ITALY   66.0
157      EC        SPAIN  134.0
158      DS  SWITZERLAND  155.0
161      EC        SPAIN  140.0
230      EC        ITALY  178.0
233      IB        SPAIN  167.0
261      EC      GERMANY  174.0
274      EC       FRANCE  124.0
294      EC        ITALY  150.0
321      EC       FRANCE  167.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17976.05956103347
Total PRMs after rounding: 18483

Raw PRM demand distribution (prm_raw):
count    11976.000000
mean         1.501007
std          1.139361
min          0.000000
25%          0.792062
50%          1.220158
75%          1.687820
max          8.285645
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
2542       QR                     QATAR  310.0   0.026728  8.285645
3894       QR                     QATAR  306.0   0.026728  8.178734
610        QR                     QATAR  305.0   0.026728  8.152006
1188       QR                     QATAR  303.0   0.026728  8.098550
8656       BY                    GREECE  189.0   0.042488  8.030258
10161      BY                    GREECE  189.0   0.042488  8.030258
10452      BY                    GREECE  189.0   0.042488  8.030258
1963       QR                     QATAR  300.0   0.026728  8.018366
2342       QR                     QATAR  300.0   0.026728  8.018366
3315       QR                     QATAR  299.0   0.026728  7.991638
5247       QR                     QATAR  298.0   0.026728  7.964911
988        QR                     QATAR  294.0   0.026728  7.857999
5526       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
8613       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
6343       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
2542            8
3894            8
610             8
1188            8
8656            8
10161           8
10452           8
1963            8
2342            8
3315            8
5247            8
988             8
5526            8
8613            8
6343            8
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=231.0 | Pen=0.00839 | Pax*Pen=1.937 | PRMs=2
[DEBUG flight] Airline=FR | Country=SLOVAKIA | Pax=179.0 | Pen=0.00226 | Pax*Pen=0.405 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=141.0 | Pen=0.00831 | Pax*Pen=1.171 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=187.0 | Pen=0.00966 | Pax*Pen=1.806 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00962 | Pax*Pen=1.375 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=130.0 | Pen=0.00918 | Pax*Pen=1.193 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=173.0 | Pen=0.01381 | Pax*Pen=2.389 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=174.0 | Pen=0.00313 | Pax*Pen=0.545 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=213.0 | Pen=0.02578 | Pax*Pen=5.491 | PRMs=5
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=134.0 | Pen=0.00694 | Pax*Pen=0.930 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=105.0 | Pen=0.00569 | Pax*Pen=0.597 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=173.0 | Pen=0.00421 | Pax*Pen=0.729 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=158.0 | Pen=0.00547 | Pax*Pen=0.864 | PRMs=1
[DEBUG flight] Airline=FR | Country=ROMANIA | Pax=197.0 | Pen=0.00422 | Pax*Pen=0.832 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=160.0 | Pen=0.00637 | Pax*Pen=1.020 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18483
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9891
WCHS     7420
WCHC     1047
OTHER     125
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-08-01 → 2026-09-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11976
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'LS' 'LH' 'RK' 'LM' 'QR']
Countries (sample): ['FRANCE' 'SLOVAKIA' 'NETHERLANDS' 'SPAIN' 'GREAT BRITAIN' 'POLAND'
 'SWITZERLAND' 'GERMANY' 'CROATIA' 'ITALY']

Pax describe:
count    11976.000000
mean       149.251670
std         50.587497
min          0.000000
25%        128.000000
50%        160.000000
75%        180.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   91.0
1       U2         FRANCE  International   D  231.0
2       FR       SLOVAKIA  International   D  179.0
3       KL    NETHERLANDS  International   D  141.0
4       FR          SPAIN  International   D  187.0
5       BA  GREAT BRITAIN       Domestic   D  143.0
6       U2  GREAT BRITAIN       Domestic   D  130.0
7       U2          SPAIN  International   D  173.0
8       FR         POLAND  International   D  174.0
9       LS          SPAIN  International   D  213.0
10      U2    SWITZERLAND  International   D  134.0
11      LH        GERMANY  International   D  105.0
12      U2        CROATIA  International   D  173.0
13      FR          ITALY  International   D  158.0
14      FR        ROMANIA  International   D  197.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,461 / 11,976 (95.7%)

Top missing (Airline, CountryName) combos in future flights:
   Airline     CountryName  flight_rows
4       EC           ITALY          116
1       DS     SWITZERLAND           80
6       EC           SPAIN           80
2       EC          FRANCE           66
5       EC     NETHERLANDS           38
3       EC         GERMANY           36
7       IB           SPAIN           26
9       RK           MALTA           18
8       LG      LUXEMBOURG           18
11      U2        SLOVENIA           18
0       BA           ITALY           10
10      RK         ROMANIA            8
12      ZT  IRISH REPUBLIC            1

Example missing keys:
    Airline  CountryName    Pax
20       RK        MALTA  169.0
35       EC  NETHERLANDS  147.0
102      EC      GERMANY  148.0
104      U2     SLOVENIA  169.0
117      EC        ITALY  145.0
122      BA        ITALY   66.0
157      EC        SPAIN  134.0
158      DS  SWITZERLAND  155.0
161      EC        SPAIN  140.0
230      EC        ITALY  178.0
233      IB        SPAIN  167.0
264      EC      GERMANY  174.0
277      EC       FRANCE  124.0
294      EC        ITALY  150.0
321      EC       FRANCE  167.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17976.05956103347
Total PRMs after rounding: 18483

Raw PRM demand distribution (prm_raw):
count    11976.000000
mean         1.501007
std          1.139361
min          0.000000
25%          0.792062
50%          1.220158
75%          1.687820
max          8.285645
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
2542       QR                     QATAR  310.0   0.026728  8.285645
3894       QR                     QATAR  306.0   0.026728  8.178734
610        QR                     QATAR  305.0   0.026728  8.152006
1188       QR                     QATAR  303.0   0.026728  8.098550
10452      BY                    GREECE  189.0   0.042488  8.030258
8656       BY                    GREECE  189.0   0.042488  8.030258
10161      BY                    GREECE  189.0   0.042488  8.030258
2342       QR                     QATAR  300.0   0.026728  8.018366
1963       QR                     QATAR  300.0   0.026728  8.018366
3315       QR                     QATAR  299.0   0.026728  7.991638
5247       QR                     QATAR  298.0   0.026728  7.964911
988        QR                     QATAR  294.0   0.026728  7.857999
112        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
5526       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
1464       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
2542            8
3894            8
610             8
1188            8
10452           8
8656            8
10161           8
2342            8
1963            8
3315            8
5247            8
988             8
112             8
5526            8
1464            8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=91.0 | Pen=0.00755 | Pax*Pen=0.687 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=231.0 | Pen=0.00839 | Pax*Pen=1.937 | PRMs=2
[DEBUG flight] Airline=FR | Country=SLOVAKIA | Pax=179.0 | Pen=0.00226 | Pax*Pen=0.405 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=141.0 | Pen=0.00831 | Pax*Pen=1.171 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=187.0 | Pen=0.00966 | Pax*Pen=1.806 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00962 | Pax*Pen=1.375 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=130.0 | Pen=0.00918 | Pax*Pen=1.193 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=173.0 | Pen=0.01381 | Pax*Pen=2.389 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=174.0 | Pen=0.00313 | Pax*Pen=0.545 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=213.0 | Pen=0.02578 | Pax*Pen=5.491 | PRMs=5
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=134.0 | Pen=0.00694 | Pax*Pen=0.930 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=105.0 | Pen=0.00569 | Pax*Pen=0.597 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=173.0 | Pen=0.00421 | Pax*Pen=0.729 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=158.0 | Pen=0.00547 | Pax*Pen=0.864 | PRMs=1
[DEBUG flight] Airline=FR | Country=ROMANIA | Pax=197.0 | Pen=0.00422 | Pax*Pen=0.832 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 18483
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9874
WCHS     7425
WCHC     1063
OTHER     121
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=18,483   [197.86s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=18,483   [0.28s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.39s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-07-31 23:30:00 end=2026-09-01 05:45:00 buckets=3002
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-08-08 08:45:00 | 90.0 / 210.0
  2026-08-08 09:00:00 | 90.0 / 210.0
  2026-08-08 08:30:00 | 60.0 / 210.0
  2026-08-08 09:15:00 | 60.0 / 210.0
  2026-08-27 15:00:00 | 60.0 / 210.0
  2026-08-29 08:45:00 | 60.0 / 210.0
  2026-08-29 09:00:00 | 60.0 / 210.0
  2026-08-28 13:45:00 | 60.0 / 210.0
  2026-08-28 14:00:00 | 60.0 / 210.0
  2026-08-01 13:30:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 371
  is_spin by dir:
dir
A    371
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.22392916666666668 33.139995766666665 59.99805311666667
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 78620.1
  total available over horizon: 612180.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 18
  min mini minutes required (forced): 312.1
  total mini minutes available: 90195090.0

Lift rough check:
  lift jobs: 76
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 3076
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
4    S26_6266_0  FR_6266_2026-08-01 06:00:00   D 2026-08-01 05:45:00
5    S26_6266_1  FR_6266_2026-08-01 06:00:00   D 2026-08-01 05:45:00
10   S26_4535_0  FR_4535_2026-08-01 06:15:00   D 2026-08-01 06:15:00
22   S26_3245_0  U2_3245_2026-08-01 06:15:00   D 2026-08-01 06:15:00
23   S26_3245_1  U2_3245_2026-08-01 06:15:00   D 2026-08-01 06:15:00
24   S26_3315_0  U2_3315_2026-08-01 06:45:00   D 2026-08-01 06:45:00
25   S26_0759_0  LS_0759_2026-08-01 07:00:00   D 2026-08-01 07:00:00
26   S26_0759_1  LS_0759_2026-08-01 07:00:00   D 2026-08-01 07:00:00
27   S26_0759_2  LS_0759_2026-08-01 07:00:00   D 2026-08-01 07:00:00
28   S26_0759_3  LS_0759_2026-08-01 07:00:00   D 2026-08-01 07:00:00
29   S26_0759_4  LS_0759_2026-08-01 07:00:00   D 2026-08-01 07:00:00
39   S26_0769_0  LS_0769_2026-08-01 07:15:00   D 2026-08-01 07:15:00
40   S26_0769_1  LS_0769_2026-08-01 07:15:00   D 2026-08-01 07:15:00
41   S26_0769_2  LS_0769_2026-08-01 07:15:00   D 2026-08-01 07:15:00
49   S26_0323_0  U2_0323_2026-08-01 07:15:00   D 2026-08-01 07:15:00
50   S26_0323_1  U2_0323_2026-08-01 07:15:00   D 2026-08-01 07:15:00
54   S26_0723_0  LS_0723_2026-08-01 07:45:00   D 2026-08-01 07:45:00
55   S26_0723_1  LS_0723_2026-08-01 07:45:00   D 2026-08-01 07:45:00
56   S26_0723_2  LS_0723_2026-08-01 07:45:00   D 2026-08-01 07:45:00
57   S26_0703_0  LS_0703_2026-08-01 08:15:00   D 2026-08-01 08:15:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
4  2026-08-01 05:55:03.389145960 2026-08-01 05:55:00   100           FR
5  2026-08-01 05:55:03.389145960 2026-08-01 05:55:00   100           FR
10 2026-08-01 06:18:19.336402308 2026-08-01 06:00:00    11           FR
22 2026-08-01 06:20:00.000000000 2026-08-01 06:20:00    22           U2
23 2026-08-01 06:20:00.000000000 2026-08-01 06:20:00    22           U2
24 2026-08-01 06:49:15.047666939 2026-08-01 06:20:00    11           U2
25 2026-08-01 07:00:08.539720464 2026-08-01 06:30:00     3           LS
26 2026-08-01 07:00:08.539720464 2026-08-01 06:30:00     3           LS
27 2026-08-01 07:00:08.539720464 2026-08-01 06:30:00     3           LS
28 2026-08-01 07:00:08.539720464 2026-08-01 06:30:00     3           LS
29 2026-08-01 07:00:08.539720464 2026-08-01 06:30:00     3           LS
39 2026-08-01 07:23:07.273767708 2026-08-01 06:45:00     6           LS
40 2026-08-01 07:23:07.273767708 2026-08-01 06:45:00     6           LS
41 2026-08-01 07:23:07.273767708 2026-08-01 06:45:00     6           LS
49 2026-08-01 07:15:50.360062230 2026-08-01 07:00:00    11           U2
50 2026-08-01 07:15:50.360062230 2026-08-01 07:00:00    11           U2
54 2026-08-01 07:48:59.299728672 2026-08-01 07:20:00     6           LS
55 2026-08-01 07:48:59.299728672 2026-08-01 07:20:00     6           LS
56 2026-08-01 07:48:59.299728672 2026-08-01 07:20:00     6           LS
57 2026-08-01 08:16:35.744537436 2026-08-01 07:35:00   104           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 1

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 808
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-09 | cutoff=2026-05-19
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11477
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    11477.000000
mean       143.088176
std         52.024302
min          0.000000
25%        117.000000
50%        154.000000
75%        177.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   88.0
1       U2          ITALY  International   D  163.0
2       FR         FRANCE  International   D  124.0
3       FR          ITALY  International   D  165.0
4       KL    NETHERLANDS  International   D   65.0
5       BA  GREAT BRITAIN       Domestic   D   79.0
6       U2  GREAT BRITAIN       Domestic   D  155.0
7       U2  GREAT BRITAIN       Domestic   D  134.0
8       U2  GREAT BRITAIN       Domestic   D  160.0
9       FR          SPAIN  International   D  194.0
10      RK        ROMANIA  International   D  125.0
11      U2  GREAT BRITAIN       Domestic   D  121.0
12      U2        CROATIA  International   D  160.0
13      LH        GERMANY  International   D   62.0
14      U2        TUNISIA  International   D  151.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,039 / 11,477 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  125.0
53       EC  NETHERLANDS  161.0
107      EC        ITALY  128.0
159      EC        SPAIN   84.0
203      U2     SLOVENIA  140.0
293      DS  SWITZERLAND  135.0
301      EC        ITALY  124.0
305      EC        SPAIN  112.0
355      IB        SPAIN  163.0
359      EC  NETHERLANDS  151.0
416      EC        ITALY  154.0
424      DS  SWITZERLAND  110.0
486      EC        ITALY  140.0
495      EC       FRANCE  183.0
521      RK        MALTA  161.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17178.077534383174
Total PRMs after rounding: 17569

Raw PRM demand distribution (prm_raw):
count    11477.000000
mean         1.496739
std          1.178373
min          0.000000
25%          0.756702
50%          1.174484
75%          1.689812
max          8.098550
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
4619       QR                     QATAR  303.0   0.026728  8.098550
7634       BY                    GREECE  189.0   0.042488  8.030258
11277      BY                    GREECE  189.0   0.042488  8.030258
11046      BY                    GREECE  189.0   0.042488  8.030258
6424       BY                    GREECE  189.0   0.042488  8.030258
5380       QR                     QATAR  300.0   0.026728  8.018366
38         QR                     QATAR  300.0   0.026728  8.018366
8952       BY                     SPAIN  185.0   0.042640  7.888470
4889       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
3554       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
2215       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
11453      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
11394      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
6825       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
880        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
4619            8
7634            8
11277           8
11046           8
6424            8
5380            8
38              8
8952            8
4889            8
3554            8
2215            8
11453           8
11394           8
6825            8
880             8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=88.0 | Pen=0.00755 | Pax*Pen=0.664 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=163.0 | Pen=0.00872 | Pax*Pen=1.421 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=124.0 | Pen=0.00686 | Pax*Pen=0.851 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=165.0 | Pen=0.00547 | Pax*Pen=0.902 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=65.0 | Pen=0.00831 | Pax*Pen=0.540 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=79.0 | Pen=0.00962 | Pax*Pen=0.760 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=155.0 | Pen=0.00918 | Pax*Pen=1.423 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=134.0 | Pen=0.00918 | Pax*Pen=1.230 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=160.0 | Pen=0.00918 | Pax*Pen=1.468 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=194.0 | Pen=0.00966 | Pax*Pen=1.873 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=125.0 | Pen=0.01000 | Pax*Pen=1.250 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=121.0 | Pen=0.00918 | Pax*Pen=1.111 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=160.0 | Pen=0.00421 | Pax*Pen=0.674 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=62.0 | Pen=0.00569 | Pax*Pen=0.353 | PRMs=0
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=151.0 | Pen=0.02346 | Pax*Pen=3.542 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 17569
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9371
WCHS     7124
WCHC      971
OTHER     103
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-09-01 → 2026-10-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11477
Airlines (sample): ['AF' 'U2' 'FR' 'KL' 'BA' 'RK' 'LH' 'LS' 'LM' 'QR']
Countries (sample): ['FRANCE' 'ITALY' 'NETHERLANDS' 'GREAT BRITAIN' 'SPAIN' 'ROMANIA'
 'CROATIA' 'GERMANY' 'TUNISIA' 'IRISH REPUBLIC']

Pax describe:
count    11477.000000
mean       143.088176
std         52.024302
min          0.000000
25%        117.000000
50%        154.000000
75%        177.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       AF         FRANCE  International   D   88.0
1       U2          ITALY  International   D  163.0
2       FR         FRANCE  International   D  124.0
3       FR          ITALY  International   D  165.0
4       KL    NETHERLANDS  International   D   65.0
5       BA  GREAT BRITAIN       Domestic   D   79.0
6       U2  GREAT BRITAIN       Domestic   D  155.0
7       U2  GREAT BRITAIN       Domestic   D  134.0
8       U2  GREAT BRITAIN       Domestic   D  160.0
9       FR          SPAIN  International   D  194.0
10      RK        ROMANIA  International   D  125.0
11      U2  GREAT BRITAIN       Domestic   D  121.0
12      U2        CROATIA  International   D  160.0
13      LH        GERMANY  International   D   62.0
14      U2        TUNISIA  International   D  151.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 11,039 / 11,477 (96.2%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY          108
5       EC        SPAIN           68
2       EC       FRANCE           62
1       DS  SWITZERLAND           58
4       EC  NETHERLANDS           52
6       IB        SPAIN           20
11      U2     SLOVENIA           18
7       LG   LUXEMBOURG           16
9       RK        MALTA           16
10      RK      ROMANIA           10
0       BA        ITALY            8
8       RC       FRANCE            2

Example missing keys:
    Airline  CountryName    Pax
10       RK      ROMANIA  125.0
53       EC  NETHERLANDS  161.0
107      EC        ITALY  128.0
159      EC        SPAIN   84.0
203      U2     SLOVENIA  140.0
293      DS  SWITZERLAND  135.0
301      EC        ITALY  124.0
305      EC        SPAIN  112.0
355      IB        SPAIN  163.0
359      EC  NETHERLANDS  151.0
416      EC        ITALY  154.0
424      DS  SWITZERLAND  110.0
486      EC        ITALY  140.0
495      EC       FRANCE  183.0
521      RK        MALTA  161.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 17178.077534383174
Total PRMs after rounding: 17569

Raw PRM demand distribution (prm_raw):
count    11477.000000
mean         1.496739
std          1.178373
min          0.000000
25%          0.756702
50%          1.174484
75%          1.689812
max          8.098550
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline               CountryName    Pax  _pen_used  _prm_raw  \
4619       QR                     QATAR  303.0   0.026728  8.098550
7634       BY                    GREECE  189.0   0.042488  8.030258
11277      BY                    GREECE  189.0   0.042488  8.030258
11046      BY                    GREECE  189.0   0.042488  8.030258
6424       BY                    GREECE  189.0   0.042488  8.030258
5380       QR                     QATAR  300.0   0.026728  8.018366
38         QR                     QATAR  300.0   0.026728  8.018366
8952       BY                     SPAIN  185.0   0.042640  7.888470
4889       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
3554       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
2215       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
11453      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
11394      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
6825       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468
880        VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468

       _prm_round
4619            8
7634            8
11277           8
11046           8
6424            8
5380            8
38              8
8952            8
4889            8
3554            8
2215            8
11453           8
11394           8
6825            8
880             8
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=88.0 | Pen=0.00755 | Pax*Pen=0.664 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=163.0 | Pen=0.00872 | Pax*Pen=1.421 | PRMs=1
[DEBUG flight] Airline=FR | Country=FRANCE | Pax=124.0 | Pen=0.00686 | Pax*Pen=0.851 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=165.0 | Pen=0.00547 | Pax*Pen=0.902 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=65.0 | Pen=0.00831 | Pax*Pen=0.540 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=79.0 | Pen=0.00962 | Pax*Pen=0.760 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=155.0 | Pen=0.00918 | Pax*Pen=1.423 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=134.0 | Pen=0.00918 | Pax*Pen=1.230 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=160.0 | Pen=0.00918 | Pax*Pen=1.468 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=194.0 | Pen=0.00966 | Pax*Pen=1.873 | PRMs=2
[DEBUG flight] Airline=RK | Country=ROMANIA | Pax=125.0 | Pen=0.01000 | Pax*Pen=1.250 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=121.0 | Pen=0.00918 | Pax*Pen=1.111 | PRMs=1
[DEBUG flight] Airline=U2 | Country=CROATIA | Pax=160.0 | Pen=0.00421 | Pax*Pen=0.674 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=62.0 | Pen=0.00569 | Pax*Pen=0.353 | PRMs=0
[DEBUG flight] Airline=U2 | Country=TUNISIA | Pax=151.0 | Pen=0.02346 | Pax*Pen=3.542 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 17569
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     9325
WCHS     7156
WCHC      994
OTHER      94
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=17,569   [229.72s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=17,569   [0.33s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.40s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-08-31 22:15:00 end=2026-10-01 06:00:00 buckets=2912
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-09-17 07:45:00 | 75.0 / 210.0
  2026-09-17 08:00:00 | 75.0 / 210.0
  2026-09-24 14:30:00 | 75.0 / 210.0
  2026-09-24 14:45:00 | 75.0 / 210.0
  2026-09-24 15:00:00 | 75.0 / 210.0
  2026-09-24 15:15:00 | 75.0 / 210.0
  2026-09-01 15:30:00 | 60.0 / 210.0
  2026-09-01 15:45:00 | 60.0 / 210.0
  2026-09-15 14:45:00 | 60.0 / 210.0
  2026-09-03 12:15:00 | 60.0 / 210.0

[Spin flag debug]
  is_spin rows: 336
  is_spin by dir:
dir
A    336
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.6704168833333333 34.354020275 59.72577368333334
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 70011.7
  total available over horizon: 594840.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 23
  min mini minutes required (forced): 394.2
  total mini minutes available: 87491040.0

Lift rough check:
  lift jobs: 51
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2924
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
0    S26_1887_0  AF_1887_2026-09-01 06:00:00   D 2026-09-01 05:45:00
4    S26_0922_0  KL_0922_2026-09-01 06:00:00   D 2026-09-01 05:45:00
14   S26_3329_0  U2_3329_2026-09-01 06:30:00   D 2026-09-01 06:30:00
15   S26_3329_1  U2_3329_2026-09-01 06:30:00   D 2026-09-01 06:30:00
16   S26_3329_2  U2_3329_2026-09-01 06:30:00   D 2026-09-01 06:30:00
17   S26_3329_3  U2_3329_2026-09-01 06:30:00   D 2026-09-01 06:30:00
24   S26_8701_0  BA_8701_2026-09-01 06:30:00   D 2026-09-01 06:15:00
26   S26_0717_0  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
27   S26_0717_1  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
28   S26_0717_2  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
29   S26_0717_3  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
30   S26_0717_4  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
31   S26_0717_5  LS_0717_2026-09-01 06:30:00   D 2026-09-01 06:30:00
32   S26_0321_0  LM_0321_2026-09-01 07:30:00   D 2026-09-01 07:15:00
48   S26_0723_0  LS_0723_2026-09-01 07:30:00   D 2026-09-01 07:30:00
49   S26_0723_1  LS_0723_2026-09-01 07:30:00   D 2026-09-01 07:30:00
63   S26_6698_0  FR_6698_2026-09-01 08:45:00   D 2026-09-01 08:45:00
64   S26_3501_0  D8_3501_2026-09-01 08:30:00   D 2026-09-01 08:30:00
74   S26_5599_0  FR_5599_2026-09-01 09:00:00   D 2026-09-01 09:00:00
84   S26_0037_0  UA_0037_2026-09-01 11:00:00   D 2026-09-01 11:00:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
0  2026-09-01 05:58:43.864105644 2026-09-01 05:40:00    31           AF
4  2026-09-01 05:59:44.791780902 2026-09-01 05:45:00    10           KL
14 2026-09-01 06:36:47.401472262 2026-09-01 06:15:00    20           U2
15 2026-09-01 06:36:47.401472262 2026-09-01 06:15:00    20           U2
16 2026-09-01 06:36:47.401472262 2026-09-01 06:15:00    20           U2
17 2026-09-01 06:36:47.401472262 2026-09-01 06:15:00    20           U2
24 2026-09-01 06:27:52.041899910 2026-09-01 06:20:00     9           BA
26 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
27 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
28 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
29 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
30 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
31 2026-09-01 06:34:36.231782016 2026-09-01 06:30:00     2           LS
32 2026-09-01 07:28:45.948760830 2026-09-01 06:40:00     8           LM
48 2026-09-01 07:38:22.523627910 2026-09-01 07:20:00    14           LS
49 2026-09-01 07:38:22.523627910 2026-09-01 07:20:00    14           LS
63 2026-09-01 08:49:46.065369030 2026-09-01 08:20:00    1B           FR
64 2026-09-01 08:39:47.529264156 2026-09-01 08:25:00   15B           D8
74 2026-09-01 09:10:00.000000000 2026-09-01 09:10:00   15B           FR
84 2026-09-01 11:00:18.497746836 2026-09-01 09:40:00    10           UA

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 756
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 634
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.


C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Running S26 2026-10 | cutoff=2026-05-19
→ FORECAST ONLY

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 9129
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'SPAIN' 'GREECE' 'GERMANY' 'POLAND']

Pax describe:
count    9129.000000
mean      145.450214
std        53.303880
min         0.000000
25%       118.000000
50%       158.000000
75%       180.000000
max       397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  178.0
1       AF         FRANCE  International   D  111.0
2       FR         LATVIA  International   D  179.0
3       KL    NETHERLANDS  International   D   82.0
4       BA  GREAT BRITAIN       Domestic   D   81.0
5       U2       PORTUGAL  International   D  166.0
6       U2          ITALY  International   D  147.0
7       FR          SPAIN  International   D  141.0
8       LS         GREECE  International   D  201.0
9       U2  GREAT BRITAIN       Domestic   D   91.0
10      U2  GREAT BRITAIN       Domestic   D   67.0
11      U2         FRANCE  International   D  193.0
12      LH        GERMANY  International   D   89.0
13      FR          ITALY  International   D  173.0
14      LS          SPAIN  International   D  224.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 8,751 / 9,129 (95.9%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY           90
2       EC       FRANCE           68
5       EC        SPAIN           54
1       DS  SWITZERLAND           48
4       EC  NETHERLANDS           40
10      RK        MALTA           16
12      U2     SLOVENIA           14
7       LG   LUXEMBOURG           14
6       IB        SPAIN           14
0       BA        ITALY            8
11      RK      ROMANIA            6
8       LS      ICELAND            4
9       RC      ICELAND            2

Example missing keys:
    Airline  CountryName    Pax
44       EC        ITALY  148.0
49       DS  SWITZERLAND   89.0
112      EC        ITALY  120.0
121      EC       FRANCE  175.0
148      RK        MALTA  157.0
170      IB        SPAIN  159.0
177      DS  SWITZERLAND   51.0
182      EC       FRANCE  175.0
186      EC        SPAIN  143.0
194      EC        SPAIN  148.0
241      EC       FRANCE  154.0
254      EC        ITALY  150.0
263      EC        ITALY  126.0
303      EC       FRANCE  223.0
312      EC        ITALY  164.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13794.431519758838
Total PRMs after rounding: 14125

Raw PRM demand distribution (prm_raw):
count    9129.000000
mean        1.511056
std         1.186593
min         0.000000
25%         0.773210
50%         1.202959
75%         1.700212
max         8.152006
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline               CountryName    Pax  _pen_used  _prm_raw  _prm_round
3659      QR                     QATAR  305.0   0.026728  8.152006           8
235       QR                     QATAR  305.0   0.026728  8.152006           8
6288      QR                     QATAR  304.0   0.026728  8.125278           8
999       QR                     QATAR  303.0   0.026728  8.098550           8
1650      BY                    GREECE  189.0   0.042488  8.030258           8
6736      BY                    GREECE  189.0   0.042488  8.030258           8
4492      BY                    GREECE  189.0   0.042488  8.030258           8
4359      BY                    GREECE  189.0   0.042488  8.030258           8
2391      QR                     QATAR  299.0   0.026728  7.991638           8
1371      QR                     QATAR  294.0   0.026728  7.857999           8
503       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
4965      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
8831      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
6384      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
2996      QR                     QATAR  292.0   0.026728  7.804543           8
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=178.0 | Pen=0.00872 | Pax*Pen=1.552 | PRMs=2
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=111.0 | Pen=0.00755 | Pax*Pen=0.838 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=179.0 | Pen=0.00414 | Pax*Pen=0.741 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=82.0 | Pen=0.00831 | Pax*Pen=0.681 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=81.0 | Pen=0.00962 | Pax*Pen=0.779 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=166.0 | Pen=0.00785 | Pax*Pen=1.303 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=147.0 | Pen=0.00872 | Pax*Pen=1.281 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=141.0 | Pen=0.00966 | Pax*Pen=1.362 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=201.0 | Pen=0.01748 | Pax*Pen=3.513 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=91.0 | Pen=0.00918 | Pax*Pen=0.835 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=67.0 | Pen=0.00918 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=193.0 | Pen=0.00839 | Pax*Pen=1.619 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=89.0 | Pen=0.00569 | Pax*Pen=0.506 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=173.0 | Pen=0.00547 | Pax*Pen=0.946 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=224.0 | Pen=0.02578 | Pax*Pen=5.775 | PRMs=6

[DEBUG ingest_s26]
Total PRM jobs (rows): 14125
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7486
WCHS     5780
WCHC      782
OTHER      77
Name: count, dtype: int64

PRM OPT — S26 Scenario 2 (v2) — Sensitivity
Window : 2026-10-01 → 2026-11-01
vertical_cycle_grid: [10]

[1/4] ingest_s26…

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 9129
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'SPAIN' 'GREECE' 'GERMANY' 'POLAND']

Pax describe:
count    9129.000000
mean      145.450214
std        53.303880
min         0.000000
25%       118.000000
50%       158.000000
75%       180.000000
max       397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  178.0
1       AF         FRANCE  International   D  111.0
2       FR         LATVIA  International   D  179.0
3       KL    NETHERLANDS  International   D   82.0
4       BA  GREAT BRITAIN       Domestic   D   81.0
5       U2       PORTUGAL  International   D  166.0
6       U2          ITALY  International   D  147.0
7       FR          SPAIN  International   D  141.0
8       LS         GREECE  International   D  201.0
9       U2  GREAT BRITAIN       Domestic   D   91.0
10      U2  GREAT BRITAIN       Domestic   D   67.0
11      U2         FRANCE  International   D  193.0
12      LH        GERMANY  International   D   89.0
13      FR          ITALY  International   D  173.0
14      LS          SPAIN  International   D  224.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 118
Flights with penetration match: 8,751 / 9,129 (95.9%)

Top missing (Airline, CountryName) combos in future flights:
   Airline  CountryName  flight_rows
3       EC        ITALY           90
2       EC       FRANCE           68
5       EC        SPAIN           54
1       DS  SWITZERLAND           48
4       EC  NETHERLANDS           40
10      RK        MALTA           16
12      U2     SLOVENIA           14
7       LG   LUXEMBOURG           14
6       IB        SPAIN           14
0       BA        ITALY            8
11      RK      ROMANIA            6
8       LS      ICELAND            4
9       RC      ICELAND            2

Example missing keys:
    Airline  CountryName    Pax
44       EC        ITALY  148.0
49       DS  SWITZERLAND   89.0
112      EC        ITALY  120.0
121      EC       FRANCE  175.0
148      RK        MALTA  157.0
170      IB        SPAIN  159.0
177      DS  SWITZERLAND   51.0
182      EC       FRANCE  175.0
186      EC        SPAIN  143.0
194      EC        SPAIN  148.0
241      EC       FRANCE  154.0
254      EC        ITALY  150.0
263      EC        ITALY  126.0
303      EC       FRANCE  223.0
312      EC        ITALY  164.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13794.43151975884
Total PRMs after rounding: 14125

Raw PRM demand distribution (prm_raw):
count    9129.000000
mean        1.511056
std         1.186593
min         0.000000
25%         0.773210
50%         1.202959
75%         1.700212
max         8.152006
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline               CountryName    Pax  _pen_used  _prm_raw  _prm_round
3659      QR                     QATAR  305.0   0.026728  8.152006           8
235       QR                     QATAR  305.0   0.026728  8.152006           8
6288      QR                     QATAR  304.0   0.026728  8.125278           8
999       QR                     QATAR  303.0   0.026728  8.098550           8
1650      BY                    GREECE  189.0   0.042488  8.030258           8
6736      BY                    GREECE  189.0   0.042488  8.030258           8
4492      BY                    GREECE  189.0   0.042488  8.030258           8
4359      BY                    GREECE  189.0   0.042488  8.030258           8
2391      QR                     QATAR  299.0   0.026728  7.991638           8
1371      QR                     QATAR  294.0   0.026728  7.857999           8
503       VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
4965      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
8831      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
6384      VS  UNITED STATES OF AMERICA  397.0   0.019717  7.827468           8
2996      QR                     QATAR  292.0   0.026728  7.804543           8
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=178.0 | Pen=0.00872 | Pax*Pen=1.552 | PRMs=2
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=111.0 | Pen=0.00755 | Pax*Pen=0.838 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=179.0 | Pen=0.00414 | Pax*Pen=0.741 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=82.0 | Pen=0.00831 | Pax*Pen=0.681 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=81.0 | Pen=0.00962 | Pax*Pen=0.779 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=166.0 | Pen=0.00785 | Pax*Pen=1.303 | PRMs=1
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=147.0 | Pen=0.00872 | Pax*Pen=1.281 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=141.0 | Pen=0.00966 | Pax*Pen=1.362 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=201.0 | Pen=0.01748 | Pax*Pen=3.513 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=91.0 | Pen=0.00918 | Pax*Pen=0.835 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=67.0 | Pen=0.00918 | Pax*Pen=0.615 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=193.0 | Pen=0.00839 | Pax*Pen=1.619 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=89.0 | Pen=0.00569 | Pax*Pen=0.506 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=173.0 | Pen=0.00547 | Pax*Pen=0.946 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=224.0 | Pen=0.02578 | Pax*Pen=5.775 | PRMs=6

[DEBUG ingest_s26]
Total PRM jobs (rows): 14125
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7488
WCHS     5775
WCHC      783
OTHER      79
Name: count, dtype: int64
    ✓ ingest_s26 done | rows=14,125   [75.96s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=14,125   [0.60s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.97s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 0}

Bucket horizon: start=2026-10-01 00:15:00 end=2026-10-25 05:00:00 buckets=2324
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2026-10-08 08:45:00 | 75.0 / 210.0
  2026-10-08 09:00:00 | 75.0 / 210.0
  2026-10-08 09:15:00 | 60.0 / 210.0
  2026-10-12 08:30:00 | 60.0 / 210.0
  2026-10-01 16:45:00 | 60.0 / 210.0
  2026-10-08 14:30:00 | 45.0 / 210.0
  2026-10-08 14:45:00 | 45.0 / 210.0
  2026-10-08 09:30:00 | 45.0 / 210.0
  2026-10-12 13:15:00 | 45.0 / 210.0
  2026-10-12 13:30:00 | 45.0 / 210.0

[Spin flag debug]
  is_spin rows: 265
  is_spin by dir:
dir
A    265
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 0.06300793333333334 30.522899716666664 59.80600083333333
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 3.0

Amb minutes (necessary condition):
  min required (vertical-only): 57707.0
  total available over horizon: 475020.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 11
  min mini minutes required (forced): 189.4
  total mini minutes available: 69824580.0

Lift rough check:
  lift jobs: 58
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 2434
Examples (first 20):
   Passenger ID                   flight_key dir                   t  \
j
6    S26_3321_0  U2_3321_2026-10-01 05:45:00   D 2026-10-01 05:45:00
8    S26_6698_0  FR_6698_2026-10-01 06:30:00   D 2026-10-01 06:30:00
9    S26_0741_0  LS_0741_2026-10-01 06:00:00   D 2026-10-01 06:00:00
10   S26_0741_1  LS_0741_2026-10-01 06:00:00   D 2026-10-01 06:00:00
11   S26_0741_2  LS_0741_2026-10-01 06:00:00   D 2026-10-01 06:00:00
12   S26_0741_3  LS_0741_2026-10-01 06:00:00   D 2026-10-01 06:00:00
14   S26_0807_0  U2_0807_2026-10-01 06:15:00   D 2026-10-01 06:15:00
17   S26_0965_0  LH_0965_2026-10-01 06:00:00   D 2026-10-01 06:00:00
26   S26_8750_0  FR_8750_2026-10-01 06:30:00   D 2026-10-01 06:30:00
27   S26_5579_0  FR_5579_2026-10-01 06:45:00   D 2026-10-01 06:45:00
28   S26_5579_1  FR_5579_2026-10-01 06:45:00   D 2026-10-01 06:45:00
29   S26_0769_0  LS_0769_2026-10-01 07:15:00   D 2026-10-01 07:15:00
30   S26_0769_1  LS_0769_2026-10-01 07:15:00   D 2026-10-01 07:15:00
31   S26_0769_2  LS_0769_2026-10-01 07:15:00   D 2026-10-01 07:15:00
32   S26_4524_0  FR_4524_2026-10-01 07:15:00   D 2026-10-01 07:00:00
37   S26_3241_0  U2_3241_2026-10-01 07:15:00   D 2026-10-01 07:15:00
40   S26_0775_0  LS_0775_2026-10-01 07:15:00   D 2026-10-01 07:15:00
41   S26_0775_1  LS_0775_2026-10-01 07:15:00   D 2026-10-01 07:15:00
42   S26_0775_2  LS_0775_2026-10-01 07:15:00   D 2026-10-01 07:15:00
43   S26_0775_3  LS_0775_2026-10-01 07:15:00   D 2026-10-01 07:15:00

              hard_deadline_time      sla_start_time Stand Airline Code
j
6  2026-10-01 05:55:00.000000000 2026-10-01 05:55:00     8           U2
8  2026-10-01 06:34:12.154591068 2026-10-01 06:00:00    22           FR
9  2026-10-01 06:02:21.379005516 2026-10-01 06:00:00    10           LS
10 2026-10-01 06:02:21.379005516 2026-10-01 06:00:00    10           LS
11 2026-10-01 06:02:21.379005516 2026-10-01 06:00:00    10           LS
12 2026-10-01 06:02:21.379005516 2026-10-01 06:00:00    10           LS
14 2026-10-01 06:18:21.278429820 2026-10-01 06:10:00    20           U2
17 2026-10-01 06:10:00.000000000 2026-10-01 06:10:00     2           LH
26 2026-10-01 06:35:00.000000000 2026-10-01 06:35:00    1A           FR
27 2026-10-01 06:49:23.886568200 2026-10-01 06:40:00    10           FR
28 2026-10-01 06:49:23.886568200 2026-10-01 06:40:00    10           FR
29 2026-10-01 07:18:56.817893010 2026-10-01 06:45:00   16B           LS
30 2026-10-01 07:18:56.817893010 2026-10-01 06:45:00   16B           LS
31 2026-10-01 07:18:56.817893010 2026-10-01 06:45:00   16B           LS
32 2026-10-01 07:14:47.102532744 2026-10-01 06:50:00    20           FR
37 2026-10-01 07:15:02.862818154 2026-10-01 07:00:00    11           U2
40 2026-10-01 07:18:42.641695818 2026-10-01 07:10:00     2           LS
41 2026-10-01 07:18:42.641695818 2026-10-01 07:10:00     2           LS
42 2026-10-01 07:18:42.641695818 2026-10-01 07:10:00     2           LS
43 2026-10-01 07:18:42.641695818 2026-10-01 07:10:00     2           LS

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 2

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 659
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 533
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 7

✅ Tight-window checks complete.

✅ Pre-solver debug complete.

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()
C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

,month,cutoff_used,S1_PeakAmb,S1_PeakMini,S2_PeakAmb,S2_PeakMini,SLA_all,SLA_arr,SLA_dep
0,2026-04,2026-05-19,10,3,11,11,0.943624,0.910186,0.994009
1,2026-05,2026-05-19,9,2,12,8,0.952840,0.977883,0.928282
2,2026-06,2026-05-19,10,1,12,7,0.944198,0.975286,0.913962
3,2026-07,2026-05-19,11,1,14,8,0.949008,0.973480,0.924181
4,2026-08,2026-05-19,11,2,12,9,0.950116,0.975901,0.924496
5,2026-09,2026-05-19,9,2,12,8,0.950538,0.974757,0.926045
6,2026-10,2026-05-19,9,1,11,7,0.949593,0.977991,0.921717

Run S25 Scenario 1 (baseline)

In [3]:

out_s1 = run_s25_s1(START_S25, END_S25, toggles=toggles)

report_s1 = build_run_report_s1(out_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s1)

# # 15-min peak day detail:
# report_s1["peak_day_report"]["bucket_level"].to_csv("S1_peak_day_15min.csv")
# report_s1["peak_day_report"]["hourly"].to_csv("S1_peak_day_hourly.csv")

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}

==============================================================================
PRM OPT — Scenario 1 (Policy Baseline) Output
==============================================================================

[1] Horizon Summary (Peak across horizon; gaps vs CURRENT fleet)
  PeakAmb       : 8
  PeakMini      : 3
  PeakDrivers   : 9
  PeakVehAgents : 9
  CurrentAmb    : 14
  CurrentMini   : 3
  GapAmb        : 0
  GapMini       : 0

[2] Peak Day (most PRM jobs) — Hourly Requirement + Gaps
  Peak day: 2025-04-29 | jobs=504
  Current fleet: Amb=14 | Mini=3
  Peak hour req : Amb=6 | Mini=1 | Drivers=7 | VehAgents=7
  Peak hour gap : Amb=0 | Mini=0

  Hourly table (first rows):
                     Amb_req  Mini_req  Drivers_req  VehAgents_req  Amb_gap  Mini_gap
s
2025-04-29 00:00:00      3.0       0.0          3.0            3.0      0.0       0.0
2025-04-29 01:00:00      NaN       NaN          NaN            NaN      NaN       NaN
2025-04-29 02:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 03:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 04:00:00      3.0       0.0          3.0            3.0      0.0       0.0
2025-04-29 05:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 06:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 07:00:00      3.0       0.0          3.0            3.0      0.0       0.0
2025-04-29 08:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 09:00:00      1.0       0.0          1.0            1.0      0.0       0.0
2025-04-29 10:00:00      3.0       1.0          4.0            4.0      0.0       0.0
2025-04-29 11:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 12:00:00      3.0       1.0          4.0            4.0      0.0       0.0
2025-04-29 13:00:00      5.0       1.0          5.0            5.0      0.0       0.0
2025-04-29 14:00:00      6.0       0.0          6.0            6.0      0.0       0.0
2025-04-29 15:00:00      6.0       1.0          7.0            7.0      0.0       0.0
2025-04-29 16:00:00      3.0       1.0          4.0            4.0      0.0       0.0
2025-04-29 17:00:00      5.0       1.0          6.0            6.0      0.0       0.0
2025-04-29 18:00:00      2.0       0.0          2.0            2.0      0.0       0.0
2025-04-29 19:00:00      2.0       1.0          3.0            3.0      0.0       0.0
2025-04-29 20:00:00      0.0       0.0          0.0            0.0      0.0       0.0
2025-04-29 21:00:00      0.0       0.0          0.0            0.0      0.0       0.0
2025-04-29 22:00:00      3.0       0.0          3.0            3.0      0.0       0.0
2025-04-29 23:00:00      2.0       0.0          2.0            2.0      0.0       0.0

Done.
==============================================================================

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:717: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_level.resample("H").max()

Run S25 Scenario 2 (optimised)

In [4]:

sens = run_s25_s2_v2_sensitivity(
    start=START_S25,
    end=END_S25,
    vertical_cycle_grid=[10],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)

# Build a comparison table

for r in sens["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY: {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r)

    # attach assumption for printing (not rebuilding anything)
    report["assumptions"] = {
        "vertical_cycle_mins": r["vertical_cycle_mins"]
    }

    print_run_report(report)

PRM OPT — S25 Scenario 2 (v2) — Sensitivity
Window : 2025-04-01 → 2025-05-01
vertical_cycle_grid: [10]

[1/4] ingest_s25…

Unmatched passenger rows after merge (missing Chocks DT): 462
Unique unmatched flight keys: 304

Unmatched key reasons:
reason
no_flight_candidate               259
scheduled_dt_mismatch              42
exact_match_should_have_joined      3
Name: count, dtype: int64

Dropped 455 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
    ✓ ingest_s25 done | rows=12,701   [88.47s]
[2/4] build_jobs…
    ✓ build_jobs done | jobs=12,701   [0.29s]
[3/4] build_tau + classes + spin_removed…
    ✓ params built | N_AMB=14   [0.41s]
[4/4] pre_solve_debug (no solver)…

======================================================================
PRE-SOLVER FEASIBILITY DEBUG (no solver)
======================================================================
✅ Required columns present.
Missingness: {'sla_start_time': 0, 'Scheduled Flight DT': 0, 'Chocks DT': 7}

Top missing-flight-anchor by Airline Code + dir (top 20):
Airline Code  dir
FR            D      6
RK            D      1
dtype: int64

Bucket horizon: start=2025-04-01 00:00:00 end=2025-05-01 04:30:00 buckets=2899
✅ All t buckets lie in horizon.
✅ All sla_start buckets lie in horizon.

Jobs with release bucket AFTER hard deadline: 0

Jobs impossible even with SLA breach y=1 (earliest_delay > L + M_BIG): 0

spin_removed > total amb minutes (impossible): 0
spin_removed >= total amb minutes (SATURATED -> available=0): 0
Top 10 spin_removed buckets (bucket, removed_mins, cap_mins):
  2025-04-15 12:00:00 | 45.0 / 210.0
  2025-04-15 12:15:00 | 45.0 / 210.0
  2025-04-15 12:30:00 | 45.0 / 210.0
  2025-04-17 14:45:00 | 30.0 / 210.0
  2025-04-29 14:30:00 | 30.0 / 210.0
  2025-04-29 14:45:00 | 30.0 / 210.0
  2025-04-29 15:00:00 | 30.0 / 210.0
  2025-04-29 15:15:00 | 30.0 / 210.0
  2025-04-21 12:00:00 | 30.0 / 210.0
  2025-04-21 12:15:00 | 30.0 / 210.0

[Spin flag debug]
  is_spin rows: 107
  is_spin by dir:
dir
A    107
Name: count, dtype: int64
  Minutes on Chocks (spin rows) min/median/max: 33.0 49.0 60.0
  Turnaround Vertical Count (spin rows) min/median/max: 1.0 1.0 5.0

Amb minutes (necessary condition):
  min required (vertical-only): 53080.5
  total available over horizon: 603990.0

Minibus forced-only (necessary condition):
  forced Mini jobs: 19
  min mini minutes required (forced): 304.6
  total mini minutes available: 87100455.0

Lift rough check:
  lift jobs: 45
  max jobs per bucket: 20

Ferry mini reservation: none

Jobs with ZERO feasible horizontal modes: 0

Missing tau keys: 0

spin_removed keys off-grid: 0

======================================================================
TIGHT-WINDOW FEASIBILITY CHECKS (2A–2E) — NO SOLVER
======================================================================
Deadlines off bucket grid (count): 0

Tight-window jobs (must be served in exactly one bucket): 179
Examples (first 20):
      Passenger ID                   flight_key dir                   t  \
j
5         10684489   LS_775_2025-04-01 07:00:00   D 2025-04-01 07:00:00
46        10691644  U2_3241_2025-04-01 09:45:00   D 2025-04-01 09:30:00
139       10695011  FR_6656_2025-04-01 15:15:00   D 2025-04-01 15:15:00
314       10707532   U2_214_2025-04-03 08:45:00   D 2025-04-03 08:45:00
347       10709017   U2_341_2025-04-03 13:30:00   D 2025-04-03 13:30:00
401       10710804   U2_313_2025-04-03 20:00:00   D 2025-04-03 20:00:00
557       10719433   LS_745_2025-04-05 16:00:00   D 2025-04-05 16:00:00
787       10734061  U2_3203_2025-04-06 14:15:00   D 2025-04-06 14:15:00
800       10734529  U2_3243_2025-04-06 16:15:00   D 2025-04-06 16:15:00
815       10735509   U2_335_2025-04-06 19:15:00   D 2025-04-06 19:15:00
846       10735976   FR_479_2025-04-06 16:45:00   D 2025-04-06 16:45:00
886       10740779   U2_315_2025-04-07 10:00:00   D 2025-04-07 10:00:00
940       10742588  U2_3201_2025-04-07 15:15:00   D 2025-04-07 15:15:00
978       10743954   RK_179_2025-04-07 15:15:00   D 2025-04-07 15:15:00
982       10744091   U2_335_2025-04-07 20:30:00   D 2025-04-07 20:30:00
983       10744093   U2_335_2025-04-07 20:45:00   D 2025-04-07 20:30:00
1196      10758563   LS_717_2025-04-10 06:00:00   D 2025-04-10 06:00:00
1203      10758916   LS_775_2025-04-10 07:00:00   D 2025-04-10 07:00:00
1204      10758917   LS_775_2025-04-10 07:00:00   D 2025-04-10 07:00:00
1267      10760524  U2_3223_2025-04-09 17:15:00   D 2025-04-09 17:15:00

      hard_deadline_time      sla_start_time Stand Airline Code
j
5    2025-04-01 07:10:00 2025-04-01 07:10:00    10           LS
46   2025-04-01 09:40:08 2025-04-01 09:40:00    24           U2
139  2025-04-01 15:20:00 2025-04-01 15:20:00   15B           FR
314  2025-04-03 08:50:00 2025-04-03 08:50:00     8           U2
347  2025-04-03 13:35:00 2025-04-03 13:35:00     3           U2
401  2025-04-03 20:00:48 2025-04-03 19:10:00    22           U2
557  2025-04-05 16:10:00 2025-04-05 16:10:00    10           LS
787  2025-04-06 14:25:00 2025-04-06 14:25:00    22           U2
800  2025-04-06 16:20:00 2025-04-06 16:20:00    22           U2
815  2025-04-06 19:20:13 2025-04-06 19:15:00   15B           U2
846  2025-04-06 16:50:00 2025-04-06 16:50:00   15B           FR
886  2025-04-07 10:10:00 2025-04-07 10:10:00    20           U2
940  2025-04-07 15:25:00 2025-04-07 15:25:00    24           U2
978  2025-04-07 15:17:38 2025-04-07 15:05:00   16A           RK
982  2025-04-07 20:39:27 2025-04-07 19:30:00    10           U2
983  2025-04-07 20:42:27 2025-04-07 19:30:00    10           U2
1196 2025-04-10 06:05:00 2025-04-10 06:05:00    10           LS
1203 2025-04-10 07:10:00 2025-04-10 07:10:00   102           LS
1204 2025-04-10 07:10:00 2025-04-10 07:10:00   102           LS
1267 2025-04-09 17:17:56 2025-04-09 16:15:00    11           U2

Lift tight-window check:
  max lift jobs per bucket: 20
  worst tight lift count in a bucket: 0

Amb tight-window time check (vertical-only, spillover-aware):
  Total ambulifts (from classes): 14
  Spill cap (buckets): 12
  tight vertical jobs: 29
  saturated (avail=0) buckets: 0
  tight vertical jobs starting in saturated bucket: 0
  buckets with spilled vertical demand: 49
  infeasible buckets (req > avail): 0
✅ No spillover-aware ambulift time overload from tight vertical jobs.

Flight+bucket vertical seat check (vertical-only):
  total ambulift seats in a bucket (if all ambs assigned to one flight): 90
  worst tight vertical seats for a flight in a bucket: 2

✅ Tight-window checks complete.

✅ Pre-solver debug complete.
    ✓ pre_solve_debug done   [0.21s]

----------------------------------------------------------------------
[SENS] vertical_cycle_mins = 10
----------------------------------------------------------------------
    ✓ ConcreteModel created   [0.00s]
    ✓ constants + toggles loaded   [0.00s]
    ✓ bucket timeline built | buckets=2,899   [0.02s]
    ✓ sets built | J=12,701 | F=7,608   [0.01s]
    ✓ SLA maps built (release/sla_start/deadline)   [1.10s]
    ✓ JB set built | JB=153,497   [0.76s]
    ✓ FB set built | FB=85,174   [0.17s]
    ✓ vehicle classes set | VC=19 | N_AMB=14 | N_MINI=2003   [0.00s]
    ✓ vars created | x=38,103 | JB=153,497 | A=153,497 | U=460,491 | k=1,618,306 | V=85,174 | Z=85,174 | W=85,174   [7.08s]
    ✓ objective created   [17.38s]
    ✓ constraints: U linearisation (JB x M)   [9.04s]
    ✓ constraints: passenger timing + SLA   [0.64s]
    ✓ constraints: eligibility   [0.19s]
    ✓ constraints: vertical visit   [49.51s]
    ✓ constraints: standby indicators   [8.29s]
    ✓ constraints: per-flight capacity (seat/wc)   [30.99s]
    ✓ constraints: FleetExclusive + TotalMiniCapWithFerry   [11.85s]
    ✓ constraints: AmbTimeCap + MiniTimeCap (trip-based)   [164.38s]
    ✓ constraints: staff   [19.61s]
    ✓ constraints: LiftCap   [0.15s]
    ✓ build_pyomo_model complete | total=321.18s   [0.00s]
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 3293487 rows; 2888013 cols; 20249118 nonzeros; 2888013 integer variables (1261010 binary)
Coefficient ranges:
  Matrix  [1e-01, 1e+04]
  Cost    [1e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 3e+04]
Presolving model
2389417 rows, 2440050 cols, 14909877 nonzeros 15s
1966466 rows, 2168832 cols, 12280104 nonzeros 117s
Presolve reductions: rows 1966466(-1327021); columns 2168832(-719181); nonzeros 12280104(-7969014)

Solving MIP model with:
   1966466 rows
   2168832 cols (2157882 binary, 10950 integer, 0 implied int., 0 continuous, 0 domain fixed)
   12280104 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            496833746.7443     Large        0      0      0         0   408.1s
         0       0         0   0.00%   348000968       496833746.7443    29.96%        0      0      0         0   434.9s
         0       0         0   0.00%   348000968       496833746.7443    29.96%        0      0     13    129392  1094.1s

Solving report
  Status            Time limit reached
  Primal bound      496833746.744
  Dual bound        348000968
  Gap               29.96% (tolerance: 20%)
  P-D integral      197.489146817
  Solution status   feasible
                    496833746.744 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            1094.14
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0
  LP iterations     129392
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
WARNING: Loading a SolverResults object with an 'aborted' status, but
containing a solution

################################################################################
VERTICAL CYCLE SENSITIVITY: 10.0 mins
################################################################################

==============================================================================
PRM OPT — Scenario 2 Output
==============================================================================
Run status : maxtimelimit
Solver     : tc=maxtimelimit | status=aborted
Loaded sol : True | load_error=None

Assumptions:
  Vertical cycle extra mins : 10.0

[1] Horizon Summary (Peak across horizon; gaps vs CURRENT fleet)
  SLA_all      : 0.962
  SLA_arr      : 0.940
  SLA_dep      : 0.994
  PeakAmb      : 11   (Current=14 | Gap=0)
  PeakMini     : 9  (Current=3 | Gap=6)
  PeakDrivers  : 1181

[2] Peak Day (most PRM jobs) — Hourly Fleet Requirement + Gaps
  Peak day: 2025-04-29 | jobs=504
  Current fleet used: Amb=14 | Mini=3
  Peak hour req      : Amb=7 | Mini=5
  Peak hour gap      : Amb=0 | Mini=2

  Hourly table (first rows):
vehicle_type         Amb_req  Mini_req  Amb_gap  Mini_gap
bucket
2025-04-29 00:00:00        2         1        0         0
2025-04-29 01:00:00        1         0        0         0
2025-04-29 02:00:00        2         1        0         0
2025-04-29 03:00:00        1         1        0         0
2025-04-29 04:00:00        3         2        0         0
2025-04-29 05:00:00        2         2        0         0
2025-04-29 06:00:00        6         3        0         0
2025-04-29 07:00:00        3         2        0         0
2025-04-29 08:00:00        2         1        0         0
2025-04-29 09:00:00        2         4        0         1
2025-04-29 10:00:00        4         2        0         0
2025-04-29 11:00:00        4         2        0         0
2025-04-29 12:00:00        6         2        0         0
2025-04-29 13:00:00        7         4        0         1
2025-04-29 14:00:00        7         2        0         0
2025-04-29 15:00:00        5         4        0         1
2025-04-29 16:00:00        6         5        0         2
2025-04-29 17:00:00        4         2        0         0
2025-04-29 18:00:00        4         2        0         0
2025-04-29 19:00:00        2         1        0         0
2025-04-29 20:00:00        2         4        0         1
2025-04-29 21:00:00        1         1        0         0
2025-04-29 22:00:00        1         0        0         0
2025-04-29 23:00:00        3         1        0         0

[3] Sanity Checks (always)

  SLA breach rates by dir:
dir  breach_rate
  A     0.059910
  D     0.006246

  Top vehicle peaks (flight, bucket, type) — top 10:
                 flight_key              bucket vehicle_type  count
 LS_760_2025-04-26 14:45:00 2025-04-26 14:45:00         Mini      4
EI_3256_2025-04-13 14:45:00 2025-04-13 15:00:00         Mini      2
 LS_747_2025-04-14 14:00:00 2025-04-14 14:30:00         Mini      2
 LS_775_2025-04-27 04:00:00 2025-04-27 06:00:00         Mini      2
 LS_776_2025-04-06 12:45:00 2025-04-06 12:45:00         Mini      2
 LS_776_2025-04-11 16:00:00 2025-04-11 16:00:00          Amb      2
 LS_776_2025-04-17 15:15:00 2025-04-17 15:00:00          Amb      2
 LS_776_2025-04-29 14:30:00 2025-04-29 14:45:00          Amb      2
 LS_800_2025-04-30 13:00:00 2025-04-30 13:15:00         Mini      2
 LS_800_2025-04-30 13:00:00 2025-04-30 13:30:00         Mini      2

  Vertical jobs with Mini horizontally — count=260 (top 10):
  j  Passenger ID                  flight_key dir    scheduled_bucket      release_bucket       served_bucket  needs_vertical  needs_wc horizontal_mode  sla_breached
 76      10692791 FR_2885_2025-04-01 11:45:00   A 2025-04-01 11:45:00 2025-04-01 11:30:00 2025-04-01 11:30:00               1         1            Mini             0
 94      10693407 FR_1676_2025-04-01 11:30:00   A 2025-04-01 11:30:00 2025-04-01 11:30:00 2025-04-01 12:00:00               1         0            Mini             1
109      10693619  U2_217_2025-04-01 16:15:00   A 2025-04-01 16:15:00 2025-04-01 16:15:00 2025-04-01 16:15:00               1         1            Mini             0
208      10700358  LS_775_2025-04-03 04:15:00   D 2025-04-03 04:15:00 2025-04-03 04:15:00 2025-04-03 06:00:00               1         0            Mini             0
239      10701476 FR_8750_2025-04-02 08:15:00   D 2025-04-02 08:15:00 2025-04-02 08:15:00 2025-04-02 10:00:00               1         0            Mini             0
253      10701867 U2_3223_2025-04-02 14:15:00   D 2025-04-02 14:15:00 2025-04-02 14:15:00 2025-04-02 16:15:00               1         0            Mini             0
262      10702306 RK_1132_2025-04-02 14:45:00   A 2025-04-02 14:45:00 2025-04-02 14:45:00 2025-04-02 15:15:00               1         0            Mini             1
290      10703597 FR_6624_2025-04-02 16:00:00   D 2025-04-02 16:00:00 2025-04-02 16:00:00 2025-04-02 17:45:00               1         0            Mini             0
312      10707376  U2_302_2025-04-03 09:15:00   A 2025-04-03 09:15:00 2025-04-03 09:15:00 2025-04-03 09:30:00               1         0            Mini             1
331      10708095  LS_717_2025-04-04 04:15:00   D 2025-04-04 04:15:00 2025-04-04 04:15:00 2025-04-04 06:15:00               1         0            Mini             0

  Vertical jobs with Push horizontally — count=611 (top 10):
  j  Passenger ID                  flight_key dir    scheduled_bucket      release_bucket       served_bucket  needs_vertical  needs_wc horizontal_mode  sla_breached
  2      10473210  FR_809_2025-04-24 22:15:00   D 2025-04-24 22:15:00 2025-04-24 22:00:00 2025-04-24 23:30:00               1         0            Push             0
 16      10685407  LS_781_2025-04-01 08:00:00   D 2025-04-01 08:00:00 2025-04-01 07:45:00 2025-04-01 08:45:00               1         1            Push             0
 80      10692877  U2_334_2025-04-01 14:00:00   A 2025-04-01 14:00:00 2025-04-01 13:45:00 2025-04-01 14:00:00               1         0            Push             0
116      10693749 U2_3223_2025-04-01 14:45:00   D 2025-04-01 14:45:00 2025-04-01 14:30:00 2025-04-01 15:45:00               1         0            Push             0
131      10694528  U2_605_2025-04-01 19:00:00   A 2025-04-01 19:00:00 2025-04-01 19:00:00 2025-04-01 19:00:00               1         1            Push             0
137      10694761 FR_2969_2025-04-01 12:00:00   D 2025-04-01 12:00:00 2025-04-01 11:45:00 2025-04-01 14:30:00               1         1            Push             0
138      10694763 FR_6267_2025-04-01 17:15:00   A 2025-04-01 17:15:00 2025-04-01 17:00:00 2025-04-01 17:45:00               1         0            Push             0
188      10699678 FR_5590_2025-04-02 07:30:00   A 2025-04-02 07:30:00 2025-04-02 07:30:00 2025-04-02 07:30:00               1         1            Push             0
236      10701353 FR_5657_2025-04-02 08:45:00   D 2025-04-02 08:45:00 2025-04-02 08:45:00 2025-04-02 10:00:00               1         0            Push             0
240      10701478  U2_330_2025-04-02 15:45:00   A 2025-04-02 15:45:00 2025-04-02 15:45:00 2025-04-02 15:45:00               1         0            Push             0

Done.
==============================================================================

C:\Users\jamie_douglas\OneDrive - Edinburgh Airport Limited\Documents\GitHub\EDI_airport_analytics\prm_opt\outputs.py:501: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = bucket_totals.resample("H").max()

Run S26 Scenario 1

In [ ]:
ASSUME_START = "2025-04-01"
ASSUME_END   = "2025-11-01" 

assumptions = build_s26_assumptions(
    s25_start=ASSUME_START,
    s25_end=ASSUME_END
)

In [ ]:
out_s26_s1 = run_s26_s1(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    toggles=toggles,
)


report_s26_s1 = build_run_report_s1(out_s26_s1, day_from="s", hour_method="max")
print_run_report_s1(report_s26_s1)


# report_s26_s1["peak_day_report"]["bucket_level"].to_csv("S26_S1_peak_day_15min.csv")
# report_s26_s1["peak_day_report"]["hourly"].to_csv("S26_S1_peak_day_hourly.csv"

Run S26 scenario 2

In [ ]:



out_s26_s2 = run_s26_s2_v2_sensitivity(
    start=START_S26,
    end=END_S26,
    **assumptions["inputs"],
    vertical_cycle_grid=[15],
    solver_name="highs",
    toggles=toggles,
    time_limit_sec=600,
    threads=8,
    mip_rel_gap=0.20,
)



for r in out_s26_s2["runs"]:
    print("\n" + "#" * 80)
    print(f"VERTICAL CYCLE SENSITIVITY (S26): {r['vertical_cycle_mins']} mins")
    print("#" * 80)

    report = build_run_report(r, day_from="s", hour_method="max")
    report["assumptions"] = {"vertical_cycle_mins": r["vertical_cycle_mins"]}
    print_run_report(report)