### Imports and Config

In [1]:
# ==========================================================
# 1. Imports and repo setup
# ==========================================================

import sys
from pathlib import Path
from datetime import date, timedelta
from calendar import monthrange

import pandas as pd

HERE = Path().resolve()
PROJECT_ROOT = HERE.parents[0]
sys.path.insert(0, str(PROJECT_ROOT))

from prm_opt.config import PlanningToggles, VEHICLE_MODELS

from prm_opt.optimise_prm_fleet_v2 import OptimiserConfig
from prm_opt.run_s25_s26_v2 import run_s25_s26_v2

from prm_opt.build_assumptions_v2 import build_assumptions_v2
from prm_opt.build_s26_assumptions import build_s26_assumptions

from prm_opt.ingest_s25 import ingest_s25
from prm_opt.ingest_s26 import ingest_s26
from prm_opt.build_jobs import build_jobs
from prm_opt.policy_s1 import apply_policy_s1
from prm_opt.outputs import baseline_s1_vehicle_curves_capacity, baseline_s1_summary

from prm_opt.ingest_s25_v2 import ingest_s25_v2
from prm_opt.ingest_s26_v2 import ingest_s26_v2
from prm_opt.build_flights_v2 import build_flights_v2

from prm_opt.policy_s2_flight_rules import run_s2_flight_rules

### User Parameters

In [2]:
# ==========================================================
# 2. User parameters
# ==========================================================

OUTPUT_ROOT = Path("outputs/prm_w26")
MONTHLY_OUTPUT_DIR = OUTPUT_ROOT / "monthly"

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
MONTHLY_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

STAND_PLAN_FILES = [
    "data/stands/stand_allocation-october.csv",
    "data/stands/stand_allocation-november.csv",
    "data/stands/stand_allocation-december.csv",
    "data/stands/stand_allocation-january.csv",
    "data/stands/stand_allocation-february.csv",
    "data/stands/stand_allocation-march.csv",
]

MONTHS_TO_RUN = [
    (2026, 10),
    (2026, 11),
    (2026, 12),
    (2027, 1),
    (2027, 2),
    (2027, 3),
]

ASSUMPTION_S25_START = "2025-07-01"
ASSUMPTION_S25_END = "2026-07-01"

PENETRATION_UPLIFT = 1.08

RUN_P100 = True
RUN_P90 = True

S2_AMB_SEATCAP = 7
S2_AMB_WCCAP = 1

S2_MINI_SEATCAP = 6
S2_MINI_WCCAP = 2

S2_MINIBUS_THRESHOLD_PRMS = 3

TIME_FREQ = "5min"

### Toggles and V2 config

In [3]:
# ==========================================================
# 3. Scenario configs
# ==========================================================

toggles_p100 = PlanningToggles(
    demand_mode="p100",
)

toggles_p90 = PlanningToggles(
    demand_mode="p90_stratified",
    p90_quantile=0.90,
    p90_strata=("SSR Code", "Has Own Chair", "A/D"),
)

v2_config = OptimiserConfig(
    tau_amb_solo_mins=31,
    tau_amb_comb_mins=26,
    tau_mini_mins=23,
    tau_push_mins=20,

    handover_buffer_mins=5,

    arrival_sla_target_pct=0.98,
    arrival_sla_target_mins=20,

    boarding_offset_mins=40,

    staff_amb=2,
    staff_mini=2,
    staff_per_prm_push=1,

    max_future_copies_per_model=5,

    solver_relative_gap=0.005,
)

### date splitting

In [4]:
# ==========================================================
# 4. Date helpers
# ==========================================================

def get_month_run_flags(year, month, *, today=None):
    """
    Historical = before today, exclusive of today.
    Future = from today, inclusive of today.

    All end dates are exclusive because the SQL queries use:
        >= start
        < end
    """

    if today is None:
        today = date.today()

    month_start = date(year, month, 1)

    month_end_inclusive = date(
        year,
        month,
        monthrange(year, month)[1],
    )

    next_month_start = month_end_inclusive + timedelta(days=1)

    kwargs = {}

    run_s25 = False
    run_s26 = False

    if month_end_inclusive < today:

        run_s25 = True
        kwargs["s25_start"] = str(month_start)
        kwargs["s25_end"] = str(next_month_start)

    elif month_start >= today:

        run_s26 = True
        kwargs["s26_start"] = str(month_start)
        kwargs["s26_end"] = str(next_month_start)

    else:

        run_s25 = True
        run_s26 = True

        kwargs["s25_start"] = str(month_start)
        kwargs["s25_end"] = str(today)

        kwargs["s26_start"] = str(today)
        kwargs["s26_end"] = str(next_month_start)

    return {
        "month_start": month_start,
        "month_end_inclusive": month_end_inclusive,
        "next_month_start": next_month_start,
        "run_s25": run_s25,
        "run_s26": run_s26,
        "kwargs": kwargs,
    }

### assumption caches

In [5]:
# ==========================================================
# 5. Assumption caches
# ==========================================================

_rule_assumptions_cache = None
_v2_assumptions_cache = None


def get_rule_assumptions():
    """
    Old S1/S1-style stack assumptions for future passenger-level ingest.
    """

    global _rule_assumptions_cache

    if _rule_assumptions_cache is None:
        _rule_assumptions_cache = build_s26_assumptions(
            s25_start=ASSUMPTION_S25_START,
            s25_end=ASSUMPTION_S25_END,
            bucket="15min",
        )

    return _rule_assumptions_cache


def get_v2_assumptions():
    """
    V2 assumptions for future flight-level ingest.
    """

    global _v2_assumptions_cache

    if _v2_assumptions_cache is None:
        _v2_assumptions_cache = build_assumptions_v2(
            s25_start=ASSUMPTION_S25_START,
            s25_end=ASSUMPTION_S25_END,
            config=v2_config,
            stand_plan_files=STAND_PLAN_FILES
        )

    return _v2_assumptions_cache


def apply_penetration_uplift_to_rule_assumptions(
    assumptions,
    uplift,
):
    """
    Apply uplift to old S1/S1-style future penetration assumptions.
    """

    out = {
        "inputs": assumptions["inputs"].copy(),
        "extras": assumptions.get("extras", {}).copy(),
    }

    pen = out["inputs"]["penetration_rates"].copy()

    pen["penetration_base"] = pen["penetration"]
    pen["penetration_uplift"] = float(uplift)
    pen["penetration"] = pen["penetration"] * float(uplift)

    out["inputs"]["penetration_rates"] = pen

    return out

### S1 runner

In [6]:
# ==========================================================
# 7. S1 runner
# ==========================================================

def build_s1_jobs_for_period(
    *,
    month_info,
    toggles,
    rule_assumptions=None,
    seed=42,
):

    run_s25 = month_info["run_s25"]
    run_s26 = month_info["run_s26"]
    kwargs = month_info["kwargs"]

    parts = []

    if run_s25:

        df_hist = ingest_s25(
            start=kwargs["s25_start"],
            end=kwargs["s25_end"],
            seed=seed,
        )

        jobs_hist = build_jobs(
            df_hist,
            bucket="15min",
            toggles=toggles,
            use_90th_percentile_cap=False,
        )

        jobs_hist["source_period"] = "S25"
        parts.append(jobs_hist)

    if run_s26:

        if rule_assumptions is None:
            raise ValueError("Future S1 requires rule_assumptions.")

        df_future = ingest_s26(
            start=kwargs["s26_start"],
            end=kwargs["s26_end"],
            **rule_assumptions["inputs"],
            seed=seed,
        )

        jobs_future = build_jobs(
            df_future,
            bucket="15min",
            toggles=toggles,
            use_90th_percentile_cap=False,
        )

        jobs_future["source_period"] = "S26"
        parts.append(jobs_future)

    if len(parts) == 0:
        return pd.DataFrame()

    jobs = pd.concat(
        parts,
        ignore_index=True,
    )

    jobs.index.name = "j"

    return jobs


def _current_fleet_counts_from_vehicle_models():

    current_amb = sum(
        1
        for _, v in VEHICLE_MODELS.items()
        if v["type"] == "Amb"
        and not bool(v.get("is_future", False))
    )

    current_mini = sum(
        1
        for _, v in VEHICLE_MODELS.items()
        if v["type"] == "Mini"
        and not bool(v.get("is_future", False))
    )

    return current_amb, current_mini


def run_s1_for_period(
    *,
    month_info,
    toggles,
    rule_assumptions=None,
    seed=42,
):

    jobs = build_s1_jobs_for_period(
        month_info=month_info,
        toggles=toggles,
        rule_assumptions=rule_assumptions,
        seed=seed,
    )

    if jobs is None or len(jobs) == 0:

        empty_series = pd.Series(dtype=int)

        return {
            "jobs": pd.DataFrame(),
            "summary": {},
            "ambulift_curve": empty_series,
            "minibus_curve": empty_series,
            "driver_curve": empty_series,
            "veh_agent_curve": empty_series,
            "pusher_curve": empty_series,
            "fb_detail": pd.DataFrame(),
        }

    decisions = apply_policy_s1(jobs)

    jobs["s1_decision"] = jobs.index.map(decisions.get)

    curves = baseline_s1_vehicle_curves_capacity(
        jobs,
        decision_col="s1_decision",
        bucket_col="s",
        count_no_vehicle_as_push=True,
        amb_seatcap=3,
        amb_wccap=1,
        mini_seatcap=6,
        mini_wccap=2,
        duration_mins=20,
        time_freq=TIME_FREQ,
    )

    current_amb, current_mini = _current_fleet_counts_from_vehicle_models()

    summary = baseline_s1_summary(
        jobs,
        curves,
        current_amb=current_amb,
        current_mini=current_mini,
    )

    return {
        "jobs": jobs,
        "summary": summary,
        "ambulift_curve": curves["ambulift_curve"],
        "minibus_curve": curves["minibus_curve"],
        "driver_curve": curves["driver_curve"],
        "veh_agent_curve": curves["veh_agent_curve"],
        "pusher_curve": curves["pusher_curve"],
        "fb_detail": curves["fb_detail"],
    }

### build V2 passengers and flights for S2

In [7]:
# ==========================================================
# 8. Build V2 passengers and flights for S2
# ==========================================================

def build_v2_passengers_for_period(
    *,
    month_info,
    v2_assumptions=None,
    seed=42,
):

    run_s25 = month_info["run_s25"]
    run_s26 = month_info["run_s26"]
    kwargs = month_info["kwargs"]

    parts = []

    if run_s25:

        df_hist = ingest_s25_v2(
            start=kwargs["s25_start"],
            end=kwargs["s25_end"],
            seed=seed,
        )

        df_hist["source_period"] = "S25"
        parts.append(df_hist)

    if run_s26:

        if v2_assumptions is None:
            raise ValueError("Future V2/S2 requires v2_assumptions.")

        df_future = ingest_s26_v2(
            start=kwargs["s26_start"],
            end=kwargs["s26_end"],
            penetration_rates=v2_assumptions["penetration_rates"],
            ssr_mix=v2_assumptions["ssr_mix"],
            stand_actuals=v2_assumptions["stand_actuals"],
            stand_dist=v2_assumptions["stand_dist"],
            penetration_uplift=PENETRATION_UPLIFT,
            seed=seed,
        )

        df_future["source_period"] = "S26"
        parts.append(df_future)

    if len(parts) == 0:
        return pd.DataFrame()

    passengers = pd.concat(
        parts,
        ignore_index=True,
    )

    return passengers


def build_v2_flights_for_period(
    *,
    month_info,
    demand_mode,
    v2_assumptions=None,
    seed=42,
):

    passengers = build_v2_passengers_for_period(
        month_info=month_info,
        v2_assumptions=v2_assumptions,
        seed=seed,
    )

    if passengers is None or len(passengers) == 0:
        return pd.DataFrame()

    flights = build_flights_v2(
        passengers,
        demand_mode=demand_mode,
        p90_quantile=0.90,
        boarding_offset_mins=v2_config.boarding_offset_mins,
        p90_strata=("demand_category", "A/D"),
    )

    return flights

### S2 runner

In [8]:
# ==========================================================
# 9. S2 runner
# ==========================================================

def run_s2_for_period(
    *,
    month_info,
    demand_mode,
    v2_assumptions=None,
    seed=42,
):

    flights = build_v2_flights_for_period(
        month_info=month_info,
        demand_mode=demand_mode,
        v2_assumptions=v2_assumptions,
        seed=seed,
    )

    if flights is None or len(flights) == 0:

        empty_series = pd.Series(dtype=int)

        return {
            "flights": pd.DataFrame(),
            "flight_requirements": pd.DataFrame(),
            "summary": {},
            "ambulift_curve": empty_series,
            "minibus_curve": empty_series,
            "driver_curve": empty_series,
            "veh_agent_curve": empty_series,
            "event_detail": pd.DataFrame(),
            "curve_df": pd.DataFrame(),
        }

    out = run_s2_flight_rules(
        flights=flights,
        config=v2_config,
        amb_seatcap=S2_AMB_SEATCAP,
        amb_wccap=S2_AMB_WCCAP,
        mini_seatcap=S2_MINI_SEATCAP,
        mini_wccap=S2_MINI_WCCAP,
        minibus_threshold_prms=S2_MINIBUS_THRESHOLD_PRMS,
        time_freq=TIME_FREQ,
    )

    out["flights"] = flights

    return out

### V2 optimiser runner

In [9]:
# ==========================================================
# 10. V2 optimiser runner
# ==========================================================

def run_v2_optimizer_for_period(
    *,
    month_info,
    v2_assumptions=None,
    output_dir,
    output_xlsx_name,
):

    run_s25 = month_info["run_s25"]
    run_s26 = month_info["run_s26"]
    kwargs = month_info["kwargs"]

    call_kwargs = {
        "run_s25": run_s25,
        "run_s26": run_s26,

        "vehicle_models": VEHICLE_MODELS,
        "config": v2_config,

        "output_dir": str(output_dir),
        "output_xlsx_name": output_xlsx_name,

        "run_p100": True,
        "run_p90": True,

        "run_fleet_report": True,
        "fleet_report_policy": "if_needed",
        "current_fleet_only_first": True,

        "max_ev10": 5,
        "max_ev18": 5,

        **kwargs,
    }

    if run_s26:

        if v2_assumptions is None:
            raise ValueError(
                "Future V2 optimiser requires v2_assumptions."
            )

        call_kwargs.update(
            {
                "penetration_rates": v2_assumptions["penetration_rates"],
                "ssr_mix": v2_assumptions["ssr_mix"],
                "stand_actuals": v2_assumptions["stand_actuals"],
                "stand_dist": v2_assumptions["stand_dist"],
                "penetration_uplift": PENETRATION_UPLIFT,
            }
        )

    result = run_s25_s26_v2(**call_kwargs)

    return result

# workbook write and V2 summary helper

In [10]:
# ==========================================================
# 11. Workbook writer and V2 summary helper
# ==========================================================

def _safe_sheet_name(name):

    invalid = ["\\", "/", "*", "?", ":", "[", "]"]

    out = str(name)

    for ch in invalid:
        out = out.replace(ch, "_")

    return out[:31]


def _write_df(
    writer,
    obj,
    sheet_name,
):

    if obj is None:
        return

    if isinstance(obj, dict):
        df = pd.DataFrame([obj])

    elif isinstance(obj, pd.Series):
        df = obj.rename("value").reset_index()

    elif isinstance(obj, pd.DataFrame):
        df = obj

    else:
        df = pd.DataFrame(obj)

    df.to_excel(
        writer,
        sheet_name=_safe_sheet_name(sheet_name),
        index=False,
    )


def write_monthly_combined_workbook(
    *,
    output_path,
    month_rows,
    s1_outputs,
    s2_outputs,
    v2_result,
):

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with pd.ExcelWriter(
        output_path,
        engine="openpyxl",
    ) as writer:

        _write_df(
            writer,
            pd.DataFrame(month_rows),
            "Monthly_Summary",
        )

        # ----------------------------
        # S1 outputs
        # ----------------------------

        for mode_key, s1 in s1_outputs.items():

            _write_df(
                writer,
                s1.get("summary"),
                f"S1_{mode_key}_Summary",
            )

            _write_df(
                writer,
                s1.get("jobs"),
                f"S1_{mode_key}_Jobs",
            )

            _write_df(
                writer,
                s1.get("fb_detail"),
                f"S1_{mode_key}_FB_Detail",
            )

            _write_df(
                writer,
                s1.get("ambulift_curve"),
                f"S1_{mode_key}_Amb_Curve",
            )

            _write_df(
                writer,
                s1.get("minibus_curve"),
                f"S1_{mode_key}_Mini_Curve",
            )

        # ----------------------------
        # S2 outputs
        # ----------------------------

        for mode_key, s2 in s2_outputs.items():

            _write_df(
                writer,
                s2.get("summary"),
                f"S2_{mode_key}_Summary",
            )

            _write_df(
                writer,
                s2.get("flights"),
                f"S2_{mode_key}_Flights",
            )

            _write_df(
                writer,
                s2.get("flight_requirements"),
                f"S2_{mode_key}_Requirements",
            )

            _write_df(
                writer,
                s2.get("curve_df"),
                f"S2_{mode_key}_Curve",
            )

            _write_df(
                writer,
                s2.get("event_detail"),
                f"S2_{mode_key}_Events",
            )

        # ----------------------------
        # V2 outputs
        # ----------------------------

        if v2_result is not None:

            if "outputs_p100" in v2_result:

                for key, df in v2_result["outputs_p100"].items():

                    if isinstance(df, pd.DataFrame):

                        _write_df(
                            writer,
                            df,
                            f"V2_P100_{key}",
                        )

            if "outputs_p90" in v2_result:

                for key, df in v2_result["outputs_p90"].items():

                    if isinstance(df, pd.DataFrame):

                        _write_df(
                            writer,
                            df,
                            f"V2_P90_{key}",
                        )
            
            extra_v2_keys = [
                "p100_base_check",
                "p90_base_check",
                "fleet_requirements_p100",
                "fleet_requirements_p90",
                "recommended_p100",
                "recommended_p90",
            ]

            for key in extra_v2_keys:

                if (
                    key in v2_result
                    and isinstance(v2_result[key], pd.DataFrame)
                ):

                    _write_df(
                        writer,
                        v2_result[key],
                        f"V2_{key}",
                    )

    return output_path


def extract_v2_month_summary(
    v2_result,
    mode_key,
):

    if v2_result is None:
        return {}

    if mode_key == "P100":
        outputs = v2_result.get("outputs_p100", {})
    else:
        outputs = v2_result.get("outputs_p90", {})

    sla = outputs.get(
        "sla_summary",
        pd.DataFrame(),
    )

    fleet = outputs.get(
        "fleet_utilisation",
        pd.DataFrame(),
    )

    arrival_sla_pct = None

    if isinstance(sla, pd.DataFrame) and len(sla) > 0:

        row = sla.iloc[0]

        arrival_sla_pct = row.get(
            "arrival_sla_pct"
        )

    peak_amb = None
    peak_mini = None

    if (
        isinstance(fleet, pd.DataFrame)
        and len(fleet) > 0
        and "vehicle_type" in fleet.columns
        and "required_for_schedule" in fleet.columns
    ):

        peak_amb = int(
            pd.to_numeric(
                fleet.loc[
                    fleet["vehicle_type"] == "Amb",
                    "required_for_schedule",
                ],
                errors="coerce",
            ).fillna(0).sum()
        )

        peak_mini = int(
            pd.to_numeric(
                fleet.loc[
                    fleet["vehicle_type"] == "Mini",
                    "required_for_schedule",
                ],
                errors="coerce",
            ).fillna(0).sum()
        )

    return {
        "V2_arrival_sla_pct": arrival_sla_pct,
        "V2_PeakAmb": peak_amb,
        "V2_PeakMini": peak_mini,
    }

### run one month

In [11]:
# ==========================================================
# 12. Run one month
# ==========================================================

def run_combined_month(
    year,
    month,
    *,
    seed=42,
):

    month_info = get_month_run_flags(
        year,
        month,
    )

    month_start = month_info["month_start"]

    month_tag = f"{year}_{month:02d}"

    print("")
    print("=" * 80)
    print(f"RUNNING COMBINED MONTH: {month_tag}")
    print("=" * 80)

    needs_future = bool(
        month_info["run_s26"]
    )

    rule_assumptions = None
    v2_assumptions = None

    if needs_future:

        rule_assumptions = (
            apply_penetration_uplift_to_rule_assumptions(
                get_rule_assumptions(),
                PENETRATION_UPLIFT,
            )
        )

        v2_assumptions = (
            get_v2_assumptions()
        )

    s1_outputs = {}
    s2_outputs = {}

    modes_to_run = []

    if RUN_P100:
        modes_to_run.append(
            (
                "P100",
                "p100",
                toggles_p100,
            )
        )

    if RUN_P90:
        modes_to_run.append(
            (
                "P90",
                "p90",
                toggles_p90,
            )
        )

    for mode_key, demand_mode, toggles in modes_to_run:

        print("")
        print(f"Running S1 {mode_key}")

        s1_outputs[mode_key] = (
            run_s1_for_period(
                month_info=month_info,
                toggles=toggles,
                rule_assumptions=rule_assumptions,
                seed=seed,
            )
        )

        print(f"Running S2 {mode_key}")

        s2_outputs[mode_key] = (
            run_s2_for_period(
                month_info=month_info,
                demand_mode=demand_mode,
                v2_assumptions=v2_assumptions,
                seed=seed,
            )
        )

    print("")
    print("Running V2 optimiser")

    v2_result = run_v2_optimizer_for_period(
        month_info=month_info,
        v2_assumptions=v2_assumptions,
        output_dir=MONTHLY_OUTPUT_DIR,
        output_xlsx_name=f"{month_tag}_v2.xlsx",
    )

    month_rows = []

    for mode_key, _, _ in modes_to_run:

        s1_summary = (
            s1_outputs[mode_key]
            .get("summary", {})
        )

        s2_summary = (
            s2_outputs[mode_key]
            .get("summary", {})
        )

        v2_summary = (
            extract_v2_month_summary(
                v2_result,
                mode_key,
            )
        )

        row = {

            "S1_PeakAmb":
                s1_summary.get("PeakAmb"),

            "S1_PeakMini":
                s1_summary.get("PeakMini"),

            "S1_PeakDrivers":
                s1_summary.get("PeakDrivers"),

            "S1_PeakVehAgents":
                s1_summary.get("PeakVehAgents"),

            "S2_PeakAmb":
                s2_summary.get("PeakAmb"),

            "S2_PeakMini":
                s2_summary.get("PeakMini"),

            "S2_PeakDrivers":
                s2_summary.get("PeakDrivers"),

            "S2_PeakVehAgents":
                s2_summary.get("PeakVehAgents"),

            **v2_summary,
        }

        month_rows.append(row)

    combined_path = (
        MONTHLY_OUTPUT_DIR
        / f"{month_tag}_combined.xlsx"
    )

    write_monthly_combined_workbook(
        output_path=combined_path,
        month_rows=month_rows,
        s1_outputs=s1_outputs,
        s2_outputs=s2_outputs,
        v2_result=v2_result,
    )

    print("")
    print(f"Completed month: {month_tag}")
    print(f"Workbook: {combined_path}")

    return {

        "month_rows":
            month_rows,

        "s1_outputs":
            s1_outputs,

        "s2_outputs":
            s2_outputs,

        "v2_result":
            v2_result,

        "combined_workbook_path":
            combined_path,
    }

### Test Call

In [12]:
october_result = run_combined_month(
    2026,
    10,
)

pd.DataFrame(october_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2026_10
================================================================================

Unmatched passenger rows after merge (missing Chocks DT): 7451
Unique unmatched flight keys: 4434

Unmatched key reasons:
reason
no_flight_candidate               3551
scheduled_dt_mismatch              729
exact_match_should_have_joined     154
Name: count, dtype: int64

Dropped 7100 passenger rows due to reasons {'no_flight_candidate', 'scheduled_dt_mismatch'}
[1/5] Penetration + SSR mix…
    ✓ penetration + SSR mix built   [242.81s]
[2/5] Service times…
[BUILD_JOBS] Dropping 66 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
53000      13159410           748           LS 2025-09-30 01:35:15
53001      13159411           748           LS 2025-09-30 01:35:15
53004      13159414           748           LS 2025-09-30 01:35:15
53005      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
53000 2025-09-30 04:59:07         20 2025-09-30 01:35:15
53001 2025-09-30 05:00:53         20 2025-09-30 01:35:15
53004 2025-09-30 04:59:15         20 2025-09-30 01:35:15
53005 2025-09-30 04:59:18         20 2025-09-30 01:35:15
    ✓ service times built   [2.92s]
[2b/5] Tau mode params (S25 medians)…
    ✓ tau mode params built   [0.03s]
[3/5] Chocks offsets…
    ✓ chocks offsets built   [0.08s]
[4/5] Early/late timing…
    ✓ early/late params built   [0.08s]
[5/5] Stand inputs…
    ✓ stand inputs built   [0.11s]

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11357
Airlines (sample): ['BA' 'U2' 'LS' 'RK' 'EI' 'AA' 'LM' 'DL' 'B6' 'FR']
Countries (sample): ['GREAT BRITAIN' 'FRANCE' 'GREECE' 'IRISH REPUBLIC'
 'UNITED STATES OF AMERICA' 'GERMANY' 'NETHERLANDS' 'SPAIN' 'POLAND'
 'ITALY']

Pax describe:
count    11357.000000
mean       149.558070
std         57.052164
min          0.000000
25%        123.000000
50%        165.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline               CountryName         Sector dir    Pax
0       BA             GREAT BRITAIN       Domestic   D   70.0
1       U2             GREAT BRITAIN       Domestic   D   25.0
2       U2                    FRANCE  International   D  149.0
3       LS                    GREECE  International   D  167.0
4       RK             GREAT BRITAIN       Domestic   D   27.0
5       EI            IRISH REPUBLIC            CTA   D   57.0
6       AA  UNITED STATES OF AMERICA  International   D  128.0
7       LM             GREAT BRITAIN       Domestic   D   54.0
8       DL  UNITED STATES OF AMERICA  International   D  188.0
9       RK             GREAT BRITAIN       Domestic   D  180.0
10      B6  UNITED STATES OF AMERICA  International   D  144.0
11      FR                   GERMANY  International   D  167.0
12      B6  UNITED STATES OF AMERICA  International   D   96.0
13      EI             GREAT BRITAIN       Domestic   D   57.0
14      LS                    GREECE  International   D  171.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 10,984 / 11,357 (96.7%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN           82
4      EC          FRANCE           82
3      EA  IRISH REPUBLIC           70
5      EC     NETHERLANDS           62
2      EA   GREAT BRITAIN           52
6      LG      LUXEMBOURG           18
1      CJ           SPAIN            2
8      RC         ICELAND            2
9      RK          SWEDEN            2
7      LS   GREAT BRITAIN            1

Example missing keys:
    Airline  CountryName    Pax
61       EC       FRANCE  152.0
107      EC       FRANCE  217.0
155      EC  NETHERLANDS  154.0
442      EC       FRANCE  185.0
542      EC  NETHERLANDS  156.0
574      LG   LUXEMBOURG  110.0
617      EC       FRANCE  182.0
667      EC       FRANCE  183.0
789      EC  NETHERLANDS  177.0
792      EC       FRANCE  138.0
855      EC       FRANCE  222.0
858      LG   LUXEMBOURG  109.0
919      EC  NETHERLANDS  174.0
930      EC       FRANCE  180.0
977      EC       FRANCE  145.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 19040.33060442364
Total PRMs after rounding: 19335

Raw PRM demand distribution (prm_raw):
count    11357.000000
mean         1.676528
std          1.604858
min          0.000000
25%          0.767639
50%          1.220300
75%          1.821620
max          9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
5853      QR       QATAR  311.0   0.031641  9.840463          10
403       QR       QATAR  311.0   0.031641  9.840463          10
56        QR       QATAR  311.0   0.031641  9.840463          10
2568      QR       QATAR  311.0   0.031641  9.840463          10
5329      QR       QATAR  311.0   0.031641  9.840463          10
2300      QR       QATAR  311.0   0.031641  9.840463          10
5495      QR       QATAR  311.0   0.031641  9.840463          10
2860      QR       QATAR  311.0   0.031641  9.840463          10
5555      QR       QATAR  311.0   0.031641  9.840463          10
986       QR       QATAR  311.0   0.031641  9.840463          10
3134      QR       QATAR  311.0   0.031641  9.840463          10
1064      QR       QATAR  311.0   0.031641  9.840463          10
263       QR       QATAR  311.0   0.031641  9.840463          10
7326      QR       QATAR  311.0   0.031641  9.840463          10
3056      QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=70.0 | Pen=0.01029 | Pax*Pen=0.720 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=25.0 | Pen=0.00920 | Pax*Pen=0.230 | PRMs=0
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=149.0 | Pen=0.00935 | Pax*Pen=1.392 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=167.0 | Pen=0.02050 | Pax*Pen=3.424 | PRMs=3
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=27.0 | Pen=0.00636 | Pax*Pen=0.172 | PRMs=0
[DEBUG flight] Airline=EI | Country=IRISH REPUBLIC | Pax=57.0 | Pen=0.01066 | Pax*Pen=0.608 | PRMs=1
[DEBUG flight] Airline=AA | Country=UNITED STATES OF AMERICA | Pax=128.0 | Pen=0.01599 | Pax*Pen=2.047 | PRMs=2
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=54.0 | Pen=0.02036 | Pax*Pen=1.099 | PRMs=1
[DEBUG flight] Airline=DL | Country=UNITED STATES OF AMERICA | Pax=188.0 | Pen=0.01525 | Pax*Pen=2.867 | PRMs=3
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=180.0 | Pen=0.00636 | Pax*Pen=1.144 | PRMs=1
[DEBUG flight] Airline=B6 | Country=UNITED STATES OF AMERICA | Pax=144.0 | Pen=0.01315 | Pax*Pen=1.894 | PRMs=2
[DEBUG flight] Airline=FR | Country=GERMANY | Pax=167.0 | Pen=0.00279 | Pax*Pen=0.467 | PRMs=0
[DEBUG flight] Airline=B6 | Country=UNITED STATES OF AMERICA | Pax=96.0 | Pen=0.01315 | Pax*Pen=1.263 | PRMs=1
[DEBUG flight] Airline=EI | Country=GREAT BRITAIN | Pax=57.0 | Pen=0.01118 | Pax*Pen=0.637 | PRMs=1
[DEBUG flight] Airline=LS | Country=GREECE | Pax=171.0 | Pen=0.02050 | Pax*Pen=3.506 | PRMs=4

[DEBUG ingest_s26]
Total PRM jobs (rows): 19335
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10106
WCHS      8138
WCHC      1017
OTHER       74
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 11357
Airlines (sample): ['U2' 'AF' 'FR' 'KL' 'BA' 'LS' 'LH' 'LM' 'RK' 'QR']
Countries (sample): ['ITALY' 'FRANCE' 'LATVIA' 'NETHERLANDS' 'GREAT BRITAIN' 'PORTUGAL'
 'SPAIN' 'GREECE' 'GERMANY' 'POLAND']

Pax describe:
count    11357.000000
mean       149.558070
std         57.052164
min          0.000000
25%        123.000000
50%        165.000000
75%        184.000000
max        397.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       U2          ITALY  International   D  175.0
1       AF         FRANCE  International   D  102.0
2       FR         LATVIA  International   D  192.0
3       KL    NETHERLANDS  International   D  109.0
4       BA  GREAT BRITAIN       Domestic   D   73.0
5       U2       PORTUGAL  International   D  166.0
6       U2          ITALY  International   D  143.0
7       FR          SPAIN  International   D  174.0
8       LS         GREECE  International   D  193.0
9       U2  GREAT BRITAIN       Domestic   D  143.0
10      U2  GREAT BRITAIN       Domestic   D   80.0
11      U2         FRANCE  International   D  184.0
12      LH        GERMANY  International   D  114.0
13      FR          ITALY  International   D  185.0
14      LM  GREAT BRITAIN       Domestic   D   15.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 10,984 / 11,357 (96.7%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN           82
4      EC          FRANCE           82
3      EA  IRISH REPUBLIC           70
5      EC     NETHERLANDS           62
2      EA   GREAT BRITAIN           52
6      LG      LUXEMBOURG           18
1      CJ           SPAIN            2
8      RC         ICELAND            2
9      RK          SWEDEN            2
7      LS   GREAT BRITAIN            1

Example missing keys:
    Airline  CountryName    Pax
119      EC       FRANCE  183.0
178      EC       FRANCE  182.0
237      EC       FRANCE  152.0
297      EC       FRANCE  217.0
317      LG   LUXEMBOURG  110.0
370      EC  NETHERLANDS  154.0
432      EC  NETHERLANDS  156.0
715      EC       FRANCE  185.0
789      EC  NETHERLANDS  177.0
792      EC       FRANCE  138.0
855      EC       FRANCE  222.0
858      LG   LUXEMBOURG  109.0
919      EC  NETHERLANDS  174.0
930      EC       FRANCE  180.0
977      EC       FRANCE  145.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 19040.330604423638
Total PRMs after rounding: 19335

Raw PRM demand distribution (prm_raw):
count    11357.000000
mean         1.676528
std          1.604858
min          0.000000
25%          0.767639
50%          1.220300
75%          1.821620
max          9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
      Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
427        QR       QATAR  311.0   0.031641  9.840463          10
4176       QR       QATAR  311.0   0.031641  9.840463          10
1355       QR       QATAR  311.0   0.031641  9.840463          10
673        QR       QATAR  311.0   0.031641  9.840463          10
10555      QR       QATAR  311.0   0.031641  9.840463          10
5555       QR       QATAR  311.0   0.031641  9.840463          10
2568       QR       QATAR  311.0   0.031641  9.840463          10
1900       QR       QATAR  311.0   0.031641  9.840463          10
6004       QR       QATAR  311.0   0.031641  9.840463          10
585        QR       QATAR  311.0   0.031641  9.840463          10
1545       QR       QATAR  311.0   0.031641  9.840463          10
5495       QR       QATAR  311.0   0.031641  9.840463          10
2861       QR       QATAR  311.0   0.031641  9.840463          10
2300       QR       QATAR  311.0   0.031641  9.840463          10
231        QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=175.0 | Pen=0.00985 | Pax*Pen=1.723 | PRMs=2
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=102.0 | Pen=0.00888 | Pax*Pen=0.906 | PRMs=1
[DEBUG flight] Airline=FR | Country=LATVIA | Pax=192.0 | Pen=0.00445 | Pax*Pen=0.854 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=109.0 | Pen=0.00911 | Pax*Pen=0.993 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=73.0 | Pen=0.01029 | Pax*Pen=0.751 | PRMs=1
[DEBUG flight] Airline=U2 | Country=PORTUGAL | Pax=166.0 | Pen=0.00958 | Pax*Pen=1.590 | PRMs=2
[DEBUG flight] Airline=U2 | Country=ITALY | Pax=143.0 | Pen=0.00985 | Pax*Pen=1.408 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=174.0 | Pen=0.01067 | Pax*Pen=1.857 | PRMs=2
[DEBUG flight] Airline=LS | Country=GREECE | Pax=193.0 | Pen=0.02050 | Pax*Pen=3.957 | PRMs=4
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=143.0 | Pen=0.00920 | Pax*Pen=1.315 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=80.0 | Pen=0.00920 | Pax*Pen=0.736 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=184.0 | Pen=0.00935 | Pax*Pen=1.720 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=114.0 | Pen=0.00745 | Pax*Pen=0.849 | PRMs=1
[DEBUG flight] Airline=FR | Country=ITALY | Pax=185.0 | Pen=0.00433 | Pax*Pen=0.802 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=15.0 | Pen=0.02036 | Pax*Pen=0.305 | PRMs=0

[DEBUG ingest_s26]
Total PRM jobs (rows): 19335
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     10114
WCHS      8147
WCHC       996
OTHER       78
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1104 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (19,360 passenger rows)   [62.07s]
    ✓ P100 built (10,394 flights)   [0.20s]
    P100 demand summary: 19,360 PRMs across 10,394 flights
    ✓ prepare_model_data started | flights=10,394   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.04s]
    ✓ ambulift intervals built | flights=10,394 ambulifts=14   [1.33s]
    ✓ minibus intervals built | minibuses=3   [0.10s]
    ✓ staff intervals built   [0.02s]
    ✓ ambulift overlaps built | overlaps=9,907,029   [2.12s]
    ✓ minibus overlaps built | overlaps=907,680   [0.17s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.05s]
    ✓ prepare_model_data complete | total=3.84s   [0.00s]
    ✓ sets built | F=10,394 AMB=14 MINI=3   [0.00s]
    ✓ variables built | x=51,970 amb=436,548 mini=62,364   [1.36s]
    ✓ ambulift overlap constraints built | 9,907,029   [55.59s]
    ✓ minibus overlap constraints built | 907,680   [2.44s]
    ✓ build_pyomo_model complete | total=60.46s   [1.07s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=10,394 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 11500780 rows; 623657 cols; 23564775 nonzeros; 550899 integer variables (550899 binary)
Coefficient ranges:
  Matrix  [1e+00, 1e+01]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
1591572 rows, 232746 cols, 3360074 nonzeros 16s
494928 rows, 204464 cols, 2192104 nonzeros 104s
494928 rows, 204464 cols, 2192104 nonzeros 207s
Presolve reductions: rows 494928(-11005852); columns 204464(-419193); nonzeros 2192104(-21372671)
Objective function is integral with scale 219

Solving MIP model with:
   494928 rows
   204464 cols (183072 binary, 0 integer, 21392 implied int., 0 continuous, 0 domain fixed)
   2192104 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            4300553098.479     Large        0      0      0         0   226.4s
 R       0       0         0   0.00%   10294419.63053  1308534461.05     99.21%        0      0      0     75422   609.3s
         0       0         0   0.00%   11294668.40434  1308534461.05     99.14%     1286    207      0     78307   647.6s
         0       0         0   0.00%   11295148.78457  1308534461.05     99.14%     1509    380      0     80158   664.7s
         0       0         0   0.00%   11296495.6464   1308534461.05     99.14%     1631    514      0     81698   681.1s
         0       0         0   0.00%   11297223.51545  1308534461.05     99.14%     1650    584      0     84332   707.1s
 C       0       0         0   0.00%   11298004.6941   807037551.2968    98.60%     1741    605      0     87794   738.6s
         0       0         0   0.00%   11298082.0218   807037551.2968    98.60%     1904    620      0     88944   758.1s
         0       0         0   0.00%   11298082.0218   807037551.2968    98.60%     1975    625      0    101795   840.8s
         0       0         0   0.00%   11299072.73503  807037551.2968    98.60%     2600    644      0    104485   868.4s
         0       0         0   0.00%   11299086.69799  807037551.2968    98.60%     2697    650      0    106478   910.5s
         0       0         0   0.00%   11299086.69799  807037551.2968    98.60%     2726    654      0    108083   930.0s
         0       0         0   0.00%   11299086.69799  807037551.2968    98.60%     2753    658      0    109499   948.3s
         0       0         0   0.00%   11299086.69799  807037551.2968    98.60%     2782    662      0    110978   967.9s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,10,2,11,11,11,16,25,25,99.806103,11,3
1,11,2,11,11,11,14,23,23,99.924528,12,3

In [13]:
november_result = run_combined_month(
    2026,
    11,
)

pd.DataFrame(november_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2026_11
================================================================================

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 8920
Airlines (sample): ['KL' 'AF' 'FR' 'U2' 'RK' 'LH' 'BA' 'LS' 'EC' 'UA']
Countries (sample): ['NETHERLANDS' 'FRANCE' 'IRISH REPUBLIC' 'PORTUGAL' 'SPAIN' 'POLAND'
 'ALBANIA' 'GERMANY' 'GREAT BRITAIN' 'ITALY']

Pax describe:
count    8920.000000
mean      144.445964
std        56.776957
min         0.000000
25%       118.000000
50%       159.000000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       KL     NETHERLANDS  International   D  227.0
1       AF          FRANCE  International   D  140.0
2       FR  IRISH REPUBLIC            CTA   D  191.0
3       FR        PORTUGAL  International   D  186.0
4       FR  IRISH REPUBLIC            CTA   D  191.0
5       U2          FRANCE  International   D  179.0
6       FR           SPAIN  International   D  165.0
7       FR          POLAND  International   D  170.0
8       RK         ALBANIA  International   D  168.0
9       LH         GERMANY  International   D  172.0
10      FR           SPAIN  International   D  170.0
11      BA   GREAT BRITAIN       Domestic   D  216.0
12      FR          POLAND  International   D  179.0
13      LS           SPAIN  International   D  167.0
14      U2   GREAT BRITAIN       Domestic   D  173.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,813 / 8,920 (87.6%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          375
2      EA  IRISH REPUBLIC          336
1      EA   GREAT BRITAIN          224
4      EC     NETHERLANDS           96
3      EC          FRANCE           52
5      LG      LUXEMBOURG           18
6      LS   GREAT BRITAIN            2
7      LS          POLAND            2
8      U2          NORWAY            2

Example missing keys:
    Airline     CountryName    Pax
28       EC          FRANCE  140.0
38       CJ   GREAT BRITAIN  106.0
44       EA  IRISH REPUBLIC   67.0
45       EA   GREAT BRITAIN   70.0
50       EA  IRISH REPUBLIC   68.0
73       EA  IRISH REPUBLIC   68.0
87       EA  IRISH REPUBLIC   70.0
98       CJ   GREAT BRITAIN  102.0
116      EA   GREAT BRITAIN   52.0
117      EA  IRISH REPUBLIC   70.0
118      CJ   GREAT BRITAIN   98.0
137      CJ   GREAT BRITAIN   98.0
153      EA  IRISH REPUBLIC   71.0
154      EA   GREAT BRITAIN   62.0
160      CJ   GREAT BRITAIN  100.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13531.089630662496
Total PRMs after rounding: 13771

Raw PRM demand distribution (prm_raw):
count    8920.000000
mean        1.516938
std         1.436822
min         0.000000
25%         0.723778
50%         1.195554
75%         1.694834
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
1931      QR       QATAR  311.0   0.031641  9.840463          10
7387      QR       QATAR  311.0   0.031641  9.840463          10
3923      QR       QATAR  311.0   0.031641  9.840463          10
3761      QR       QATAR  311.0   0.031641  9.840463          10
3674      QR       QATAR  311.0   0.031641  9.840463          10
301       QR       QATAR  311.0   0.031641  9.840463          10
602       QR       QATAR  311.0   0.031641  9.840463          10
2930      QR       QATAR  311.0   0.031641  9.840463          10
1769      QR       QATAR  311.0   0.031641  9.840463          10
5553      QR       QATAR  311.0   0.031641  9.840463          10
769       QR       QATAR  311.0   0.031641  9.840463          10
932       QR       QATAR  311.0   0.031641  9.840463          10
679       QR       QATAR  311.0   0.031641  9.840463          10
8022      QR       QATAR  310.0   0.031641  9.808822          10
8242      QR       QATAR  308.0   0.031641  9.745539          10
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=227.0 | Pen=0.00911 | Pax*Pen=2.068 | PRMs=2
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=140.0 | Pen=0.00888 | Pax*Pen=1.243 | PRMs=1
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=191.0 | Pen=0.00646 | Pax*Pen=1.233 | PRMs=1
[DEBUG flight] Airline=FR | Country=PORTUGAL | Pax=186.0 | Pen=0.00860 | Pax*Pen=1.600 | PRMs=2
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=191.0 | Pen=0.00646 | Pax*Pen=1.233 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=179.0 | Pen=0.00935 | Pax*Pen=1.673 | PRMs=2
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=165.0 | Pen=0.01067 | Pax*Pen=1.761 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=170.0 | Pen=0.00337 | Pax*Pen=0.573 | PRMs=1
[DEBUG flight] Airline=RK | Country=ALBANIA | Pax=168.0 | Pen=0.00837 | Pax*Pen=1.407 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=172.0 | Pen=0.00745 | Pax*Pen=1.281 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=170.0 | Pen=0.01067 | Pax*Pen=1.814 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=216.0 | Pen=0.01029 | Pax*Pen=2.222 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=179.0 | Pen=0.00337 | Pax*Pen=0.604 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=167.0 | Pen=0.03201 | Pax*Pen=5.346 | PRMs=5
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=173.0 | Pen=0.00920 | Pax*Pen=1.591 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 13771
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7106
WCHS     5753
WCHC      765
OTHER     147
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 8920
Airlines (sample): ['KL' 'AF' 'FR' 'U2' 'RK' 'LH' 'BA' 'LS' 'QR' 'EA']
Countries (sample): ['NETHERLANDS' 'FRANCE' 'IRISH REPUBLIC' 'PORTUGAL' 'SPAIN' 'POLAND'
 'ALBANIA' 'GERMANY' 'GREAT BRITAIN' 'ITALY']

Pax describe:
count    8920.000000
mean      144.445964
std        56.776957
min         0.000000
25%       118.000000
50%       159.000000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       KL     NETHERLANDS  International   D  227.0
1       AF          FRANCE  International   D  140.0
2       FR  IRISH REPUBLIC            CTA   D  191.0
3       FR        PORTUGAL  International   D  186.0
4       FR  IRISH REPUBLIC            CTA   D  191.0
5       U2          FRANCE  International   D  179.0
6       FR           SPAIN  International   D  165.0
7       FR          POLAND  International   D  170.0
8       RK         ALBANIA  International   D  168.0
9       LH         GERMANY  International   D  172.0
10      FR           SPAIN  International   D  170.0
11      BA   GREAT BRITAIN       Domestic   D  216.0
12      FR          POLAND  International   D  179.0
13      LS           SPAIN  International   D  167.0
14      U2   GREAT BRITAIN       Domestic   D  173.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,813 / 8,920 (87.6%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          375
2      EA  IRISH REPUBLIC          336
1      EA   GREAT BRITAIN          224
4      EC     NETHERLANDS           96
3      EC          FRANCE           52
5      LG      LUXEMBOURG           18
6      LS   GREAT BRITAIN            2
7      LS          POLAND            2
8      U2          NORWAY            2

Example missing keys:
    Airline     CountryName    Pax
37       EA   GREAT BRITAIN   72.0
39       EA  IRISH REPUBLIC   68.0
42       EC          FRANCE  140.0
61       CJ   GREAT BRITAIN  106.0
62       CJ   GREAT BRITAIN  106.0
75       EA  IRISH REPUBLIC   67.0
76       EA   GREAT BRITAIN   70.0
77       EC     NETHERLANDS  156.0
87       EA  IRISH REPUBLIC   68.0
114      EC     NETHERLANDS  186.0
117      EA  IRISH REPUBLIC   68.0
125      EA   GREAT BRITAIN   61.0
131      EA  IRISH REPUBLIC   68.0
143      CJ   GREAT BRITAIN  106.0
160      EA   GREAT BRITAIN   55.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13531.089630662496
Total PRMs after rounding: 13771

Raw PRM demand distribution (prm_raw):
count    8920.000000
mean        1.516938
std         1.436822
min         0.000000
25%         0.723778
50%         1.195554
75%         1.694834
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
24        QR       QATAR  311.0   0.031641  9.840463          10
769       QR       QATAR  311.0   0.031641  9.840463          10
932       QR       QATAR  311.0   0.031641  9.840463          10
7387      QR       QATAR  311.0   0.031641  9.840463          10
3761      QR       QATAR  311.0   0.031641  9.840463          10
416       QR       QATAR  311.0   0.031641  9.840463          10
4833      QR       QATAR  311.0   0.031641  9.840463          10
2930      QR       QATAR  311.0   0.031641  9.840463          10
1931      QR       QATAR  311.0   0.031641  9.840463          10
679       QR       QATAR  311.0   0.031641  9.840463          10
3674      QR       QATAR  311.0   0.031641  9.840463          10
3923      QR       QATAR  311.0   0.031641  9.840463          10
1769      QR       QATAR  311.0   0.031641  9.840463          10
8022      QR       QATAR  310.0   0.031641  9.808822          10
8242      QR       QATAR  308.0   0.031641  9.745539          10
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=227.0 | Pen=0.00911 | Pax*Pen=2.068 | PRMs=2
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=140.0 | Pen=0.00888 | Pax*Pen=1.243 | PRMs=1
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=191.0 | Pen=0.00646 | Pax*Pen=1.233 | PRMs=1
[DEBUG flight] Airline=FR | Country=PORTUGAL | Pax=186.0 | Pen=0.00860 | Pax*Pen=1.600 | PRMs=2
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=191.0 | Pen=0.00646 | Pax*Pen=1.233 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=179.0 | Pen=0.00935 | Pax*Pen=1.673 | PRMs=2
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=165.0 | Pen=0.01067 | Pax*Pen=1.761 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=170.0 | Pen=0.00337 | Pax*Pen=0.573 | PRMs=1
[DEBUG flight] Airline=RK | Country=ALBANIA | Pax=168.0 | Pen=0.00837 | Pax*Pen=1.407 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=172.0 | Pen=0.00745 | Pax*Pen=1.281 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=170.0 | Pen=0.01067 | Pax*Pen=1.814 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=216.0 | Pen=0.01029 | Pax*Pen=2.222 | PRMs=2
[DEBUG flight] Airline=FR | Country=POLAND | Pax=179.0 | Pen=0.00337 | Pax*Pen=0.604 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=167.0 | Pen=0.03201 | Pax*Pen=5.346 | PRMs=5
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=173.0 | Pen=0.00920 | Pax*Pen=1.591 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 13771
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7111
WCHS     5727
WCHC      773
OTHER     160
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1396 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (13,831 passenger rows)   [46.21s]
    ✓ P100 built (8,081 flights)   [0.20s]
    P100 demand summary: 13,831 PRMs across 8,081 flights
    ✓ prepare_model_data started | flights=8,081   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.04s]
    ✓ ambulift intervals built | flights=8,081 ambulifts=14   [0.99s]
    ✓ minibus intervals built | minibuses=3   [0.09s]
    ✓ staff intervals built   [0.02s]
    ✓ ambulift overlaps built | overlaps=6,484,534   [1.30s]
    ✓ minibus overlaps built | overlaps=590,232   [0.13s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=2.60s   [0.00s]
    ✓ sets built | F=8,081 AMB=14 MINI=3   [0.01s]
    ✓ variables built | x=40,405 amb=339,402 mini=48,486   [3.96s]
    ✓ ambulift overlap constraints built | 6,484,534   [37.94s]
    ✓ minibus overlap constraints built | 590,232   [2.11s]
    ✓ build_pyomo_model complete | total=45.47s   [1.46s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=8,081 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 7608151 rows; 484877 cols; 15653979 nonzeros; 428310 integer variables (428310 binary)
Coefficient ranges:
  Matrix  [1e+00, 1e+01]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
1184552 rows, 190964 cols, 2523566 nonzeros 8s
404242 rows, 167109 cols, 1719758 nonzeros 66s
404242 rows, 167109 cols, 1719758 nonzeros 135s
Presolve reductions: rows 404242(-7203909); columns 167109(-317768); nonzeros 1719758(-13934221)
Objective function is integral with scale 219

Solving MIP model with:
   404242 rows
   167109 cols (150021 binary, 0 integer, 17088 implied int., 0 continuous, 0 domain fixed)
   1719758 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            3758442641.653     Large        0      0      0         0   153.0s
 R       0       0         0   0.00%   16448059.03439  1426185414.297    98.85%        0      0      0    121560   706.6s
         0       0         0   0.00%   16448086.03439  1426185414.297    98.85%      790     40      0    123412   744.4s
         0       0         0   0.00%   16448086.03439  1426185414.297    98.85%      923     70      0    126573   784.6s
         0       0         0   0.00%   16448086.03439  1426185414.297    98.85%      968     72      0    128384   817.1s
         0       0         0   0.00%   16448279.03439  1426185414.297    98.85%      981    219      0    129799   852.2s
         0       0         0   0.00%   16448524.84391  1426185414.297    98.85%     1089    329  12849    130298   875.1s
         0       0         0   0.00%   16449058.33598  1426185414.297    98.85%     1137    399  12849    131536   895.7s
         0       0         0   0.00%   16449086.16931  1426185414.297    98.85%     1148    406  12849    141317   979.1s
         0       0         0   0.00%   16449891.96931  1426185414.297    98.85%     1347    420  12849    142706  1006.7s
         0       0         0   0.00%   16449974.36931  1426185414.297    98.85%     1357    424  12849    144784  1056.0s
         0       0         0   0.00%   16449974.36931  1426185414.297    98.85%     1506    426  12849    157673  1427.2s
         0       0         0   0.00%   16450490.70264  1426185414.297    98.85%     2143    443  12849    159161  1837.8s
         0       0         0   0.00%   16450490.70264  1426185414.297    98.85%     2302    445  12849    160329  2139.3s
         0       0         0   0.00%   16450490.70264  1426185414.297    98.85%     2468    447  12849    162029  2456.2s
         0       0         0   0.00%   16450490.70264  1426185414.297    98.85%     2648    449  12849    163311  2766.9s
         0       0         0   0.00%   16450933.09153  1426185414.297    98.85%     2801    511  12849    166833  3100.8s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     2852    523  12849    202816  3320.6s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     3870    528  12849    205175  3408.1s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     3892    531  12849    207883  3505.8s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     3902    534  12849    208214  3559.3s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     3919    525  12849    210415  3626.7s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     4084    528  12849    212059  3713.5s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     4174    532  12849    215320  3825.5s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     4242    535  12849    216804  3899.5s
         0       0         0   0.00%   16451182.42487  1426185414.297    98.85%     4275    538  12849    220250  4011.8s
 L       0       0         0   0.00%   16451182.42487  16451278.2968      0.00%     4275    538  12849    220250  5852.9s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,10,2,10,10,10,11,19,19,99.769884,12,3
1,10,2,10,10,10,11,19,19,99.920102,12,3

In [14]:
december_result = run_combined_month(
    2026,
    12,
)

pd.DataFrame(december_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2026_12
================================================================================

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 9150
Airlines (sample): ['FR' 'U2' 'BA' 'FI' 'AF' 'A3' 'EA' 'DY' 'LM' 'KL']
Countries (sample): ['SPAIN' 'GREAT BRITAIN' 'GERMANY' 'ICELAND' 'FRANCE' 'EGYPT' 'GREECE'
 'IRISH REPUBLIC' 'NORWAY' 'NETHERLANDS']

Pax describe:
count    9150.000000
mean      144.236503
std        54.975747
min         0.000000
25%       118.000000
50%       157.500000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       FR           SPAIN  International   D   85.0
1       U2   GREAT BRITAIN       Domestic   D  146.0
2       BA   GREAT BRITAIN       Domestic   D  204.0
3       U2         GERMANY  International   D  235.0
4       FI         ICELAND  International   D  160.0
5       AF          FRANCE  International   D  131.0
6       U2           EGYPT  International   D  162.0
7       A3          GREECE  International   D  152.0
8       EA  IRISH REPUBLIC            CTA   D   71.0
9       DY          NORWAY  International   D  149.0
10      LM   GREAT BRITAIN       Domestic   D   26.0
11      U2   GREAT BRITAIN       Domestic   D  180.0
12      U2         ICELAND  International   D  213.0
13      EA  IRISH REPUBLIC            CTA   D   72.0
14      LM   GREAT BRITAIN       Domestic   D   29.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 8,162 / 9,150 (89.2%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
2      EA  IRISH REPUBLIC          344
0      CJ   GREAT BRITAIN          270
1      EA   GREAT BRITAIN          178
4      EC     NETHERLANDS           96
3      EC          FRANCE           58
8      U2          NORWAY           18
5      LG      LUXEMBOURG           16
6      LS         FINLAND            6
7      LS  IRISH REPUBLIC            2

Example missing keys:
    Airline     CountryName    Pax
8        EA  IRISH REPUBLIC   71.0
13       EA  IRISH REPUBLIC   72.0
26       CJ   GREAT BRITAIN   76.0
29       CJ   GREAT BRITAIN   72.0
34       CJ   GREAT BRITAIN   72.0
38       EA   GREAT BRITAIN   23.0
39       EA  IRISH REPUBLIC   61.0
48       CJ   GREAT BRITAIN   80.0
59       EA  IRISH REPUBLIC   72.0
76       CJ   GREAT BRITAIN   92.0
79       EA  IRISH REPUBLIC   68.0
94       EC     NETHERLANDS  156.0
95       CJ   GREAT BRITAIN   83.0
99       EA  IRISH REPUBLIC   72.0
112      CJ   GREAT BRITAIN   98.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13270.748163820066
Total PRMs after rounding: 13525

Raw PRM demand distribution (prm_raw):
count    9150.000000
mean        1.450355
std         1.336170
min         0.000000
25%         0.720000
50%         1.180756
75%         1.645604
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
1578      QR       QATAR  311.0   0.031641  9.840463          10
4745      QR       QATAR  311.0   0.031641  9.840463          10
596       QR       QATAR  311.0   0.031641  9.840463          10
2068      QR       QATAR  311.0   0.031641  9.840463          10
3310      QR       QATAR  311.0   0.031641  9.840463          10
1701      QR       QATAR  311.0   0.031641  9.840463          10
7620      QR       QATAR  311.0   0.031641  9.840463          10
3051      QR       QATAR  311.0   0.031641  9.840463          10
243       QR       QATAR  311.0   0.031641  9.840463          10
173       QR       QATAR  311.0   0.031641  9.840463          10
7219      QR       QATAR  311.0   0.031641  9.840463          10
2785      QR       QATAR  311.0   0.031641  9.840463          10
6903      QR       QATAR  311.0   0.031641  9.840463          10
6862      QR       QATAR  310.0   0.031641  9.808822          10
7885      QR       QATAR  309.0   0.031641  9.777180          10
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=85.0 | Pen=0.01067 | Pax*Pen=0.907 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=146.0 | Pen=0.00920 | Pax*Pen=1.343 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=204.0 | Pen=0.01029 | Pax*Pen=2.098 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GERMANY | Pax=235.0 | Pen=0.00673 | Pax*Pen=1.582 | PRMs=2
[DEBUG flight] Airline=FI | Country=ICELAND | Pax=160.0 | Pen=0.00740 | Pax*Pen=1.184 | PRMs=1
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=131.0 | Pen=0.00888 | Pax*Pen=1.163 | PRMs=1
[DEBUG flight] Airline=U2 | Country=EGYPT | Pax=162.0 | Pen=0.02742 | Pax*Pen=4.443 | PRMs=4
[DEBUG flight] Airline=A3 | Country=GREECE | Pax=152.0 | Pen=0.00821 | Pax*Pen=1.247 | PRMs=1
[DEBUG flight] Airline=EA | Country=IRISH REPUBLIC | Pax=71.0 | Pen=0.01000 | Pax*Pen=0.710 | PRMs=1
[DEBUG flight] Airline=DY | Country=NORWAY | Pax=149.0 | Pen=0.00496 | Pax*Pen=0.739 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=26.0 | Pen=0.02036 | Pax*Pen=0.529 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=180.0 | Pen=0.00920 | Pax*Pen=1.655 | PRMs=2
[DEBUG flight] Airline=U2 | Country=ICELAND | Pax=213.0 | Pen=0.00533 | Pax*Pen=1.136 | PRMs=1
[DEBUG flight] Airline=EA | Country=IRISH REPUBLIC | Pax=72.0 | Pen=0.01000 | Pax*Pen=0.720 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=29.0 | Pen=0.02036 | Pax*Pen=0.590 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 13525
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7058
WCHS     5551
WCHC      786
OTHER     130
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 9150
Airlines (sample): ['KL' 'AF' 'FR' 'BA' 'U2' 'CJ' 'LM' 'LH' 'LS' 'RK']
Countries (sample): ['NETHERLANDS' 'FRANCE' 'SPAIN' 'GREAT BRITAIN' 'ITALY' 'SWITZERLAND'
 'GERMANY' 'PORTUGAL' 'MOROCCO' 'IRISH REPUBLIC']

Pax describe:
count    9150.000000
mean      144.236503
std        54.975747
min         0.000000
25%       118.000000
50%       157.500000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       KL    NETHERLANDS  International   D  124.0
1       AF         FRANCE  International   D  102.0
2       FR          SPAIN  International   D   91.0
3       BA  GREAT BRITAIN       Domestic   D   94.0
4       U2          SPAIN  International   D  122.0
5       U2  GREAT BRITAIN       Domestic   D  170.0
6       FR          ITALY  International   D  176.0
7       U2    SWITZERLAND  International   D  169.0
8       FR          SPAIN  International   D   85.0
9       U2         FRANCE  International   D  168.0
10      CJ  GREAT BRITAIN       Domestic   D   84.0
11      LM  GREAT BRITAIN       Domestic   D   12.0
12      U2  GREAT BRITAIN       Domestic   D   55.0
13      LH        GERMANY  International   D  166.0
14      LM  GREAT BRITAIN       Domestic   D   29.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 8,162 / 9,150 (89.2%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
2      EA  IRISH REPUBLIC          344
0      CJ   GREAT BRITAIN          270
1      EA   GREAT BRITAIN          178
4      EC     NETHERLANDS           96
3      EC          FRANCE           58
8      U2          NORWAY           18
5      LG      LUXEMBOURG           16
6      LS         FINLAND            6
7      LS  IRISH REPUBLIC            2

Example missing keys:
    Airline     CountryName    Pax
10       CJ   GREAT BRITAIN   84.0
15       CJ   GREAT BRITAIN   90.0
21       CJ   GREAT BRITAIN   90.0
26       EA   GREAT BRITAIN   38.0
28       EA  IRISH REPUBLIC   72.0
30       CJ   GREAT BRITAIN   86.0
40       CJ   GREAT BRITAIN   76.0
53       EA  IRISH REPUBLIC   71.0
76       CJ   GREAT BRITAIN  106.0
79       EA  IRISH REPUBLIC   72.0
89       EA  IRISH REPUBLIC   72.0
102      EC     NETHERLANDS  172.0
106      CJ   GREAT BRITAIN   97.0
107      EA   GREAT BRITAIN   66.0
109      EA  IRISH REPUBLIC   65.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 13270.748163820066
Total PRMs after rounding: 13525

Raw PRM demand distribution (prm_raw):
count    9150.000000
mean        1.450355
std         1.336170
min         0.000000
25%         0.720000
50%         1.180756
75%         1.645604
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
1578      QR       QATAR  311.0   0.031641  9.840463          10
6903      QR       QATAR  311.0   0.031641  9.840463          10
2068      QR       QATAR  311.0   0.031641  9.840463          10
3310      QR       QATAR  311.0   0.031641  9.840463          10
324       QR       QATAR  311.0   0.031641  9.840463          10
7620      QR       QATAR  311.0   0.031641  9.840463          10
4745      QR       QATAR  311.0   0.031641  9.840463          10
7219      QR       QATAR  311.0   0.031641  9.840463          10
412       QR       QATAR  311.0   0.031641  9.840463          10
2911      QR       QATAR  311.0   0.031641  9.840463          10
1701      QR       QATAR  311.0   0.031641  9.840463          10
575       QR       QATAR  311.0   0.031641  9.840463          10
3051      QR       QATAR  311.0   0.031641  9.840463          10
6862      QR       QATAR  310.0   0.031641  9.808822          10
7885      QR       QATAR  309.0   0.031641  9.777180          10
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=124.0 | Pen=0.00911 | Pax*Pen=1.130 | PRMs=1
[DEBUG flight] Airline=AF | Country=FRANCE | Pax=102.0 | Pen=0.00888 | Pax*Pen=0.906 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=91.0 | Pen=0.01067 | Pax*Pen=0.971 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=94.0 | Pen=0.01029 | Pax*Pen=0.967 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SPAIN | Pax=122.0 | Pen=0.01800 | Pax*Pen=2.197 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=170.0 | Pen=0.00920 | Pax*Pen=1.563 | PRMs=2
[DEBUG flight] Airline=FR | Country=ITALY | Pax=176.0 | Pen=0.00433 | Pax*Pen=0.763 | PRMs=1
[DEBUG flight] Airline=U2 | Country=SWITZERLAND | Pax=169.0 | Pen=0.00697 | Pax*Pen=1.179 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=85.0 | Pen=0.01067 | Pax*Pen=0.907 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=168.0 | Pen=0.00935 | Pax*Pen=1.570 | PRMs=2
[DEBUG flight] Airline=CJ | Country=GREAT BRITAIN | Pax=84.0 | Pen=0.01000 | Pax*Pen=0.840 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=12.0 | Pen=0.02036 | Pax*Pen=0.244 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=55.0 | Pen=0.00920 | Pax*Pen=0.506 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=166.0 | Pen=0.00745 | Pax*Pen=1.236 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=29.0 | Pen=0.02036 | Pax*Pen=0.590 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 13525
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     7009
WCHS     5580
WCHC      788
OTHER     148
Name: count, dtype: int64
[BUILD_JOBS] Dropping 2 jobs already impossible at release (beyond SLA + max late)
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1221 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (13,581 passenger rows)   [49.58s]
    ✓ P100 built (8,292 flights)   [0.15s]
    P100 demand summary: 13,581 PRMs across 8,292 flights
    ✓ prepare_model_data started | flights=8,292   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.03s]
    ✓ ambulift intervals built | flights=8,292 ambulifts=14   [0.94s]
    ✓ minibus intervals built | minibuses=3   [0.09s]
    ✓ staff intervals built   [0.02s]
    ✓ ambulift overlaps built | overlaps=6,548,265   [1.28s]
    ✓ minibus overlaps built | overlaps=594,810   [0.11s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=2.50s   [0.00s]
    ✓ sets built | F=8,292 AMB=14 MINI=3   [0.00s]
    ✓ variables built | x=41,460 amb=348,264 mini=49,752   [0.72s]
    ✓ ambulift overlap constraints built | 6,548,265   [40.72s]
    ✓ minibus overlap constraints built | 594,810   [6.40s]
    ✓ build_pyomo_model complete | total=49.68s   [1.84s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=8,292 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 7690387 rows; 497537 cols; 15829790 nonzeros; 439493 integer variables (439493 binary)
Coefficient ranges:
  Matrix  [1e+00, 1e+01]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
1230047 rows, 196862 cols, 2616870 nonzeros 10s
415059 rows, 172376 cols, 1776787 nonzeros 82s
415059 rows, 172376 cols, 1776787 nonzeros 158s
Presolve reductions: rows 415059(-7275328); columns 172376(-325161); nonzeros 1776787(-14053003)
Objective function is integral with scale 219

Solving MIP model with:
   415059 rows
   172376 cols (154831 binary, 0 integer, 17545 implied int., 0 continuous, 0 domain fixed)
   1776787 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            3966435641.826     Large        0      0      0         0   182.8s
 R       0       0         0   0.00%   7698382.429069  1084439138.635    99.29%        0      0      0    110824   593.3s
         0       0         0   0.00%   7698382.429069  1084439138.635    99.29%      991     38      0    111231   611.1s
         0       0         0   0.00%   7698382.429069  1084439138.635    99.29%     1033     69      0    112952   638.9s
         0       0         0   0.00%   7698547.762403  1084439138.635    99.29%     1126    202      0    114446   656.8s
         0       0         0   0.00%   7698818.238593  1084439138.635    99.29%     1225    328      0    115904   672.4s
 C       0       0         0   0.00%   7699475.071926  888440444.2968    99.13%     1265    425      0    116392   682.0s
         0       0         0   0.00%   7699628.071926  888440444.2968    99.13%     1277    440      0    116530   689.1s
         0       0         0   0.00%   7699667.738593  888440444.2968    99.13%     1283    446      0    122302   740.9s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1530    463      0    123606   777.0s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1537    465      0    123934   788.6s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1561    467      0    125100   808.6s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1583    469      0    126358   835.3s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1628    471      0    128006   866.4s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1728    474      0    129724   895.6s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1786    476      0    130247   919.0s
         0       0         0   0.00%   7700115.976688  888440444.2968    99.13%     1844    434      0    130360   957.7s
         0       0         0   0.00%   7700120.310022  888440444.2968    99.13%     1869    442      0    169803  1197.1s
         0       0         0   0.00%   7700139.624974  888440444.2968    99.13%     2890    454      0    204476  1412.6s
         0       0         0   0.00%   7700186.922963  888440444.2968    99.13%     3562    484      0    219970  1508.9s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   7700186.922963  888440444.2968    99.13%     4208    497      0    221882  1563.8s
         0       0         0   0.00%   7700186.922963  888440444.2968    99.13%     4242    493      0    228649  1645.1s
         0       0         0   0.00%   7700187.258143  888440444.2968    99.13%     4613    504      0    263395  1849.2s
         0       0         0   0.00%   7700187.258143  888440444.2968    99.13%     5628    512      0    278551  1968.8s
         0       0         0   0.00%   7700187.258143  888440444.2968    99.13%     6106    522      0    310161  2127.6s
         0       0         0   0.00%   7700194.388128  888440444.2968    99.13%     7147    531      0    339351  2279.8s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,10,2,10,10,11,11,21,21,99.864171,13,3
1,9,1,9,9,11,11,21,21,99.950650,12,3

In [15]:
january_result = run_combined_month(
    2027,
    1,
)

pd.DataFrame(january_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2027_01
================================================================================

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 8099
Airlines (sample): ['VY' 'FR' 'U2' 'RK' 'SK' 'LM' 'BA' 'UA' 'AF' 'DY']
Countries (sample): ['SPAIN' 'POLAND' 'AUSTRIA' 'GREAT BRITAIN' 'CZECH REPUBLIC' 'DENMARK'
 'GERMANY' 'UNITED STATES OF AMERICA' 'FRANCE' 'NORWAY']

Pax describe:
count    8099.000000
mean      142.145820
std        57.164454
min         0.000000
25%       112.000000
50%       156.000000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       VY           SPAIN  International   A  186.0
1       FR          POLAND  International   A  175.0
2       FR         AUSTRIA  International   A  195.0
3       U2   GREAT BRITAIN       Domestic   A  120.0
4       FR  CZECH REPUBLIC  International   D  177.0
5       RK   GREAT BRITAIN       Domestic   D  187.0
6       FR          POLAND  International   D  190.0
7       FR           SPAIN  International   D  150.0
8       U2   GREAT BRITAIN       Domestic   A   91.0
9       U2   GREAT BRITAIN       Domestic   D  183.0
10      U2   GREAT BRITAIN       Domestic   A  168.0
11      SK         DENMARK  International   A  111.0
12      U2         GERMANY  International   A  179.0
13      FR  CZECH REPUBLIC  International   A  172.0
14      U2   GREAT BRITAIN       Domestic   D  127.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,284 / 8,099 (89.9%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          269
2      EA  IRISH REPUBLIC          240
1      EA   GREAT BRITAIN          154
4      EC     NETHERLANDS           80
3      EC          FRANCE           38
5      LG      LUXEMBOURG           18
6      U2          NORWAY           16

Example missing keys:
    Airline     CountryName    Pax
41       CJ   GREAT BRITAIN   94.0
73       EC          FRANCE  235.0
83       EA   GREAT BRITAIN   51.0
92       EA  IRISH REPUBLIC   72.0
104      CJ   GREAT BRITAIN   93.0
142      LG      LUXEMBOURG  127.0
143      EA  IRISH REPUBLIC   68.0
165      EA  IRISH REPUBLIC   57.0
194      CJ   GREAT BRITAIN   88.0
197      EA  IRISH REPUBLIC   65.0
212      EA   GREAT BRITAIN   58.0
250      EA  IRISH REPUBLIC   72.0
257      CJ   GREAT BRITAIN   58.0
268      EC     NETHERLANDS  173.0
269      LG      LUXEMBOURG  101.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11960.133112213824
Total PRMs after rounding: 12087

Raw PRM demand distribution (prm_raw):
count    8099.000000
mean        1.476742
std         1.471391
min         0.000000
25%         0.710000
50%         1.158768
75%         1.614749
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
8044      QR       QATAR  311.0   0.031641  9.840463          10
2422      QR       QATAR  311.0   0.031641  9.840463          10
6275      QR       QATAR  311.0   0.031641  9.840463          10
7119      QR       QATAR  311.0   0.031641  9.840463          10
7139      QR       QATAR  311.0   0.031641  9.840463          10
5813      QR       QATAR  311.0   0.031641  9.840463          10
7232      QR       QATAR  311.0   0.031641  9.840463          10
4306      QR       QATAR  311.0   0.031641  9.840463          10
3869      QR       QATAR  311.0   0.031641  9.840463          10
6321      QR       QATAR  311.0   0.031641  9.840463          10
6370      QR       QATAR  311.0   0.031641  9.840463          10
4809      QR       QATAR  311.0   0.031641  9.840463          10
7379      QR       QATAR  311.0   0.031641  9.840463          10
7056      QR       QATAR  311.0   0.031641  9.840463          10
7643      QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=VY | Country=SPAIN | Pax=186.0 | Pen=0.00604 | Pax*Pen=1.124 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=175.0 | Pen=0.00337 | Pax*Pen=0.590 | PRMs=1
[DEBUG flight] Airline=FR | Country=AUSTRIA | Pax=195.0 | Pen=0.00153 | Pax*Pen=0.299 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=120.0 | Pen=0.00920 | Pax*Pen=1.104 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=177.0 | Pen=0.00317 | Pax*Pen=0.561 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=187.0 | Pen=0.00636 | Pax*Pen=1.189 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=190.0 | Pen=0.00337 | Pax*Pen=0.641 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=150.0 | Pen=0.01067 | Pax*Pen=1.600 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=91.0 | Pen=0.00920 | Pax*Pen=0.837 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=183.0 | Pen=0.00920 | Pax*Pen=1.683 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=168.0 | Pen=0.00920 | Pax*Pen=1.545 | PRMs=2
[DEBUG flight] Airline=SK | Country=DENMARK | Pax=111.0 | Pen=0.00545 | Pax*Pen=0.605 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GERMANY | Pax=179.0 | Pen=0.00673 | Pax*Pen=1.205 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=172.0 | Pen=0.00317 | Pax*Pen=0.545 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=127.0 | Pen=0.00920 | Pax*Pen=1.168 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 12087
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     6162
WCHS     5107
WCHC      705
OTHER     113
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 8099
Airlines (sample): ['VY' 'FR' 'U2' 'RK' 'SK' 'LM' 'BA' 'EA' 'UA' 'AF']
Countries (sample): ['SPAIN' 'POLAND' 'AUSTRIA' 'GREAT BRITAIN' 'CZECH REPUBLIC' 'DENMARK'
 'GERMANY' 'IRISH REPUBLIC' 'UNITED STATES OF AMERICA' 'FRANCE']

Pax describe:
count    8099.000000
mean      142.145820
std        57.164454
min         0.000000
25%       112.000000
50%       156.000000
75%       180.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       VY           SPAIN  International   A  186.0
1       FR          POLAND  International   A  175.0
2       FR         AUSTRIA  International   A  195.0
3       U2   GREAT BRITAIN       Domestic   A  120.0
4       FR  CZECH REPUBLIC  International   D  177.0
5       RK   GREAT BRITAIN       Domestic   D  187.0
6       FR          POLAND  International   D  190.0
7       FR           SPAIN  International   D  150.0
8       U2   GREAT BRITAIN       Domestic   A   91.0
9       U2   GREAT BRITAIN       Domestic   D  183.0
10      U2   GREAT BRITAIN       Domestic   A  168.0
11      SK         DENMARK  International   A  111.0
12      U2         GERMANY  International   A  179.0
13      FR  CZECH REPUBLIC  International   A  172.0
14      U2   GREAT BRITAIN       Domestic   D  127.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,284 / 8,099 (89.9%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          269
2      EA  IRISH REPUBLIC          240
1      EA   GREAT BRITAIN          154
4      EC     NETHERLANDS           80
3      EC          FRANCE           38
5      LG      LUXEMBOURG           18
6      U2          NORWAY           16

Example missing keys:
    Airline     CountryName    Pax
19       EA  IRISH REPUBLIC   70.0
32       CJ   GREAT BRITAIN   99.0
38       CJ   GREAT BRITAIN  102.0
56       EA   GREAT BRITAIN   57.0
57       CJ   GREAT BRITAIN   94.0
80       CJ   GREAT BRITAIN   97.0
87       CJ   GREAT BRITAIN   26.0
92       CJ   GREAT BRITAIN  106.0
110      EC          FRANCE  235.0
116      EA   GREAT BRITAIN   31.0
123      EA   GREAT BRITAIN   51.0
133      EA  IRISH REPUBLIC   72.0
137      CJ   GREAT BRITAIN   91.0
141      EA  IRISH REPUBLIC   65.0
150      EC          FRANCE  170.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11960.133112213824
Total PRMs after rounding: 12087

Raw PRM demand distribution (prm_raw):
count    8099.000000
mean        1.476742
std         1.471391
min         0.000000
25%         0.710000
50%         1.158768
75%         1.614749
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
4809      QR       QATAR  311.0   0.031641  9.840463          10
7232      QR       QATAR  311.0   0.031641  9.840463          10
4566      QR       QATAR  311.0   0.031641  9.840463          10
6275      QR       QATAR  311.0   0.031641  9.840463          10
5813      QR       QATAR  311.0   0.031641  9.840463          10
6370      QR       QATAR  311.0   0.031641  9.840463          10
4306      QR       QATAR  311.0   0.031641  9.840463          10
7119      QR       QATAR  311.0   0.031641  9.840463          10
7139      QR       QATAR  311.0   0.031641  9.840463          10
7379      QR       QATAR  311.0   0.031641  9.840463          10
7684      QR       QATAR  311.0   0.031641  9.840463          10
4677      QR       QATAR  311.0   0.031641  9.840463          10
2422      QR       QATAR  311.0   0.031641  9.840463          10
6321      QR       QATAR  311.0   0.031641  9.840463          10
8044      QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=VY | Country=SPAIN | Pax=186.0 | Pen=0.00604 | Pax*Pen=1.124 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=175.0 | Pen=0.00337 | Pax*Pen=0.590 | PRMs=1
[DEBUG flight] Airline=FR | Country=AUSTRIA | Pax=195.0 | Pen=0.00153 | Pax*Pen=0.299 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=120.0 | Pen=0.00920 | Pax*Pen=1.104 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=177.0 | Pen=0.00317 | Pax*Pen=0.561 | PRMs=1
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=187.0 | Pen=0.00636 | Pax*Pen=1.189 | PRMs=1
[DEBUG flight] Airline=FR | Country=POLAND | Pax=190.0 | Pen=0.00337 | Pax*Pen=0.641 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=150.0 | Pen=0.01067 | Pax*Pen=1.600 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=91.0 | Pen=0.00920 | Pax*Pen=0.837 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=183.0 | Pen=0.00920 | Pax*Pen=1.683 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=168.0 | Pen=0.00920 | Pax*Pen=1.545 | PRMs=2
[DEBUG flight] Airline=SK | Country=DENMARK | Pax=111.0 | Pen=0.00545 | Pax*Pen=0.605 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GERMANY | Pax=179.0 | Pen=0.00673 | Pax*Pen=1.205 | PRMs=1
[DEBUG flight] Airline=FR | Country=CZECH REPUBLIC | Pax=172.0 | Pen=0.00317 | Pax*Pen=0.545 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=127.0 | Pen=0.00920 | Pax*Pen=1.168 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 12087
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     6199
WCHS     5073
WCHC      687
OTHER     128
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1278 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (12,142 passenger rows)   [36.83s]
    ✓ P100 built (7,246 flights)   [0.12s]
    P100 demand summary: 12,142 PRMs across 7,246 flights
    ✓ prepare_model_data started | flights=7,246   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.03s]
    ✓ ambulift intervals built | flights=7,246 ambulifts=14   [0.70s]
    ✓ minibus intervals built | minibuses=3   [0.06s]
    ✓ staff intervals built   [0.01s]
    ✓ ambulift overlaps built | overlaps=5,074,694   [0.94s]
    ✓ minibus overlaps built | overlaps=461,919   [0.08s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=1.85s   [0.00s]
    ✓ sets built | F=7,246 AMB=14 MINI=3   [0.00s]
    ✓ variables built | x=36,230 amb=304,332 mini=43,476   [0.21s]
    ✓ ambulift overlap constraints built | 5,074,694   [28.41s]
    ✓ minibus overlap constraints built | 461,919   [1.43s]
    ✓ build_pyomo_model complete | total=31.15s   [1.09s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=7,246 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 6014870 rows; 434777 cols; 12422179 nonzeros; 384055 integer variables (384055 binary)
Coefficient ranges:
  Matrix  [1e+00, 1e+01]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
985848 rows, 173185 cols, 2114732 nonzeros 8s
360066 rows, 151720 cols, 1482571 nonzeros 50s
360066 rows, 151720 cols, 1482571 nonzeros 98s
Presolve reductions: rows 360066(-5654804); columns 151720(-283057); nonzeros 1482571(-10939608)
Objective function is integral with scale 219

Solving MIP model with:
   360066 rows
   151720 cols (136297 binary, 0 integer, 15423 implied int., 0 continuous, 0 domain fixed)
   1482571 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            3339385772.653     Large        0      0      0         0   116.0s
 R       0       0         0   0.00%   5639024.80206   833382781.6347    99.32%        0      0      0    145619   490.6s
         0       0         0   0.00%   5639038.80206   833382781.6347    99.32%     1281     63      0    146911   507.3s
         0       0         0   0.00%   5639436.587774  833382781.6347    99.32%     2346    241      0    147541   517.8s
         0       0         0   0.00%   5639838.540155  833382781.6347    99.32%     2498    399      0    148272   523.6s
         0       0         0   0.00%   5640788.77825   833382781.6347    99.32%     2548    554      0    149237   529.5s
 C       0       0         0   0.00%   5640943.77825   560384733.2968    98.99%     2560    578      0    150416   541.8s
         0       0         0   0.00%   5640970.77825   560384733.2968    98.99%     2611    589      0    150991   554.0s
         0       0         0   0.00%   5640975.77825   560384733.2968    98.99%     2640    594      0    151539   583.5s
         0       0         0   0.00%   5640976.649507  560384733.2968    98.99%     2669    597      0    183709   727.4s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3574    604      0    184377   763.0s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3590    608      0    186133   793.4s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3690    610      0    187146   825.4s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3723    612      0    188077   847.8s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3807    615      0    190325   887.1s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     3976    618      0    191313   910.3s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     4021    548      0    194398   948.8s
         0       0         0   0.00%   5641070.649507  560384733.2968    98.99%     4083    551      0    210896  1022.5s
         0       0         0   0.00%   5641070.768501  560384733.2968    98.99%     4806    556      0    244886  1197.8s
         0       0         0   0.00%   5641071.348252  560384733.2968    98.99%     5864    573      0    305664  1438.9s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   5641071.891312  560384733.2968    98.99%     6867    596      0    368958  1705.8s
         0       0         0   0.00%   5641072.122162  560384733.2968    98.99%     7713    600      0    413924  1900.6s
         0       0         0   0.00%   5641072.235408  560384733.2968    98.99%     8043    617      0    426056  1974.2s
         0       0         0   0.00%   5641072.464217  560384733.2968    98.99%     8704    634      0    457747  2145.0s
         0       0         0   0.00%   5641072.469068  560384733.2968    98.99%     9447    653      0    461748  2176.5s
         0       0         0   0.00%   5641072.576955  560384733.2968    98.99%     9529    663      0    492464  2326.0s
         0       0         0   0.00%   5641072.719623  560384733.2968    98.99%    10397    691      0    531165  2491.4s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,11,2,12,12,13,12,23,23,99.855538,14,3
1,9,1,9,9,13,12,23,23,99.964126,13,3

In [16]:
february_result = run_combined_month(
    2027,
    2,
)

pd.DataFrame(february_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2027_02
================================================================================

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 7784
Airlines (sample): ['FR' 'LS' 'U2' 'RK' 'LM' 'VY' 'BA' 'EA' 'EC' 'DS']
Countries (sample): ['BELGIUM' 'PORTUGAL' 'NORWAY' 'GREAT BRITAIN' 'GREECE' 'SPAIN' 'FRANCE'
 'IRISH REPUBLIC' 'SWITZERLAND' 'AUSTRIA']

Pax describe:
count    7784.000000
mean      145.576953
std        56.478301
min         0.000000
25%       117.000000
50%       160.000000
75%       181.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       FR        BELGIUM  International   A  170.0
1       LS       PORTUGAL  International   D  198.0
2       U2         NORWAY  International   D  152.0
3       RK  GREAT BRITAIN       Domestic   D  182.0
4       LM  GREAT BRITAIN       Domestic   A   13.0
5       U2  GREAT BRITAIN       Domestic   A  181.0
6       U2         GREECE  International   D  173.0
7       VY          SPAIN  International   D  163.0
8       LS          SPAIN  International   D  232.0
9       BA  GREAT BRITAIN       Domestic   D   14.0
10      FR          SPAIN  International   A  173.0
11      BA  GREAT BRITAIN       Domestic   D  147.0
12      VY          SPAIN  International   D  170.0
13      U2  GREAT BRITAIN       Domestic   D  101.0
14      FR          SPAIN  International   D  178.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 6,936 / 7,784 (89.1%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          288
2      EA  IRISH REPUBLIC          234
1      EA   GREAT BRITAIN          144
4      EC     NETHERLANDS           88
3      EC          FRANCE           56
5      LG      LUXEMBOURG           16
8      U2          NORWAY           16
6      LS           EGYPT            4
7      LS   GREAT BRITAIN            2

Example missing keys:
    Airline     CountryName    Pax
2        U2          NORWAY  152.0
18       EA   GREAT BRITAIN    0.0
41       EC          FRANCE  151.0
55       EA  IRISH REPUBLIC   72.0
62       CJ   GREAT BRITAIN   95.0
71       EC          FRANCE  172.0
73       EC     NETHERLANDS    0.0
79       EA  IRISH REPUBLIC   53.0
89       CJ   GREAT BRITAIN   74.0
96       EA   GREAT BRITAIN   57.0
98       EC          FRANCE  205.0
111      EA   GREAT BRITAIN   28.0
114      CJ   GREAT BRITAIN   88.0
115      EC          FRANCE  185.0
125      EA   GREAT BRITAIN   62.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11769.59887326046
Total PRMs after rounding: 11960

Raw PRM demand distribution (prm_raw):
count    7784.000000
mean        1.512025
std         1.458266
min         0.000000
25%         0.734922
50%         1.189621
75%         1.670000
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
889       QR       QATAR  311.0   0.031641  9.840463          10
3672      QR       QATAR  311.0   0.031641  9.840463          10
1326      QR       QATAR  311.0   0.031641  9.840463          10
1423      QR       QATAR  311.0   0.031641  9.840463          10
4920      QR       QATAR  311.0   0.031641  9.840463          10
4559      QR       QATAR  311.0   0.031641  9.840463          10
2330      QR       QATAR  311.0   0.031641  9.840463          10
5013      QR       QATAR  311.0   0.031641  9.840463          10
5156      QR       QATAR  311.0   0.031641  9.840463          10
7644      QR       QATAR  311.0   0.031641  9.840463          10
5103      QR       QATAR  311.0   0.031641  9.840463          10
2934      QR       QATAR  311.0   0.031641  9.840463          10
3697      QR       QATAR  311.0   0.031641  9.840463          10
1864      QR       QATAR  311.0   0.031641  9.840463          10
4949      QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=170.0 | Pen=0.00408 | Pax*Pen=0.694 | PRMs=1
[DEBUG flight] Airline=LS | Country=PORTUGAL | Pax=198.0 | Pen=0.02353 | Pax*Pen=4.660 | PRMs=5
[DEBUG flight] Airline=U2 | Country=NORWAY | Pax=152.0 | Pen=0.01000 | Pax*Pen=1.520 | PRMs=2
[DEBUG flight] Airline=RK | Country=GREAT BRITAIN | Pax=182.0 | Pen=0.00636 | Pax*Pen=1.157 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=13.0 | Pen=0.02036 | Pax*Pen=0.265 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=181.0 | Pen=0.00920 | Pax*Pen=1.665 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREECE | Pax=173.0 | Pen=0.01359 | Pax*Pen=2.351 | PRMs=2
[DEBUG flight] Airline=VY | Country=SPAIN | Pax=163.0 | Pen=0.00604 | Pax*Pen=0.985 | PRMs=1
[DEBUG flight] Airline=LS | Country=SPAIN | Pax=232.0 | Pen=0.03201 | Pax*Pen=7.427 | PRMs=7
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=14.0 | Pen=0.01029 | Pax*Pen=0.144 | PRMs=0
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=173.0 | Pen=0.01067 | Pax*Pen=1.846 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=147.0 | Pen=0.01029 | Pax*Pen=1.512 | PRMs=2
[DEBUG flight] Airline=VY | Country=SPAIN | Pax=170.0 | Pen=0.00604 | Pax*Pen=1.028 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=101.0 | Pen=0.00920 | Pax*Pen=0.929 | PRMs=1
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=178.0 | Pen=0.01067 | Pax*Pen=1.899 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 11960
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     6079
WCHS     5097
WCHC      684
OTHER     100
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 7784
Airlines (sample): ['U2' 'SK' 'EC' 'KL' 'LS' 'CJ' 'FR' 'RK' 'BA' 'BY']
Countries (sample): ['GREAT BRITAIN' 'DENMARK' 'GERMANY' 'NETHERLANDS' 'AUSTRIA' 'FRANCE'
 'BELGIUM' 'ALBANIA' 'IRISH REPUBLIC' 'SPAIN']

Pax describe:
count    7784.000000
mean      145.576953
std        56.478301
min         0.000000
25%       117.000000
50%       160.000000
75%       181.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline     CountryName         Sector dir    Pax
0       U2   GREAT BRITAIN       Domestic   A    0.0
1       SK         DENMARK  International   D  116.0
2       EC         GERMANY  International   A  164.0
3       KL     NETHERLANDS  International   D  196.0
4       LS         AUSTRIA  International   D  190.0
5       U2          FRANCE  International   A  184.0
6       CJ   GREAT BRITAIN       Domestic   D   66.0
7       KL     NETHERLANDS  International   A  227.0
8       FR         BELGIUM  International   A  177.0
9       U2   GREAT BRITAIN       Domestic   D  126.0
10      RK         ALBANIA  International   A  163.0
11      U2          FRANCE  International   A  186.0
12      FR  IRISH REPUBLIC            CTA   A  177.0
13      U2   GREAT BRITAIN       Domestic   D  164.0
14      FR           SPAIN  International   D  190.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 6,936 / 7,784 (89.1%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
0      CJ   GREAT BRITAIN          288
2      EA  IRISH REPUBLIC          234
1      EA   GREAT BRITAIN          144
4      EC     NETHERLANDS           88
3      EC          FRANCE           56
5      LG      LUXEMBOURG           16
8      U2          NORWAY           16
6      LS           EGYPT            4
7      LS   GREAT BRITAIN            2

Example missing keys:
    Airline     CountryName    Pax
6        CJ   GREAT BRITAIN   66.0
22       EC     NETHERLANDS   93.0
25       EC     NETHERLANDS  161.0
29       U2          NORWAY  152.0
35       EA  IRISH REPUBLIC   59.0
37       CJ   GREAT BRITAIN  101.0
50       EA   GREAT BRITAIN   65.0
52       EA  IRISH REPUBLIC   64.0
73       CJ   GREAT BRITAIN   33.0
74       EA  IRISH REPUBLIC   51.0
107      CJ   GREAT BRITAIN   45.0
109      EA  IRISH REPUBLIC   72.0
111      EA   GREAT BRITAIN    0.0
134      EA  IRISH REPUBLIC   60.0
148      CJ   GREAT BRITAIN  101.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11769.59887326046
Total PRMs after rounding: 11960

Raw PRM demand distribution (prm_raw):
count    7784.000000
mean        1.512025
std         1.458266
min         0.000000
25%         0.734922
50%         1.189621
75%         1.670000
max         9.840463
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
2934      QR       QATAR  311.0   0.031641  9.840463          10
1180      QR       QATAR  311.0   0.031641  9.840463          10
5103      QR       QATAR  311.0   0.031641  9.840463          10
5013      QR       QATAR  311.0   0.031641  9.840463          10
4949      QR       QATAR  311.0   0.031641  9.840463          10
4920      QR       QATAR  311.0   0.031641  9.840463          10
1423      QR       QATAR  311.0   0.031641  9.840463          10
1326      QR       QATAR  311.0   0.031641  9.840463          10
7644      QR       QATAR  311.0   0.031641  9.840463          10
5156      QR       QATAR  311.0   0.031641  9.840463          10
3672      QR       QATAR  311.0   0.031641  9.840463          10
3697      QR       QATAR  311.0   0.031641  9.840463          10
2330      QR       QATAR  311.0   0.031641  9.840463          10
4559      QR       QATAR  311.0   0.031641  9.840463          10
1864      QR       QATAR  311.0   0.031641  9.840463          10
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=0.0 | Pen=0.00920 | Pax*Pen=0.000 | PRMs=0
[DEBUG flight] Airline=SK | Country=DENMARK | Pax=116.0 | Pen=0.00545 | Pax*Pen=0.633 | PRMs=1
[DEBUG flight] Airline=EC | Country=GERMANY | Pax=164.0 | Pen=0.00041 | Pax*Pen=0.068 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=196.0 | Pen=0.00911 | Pax*Pen=1.786 | PRMs=2
[DEBUG flight] Airline=LS | Country=AUSTRIA | Pax=190.0 | Pen=0.00852 | Pax*Pen=1.618 | PRMs=2
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=184.0 | Pen=0.00935 | Pax*Pen=1.720 | PRMs=2
[DEBUG flight] Airline=CJ | Country=GREAT BRITAIN | Pax=66.0 | Pen=0.01000 | Pax*Pen=0.660 | PRMs=1
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=227.0 | Pen=0.00911 | Pax*Pen=2.068 | PRMs=2
[DEBUG flight] Airline=FR | Country=BELGIUM | Pax=177.0 | Pen=0.00408 | Pax*Pen=0.723 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=126.0 | Pen=0.00920 | Pax*Pen=1.159 | PRMs=1
[DEBUG flight] Airline=RK | Country=ALBANIA | Pax=163.0 | Pen=0.00837 | Pax*Pen=1.365 | PRMs=1
[DEBUG flight] Airline=U2 | Country=FRANCE | Pax=186.0 | Pen=0.00935 | Pax*Pen=1.738 | PRMs=2
[DEBUG flight] Airline=FR | Country=IRISH REPUBLIC | Pax=177.0 | Pen=0.00646 | Pax*Pen=1.143 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=164.0 | Pen=0.00920 | Pax*Pen=1.508 | PRMs=2
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=190.0 | Pen=0.01067 | Pax*Pen=2.027 | PRMs=2

[DEBUG ingest_s26]
Total PRM jobs (rows): 11960
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     6082
WCHS     5092
WCHC      680
OTHER     106
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1212 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (11,995 passenger rows)   [35.34s]
    ✓ P100 built (7,052 flights)   [0.12s]
    P100 demand summary: 11,995 PRMs across 7,052 flights
    ✓ prepare_model_data started | flights=7,052   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.02s]
    ✓ ambulift intervals built | flights=7,052 ambulifts=14   [0.65s]
    ✓ minibus intervals built | minibuses=3   [0.06s]
    ✓ staff intervals built   [0.01s]
    ✓ ambulift overlaps built | overlaps=5,284,233   [0.96s]
    ✓ minibus overlaps built | overlaps=480,513   [0.09s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=1.82s   [0.00s]
    ✓ sets built | F=7,052 AMB=14 MINI=3   [0.00s]
    ✓ variables built | x=35,260 amb=296,184 mini=42,312   [0.21s]
    ✓ ambulift overlap constraints built | 5,284,233   [28.56s]
    ✓ minibus overlap constraints built | 480,513   [1.43s]
    ✓ build_pyomo_model complete | total=31.19s   [0.99s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=7,052 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 6230217 rows; 423137 cols; 12842409 nonzeros; 373773 integer variables (373773 binary)
Coefficient ranges:
  Matrix  [1e+00, 1e+01]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
1059891 rows, 171943 cols, 2258969 nonzeros 8s
359493 rows, 150411 cols, 1541090 nonzeros 52s
359493 rows, 150411 cols, 1541090 nonzeros 100s
Presolve reductions: rows 359493(-5870724); columns 150411(-272726); nonzeros 1541090(-11301319)
Objective function is integral with scale 219

Solving MIP model with:
   359493 rows
   150411 cols (135189 binary, 0 integer, 15222 implied int., 0 continuous, 0 domain fixed)
   1541090 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            3464389465.826     Large        0      0      0         0   116.8s
 R       0       0         0   0.00%   11895519.41617  1020386870.804    98.83%        0      0      0     74891   413.6s
         0       0         0   0.00%   11895519.41617  1020386870.804    98.83%     1116     41      0     77298   436.0s
         0       0         0   0.00%   11895598.74951  1020386870.804    98.83%     1246     80      0     78694   446.4s
         0       0         0   0.00%   11895598.74951  1020386870.804    98.83%     1296     84      0     84229   488.2s
         0       0         0   0.00%   11895742.74951  1020386870.804    98.83%     1353    226      0     86951   509.5s
 C       0       0         0   0.00%   11896124.47014  810888461.2968    98.53%     1465    359      0     88582   520.8s
         0       0         0   0.00%   11896718.9876   810888461.2968    98.53%     1525    439      0     89998   530.6s
         0       0         0   0.00%   11896741.9876   810888461.2968    98.53%     1545    449      0     91705   542.0s
         0       0         0   0.00%   11896756.32093  810888461.2968    98.53%     1562    457      0     93541   556.1s
         0       0         0   0.00%   11896776.32093  810888461.2968    98.53%     1613    463      0     95766   576.2s
         0       0         0   0.00%   11896776.32093  810888461.2968    98.53%     1640    468      0     97212   589.2s
         0       0         0   0.00%   11896776.32093  810888461.2968    98.53%     1667    472      0     99342   607.3s
         0       0         0   0.00%   11896776.32093  810888461.2968    98.53%     1680    476      0    100338   624.0s
         0       0         0   0.00%   11896776.32093  810888461.2968    98.53%     1691    480      0    116111   700.6s
         0       0         0   0.00%   11897490.72093  810888461.2968    98.53%     2352    496      0    118454   719.1s
         0       0         0   0.00%   11897490.72093  810888461.2968    98.53%     2376    454      0    120053   734.7s
         0       0         0   0.00%   11897497.72093  810888461.2968    98.53%     2430    461      0    120617   748.4s
         0       0         0   0.00%   11897497.72093  810888461.2968    98.53%     2453    465      0    122250   763.6s
         0       0         0   0.00%   11897498.53309  810888461.2968    98.53%     2508    469      0    160250   933.7s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   11898069.86642  810888461.2968    98.53%     3510    485      0    163132   956.1s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     3541    470      0    165320   976.1s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     3606    475      0    176174  1029.3s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     3828    479      0    196627  1149.8s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     4441    485      0    217773  1249.0s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     5053    490      0    220211  1271.8s
         0       0         0   0.00%   11898079.86642  810888461.2968    98.53%     5071    488      0    222707  1292.7s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,9,2,9,9,11,11,21,21,99.768058,13,3
1,9,1,9,9,11,10,20,20,99.833887,12,3

In [12]:
march_result = run_combined_month(
    2027,
    3,
)

pd.DataFrame(march_result["month_rows"])

================================================================================
RUNNING COMBINED MONTH: 2027_03
================================================================================

Unmatched passenger rows after merge (missing Chocks DT): 7451
Unique unmatched flight keys: 4434

Unmatched key reasons:
reason
no_flight_candidate               3551
scheduled_dt_mismatch              729
exact_match_should_have_joined     154
Name: count, dtype: int64

Dropped 7100 passenger rows due to reasons {'scheduled_dt_mismatch', 'no_flight_candidate'}
[1/5] Penetration + SSR mix…
    ✓ penetration + SSR mix built   [675.81s]
[2/5] Service times…
[BUILD_JOBS] Dropping 66 jobs already impossible at release (beyond SLA + max late)

[BUILD_JOBS] Dropping 4 arrival jobs with expired SLA window (max_late_mins=180).
       Passenger ID Flight Number Airline Code      sla_start_time  \
53000      13159410           748           LS 2025-09-30 01:35:15
53001      13159411           748           LS 2025-09-30 01:35:15
53004      13159414           748           LS 2025-09-30 01:35:15
53005      13159415           748           LS 2025-09-30 01:35:15

           Job Start Time  sla_limit           Chocks DT
53000 2025-09-30 04:59:07         20 2025-09-30 01:35:15
53001 2025-09-30 05:00:53         20 2025-09-30 01:35:15
53004 2025-09-30 04:59:15         20 2025-09-30 01:35:15
53005 2025-09-30 04:59:18         20 2025-09-30 01:35:15
    ✓ service times built   [4.05s]
[2b/5] Tau mode params (S25 medians)…
    ✓ tau mode params built   [0.05s]
[3/5] Chocks offsets…
    ✓ chocks offsets built   [0.10s]
[4/5] Early/late timing…
    ✓ early/late params built   [0.09s]
[5/5] Stand inputs…
    ✓ stand inputs built   [0.11s]

Running S1 P100

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 7963
Airlines (sample): ['PC' 'LH' 'U2' 'LM' 'BA' 'EC' 'FR' 'CJ' 'EA' 'AF']
Countries (sample): ['TURKEY' 'GERMANY' 'GREAT BRITAIN' 'NETHERLANDS' 'POLAND' 'ITALY'
 'IRISH REPUBLIC' 'CZECH REPUBLIC' 'FRANCE' 'SPAIN']

Pax describe:
count    7963.000000
mean      137.864373
std        59.914615
min         0.000000
25%       100.000000
50%       156.000000
75%       179.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline    CountryName         Sector dir    Pax
0       PC         TURKEY  International   D  184.0
1       LH        GERMANY  International   A  140.0
2       U2  GREAT BRITAIN       Domestic   D  152.0
3       LM  GREAT BRITAIN       Domestic   A   60.0
4       LH        GERMANY  International   A  162.0
5       BA  GREAT BRITAIN       Domestic   A  187.0
6       U2  GREAT BRITAIN       Domestic   D    0.0
7       PC         TURKEY  International   D    0.0
8       U2  GREAT BRITAIN       Domestic   A  124.0
9       BA  GREAT BRITAIN       Domestic   A   79.0
10      EC    NETHERLANDS  International   D  156.0
11      U2         POLAND  International   D  225.0
12      BA  GREAT BRITAIN       Domestic   A   41.0
13      FR          ITALY  International   A  180.0
14      CJ  GREAT BRITAIN       Domestic   D  106.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,009 / 7,963 (88.0%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
2      EA  IRISH REPUBLIC          314
0      CJ   GREAT BRITAIN          300
1      EA   GREAT BRITAIN          146
4      EC     NETHERLANDS           84
3      EC          FRANCE           62
5      LG      LUXEMBOURG           16
8      U2          NORWAY           16
6      LS           EGYPT            8
7      LS  IRISH REPUBLIC            8

Example missing keys:
   Airline     CountryName    Pax
10      EC     NETHERLANDS  156.0
14      CJ   GREAT BRITAIN  106.0
20      EA  IRISH REPUBLIC   60.0
27      EA   GREAT BRITAIN   59.0
28      EC     NETHERLANDS  134.0
40      EC     NETHERLANDS  169.0
43      LG      LUXEMBOURG  126.0
46      EA   GREAT BRITAIN   62.0
56      CJ   GREAT BRITAIN  104.0
58      CJ   GREAT BRITAIN   78.0
59      EA  IRISH REPUBLIC   70.0
61      EA   GREAT BRITAIN   48.0
73      EC          FRANCE  169.0
74      EA   GREAT BRITAIN   48.0
76      EC          FRANCE  186.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11590.552059598824
Total PRMs after rounding: 11720

Raw PRM demand distribution (prm_raw):
count    7963.000000
mean        1.455551
std         1.401372
min         0.000000
25%         0.690000
50%         1.165468
75%         1.655889
max         9.524049
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
2219      QR       QATAR  301.0   0.031641  9.524049          10
184       QR       QATAR  298.0   0.031641  9.429125           9
969       QR       QATAR  295.0   0.031641  9.334201           9
552       QR       QATAR  295.0   0.031641  9.334201           9
4553      QR       QATAR  293.0   0.031641  9.270919           9
7096      QR       QATAR  286.0   0.031641  9.049429           9
1836      QR       QATAR  281.0   0.031641  8.891222           9
3098      QR       QATAR  280.0   0.031641  8.859581           9
534       QR       QATAR  277.0   0.031641  8.764657           9
6998      QR       QATAR  276.0   0.031641  8.733015           9
4208      QR       QATAR  276.0   0.031641  8.733015           9
3482      QR       QATAR  276.0   0.031641  8.733015           9
2721      QR       QATAR  275.0   0.031641  8.701374           9
3139      QR       QATAR  275.0   0.031641  8.701374           9
3783      QR       QATAR  275.0   0.031641  8.701374           9
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=184.0 | Pen=0.01006 | Pax*Pen=1.851 | PRMs=2
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=140.0 | Pen=0.00745 | Pax*Pen=1.042 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=152.0 | Pen=0.00920 | Pax*Pen=1.398 | PRMs=1
[DEBUG flight] Airline=LM | Country=GREAT BRITAIN | Pax=60.0 | Pen=0.02036 | Pax*Pen=1.221 | PRMs=1
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=162.0 | Pen=0.00745 | Pax*Pen=1.206 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=187.0 | Pen=0.01029 | Pax*Pen=1.923 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=0.0 | Pen=0.00920 | Pax*Pen=0.000 | PRMs=0
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=0.0 | Pen=0.01006 | Pax*Pen=0.000 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=124.0 | Pen=0.00920 | Pax*Pen=1.140 | PRMs=1
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=79.0 | Pen=0.01029 | Pax*Pen=0.813 | PRMs=1
[DEBUG flight] Airline=EC | Country=NETHERLANDS | Pax=156.0 | Pen=0.01000 | Pax*Pen=1.560 | PRMs=2
[DEBUG flight] Airline=U2 | Country=POLAND | Pax=225.0 | Pen=0.00894 | Pax*Pen=2.012 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=41.0 | Pen=0.01029 | Pax*Pen=0.422 | PRMs=0
[DEBUG flight] Airline=FR | Country=ITALY | Pax=180.0 | Pen=0.00433 | Pax*Pen=0.780 | PRMs=1
[DEBUG flight] Airline=CJ | Country=GREAT BRITAIN | Pax=106.0 | Pen=0.01000 | Pax*Pen=1.060 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 11720
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     5947
WCHS     4974
WCHC      656
OTHER     143
Name: count, dtype: int64
Running S2 P100

Running S1 P90

================================================================================
[DEBUG A] Future flights loaded & Pax computed
================================================================================
df_flights rows: 7963
Airlines (sample): ['QR' 'EA' 'U2' 'EC' 'PC' 'BA' 'DL' 'FR' 'KL' 'LH']
Countries (sample): ['QATAR' 'GREAT BRITAIN' 'NETHERLANDS' 'TURKEY' 'UNITED STATES OF AMERICA'
 'SPAIN' 'GERMANY' 'FRANCE' 'ITALY' 'UNITED ARAB EMIRATES']

Pax describe:
count    7963.000000
mean      137.864373
std        59.914615
min         0.000000
25%       100.000000
50%       156.000000
75%       179.000000
max       312.000000
Name: Pax, dtype: float64

Top 10 rows (Airline, CountryName, Sector, dir, Pax):
   Airline               CountryName         Sector dir    Pax
0       QR                     QATAR  International   D    0.0
1       EA             GREAT BRITAIN       Domestic   D   23.0
2       U2             GREAT BRITAIN       Domestic   D  183.0
3       U2             GREAT BRITAIN       Domestic   A  176.0
4       EC               NETHERLANDS  International   D  135.0
5       U2             GREAT BRITAIN       Domestic   A  151.0
6       PC                    TURKEY  International   D  184.0
7       BA             GREAT BRITAIN       Domestic   A  193.0
8       DL  UNITED STATES OF AMERICA  International   A  215.0
9       FR                     SPAIN  International   D   44.0
10      KL               NETHERLANDS  International   A  176.0
11      U2             GREAT BRITAIN       Domestic   A  140.0
12      DL  UNITED STATES OF AMERICA  International   A  177.0
13      LH                   GERMANY  International   A  140.0
14      U2               NETHERLANDS  International   A  128.0

================================================================================
[DEBUG B] Penetration lookup match rate
================================================================================
Penetration keys available: 139
Flights with penetration match: 7,009 / 7,963 (88.0%)

Top missing (Airline, CountryName) combos in future flights:
  Airline     CountryName  flight_rows
2      EA  IRISH REPUBLIC          314
0      CJ   GREAT BRITAIN          300
1      EA   GREAT BRITAIN          146
4      EC     NETHERLANDS           84
3      EC          FRANCE           62
5      LG      LUXEMBOURG           16
8      U2          NORWAY           16
6      LS           EGYPT            8
7      LS  IRISH REPUBLIC            8

Example missing keys:
    Airline     CountryName    Pax
1        EA   GREAT BRITAIN   23.0
4        EC     NETHERLANDS  135.0
17       EA   GREAT BRITAIN   54.0
22       CJ   GREAT BRITAIN   99.0
29       EA   GREAT BRITAIN   48.0
37       CJ   GREAT BRITAIN   89.0
53       CJ   GREAT BRITAIN   79.0
64       EA  IRISH REPUBLIC   29.0
72       EA  IRISH REPUBLIC   39.0
76       LG      LUXEMBOURG  109.0
77       EC     NETHERLANDS  156.0
85       CJ   GREAT BRITAIN  106.0
90       CJ   GREAT BRITAIN   54.0
95       EA   GREAT BRITAIN   55.0
105      EA  IRISH REPUBLIC   60.0

================================================================================
[DEBUG C] Expected PRMs vs rounding
================================================================================
Total expected PRMs (raw sum, BEFORE rounding): 11590.552059598824
Total PRMs after rounding: 11720

Raw PRM demand distribution (prm_raw):
count    7963.000000
mean        1.455551
std         1.401372
min         0.000000
25%         0.690000
50%         1.165468
75%         1.655889
max         9.524049
Name: _prm_raw, dtype: float64

Top flights by raw PRM demand:
     Airline CountryName    Pax  _pen_used  _prm_raw  _prm_round
2219      QR       QATAR  301.0   0.031641  9.524049          10
423       QR       QATAR  298.0   0.031641  9.429125           9
975       QR       QATAR  295.0   0.031641  9.334201           9
863       QR       QATAR  295.0   0.031641  9.334201           9
4553      QR       QATAR  293.0   0.031641  9.270919           9
7096      QR       QATAR  286.0   0.031641  9.049429           9
1836      QR       QATAR  281.0   0.031641  8.891222           9
3098      QR       QATAR  280.0   0.031641  8.859581           9
845       QR       QATAR  277.0   0.031641  8.764657           9
4208      QR       QATAR  276.0   0.031641  8.733015           9
3482      QR       QATAR  276.0   0.031641  8.733015           9
6998      QR       QATAR  276.0   0.031641  8.733015           9
2721      QR       QATAR  275.0   0.031641  8.701374           9
3139      QR       QATAR  275.0   0.031641  8.701374           9
6103      QR       QATAR  275.0   0.031641  8.701374           9
[DEBUG flight] Airline=QR | Country=QATAR | Pax=0.0 | Pen=0.03164 | Pax*Pen=0.000 | PRMs=0
[DEBUG flight] Airline=EA | Country=GREAT BRITAIN | Pax=23.0 | Pen=0.01000 | Pax*Pen=0.230 | PRMs=0
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=183.0 | Pen=0.00920 | Pax*Pen=1.683 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=176.0 | Pen=0.00920 | Pax*Pen=1.619 | PRMs=2
[DEBUG flight] Airline=EC | Country=NETHERLANDS | Pax=135.0 | Pen=0.01000 | Pax*Pen=1.350 | PRMs=1
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=151.0 | Pen=0.00920 | Pax*Pen=1.389 | PRMs=1
[DEBUG flight] Airline=PC | Country=TURKEY | Pax=184.0 | Pen=0.01006 | Pax*Pen=1.851 | PRMs=2
[DEBUG flight] Airline=BA | Country=GREAT BRITAIN | Pax=193.0 | Pen=0.01029 | Pax*Pen=1.985 | PRMs=2
[DEBUG flight] Airline=DL | Country=UNITED STATES OF AMERICA | Pax=215.0 | Pen=0.01525 | Pax*Pen=3.279 | PRMs=3
[DEBUG flight] Airline=FR | Country=SPAIN | Pax=44.0 | Pen=0.01067 | Pax*Pen=0.469 | PRMs=0
[DEBUG flight] Airline=KL | Country=NETHERLANDS | Pax=176.0 | Pen=0.00911 | Pax*Pen=1.604 | PRMs=2
[DEBUG flight] Airline=U2 | Country=GREAT BRITAIN | Pax=140.0 | Pen=0.00920 | Pax*Pen=1.288 | PRMs=1
[DEBUG flight] Airline=DL | Country=UNITED STATES OF AMERICA | Pax=177.0 | Pen=0.01525 | Pax*Pen=2.699 | PRMs=3
[DEBUG flight] Airline=LH | Country=GERMANY | Pax=140.0 | Pen=0.00745 | Pax*Pen=1.042 | PRMs=1
[DEBUG flight] Airline=U2 | Country=NETHERLANDS | Pax=128.0 | Pen=0.00639 | Pax*Pen=0.818 | PRMs=1

[DEBUG ingest_s26]
Total PRM jobs (rows): 11720
Columns: ['Passenger ID', 'Airline Code', 'Flight Number', 'A/D', 'Sector', 'CountryName', 'Stand', 'Scheduled Flight DT', 'Chocks DT', 'Minutes on Chocks', 'ScheduledDateTime_Local', 'Chocks_Est', 'Departure Gate', 'SSR Code', 'Has Own Chair', 'IsEffectiveRemote', 'PRM Flight Count', 'Concurrent Stress', 'Turnaround PRM Count', 'Turnaround Vertical Count', 'IsArrival', 'Adhoc Or Planned', 'IsAdhoc', 'Job Start Time', 'Job End Time', 'tau_amb_mins', 'tau_mini_mins', 'tau_push_mins']
SSR Code present: True
SSR Code distribution:
SSR Code
WCHR     5950
WCHS     4978
WCHC      644
OTHER     148
Name: count, dtype: int64
[BUILD_JOBS] Applying stratified percentile cap: q=0.90 | strata=['SSR Code', 'Has Own Chair', 'A/D']
[BUILD_JOBS] Dropped 1122 PRM jobs via stratified percentile cap
Running S2 P90

Running V2 optimiser
    ✓ Passenger dataset combined (11,765 passenger rows)   [60.14s]
    ✓ P100 built (6,944 flights)   [0.17s]
    P100 demand summary: 11,765 PRMs across 6,944 flights
    ✓ prepare_model_data started | flights=6,944   [0.00s]
    ✓ vehicle expansion complete | vehicles=17   [0.03s]
    ✓ ambulift intervals built | flights=6,944 ambulifts=14   [0.86s]
    ✓ minibus intervals built | minibuses=3   [0.07s]
    ✓ staff intervals built   [0.01s]
    ✓ ambulift overlaps built | overlaps=5,484,522   [1.17s]
    ✓ minibus overlaps built | overlaps=501,087   [0.11s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=2.27s   [0.00s]
    ✓ sets built | F=6,944 AMB=14 MINI=3   [0.00s]
    ✓ variables built | x=34,720 amb=291,648 mini=41,664   [1.02s]
    ✓ ambulift overlap constraints built | 5,484,522   [36.96s]
    ✓ minibus overlap constraints built | 501,087   [4.90s]
    ✓ build_pyomo_model complete | total=44.09s   [1.20s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=6,944 Vehicles=17
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 6443938 rows; 416657 cols; 13264009 nonzeros; 368049 integer variables (368049 binary)
Coefficient ranges:
  Matrix  [1e+00, 9e+00]
  Cost    [2e+00, 2e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
WARNING: Problem has some excessively large costs
WARNING:    Consider scaling the objective by 1e-1, or setting the user_objective_scale option to -1
Presolving model
1019972 rows, 165230 cols, 2175639 nonzeros 9s
348907 rows, 144653 cols, 1490236 nonzeros 67s
348907 rows, 144653 cols, 1490236 nonzeros 145s
Presolve reductions: rows 348907(-6095031); columns 144653(-272004); nonzeros 1490236(-11773773)
Objective function is integral with scale 219

Solving MIP model with:
   348907 rows
   144653 cols (129891 binary, 0 integer, 14762 implied int., 0 continuous, 0 domain fixed)
   1490236 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            3287372327.653     Large        0      0      0         0   165.5s
 R       0       0         0   0.00%   10880930.94397  1019122080.219    98.93%        0      0      0    115782   648.4s
         0       0         0   0.00%   10880930.94397  1019122080.219    98.93%     1324     58      0    116645   725.8s
         0       0         0   0.00%   10881474.61063  1019122080.219    98.93%     1808    198      0    120982   760.5s
         0       0         0   0.00%   10881867.94397  1019122080.219    98.93%     1939    311      0    122234   781.4s
         0       0         0   0.00%   10882697.46778  1019122080.219    98.93%     1967    419      0    123779   794.7s
         0       0         0   0.00%   10882816.46778  1019122080.219    98.93%     1978    432   3444    124232   811.0s
         0       0         0   0.00%   10882835.13444  1019122080.219    98.93%     1980    439   3444    124695   819.3s
         0       0         0   0.00%   10882840.13444  1019122080.219    98.93%     1983    443   3444    125990   836.2s
         0       0         0   0.00%   10882840.13444  1019122080.219    98.93%     1995    446   3444    127188   846.3s
         0       0         0   0.00%   10882840.13444  1019122080.219    98.93%     2001    449   3444    142640   934.8s
         0       0         0   0.00%   10882942.13444  1019122080.219    98.93%     2430    467   3444    154656  1004.4s
         0       0         0   0.00%   10882942.13444  1019122080.219    98.93%     2685    473   3444    156577  1065.5s
         0       0         0   0.00%   10882942.13444  1019122080.219    98.93%     2701    476   3444    159288  1090.8s

,S1_PeakAmb,S1_PeakMini,S1_PeakDrivers,S1_PeakVehAgents,S2_PeakAmb,S2_PeakMini,S2_PeakDrivers,S2_PeakVehAgents,V2_arrival_sla_pct,V2_PeakAmb,V2_PeakMini
0,11,1,11,11,10,12,20,20,99.833528,11,3
1,9,1,9,9,10,11,20,20,99.889827,13,3